// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/synth/patch/v1/contract.yaml

package patch

// Request — http.synth.patch.v1.request (negative fixture: bare bool, should be *bool)
type Request struct {
	ID   string `json:"id"`
	Flag bool   `json:"flag,omitempty"`
}

// Response — http.synth.patch.v1.response
type Response struct{}
