// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/auditcore/slices/auditappend/slice.yaml

package auditappend

import (
	"context"

	"github.com/ghbvf/gocell/kernel/outbox"
)

// eventHandlerService documents the handler methods auditappend's service
// must provide so that cell_gen.go's reg.Subscribe call is typed. The interface
// is intentionally unexported to avoid colliding with a concrete Service struct.
// Build-time safety comes from the c.<field>.<method>(...) invocations in
// cell_gen.go — Go rejects compilation if the method is missing or renamed.
type eventHandlerService interface {
	// HandleEvent handles event.user.created.v1.
	HandleEvent(ctx context.Context, e outbox.Entry) outbox.HandleResult
}
