// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/policy/get/v1/contract.yaml

/** http.policy.get.v1.request */
export interface Request {
  id: string;
}

/** http.policy.get.v1.response */
export interface Response {
  data: ResponseData;
}

/** policy */
export interface ResponseData {
  id: string;
  name: string;
  description?: string;
  version: number;
  rules: ResponseDataRulesItem[];
}

/** policy rule */
export interface ResponseDataRulesItem {
  id: string;
  name: string;
  effect: string;
  conditions?: ResponseDataRulesItemConditionsItem[];
  obligations?: ResponseDataRulesItemObligations;
}

export interface ResponseDataRulesItemConditionsItem {
  source: string;
  key: string;
  operator: string;
  values?: string[];
  rhsSource?: string;
  rhsKey?: string;
}

export interface ResponseDataRulesItemObligations {
  rowScope?: string;
  fieldMask?: string[];
}
