// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/configcore/slices/configsubscribe/slice.yaml

package configsubscribe

import (
	"context"

	"github.com/ghbvf/gocell/kernel/outbox"
)

// eventHandlerService documents the handler methods configsubscribe's service
// must provide so that cell_gen.go's reg.Subscribe call is typed. The interface
// is intentionally unexported to avoid colliding with a concrete Service struct.
// Build-time safety comes from the c.<field>.<method>(...) invocations in
// cell_gen.go — Go rejects compilation if the method is missing or renamed.
type eventHandlerService interface {
	// HandleEntryDeleted handles event.config.entry-deleted.v1.
	HandleEntryDeleted(ctx context.Context, e outbox.Entry) outbox.HandleResult
	// HandleEntryUpserted handles event.config.entry-upserted.v1.
	HandleEntryUpserted(ctx context.Context, e outbox.Entry) outbox.HandleResult
}
