// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/configcore/slices/configsubscribe/slice.yaml

package configsubscribe

import (
	"context"

	"github.com/ghbvf/gocell/kernel/outbox"
)

// eventHandlerService is the interface configsubscribe's service must implement.
// Concrete implementation lives in service.go (hand-written); this interface
// keeps the cell-side reference typed so cell_gen.go's reg.Subscribe call
// fails the build if the slice loses or renames a handler method.
// The unexported name avoids colliding with the concrete Service struct.
type eventHandlerService interface {
	// HandleEntryDeleted handles event.config.entry-deleted.v1.
	HandleEntryDeleted(ctx context.Context, e outbox.Entry) outbox.HandleResult
	// HandleEntryUpserted handles event.config.entry-upserted.v1.
	HandleEntryUpserted(ctx context.Context, e outbox.Entry) outbox.HandleResult
}

// _ is a compile-time proof that Service satisfies eventHandlerService.
var _ eventHandlerService = (*Service)(nil)
