// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/event/role/assigned/v1/contract.yaml

/** event.role.assigned.v1.payload */
export interface Payload {
  userId: string;
  roleId: string;
  action: string;
  actorId?: string;
}

/** event.role.assigned.v1.headers */
export interface Headers {
  eventId: string;
}
