// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/config/flags/update/v1/contract.yaml

/** http.config.flags.update.v1.request */
export interface Request {
  key: string;
  enabled: boolean;
  rolloutPercentage: number;
  description: string;
  expectedVersion: number;
}

/** http.config.flags.update.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  id: string;
  key: string;
  enabled: boolean;
  rolloutPercentage: number;
  description: string;
  version: number;
  createdAt?: string;
  updatedAt?: string;
}
