// Code generated by gocell generate contract. DO NOT EDIT.
// source: examples/iotdevice/contracts/http/device/command/enqueue-async/v1/contract.yaml

/** http.device.command.enqueue-async.v1.request */
export interface Request {
  id: string;
  commandType?: string;
  payload: string;
}

/** http.device.command.enqueue-async.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  deviceId: string;
  commandType?: string;
  status: string;
}
