// Package cellmodulemeta derives the cellmodules exported-metadata bundle: a
// byte-stable, re-parseable copy of the GoCell platform metadata closure
// (corecells cell.yaml + slice.yaml + the root contracts those slices reference
// + shared schemas) published under cellmodules/.gocell/exported-metadata/.
//
// # Why
//
// cellmodules/<cell> is already the Go API surface external Operator-SDK
// consumers assemble platform cells against (it distributes Module()). This
// bundle makes it ALSO distribute the corresponding metadata closure, so an
// external repo's `gocell generate assembly` (#1515 PR2) can read platform
// cell/slice/contract metadata from the cellmodules module cache — without a
// local go.work clone of the platform module. The bundle ships in the
// cellmodules module zip (golang.org/x/mod/zip excludes only VCS dirs, not
// .gocell/), so it reaches the module cache verbatim.
//
// corecells contracts live in the gocell ROOT module, not in corecells; reading
// corecells alone would leave those contracts unresolved and silently
// under-count broker cells. Publishing the CLOSURE (cells + slices + the
// contracts they reference) here is what closes that fail-open gap at the root.
//
// # Single source of truth
//
// [desiredBundle] computes the complete desired file set once; both [Generate]
// (write + prune stale) and [Verify] (Layer-1 byte diff + extra-file detection)
// consume it, so the two cannot drift. Layer-2 semantic equivalence (re-parsed
// bundle platform closure == monorepo platform closure) lives in [Verify] and
// catches a closure-traversal omission that a byte-self-consistent bundle would
// hide.
//
// # AI-robust grade (codegen funnel + golden — Hard per ai-robust.md)
//
// The single enforcement carrier is `gocell verify codegen-cellmodule-metadata`
// (hack/verify-codegen-cellmodule-metadata.sh, CI codegen bucket):
//
//   - Layer-1 (byte regenerate golden): Hard — the committed bundle must be
//     byte-identical to a fresh Generate(); a hand edit, a stale file from a
//     dropped contract, or a forgotten regenerate after a corecells/contract
//     change all surface as byte/missing/stale drift. modules_gen.go /
//     shared-schema mirror precedent.
//   - Layer-2 (semantic closure equivalence): Medium-Hard — runtime guard,
//     machine-judged every CI run: the re-parsed bundle's platform closure
//     (cell IDs + slice keys + reachable contract IDs) must equal the monorepo's.
//     This SUBSUMES the coverage invariant (bundle cell set == all corecells
//     cells) and the completeness invariant (every contract a platform slice
//     references is in the bundle) — the latter is what defends broker-cell
//     derivation from a fail-open under-count. A closure-traversal omission that
//     Layer-1 cannot see (byte-self-consistent but missing a contract) is caught
//     here. Red-case coverage: cellmodulemeta_test.go.
//
// A dedicated tools/archtest funnel (sanctioned-writer / coverage as separate
// named invariants) is defense-in-depth over the byte golden and is tracked as
// an optional fast-follow; the codegen golden already makes any divergent bundle
// content CI-red regardless of writer.
//
// ADR ref: docs/architecture/202606200300-1515-adr-cellmodules-metadata-distribution.md
package cellmodulemeta

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"

	"github.com/ghbvf/gocell/framework/kernel/metadata"
	"github.com/ghbvf/gocell/tools/codegen"
)

// bundleDirFromRoot is the monorepo-root-relative directory the bundle is
// generated into. Within the published cellmodules module the bundle is at
// .gocell/exported-metadata (the consumer-side path used by the #1515 PR2
// resolver after `go list -json` resolves the cellmodules module dir).
const bundleDirFromRoot = "cellmodules/.gocell/exported-metadata"

// bundleManifestRel is the synthesized manifest path WITHIN the bundle, so a
// consumer's metadata.NewParser(<bundleDir>) auto-detects manifest mode and
// discovers the copied flat-layout corecells cells + root contracts.
const bundleManifestRel = ".gocell/manifest.yaml"

// bundleManifest is the byte-stable manifest synthesized into every bundle. It
// mirrors the root .gocell/manifest.yaml entries for corecells (flat cell/slice
// layout) and contracts, scoped to exactly the files the closure copies. No
// actors/statusBoard singletons (the platform closure has none).
const bundleManifest = `# GENERATED by gocell generate cellmodule-metadata — DO NOT EDIT.
# Exported platform metadata bundle (#1515): lets an external Operator-SDK
# consumer's metadata.NewParser(<this dir>) discover the platform cell/slice/
# contract closure read from the cellmodules module cache.
version: v1
modules:
  - path: .
    includes:
      contracts:
        - "contracts/**/contract.yaml"
  - path: corecells
    includes:
      cells:
        - "*/cell.yaml"
      slices:
        - "*/slices/*/slice.yaml"
`

// Generate derives the bundle from the monorepo at root and writes every file
// under bundleDirFromRoot, pruning any committed bundle file that is no longer
// part of the closure (so a removed contract leaves no stale copy). When dryRun
// is true nothing is written/removed; written still lists the paths that would
// change. written holds bundle-relative slash paths, sorted.
func Generate(root string, dryRun bool) (written []string, err error) {
	desired, err := desiredBundle(root)
	if err != nil {
		return nil, err
	}
	for _, rel := range sortedKeys(desired) {
		abs := filepath.Join(root, filepath.FromSlash(bundleDirFromRoot), filepath.FromSlash(rel))
		res, werr := codegen.Write(codegen.WriteOptions{
			Path:       abs,
			Content:    desired[rel],
			RepoRoot:   root,
			Headerless: true,
			DryRun:     dryRun,
		})
		if werr != nil {
			return nil, fmt.Errorf("cellmodulemeta: write %s: %w", rel, werr)
		}
		if res.Action == codegen.ActionWritten || res.Action == codegen.ActionWouldWrite {
			written = append(written, rel)
		}
	}
	pruned, err := pruneStale(root, desired, dryRun)
	if err != nil {
		return nil, err
	}
	written = append(written, pruned...)
	sort.Strings(written)
	return written, nil
}

// Verify reports every bundle drift: Layer-1 (a desired file is missing or
// byte-differs, or an extra committed file is not in the closure) and Layer-2
// (the committed bundle re-parses to a platform closure that differs from the
// monorepo platform closure). An empty drift slice means the bundle is current
// AND semantically complete. drift entries are human-readable, sorted.
func Verify(root string) (drift []string, err error) {
	desired, err := desiredBundle(root)
	if err != nil {
		return nil, err
	}
	drift = append(drift, verifyByteLayer(root, desired)...)
	semantic, err := verifySemanticLayer(root)
	if err != nil {
		return nil, err
	}
	drift = append(drift, semantic...)
	sort.Strings(drift)
	return drift, nil
}

// verifyByteLayer performs the Layer-1 byte checks: every desired file present
// and byte-identical, and no extra committed bundle file outside the closure.
func verifyByteLayer(root string, desired map[string][]byte) []string {
	var drift []string
	for _, rel := range sortedKeys(desired) {
		abs := filepath.Join(root, filepath.FromSlash(bundleDirFromRoot), filepath.FromSlash(rel))
		got, rerr := os.ReadFile(abs) //nolint:gosec // G304: path derived from the closure, not user input
		switch {
		case os.IsNotExist(rerr):
			drift = append(drift, "missing: "+rel)
		case rerr != nil:
			drift = append(drift, fmt.Sprintf("unreadable %s: %v", rel, rerr))
		case !bytes.Equal(got, desired[rel]):
			drift = append(drift, "byte-drift: "+rel)
		}
	}
	extra, err := extraBundleFiles(root, desired)
	if err != nil {
		return append(drift, "scan-bundle: "+err.Error())
	}
	for _, rel := range extra {
		drift = append(drift, "stale: "+rel)
	}
	return drift
}

// verifySemanticLayer performs the Layer-2 check: the committed bundle, parsed
// in isolation, must yield the same platform closure (cell IDs + slice keys +
// reachable contract IDs) as parsing the monorepo and filtering to platform
// cells. A closure-traversal omission that drops a contract makes the bundle's
// reachable-contract set smaller than the monorepo's — caught here even though
// the bundle is byte-self-consistent.
func verifySemanticLayer(root string) ([]string, error) {
	monoPM, err := metadata.NewParser(root).Parse()
	if err != nil {
		return nil, fmt.Errorf("cellmodulemeta: parse monorepo: %w", err)
	}
	want := platformClosureSignature(monoPM)

	bundleAbs := filepath.Join(root, filepath.FromSlash(bundleDirFromRoot))
	if _, statErr := os.Stat(bundleAbs); os.IsNotExist(statErr) {
		return []string{"semantic: bundle dir absent — run `gocell generate cellmodule-metadata`"}, nil
	}
	bundlePM, err := metadata.NewParser(bundleAbs).Parse()
	if err != nil {
		// A bundle that does not re-parse is reported DRIFT (surfaced via the
		// drift slice + non-zero drift count), not a propagated tool error — the
		// committed bundle is stale/corrupt and `gocell generate cellmodule-metadata`
		// must be re-run. Mirrors the byte-drift path's "report, don't propagate".
		return []string{"semantic: bundle does not re-parse: " + err.Error()}, nil //nolint:nilerr // reported drift (see above)
	}
	got := closureSignature(bundlePM)
	return diffSignatures(want, got), nil
}

// desiredBundle is the single source of truth for the bundle's complete file
// set: the synthesized manifest plus a verbatim copy of every monorepo file in
// the platform closure, keyed by bundle-relative slash path (== monorepo-
// relative path, so re-parse resolves $ref/SchemaRefs siblings unchanged).
func desiredBundle(root string) (map[string][]byte, error) {
	pm, err := metadata.NewParser(root).Parse()
	if err != nil {
		return nil, fmt.Errorf("cellmodulemeta: parse monorepo: %w", err)
	}
	srcFiles, err := platformClosureFiles(root, pm)
	if err != nil {
		return nil, err
	}
	out := make(map[string][]byte, len(srcFiles)+1)
	out[bundleManifestRel] = []byte(bundleManifest)
	for _, rel := range srcFiles {
		abs := filepath.Join(root, filepath.FromSlash(rel))
		content, rerr := os.ReadFile(abs) //nolint:gosec // G304: rel derived from parsed metadata, not user input
		if rerr != nil {
			return nil, fmt.Errorf("cellmodulemeta: read closure file %s: %w", rel, rerr)
		}
		out[rel] = content
	}
	return out, nil
}

// platformClosureFiles returns the sorted, de-duplicated set of monorepo-
// relative files that constitute the platform metadata closure:
//   - every corecells cell.yaml (the platform cell module — coverage anchor);
//   - every slice.yaml belonging to a corecells cell;
//   - every file in the directory of each contract referenced by those slices'
//     contractUsages (contract.yaml + its sibling *.schema.json);
//   - each out-of-dir param $ref mixin those contracts resolve at parse time
//     (e.g. a shared contracts/shared/cas/... mixin), which re-parse must read.
//
// Whole-dir copying for the contract's own directory is deliberate safe
// over-inclusion (it avoids enumerating each in-dir schema file). The shared
// mixin closure, by contrast, is PRECISE: only files actually targeted by a
// param $ref are copied — NOT all of contracts/shared/. Wholesale-copying
// contracts/shared/ would pull in response-envelope schemas (e.g. the
// error-response-v1 shared-schema mirror canonical) that parse never reads
// (only param $refs are resolved at parse, see metadata.resolveParamRefs),
// creating an undeclared copy that SHARED-SCHEMA-MIRROR-FUNNEL-01 flags. Layer-2
// semantic verify confirms the reachable-contract SET is complete regardless;
// a missed mixin would instead break re-parse and red the re-parse test.
func platformClosureFiles(root string, pm *metadata.ProjectMeta) ([]string, error) {
	set := make(map[string]struct{})
	platformCells := make(map[string]struct{})
	for _, c := range pm.Cells {
		if metadata.IsInCorecellsSubtree(c.File) {
			platformCells[c.ID] = struct{}{}
			set[c.File] = struct{}{}
		}
	}
	// Fail-fast on a zero-cell closure: the only way the platform module yields no
	// cells is a misresolved root — typically running `gocell generate
	// cellmodule-metadata` from a nested module (e.g. cmd/gocell/) whose go.mod
	// makes findRoot() stop short of the repo root, so the parse sees no corecells
	// subtree. Without this guard Generate would silently write an empty bundle and
	// exit 0 (the foot-gun parseProjectGuarded guards for validate/check).
	if len(platformCells) == 0 {
		return nil, fmt.Errorf(
			"cellmodulemeta: no corecells cells discovered under %q — run gocell from the repo "+
				"root (the directory holding .gocell/manifest.yaml), not a nested module", root,
		)
	}
	contractIDs := make(map[string]struct{})
	for _, s := range pm.Slices {
		if _, ok := platformCells[s.BelongsToCell]; !ok {
			continue
		}
		set[s.File] = struct{}{}
		for _, cu := range s.ContractUsages {
			contractIDs[cu.Contract] = struct{}{}
		}
	}
	if err := addContractDirFiles(root, pm, contractIDs, set); err != nil {
		return nil, err
	}
	addContractParamRefTargets(pm, contractIDs, set)
	return sortedSet(set), nil
}

// addContractParamRefTargets adds the monorepo-relative path of each HTTP param
// $ref target (query + path params) of every referenced contract to set. These
// shared mixin files are read by metadata.resolveParamRefs at parse time, so the
// bundle must carry them for re-parse; their relative layout is preserved so the
// $ref (resolved against the contract Dir) still resolves inside the bundle.
// A within-dir ref is already covered by addContractDirFiles; an out-of-dir ref
// (e.g. ../../shared/...) is the one this adds.
func addContractParamRefTargets(pm *metadata.ProjectMeta, contractIDs, set map[string]struct{}) {
	for id := range contractIDs {
		c := pm.Contracts[id]
		if c == nil || c.Endpoints.HTTP == nil {
			continue
		}
		for _, p := range c.Endpoints.HTTP.QueryParams {
			addParamRefTarget(c.Dir, p.Ref, set)
		}
		for _, p := range c.Endpoints.HTTP.PathParams {
			addParamRefTarget(c.Dir, p.Ref, set)
		}
	}
}

// addParamRefTarget records the contract-Dir-relative $ref resolved to a
// monorepo-relative slash path. Resolution + validity use the SAME rule as the
// parser's resolveRefPath (path.Clean(path.Join(dir, ref)) gated by
// fs.ValidPath), so the closure cannot diverge from what re-parse will accept:
// fs.ValidPath rejects empty, absolute, and any ".."-escaping path. "." (the
// root itself) is additionally skipped — it is never a real schema file and
// would otherwise make desiredBundle try to read the root directory.
func addParamRefTarget(contractDir, ref string, set map[string]struct{}) {
	if ref == "" {
		return
	}
	target := path.Clean(path.Join(contractDir, ref))
	if target == "." || !fs.ValidPath(target) {
		return
	}
	set[target] = struct{}{}
}

// addContractDirFiles adds every file in each referenced contract's directory
// (contract.yaml + sibling schemas) to set. Unknown contract references are
// skipped — they wire no platform metadata and `gocell validate` flags them; the
// Layer-2 semantic closure compares only contracts actually resolvable in the
// monorepo, so skipping a dangling ref cannot mask a real omission.
func addContractDirFiles(root string, pm *metadata.ProjectMeta, contractIDs map[string]struct{}, set map[string]struct{}) error {
	for id := range contractIDs {
		c := pm.Contracts[id]
		if c == nil || c.Dir == "" {
			continue
		}
		if err := addDirFiles(root, c.Dir, set); err != nil {
			return err
		}
	}
	return nil
}

// addDirFiles adds every regular file under dirRel (monorepo-relative) to set,
// as monorepo-relative slash paths. A non-existent dir is skipped silently
// (contracts/shared may legitimately be absent in a minimal tree).
func addDirFiles(root, dirRel string, set map[string]struct{}) error {
	abs := filepath.Join(root, filepath.FromSlash(dirRel))
	info, err := os.Stat(abs)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("cellmodulemeta: stat %s: %w", dirRel, err)
	}
	if !info.IsDir() {
		set[filepath.ToSlash(dirRel)] = struct{}{}
		return nil
	}
	return filepath.WalkDir(abs, func(p string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() || !d.Type().IsRegular() {
			return nil
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil {
			return rerr
		}
		set[filepath.ToSlash(rel)] = struct{}{}
		return nil
	})
}

// pruneStale removes (or, in dryRun, reports) any committed bundle file not in
// the desired set, so a dropped closure file leaves no orphan copy. Returns
// "prune: <rel>" markers for changed paths.
func pruneStale(root string, desired map[string][]byte, dryRun bool) ([]string, error) {
	extra, err := extraBundleFiles(root, desired)
	if err != nil {
		return nil, err
	}
	var pruned []string
	for _, rel := range extra {
		pruned = append(pruned, "prune: "+rel)
		if dryRun {
			continue
		}
		abs := filepath.Join(root, filepath.FromSlash(bundleDirFromRoot), filepath.FromSlash(rel))
		if rmErr := os.Remove(abs); rmErr != nil {
			return nil, fmt.Errorf("cellmodulemeta: prune %s: %w", rel, rmErr)
		}
	}
	return pruned, nil
}

// extraBundleFiles returns bundle-relative slash paths of committed files under
// the bundle dir that are NOT in desired. An absent bundle dir yields none.
func extraBundleFiles(root string, desired map[string][]byte) ([]string, error) {
	bundleAbs := filepath.Join(root, filepath.FromSlash(bundleDirFromRoot))
	if _, err := os.Stat(bundleAbs); os.IsNotExist(err) {
		return nil, nil
	}
	var extra []string
	err := filepath.WalkDir(bundleAbs, func(p string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() || !d.Type().IsRegular() {
			return nil
		}
		rel, rerr := filepath.Rel(bundleAbs, p)
		if rerr != nil {
			return rerr
		}
		slash := filepath.ToSlash(rel)
		if _, ok := desired[slash]; !ok {
			extra = append(extra, slash)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("cellmodulemeta: scan bundle: %w", err)
	}
	sort.Strings(extra)
	return extra, nil
}

// platformClosureSignature is the monorepo platform closure: cell IDs that are
// corecells cells, their slice keys, and the contract IDs reachable from those
// slices' contractUsages (intersected with resolvable contracts).
func platformClosureSignature(pm *metadata.ProjectMeta) closureSig {
	platform := make(map[string]struct{})
	sig := newClosureSig()
	for _, c := range pm.Cells {
		if metadata.IsInCorecellsSubtree(c.File) {
			platform[c.ID] = struct{}{}
			sig.cells[c.ID] = struct{}{}
		}
	}
	collectSliceClosure(pm, platform, func(id string) bool { return pm.Contracts[id] != nil }, sig)
	return sig
}

// closureSignature is the bundle-side closure: the bundle is the platform
// closure already, so every cell/slice/contract it parsed counts.
func closureSignature(pm *metadata.ProjectMeta) closureSig {
	all := make(map[string]struct{}, len(pm.Cells))
	sig := newClosureSig()
	for id := range pm.Cells {
		all[id] = struct{}{}
		sig.cells[id] = struct{}{}
	}
	collectSliceClosure(pm, all, func(id string) bool { return pm.Contracts[id] != nil }, sig)
	return sig
}

// collectSliceClosure records, for every slice whose owning cell is in cells,
// the slice key and each referenced contract id that passes resolvable.
func collectSliceClosure(pm *metadata.ProjectMeta, cells map[string]struct{}, resolvable func(string) bool, sig closureSig) {
	for key, s := range pm.Slices {
		if _, ok := cells[s.BelongsToCell]; !ok {
			continue
		}
		sig.slices[key] = struct{}{}
		for _, cu := range s.ContractUsages {
			if resolvable(cu.Contract) {
				sig.contracts[cu.Contract] = struct{}{}
			}
		}
	}
}

// closureSig is a comparable platform-closure fingerprint.
type closureSig struct {
	cells     map[string]struct{}
	slices    map[string]struct{}
	contracts map[string]struct{}
}

func newClosureSig() closureSig {
	return closureSig{
		cells:     map[string]struct{}{},
		slices:    map[string]struct{}{},
		contracts: map[string]struct{}{},
	}
}

// diffSignatures returns human-readable "semantic: <kind> <id> only in
// <monorepo|bundle>" markers for every element present in exactly one of want
// (monorepo) and got (bundle). Empty means the platform closures are identical.
func diffSignatures(want, got closureSig) []string {
	var drift []string
	drift = append(drift, diffSet("cell", want.cells, got.cells)...)
	drift = append(drift, diffSet("slice", want.slices, got.slices)...)
	drift = append(drift, diffSet("contract", want.contracts, got.contracts)...)
	return drift
}

func diffSet(kind string, want, got map[string]struct{}) []string {
	var drift []string
	for id := range want {
		if _, ok := got[id]; !ok {
			drift = append(drift, fmt.Sprintf("semantic: %s %q missing from bundle", kind, id))
		}
	}
	for id := range got {
		if _, ok := want[id]; !ok {
			drift = append(drift, fmt.Sprintf("semantic: %s %q in bundle but not monorepo platform closure", kind, id))
		}
	}
	return drift
}

func sortedKeys(m map[string][]byte) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedSet(m map[string]struct{}) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
