// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/accesscore/slices/rbacassign/slice.yaml

package rbacassign

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "rbacassign",
	BelongsToCell:    "accesscore",
	ConsistencyLevel: "L2",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "http.auth.role.assign.v1", Role: "serve"},
		{Contract: "http.auth.role.revoke.v1", Role: "serve"},
		{Contract: "event.role.assigned.v1", Role: "publish"},
		{Contract: "event.role.revoked.v1", Role: "publish"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.rbacassign.service",
		},
		Contract: []string{
			"contract.http.auth.role.assign.v1.serve",
			"contract.http.auth.role.revoke.v1.serve",
			"contract.event.role.assigned.v1.publish",
			"contract.event.role.revoked.v1.publish",
		},
	},
	AllowedFiles: []string{
		"cells/accesscore/slices/rbacassign/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta }
