package refresh

import (
	"context"
	"time"
)

// Store persists refresh token chains with CAS-protected Rotate and
// reuse detection. Implementations must honour contract C1-C7 from
// docs/plans/202604191515-auth-federated-whistle.md §F2.
//
// ref: dexidp/dex storage/storage.go RefreshToken + server/refreshhandlers.go
// (single-transaction CAS + reuse detection + cascade revoke)
type Store interface {
	// Issue creates a new refresh chain for (sessionID, subjectID). The token
	// string is generated by the Store (43-char base64url of 32 rand bytes);
	// callers receive the token via Token.ID. ExpiresAt = now + Policy.MaxAge.
	//
	// Consistency: L1 LocalTx — atomic write, no outbox event.
	Issue(ctx context.Context, sessionID, subjectID string) (*Token, error)

	// Rotate presents a token and advances the chain one generation. The call
	// is all-or-nothing at the store level:
	//
	//   - happy path: presentedToken is the current active token. A new
	//     generation is issued; the old token becomes the new ObsoleteToken.
	//   - grace retry: presentedToken is the previous generation's obsolete
	//     token AND (now - current.LastUsed) <= Policy.ReuseInterval. Returns
	//     the current active token idempotently (no new rotate).
	//   - reuse detection: presentedToken matches an obsolete token but the
	//     grace window has elapsed. The entire session chain is revoked and
	//     ErrTokenReused is returned.
	//   - not found / expired / revoked: returns the matching sentinel.
	//
	// Consistency: L1 LocalTx — CAS rotate is atomic; reuse detection triggers
	// an inline Revoke(sessionID) within the same logical operation.
	//
	// ref: dexidp/dex server/refreshhandlers.go UpdateRefreshToken(callback)
	// ref: F2 contract C1 + C5 (CAS SQL branches)
	Rotate(ctx context.Context, presentedToken string) (*Token, error)

	// Revoke marks all tokens in the session as revoked. The only entry point
	// for revocation is by sessionID (contract C7); token-level or subject-level
	// revocation is intentionally absent.
	//
	// Consistency: L1 LocalTx — bulk UPDATE within a single statement.
	Revoke(ctx context.Context, sessionID string) error

	// GC removes all tokens whose ExpiresAt < olderThan (both active and
	// previously-revoked rows). Returns the count removed. Callers are
	// expected to invoke GC from a background worker.
	//
	// Design: GC drives cleanup from a single time axis (ExpiresAt) rather
	// than a dual revoked_at/expired_at bifurcation. Revoked tokens retain
	// their original ExpiresAt so they are purged at the same cadence as
	// naturally-expired tokens — simpler contract, simpler index design.
	//
	// ref: dexidp/dex + ory/fosite both use a single expiration timestamp
	// to drive refresh token cleanup.
	//
	// Consistency: L0 LocalOnly — best-effort cleanup, no transactional
	// guarantee required.
	GC(ctx context.Context, olderThan time.Time) (int, error)
}
