// Package governance — MetricsSchema baseline data model and AST-based scanner.
//
// MetricsSchema describes all Prometheus metric registrations found within an
// assembly's observable source paths (runtime/observability/metrics/ and
// adapters/). It is the Source-of-Record baseline artifact committed under
// assemblies/<id>/generated/metrics-schema.yaml.
//
// CI regenerates and diffs; any drift (new metric, label change, bucket change)
// blocks merge and requires a bucket-migration table in the PR description
// (OBS-01 policy enforcement).
//
// Note on typed identity: a full type-checked identity upgrade (verifying that
// CounterOpts/HistogramOpts originate from the canonical kernel/observability/metrics
// package via go/types) is blocked by kernel's dependency policy — kernel/ must
// not import golang.org/x/tools/go/packages. The AST name-suffix matching below
// is intentionally consistent with OBS-01's approach. A typed-identity upgrade
// requires either extracting a typeseval helper into the tools/ layer or relaxing
// the kernel dependency policy.

package governance

import (
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// MetricsSchema describes all Prometheus metric registrations found within an
// assembly's observable source paths. It is the Source-of-Record artifact
// written to assemblies/<id>/generated/metrics-schema.yaml.
type MetricsSchema struct {
	AssemblyID string        `yaml:"assemblyId"`
	Metrics    []MetricEntry `yaml:"metrics"` // sorted by Name
}

// MetricEntry describes a single metric registration site.
type MetricEntry struct {
	Name    string   `yaml:"name"`
	Type    string   `yaml:"type"` // counter / histogram / gauge / summary
	Help    string   `yaml:"help,omitempty"`
	Labels  []string `yaml:"labels"`            // sorted; unresolvable refs marked <unresolved>
	Buckets []string `yaml:"buckets,omitempty"` // histogram only; literal values only
	File    string   `yaml:"file"`              // source file relative to project root
	Line    int      `yaml:"line"`
}

// metricsSchemaHeader is prepended to the generated YAML file.
const metricsSchemaHeader = "# Generated by gocell generate metrics-schema. DO NOT EDIT.\n"

// metricsScanDirs are the directories BuildMetricsSchema scans relative to project root.
var metricsScanDirs = []string{
	filepath.FromSlash("runtime/observability/metrics"),
	"adapters",
}

// optsTypeToMetricType maps struct selector name to canonical metric type string.
var optsTypeToMetricType = map[string]string{
	"CounterOpts":   "counter",
	"HistogramOpts": "histogram",
	"GaugeOpts":     "gauge",
	"SummaryOpts":   "summary",
}

// BuildMetricsSchema walks the observable source paths under projectRoot and
// returns a MetricsSchema for the given assemblyID.
//
// Scanning is AST-based (go/parser). Metric registrations are identified by
// composite literal types whose selector name ends with CounterOpts,
// HistogramOpts, GaugeOpts, or SummaryOpts.
func BuildMetricsSchema(projectRoot, assemblyID string) (*MetricsSchema, error) {
	schema := &MetricsSchema{AssemblyID: assemblyID}

	for _, rel := range metricsScanDirs {
		dir := filepath.Join(projectRoot, rel)
		if _, err := os.Stat(dir); os.IsNotExist(err) {
			continue
		}
		entries, err := scanMetricEntries(projectRoot, dir)
		if err != nil {
			return nil, err
		}
		schema.Metrics = append(schema.Metrics, entries...)
	}

	sort.Slice(schema.Metrics, func(i, j int) bool {
		if schema.Metrics[i].Name != schema.Metrics[j].Name {
			return schema.Metrics[i].Name < schema.Metrics[j].Name
		}
		return schema.Metrics[i].File < schema.Metrics[j].File
	})

	return schema, nil
}

// MarshalMetricsSchema serializes schema to YAML with the canonical header.
func MarshalMetricsSchema(schema *MetricsSchema) ([]byte, error) {
	body, err := yaml.Marshal(schema)
	if err != nil {
		return nil, err
	}
	return append([]byte(metricsSchemaHeader), body...), nil
}

// scanMetricEntries walks dir and collects MetricEntry values from all non-test
// .go files. projectRoot is used to make file paths relative.
func scanMetricEntries(projectRoot, dir string) ([]MetricEntry, error) {
	var entries []MetricEntry
	fset := token.NewFileSet()
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			switch d.Name() {
			case "vendor", "testdata", "generated", "worktrees", ".git":
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		file, parseErr := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
		if parseErr != nil {
			return nil //nolint:nilerr // skip unparseable files; OBS-01 already reports parse errors
		}
		rel, relErr := filepath.Rel(projectRoot, path)
		if relErr != nil {
			rel = path
		}
		rel = filepath.ToSlash(rel)
		found := extractMetricEntries(fset, file, rel)
		entries = append(entries, found...)
		return nil
	})
	return entries, err
}

// extractMetricEntries finds all composite literals that look like metric Opts
// registrations in the given file. It extracts Name, Help, LabelNames, and
// Buckets from struct field literals.
func extractMetricEntries(fset *token.FileSet, file *ast.File, relPath string) []MetricEntry {
	var entries []MetricEntry
	ast.Inspect(file, func(n ast.Node) bool {
		entry, ok := tryExtractMetricEntry(fset, n, relPath)
		if ok {
			entries = append(entries, entry)
		}
		return true
	})
	return entries
}

// tryExtractMetricEntry attempts to parse n as a metric Opts composite literal
// and return a MetricEntry. Returns (entry, true) on success, (zero, false)
// when n is not a metric Opts literal or has no Name field.
func tryExtractMetricEntry(fset *token.FileSet, n ast.Node, relPath string) (MetricEntry, bool) {
	lit, ok := n.(*ast.CompositeLit)
	if !ok {
		return MetricEntry{}, false
	}
	metricType, ok := resolveMetricOptsType(lit)
	if !ok {
		return MetricEntry{}, false
	}
	entry := MetricEntry{
		Type: metricType,
		File: relPath,
		Line: fset.Position(lit.Pos()).Line,
	}
	applyOptsFields(&entry, lit)
	if entry.Name == "" {
		return MetricEntry{}, false // nameless — cannot be stably identified
	}
	sort.Strings(entry.Labels)
	return entry, true
}

// applyOptsFields populates entry fields from the key-value pairs of a metric
// Opts composite literal (Name, Help, LabelNames, Buckets).
func applyOptsFields(entry *MetricEntry, lit *ast.CompositeLit) {
	for _, elt := range lit.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		key, ok := kv.Key.(*ast.Ident)
		if !ok {
			continue
		}
		applyOptsField(entry, key.Name, kv.Value)
	}
}

// applyOptsField sets the named field on entry from the given value expression.
func applyOptsField(entry *MetricEntry, fieldName string, value ast.Expr) {
	switch fieldName {
	case "Name":
		if s, ok := extractStringLiteral(value); ok {
			entry.Name = s
		}
	case "Help":
		if s, ok := extractStringLiteral(value); ok {
			entry.Help = s
		}
	case "LabelNames":
		entry.Labels = extractStringSliceLiteral(value)
	case "Buckets":
		entry.Buckets = extractNumberSliceLiteral(value)
	}
}

// resolveMetricOptsType returns the canonical metric type string if lit's type
// selector name matches a known Opts suffix, otherwise ("", false).
func resolveMetricOptsType(lit *ast.CompositeLit) (string, bool) {
	sel, ok := lit.Type.(*ast.SelectorExpr)
	if !ok {
		return "", false
	}
	t, ok := optsTypeToMetricType[sel.Sel.Name]
	return t, ok
}

// extractStringLiteral returns the unquoted value of a basic string literal
// expression, or ("", false) for non-literals.
func extractStringLiteral(expr ast.Expr) (string, bool) {
	bl, ok := expr.(*ast.BasicLit)
	if !ok || bl.Kind != token.STRING {
		return "", false
	}
	s, err := strconv.Unquote(bl.Value)
	if err != nil {
		return bl.Value, true
	}
	return s, true
}

// extractStringSliceLiteral extracts literal string elements from a composite
// literal slice expression ([]string{...}). Non-literal elements are
// represented as "<unresolved>" to signal static analysis limitations.
func extractStringSliceLiteral(expr ast.Expr) []string {
	cl, ok := expr.(*ast.CompositeLit)
	if !ok {
		return nil
	}
	result := make([]string, 0, len(cl.Elts))
	for _, elt := range cl.Elts {
		if s, ok := extractStringLiteral(elt); ok {
			result = append(result, s)
		} else {
			result = append(result, "<unresolved>")
		}
	}
	return result
}

// extractNumberSliceLiteral extracts numeric literal elements (as strings) from
// a composite literal slice expression. Used for histogram Buckets fields.
// Variable references are represented as "<VarName>" for traceability.
func extractNumberSliceLiteral(expr ast.Expr) []string {
	cl, ok := expr.(*ast.CompositeLit)
	if !ok {
		// May be a variable reference (e.g., DefaultDurationBuckets).
		if id, ok := expr.(*ast.Ident); ok {
			return []string{"<" + id.Name + ">"}
		}
		if sel, ok := expr.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok {
				return []string{"<" + id.Name + "." + sel.Sel.Name + ">"}
			}
		}
		return nil
	}
	result := make([]string, 0, len(cl.Elts))
	for _, elt := range cl.Elts {
		bl, ok := elt.(*ast.BasicLit)
		if ok {
			result = append(result, bl.Value)
		} else {
			result = append(result, "<unresolved>")
		}
	}
	return result
}
