// Code generated by gocell generate required-deps. DO NOT EDIT.

package accountlockout

import (
	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/validation"
)

// validateRequired verifies every required dependency on the Service struct
// is present and non-typed-nil. Generated from gocell:"required" struct field
// tags; do not edit by hand.
func (s *Service) validateRequired() error {
	if validation.IsNilInterface(s.userRepo) {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"accountlockout.NewService: UserRepository required")
	}
	if s.authzmutator == nil {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"accountlockout.NewService: authzmutate.Mutator required")
	}
	if validation.IsNilInterface(s.emitter) {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"accountlockout.NewService: outbox.CellEmitter required")
	}
	if validation.IsNilInterface(s.clk) {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"accountlockout.NewService: clock.Clock required")
	}
	return nil
}
