version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      golangci-lint:
        patterns:
          - "golangci/golangci-lint-action"
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-testcontainers:
        patterns:
          - "github.com/testcontainers/testcontainers-go*"
      go-opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
      go-x-modules:
        patterns:
          - "golang.org/x/*"
      go-other-modules:
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/testcontainers/testcontainers-go*"
          - "go.opentelemetry.io/*"
          - "golang.org/x/*"
