// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/event/user/locked/v1/contract.yaml

/** event.user.locked.v1.payload */
export interface Payload {
  userId: string;
  actorId: string;
}

/** event.user.locked.v1.headers */
export interface Headers {
  eventId: string;
}
