// Code generated by gocell generate cell. DO NOT EDIT.
// Source: corecells/registrycore/cell.yaml

package registrycore

import (
	"context"

	"github.com/ghbvf/gocell/framework/kernel/cell"
	"github.com/ghbvf/gocell/framework/kernel/metadata"
)

var _ cell.Cell = (*RegistryCore)(nil)

// cellMeta is the canonical metadata literal projected from cell.yaml.
// loadCellMetadata returns the package-scope pointer; cell.go's constructor
// passes it to cell.MustNewBaseCell which deep-copies the value so callers
// cannot mutate the generated literal.
var cellMeta = &metadata.CellMeta{
	ID:               "registrycore",
	Type:             "core",
	ConsistencyLevel: "L1",
	Lifecycle:        "asset",
	Owner:            metadata.OwnerMeta{Team: "platform", Role: "cell-owner"},
	Schema:           metadata.SchemaMeta{Primary: "cell_registry_core"},
	Verify: metadata.CellVerifyMeta{Smoke: []string{
		"smoke.registrycore.startup",
	}},
	GoStructName: metadata.MustNewGoIdentifier("RegistryCore"),
}

func loadCellMetadata() *metadata.CellMeta { return cellMeta.Clone() }

//nolint:gocognit // generated code: complexity intrinsic to cell's subscribe count
func (c *RegistryCore) Init(ctx context.Context, reg cell.Registrar) error {
	if err := c.BaseCell.Init(ctx, reg); err != nil {
		return err
	}
	// initInternal: hand-written init hook (permanent K#04 convention; implement in cell.go)
	if err := c.initInternal(ctx, reg); err != nil {
		return err
	}

	reg.RouteGroup(cell.RouteGroup{
		Listener: cell.PrimaryListener,
		Prefix:   "/api/v1/registry",
		Register: func(mux cell.RouteMux) error {
			var firstErr error
			captureErr := func(err error) {
				if err != nil && firstErr == nil {
					firstErr = err
				}
			}
			mux.Route("/contracts", func(s cell.RouteMux) {
				captureErr(c.writeHandler.RegisterRoutes(s))
				captureErr(c.readHandler.RegisterRoutes(s))
			})
			return firstErr
		},
	})

	return nil
}
