// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/iotdevice/cells/devicecell/slices/devicecommand/slice.yaml

package devicecommand

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "devicecommand",
	BelongsToCell:    "devicecell",
	ConsistencyLevel: "L4",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "http.device.command.enqueue.v1", Role: "serve"},
		{Contract: "http.device.command.dequeue.v1", Role: "serve"},
		{Contract: "http.device.command.report.v1", Role: "serve"},
		{Contract: "http.device.command.ack.v1", Role: "serve"},
		{Contract: "http.device.command.extend-lease.v1", Role: "serve"},
		{Contract: "http.internal.devicecommands.list.v1", Role: "serve"},
		{Contract: "command.device-command.enqueue.v1", Role: "handle"},
		{Contract: "command.device-command.dequeue.v1", Role: "handle"},
		{Contract: "command.device-command.report.v1", Role: "handle"},
		{Contract: "command.device-command.ack.v1", Role: "handle"},
		{Contract: "command.device-command.extend-lease.v1", Role: "handle"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.devicecommand.service",
		},
		Contract: []string{
			"contract.http.device.command.enqueue.v1.serve",
			"contract.http.device.command.dequeue.v1.serve",
			"contract.http.device.command.report.v1.serve",
			"contract.http.device.command.ack.v1.serve",
			"contract.http.device.command.extend-lease.v1.serve",
			"contract.http.internal.devicecommands.list.v1.serve",
			"contract.command.device-command.enqueue.v1.handle",
			"contract.command.device-command.dequeue.v1.handle",
			"contract.command.device-command.report.v1.handle",
			"contract.command.device-command.ack.v1.handle",
			"contract.command.device-command.extend-lease.v1.handle",
		},
	},
	AllowedFiles: []string{
		"examples/iotdevice/cells/devicecell/slices/devicecommand/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta }
