package archtest

// assembly_modules_gen_test.go — AST guards for assembly code-gen artifacts.
//
// Rules:
//
//	ASSEMBLY-MODULES-GEN-01            cmd/*/modules_gen.go must carry the
//	                                   "Code generated … DO NOT EDIT." marker
//	                                   as the first line comment, declare
//	                                   package main, and expose a top-level
//	                                   func generatedCellModules() []CellModule.
//
//	ASSEMBLY-MODULES-SWITCH-FORBIDDEN-02   cmd/*/run.go (and all other *.go
//	                                       files under cmd/) must not contain
//	                                       a switch statement whose case labels
//	                                       are known cell-ID string literals.
//	                                       Use generatedCellModules() from
//	                                       modules_gen.go instead; run
//	                                       `gocell generate assembly --id=<id>`.
//
//	ASSEMBLY-MAXCONSISTENCY-DERIVED-03  kernel/metadata/types.go:
//	                                    AssemblyMeta.MaxConsistencyLevel must
//	                                    carry yaml:"-" to prevent yaml override
//	                                    of the derived-only field.
//
// Background (K#10, PR-V1-ASSEMBLY-YAML-MINIMAL):
//   - modules_gen.go is exclusively machine-generated; hand-edits are caught
//     by the missing DO-NOT-EDIT marker.
//   - The cell-ID switch in run.go was deleted in favor of generatedCellModules();
//     these tests prevent re-introduction of the old dispatch pattern.
//   - MaxConsistencyLevel is derived from cell metadata at runtime and must
//     never be settable from YAML; yaml:"-" is the single enforced mechanism.

import (
	"bufio"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	ruleAssemblyModulesGen01            = "ASSEMBLY-MODULES-GEN-01"
	ruleAssemblySwitchForbidden02       = "ASSEMBLY-MODULES-SWITCH-FORBIDDEN-02"
	ruleAssemblyMaxConsistencyDerived03 = "ASSEMBLY-MAXCONSISTENCY-DERIVED-03"
)

// generatedMarkerPrefix is the exact prefix every modules_gen.go must start with.
const generatedMarkerPrefix = "// Code generated by gocell generate assembly. DO NOT EDIT."

// knownCellIDs is the authoritative set of platform cell IDs declared in
// cells/ (configcore / accesscore / auditcore). It is intentionally
// hardcoded here rather than loaded via metadata.NewParser so that this
// archtest has zero runtime dependencies on the parse path — the rule is a
// static source-code guard, not a metadata-driven rule.
//
// Extend this slice when a new platform cell is added; removing a cell from
// this list does not weaken the guard because the forbidden switch pattern
// must not exist for any currently registered cell.
var knownCellIDs = []string{
	"configcore",
	"accesscore",
	"auditcore",
}

// TestAssemblyModulesGen_HasGeneratedMarker enforces ASSEMBLY-MODULES-GEN-01:
// every cmd/*/modules_gen.go file must carry the canonical DO NOT EDIT marker
// as the first line, declare `package main`, and expose a top-level
// `func generatedCellModules() []CellModule` function.
//
// If no modules_gen.go files exist the test passes (the rule only fires when
// the file is present; new cmd packages without codegen are not penalized).
func TestAssemblyModulesGen_HasGeneratedMarker(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)

	matches, err := filepath.Glob(filepath.Join(root, "cmd", "*", "modules_gen.go"))
	require.NoError(t, err, "%s: glob cmd/*/modules_gen.go", ruleAssemblyModulesGen01)

	if len(matches) == 0 {
		t.Logf("%s: no cmd/*/modules_gen.go files found — nothing to enforce", ruleAssemblyModulesGen01)
		return
	}

	for _, path := range matches {
		path := path
		rel, _ := filepath.Rel(root, path)
		t.Run(rel, func(t *testing.T) {
			t.Parallel()
			checkModulesGenFile(t, path, rel)
		})
	}
}

// checkModulesGenFile verifies the three ASSEMBLY-MODULES-GEN-01 invariants
// for a single modules_gen.go file.
func checkModulesGenFile(t *testing.T, path, rel string) {
	t.Helper()

	// 1. First line must be the exact DO NOT EDIT marker.
	f, err := os.Open(filepath.Clean(path))
	require.NoError(t, err, "%s: open %s", ruleAssemblyModulesGen01, rel)
	defer func() { require.NoError(t, f.Close()) }()

	scanner := bufio.NewScanner(f)
	require.True(t, scanner.Scan(),
		"%s: %s is empty — must start with DO NOT EDIT marker", ruleAssemblyModulesGen01, rel)
	firstLine := scanner.Text()
	assert.True(t,
		strings.HasPrefix(firstLine, generatedMarkerPrefix),
		"%s: %s first line must be %q; got %q",
		ruleAssemblyModulesGen01, rel, generatedMarkerPrefix, firstLine,
	)

	// 2 & 3. Parse the AST to verify package main + generatedCellModules.
	fset := token.NewFileSet()
	af, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
	require.NoError(t, err, "%s: parse %s", ruleAssemblyModulesGen01, rel)

	assert.Equal(t, "main", af.Name.Name,
		"%s: %s must declare `package main`", ruleAssemblyModulesGen01, rel)

	assert.True(t, hasGeneratedCellModulesFunc(af),
		"%s: %s must declare top-level `func generatedCellModules() []CellModule`; "+
			"run `gocell generate assembly` to regenerate",
		ruleAssemblyModulesGen01, rel,
	)
}

// hasGeneratedCellModulesFunc returns true when the file contains a top-level
// function declaration `func generatedCellModules() []CellModule`.
func hasGeneratedCellModulesFunc(af *ast.File) bool {
	for _, decl := range af.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv != nil {
			continue // skip non-functions and methods
		}
		if fn.Name.Name != "generatedCellModules" {
			continue
		}
		ft := fn.Type
		// No parameters.
		if ft.Params != nil && len(ft.Params.List) != 0 {
			continue
		}
		// Returns exactly one result: []CellModule.
		if ft.Results == nil || len(ft.Results.List) != 1 {
			continue
		}
		result := ft.Results.List[0]
		arr, ok := result.Type.(*ast.ArrayType)
		if !ok || arr.Len != nil {
			continue
		}
		id, ok := arr.Elt.(*ast.Ident)
		if !ok || id.Name != "CellModule" {
			continue
		}
		return true
	}
	return false
}

// TestRunGoNoCellIDSwitch enforces ASSEMBLY-MODULES-SWITCH-FORBIDDEN-02:
// no Go source file under cmd/ may contain a switch statement with case labels
// that are known cell-ID string literals. The cell-ID dispatch was replaced by
// generatedCellModules(); re-introducing the switch pattern defeats the
// single-source-of-truth guarantee provided by modules_gen.go.
func TestRunGoNoCellIDSwitch(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	cmdDir := filepath.Join(root, "cmd")

	knownIDSet := make(map[string]struct{}, len(knownCellIDs))
	for _, id := range knownCellIDs {
		knownIDSet[id] = struct{}{}
	}

	// Collect all non-test .go files under cmd/.
	var goFiles []string
	walkErr := filepath.WalkDir(cmdDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == "vendor" || d.Name() == "testdata" {
				return filepath.SkipDir
			}
			return nil
		}
		if strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go") {
			goFiles = append(goFiles, path)
		}
		return nil
	})
	require.NoError(t, walkErr, "%s: walk cmd/", ruleAssemblySwitchForbidden02)

	type violation struct {
		file   string
		line   int
		cellID string
	}
	var violations []violation

	fset := token.NewFileSet()
	for _, path := range goFiles {
		af, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
		if err != nil {
			// Unparseable files are a build error; surface but don't block.
			t.Logf("%s: parse %s: %v", ruleAssemblySwitchForbidden02, path, err)
			continue
		}
		ast.Inspect(af, func(n ast.Node) bool {
			sw, ok := n.(*ast.SwitchStmt)
			if !ok {
				return true
			}
			for _, stmt := range sw.Body.List {
				cc, ok := stmt.(*ast.CaseClause)
				if !ok {
					continue
				}
				for _, expr := range cc.List {
					lit, ok := expr.(*ast.BasicLit)
					if !ok || lit.Kind != token.STRING {
						continue
					}
					unquoted, err := strconv.Unquote(lit.Value)
					if err != nil {
						continue
					}
					if _, found := knownIDSet[unquoted]; found {
						pos := fset.Position(lit.Pos())
						rel, _ := filepath.Rel(root, pos.Filename)
						violations = append(violations, violation{
							file:   rel,
							line:   pos.Line,
							cellID: unquoted,
						})
					}
				}
			}
			return true
		})
	}

	for _, v := range violations {
		t.Errorf("%s: %s:%d — cell-ID literal %q found as switch case; "+
			"use generatedCellModules() from modules_gen.go instead; "+
			"run `gocell generate assembly --id=<id>`",
			ruleAssemblySwitchForbidden02, v.file, v.line, v.cellID)
	}
}

// TestAssemblyMetaMaxConsistencyDerivedTag enforces
// ASSEMBLY-MAXCONSISTENCY-DERIVED-03: AssemblyMeta.MaxConsistencyLevel must
// carry the struct tag `yaml:"-"` so that yaml.v3 strict-mode decoding
// rejects any yaml file that tries to set it, preserving the "derived-only"
// semantic.
func TestAssemblyMetaMaxConsistencyDerivedTag(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	srcPath := filepath.Join(root, "kernel", "metadata", "types.go")

	fset := token.NewFileSet()
	af, err := parser.ParseFile(fset, srcPath, nil, parser.SkipObjectResolution)
	require.NoError(t, err, "%s: parse %s", ruleAssemblyMaxConsistencyDerived03, srcPath)

	structType := findStructDecl(af, "AssemblyMeta")
	require.NotNil(t, structType,
		"%s: type AssemblyMeta struct not found in %s",
		ruleAssemblyMaxConsistencyDerived03, srcPath)

	for _, field := range structType.Fields.List {
		for _, name := range field.Names {
			if name.Name != "MaxConsistencyLevel" {
				continue
			}
			pos := fset.Position(field.Pos())
			rel, _ := filepath.Rel(root, pos.Filename)

			require.NotNil(t, field.Tag,
				"%s: %s:%d AssemblyMeta.MaxConsistencyLevel has no struct tag; "+
					"must be `yaml:\"-\"` to prevent yaml override of derived field",
				ruleAssemblyMaxConsistencyDerived03, rel, pos.Line)

			tag := field.Tag.Value // raw literal including backticks
			// tag looks like "`yaml:\"-\" foo:\"bar\"`"
			unquoted, err := strconv.Unquote(tag)
			if err != nil {
				// tag is a raw string literal (`...`), strip the surrounding backticks.
				unquoted = strings.Trim(tag, "`")
			}

			assert.True(t,
				containsYAMLDashTag(unquoted),
				"%s: %s:%d AssemblyMeta.MaxConsistencyLevel struct tag is %q; "+
					"must be `yaml:\"-\"` to prevent yaml override of derived field",
				ruleAssemblyMaxConsistencyDerived03, rel, pos.Line, tag,
			)
			return // field found; test done
		}
	}

	t.Errorf("%s: field MaxConsistencyLevel not found in AssemblyMeta — "+
		"ensure the field exists and carries `yaml:\"-\"`",
		ruleAssemblyMaxConsistencyDerived03)
}

// containsYAMLDashTag reports whether the raw struct tag string contains a
// yaml tag whose value is exactly "-". It handles both `yaml:"-"` alone and
// mixed tags like `yaml:"-" json:"foo"`.
func containsYAMLDashTag(rawTag string) bool {
	// Use Go's reflect.StructTag semantics via manual parsing to avoid
	// importing reflect in the test. The yaml tag value is the portion between
	// `yaml:"` and `"`, handling the first comma-separated segment.
	const prefix = `yaml:"`
	idx := strings.Index(rawTag, prefix)
	if idx < 0 {
		return false
	}
	rest := rawTag[idx+len(prefix):]
	end := strings.Index(rest, `"`)
	if end < 0 {
		return false
	}
	tagVal := rest[:end]
	// The yaml tag value for "yaml:"-"" is "-" (exactly).
	// If it contains a comma (e.g. "yaml:"name,omitempty""), split on the first comma.
	tagVal = strings.SplitN(tagVal, ",", 2)[0]
	return tagVal == "-"
}

// findStructDecl returns the *ast.StructType for `type <name> struct { … }` in
// af, or nil if not found.
func findStructDecl(af *ast.File, name string) *ast.StructType {
	for _, decl := range af.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != name {
				continue
			}
			if st, ok := ts.Type.(*ast.StructType); ok {
				return st
			}
		}
	}
	return nil
}
