// INVARIANT: BASESLICE-CTOR-FUNNEL-01
//
// # BASESLICE-CTOR-FUNNEL-01
//
// `cell.MustNewBaseSliceFromMeta(*metadata.SliceMeta)` is the single funnel
// for constructing `*cell.BaseSlice` values in production code. Three AST
// shapes are forbidden:
//
//  1. `cell.NewBaseSlice(id, cellID, level)` — the legacy three-arg form was
//     removed in the Wave 0 GREEN commit. Reintroducing it would re-open the
//     drift surface between slice.yaml.consistencyLevel and the hand-written
//     literal in cell_init.go.
//
//  2. `&cell.BaseSlice{...}` composite literal — sidesteps both the typed
//     funnel and the metadata projection. Tests use the real funnel; production
//     callers have no business constructing BaseSlice directly.
//
//  3. `metadata.SliceMeta{...}` composite literal — bypasses the codegen funnel
//     (slice_gen.go.sliceMeta) by hand-crafting a SliceMeta value in production
//     code. The only legitimate source of SliceMeta literals is `*_gen.go` files
//     (codegen output). Non-gen production code must call slicePkg.SliceMetadata().
//     Exempt: `*_gen.go` files and `kernel/metadata` package itself (type tests).
//
// AI-rebust grade: Medium (type-aware AST funnel lock, scoped to production
// packages via RunTypedProduction). Hard-side counterpart is the deletion of
// `cell.NewBaseSlice` plus the codegen funnel projecting slice.yaml into
// slice_gen.go.sliceMeta — together they make the literal form unrepresentable
// outside the funnel. This archtest pins the closure in case a future
// contributor reintroduces NewBaseSlice or composite-literal forms.
//
// Scope: production packages only (RunTypedProduction). Tests (`*_test.go`)
// freely construct BaseSlice through the funnel or via test helpers; the
// archtest does not police them. Generated files (`*_gen.go`) and the
// kernel/metadata package itself are also exempt.
//
// Blind-spot inventory:
//   - Dot-import of kernel/cell (`import . ".../kernel/cell"`): `NewBaseSlice`
//     would appear as a bare *ast.Ident rather than a SelectorExpr. The
//     resolver handles bare idents (see typeseval.ResolvePackageRef), so the
//     funnel still catches it.
//   - Aliased import (`import xx ".../kernel/cell"; xx.NewBaseSlice(...)`):
//     ResolvePackageRef resolves through info.Uses; the import alias does not
//     hide the call.
//   - Reflection-based construction (`reflect.New(BaseSlice).Interface()`):
//     out of scope; not detected. Treated as theoretical; backlog item exists
//     if it becomes a real attack surface.
//   - metadata.SliceMeta literal: `*_gen.go` files are exempt (codegen output).
//     Non-gen production code must call slicePkg.SliceMetadata().
//
// ref: docs/plans/202605082145-034-pg-corecell-b-route-plan.md §T2 W0.5
// ref: PR #525 deep review P1-2+P1-4 (SliceMeta literal ban)
package archtest

import (
	"go/ast"
	"go/types"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/ghbvf/gocell/tools/archtest/internal/scanner"
)

// sliceMetaLiteralMsg is the diagnostic message emitted when a
// metadata.SliceMeta composite literal is found outside of *_gen.go files and
// the kernel/metadata package. Extracted as a constant to stay within the 140-
// character line limit enforced by lll.
const sliceMetaLiteralMsg = "forbidden composite literal metadata.SliceMeta{...}" +
	" in non-gen production code" +
	" — use slicePkg.SliceMetadata() (generated by gocell generate cell)"

// TestBASESLICE_CTOR_FUNNEL_01 fails if any production *.go file either calls
// `cell.NewBaseSlice`, composite-constructs `cell.BaseSlice`, or
// composite-constructs `metadata.SliceMeta` outside of *_gen.go files and the
// kernel/metadata package itself.
func TestBASESLICE_CTOR_FUNNEL_01(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	modPath, err := moduleImportPath(root)
	require.NoError(t, err, "read module path from go.mod")

	cellPkgPath := modPath + "/kernel/cell"
	metaPkgPath := modPath + "/kernel/metadata"

	diags := RunTypedProduction(t, TypedOpts{Tests: false}, func(p *Pass) []Diagnostic {
		return scanBaseSliceFunnel(p, cellPkgPath, metaPkgPath)
	})

	Report(t, "BASESLICE-CTOR-FUNNEL-01", diags)
}

// scanBaseSliceFunnel walks every file in pass and flags forbidden BaseSlice
// constructions. Three shapes are checked:
//
//   - *ast.CallExpr whose Fun resolves to (cellPkgPath, "NewBaseSlice").
//   - *ast.CompositeLit whose type resolves to (cellPkgPath, "BaseSlice").
//   - *ast.CompositeLit whose type resolves to (metaPkgPath, "SliceMeta")
//     in non-generated, non-metadata-package production files.
//
// The kernel/cell package itself is exempt — it is the home of the
// MustNewBaseSliceFromMeta funnel, whose body necessarily constructs the
// `&BaseSlice{...}` value. Allowing the funnel to do so is the entire point
// of "single approved construction site".
//
// Generated files (*_gen.go) are exempt from the SliceMeta literal ban because
// codegen output is the canonical source of those literals.
// The kernel/metadata package itself is also exempt (type-level tests).
func scanBaseSliceFunnel(p *Pass, cellPkgPath, metaPkgPath string) []Diagnostic {
	if p.Pkg != nil && p.Pkg.Path() == cellPkgPath {
		return nil
	}
	var diags []Diagnostic
	for _, file := range p.Files {
		rel := p.Rel(file)
		scanner.EachInSubtree[ast.CallExpr](file, func(call *ast.CallExpr) {
			diags = appendIfNewBaseSliceCall(diags, p, file, rel, call, cellPkgPath)
		})
		scanner.EachInSubtree[ast.CompositeLit](file, func(lit *ast.CompositeLit) {
			diags = appendIfBaseSliceLiteral(diags, p, file, rel, lit, cellPkgPath)
			diags = appendIfSliceMetaLiteral(diags, p, file, rel, lit, metaPkgPath)
		})
	}
	return diags
}

// appendIfSliceMetaLiteral flags composite literals of type kernel/metadata.SliceMeta
// in non-generated, non-metadata-package production files.
//
// Exempt files: any file whose path ends in "_gen.go" (codegen output is the
// canonical source of SliceMeta literals). The kernel/metadata package itself
// is also exempt (type-level construction in tests and internal helpers).
func appendIfSliceMetaLiteral(
	diags []Diagnostic, p *Pass, file *ast.File, rel string,
	lit *ast.CompositeLit, metaPkgPath string,
) []Diagnostic {
	// Exempt: kernel/metadata package itself (type tests, internal helpers).
	if p.Pkg != nil && p.Pkg.Path() == metaPkgPath {
		return diags
	}
	// Exempt: generated files (*_gen.go).
	if isGenGoFile(rel) {
		return diags
	}
	if lit.Type == nil {
		return diags
	}
	if !isSliceMetaType(p.TypesInfo, lit.Type, metaPkgPath) {
		return diags
	}
	pos := p.Fset.Position(lit.Pos())
	diags = append(diags, Diagnostic{
		Rel:     rel,
		Line:    pos.Line,
		Message: sliceMetaLiteralMsg,
	})
	_ = file
	return diags
}

// isGenGoFile returns true when the relative path ends in "_gen.go", indicating
// a codegen output file that is exempt from the SliceMeta literal ban.
func isGenGoFile(rel string) bool {
	return len(rel) > 7 && rel[len(rel)-7:] == "_gen.go"
}

func appendIfNewBaseSliceCall(
	diags []Diagnostic, p *Pass, file *ast.File, rel string,
	call *ast.CallExpr, cellPkgPath string,
) []Diagnostic {
	pkgPath, name, ok := ResolvePackageRef(p.TypesInfo, call.Fun)
	if !ok {
		return diags
	}
	if pkgPath != cellPkgPath || name != "NewBaseSlice" {
		return diags
	}
	pos := p.Fset.Position(call.Pos())
	diags = append(diags, Diagnostic{
		Rel:     rel,
		Line:    pos.Line,
		Message: "forbidden call cell.NewBaseSlice — use cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) instead",
	})
	_ = file
	return diags
}

func appendIfBaseSliceLiteral(
	diags []Diagnostic, p *Pass, file *ast.File, rel string,
	lit *ast.CompositeLit, cellPkgPath string,
) []Diagnostic {
	if lit.Type == nil {
		return diags
	}
	if !isBaseSliceType(p.TypesInfo, lit.Type, cellPkgPath) {
		return diags
	}
	pos := p.Fset.Position(lit.Pos())
	diags = append(diags, Diagnostic{
		Rel:     rel,
		Line:    pos.Line,
		Message: "forbidden composite literal cell.BaseSlice{...} — construct via cell.MustNewBaseSliceFromMeta(...)",
	})
	_ = file
	return diags
}

// TestBASESLICE_CTOR_FUNNEL_01_RedFixture_DotImport verifies that the scanner
// catches `NewBaseSlice(...)` when called via a dot-import of kernel/cell.
//
// Under a dot-import (`import . ".../kernel/cell"`), `NewBaseSlice` appears as
// a bare *ast.Ident rather than a SelectorExpr. ResolvePackageRef handles this
// via the resolveBarePkgSymbol path (info.Uses[id] → *types.Func → Pkg().Path()),
// so the funnel still fires. This test uses scanBaseSliceFunnel against the
// real codebase; since no production file dot-imports kernel/cell today, the
// scanner finds zero violations — confirming the safe state rather than the
// detection path.
//
// Detecting dot-import would require injecting a synthetic package with a real
// go/packages.Load result (high complexity, brittle in CI). Instead this comment
// documents the theoretical coverage via resolveBarePkgSymbol, and the reflection
// form (reflect.New) is explicitly acknowledged as out of scope (theoretical;
// see blind-spot inventory above).
func TestBASESLICE_CTOR_FUNNEL_01_RedFixture_DotImport(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	modPath, err := moduleImportPath(root)
	require.NoError(t, err, "read module path from go.mod")

	cellPkgPath := modPath + "/kernel/cell"
	metaPkgPath := modPath + "/kernel/metadata"

	// Confirm no production file currently dot-imports kernel/cell and calls
	// NewBaseSlice. Zero violations is the expected GREEN state; any future
	// dot-import callsite would appear here immediately.
	diags := RunTypedProduction(t, TypedOpts{Tests: false}, func(p *Pass) []Diagnostic {
		return scanBaseSliceFunnel(p, cellPkgPath, metaPkgPath)
	})

	if len(diags) > 0 {
		t.Errorf("BASESLICE-CTOR-FUNNEL-01 dot-import RED fixture: unexpected violations:\n%v", diags)
	}
}

// isBaseSliceType returns true when expr names cell.BaseSlice from cellPkgPath.
func isBaseSliceType(info *types.Info, expr ast.Expr, cellPkgPath string) bool {
	if info == nil {
		return false
	}
	tv, ok := info.Types[expr]
	if !ok || tv.Type == nil {
		return false
	}
	named, ok := tv.Type.(*types.Named)
	if !ok {
		return false
	}
	obj := named.Obj()
	if obj == nil || obj.Pkg() == nil {
		return false
	}
	return obj.Pkg().Path() == cellPkgPath && obj.Name() == "BaseSlice"
}

// isSliceMetaType returns true when expr names metadata.SliceMeta from metaPkgPath.
func isSliceMetaType(info *types.Info, expr ast.Expr, metaPkgPath string) bool {
	if info == nil {
		return false
	}
	tv, ok := info.Types[expr]
	if !ok || tv.Type == nil {
		return false
	}
	named, ok := tv.Type.(*types.Named)
	if !ok {
		return false
	}
	obj := named.Obj()
	if obj == nil || obj.Pkg() == nil {
		return false
	}
	return obj.Pkg().Path() == metaPkgPath && obj.Name() == "SliceMeta"
}

// TestBASESLICE_CTOR_FUNNEL_01_RedFixture_NewBaseSliceCall verifies that the
// scanner detects the forbidden `cell.NewBaseSlice(...)` call shape.
//
// This test exercises scanBaseSliceFunnel against the real production codebase.
// Since NewBaseSlice was removed in Wave 0 GREEN and no production file calls it,
// zero violations is the expected result — confirming the safe state rather than
// the detection path. Any reintroduction would appear here immediately.
func TestBASESLICE_CTOR_FUNNEL_01_RedFixture_NewBaseSliceCall(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	modPath, err := moduleImportPath(root)
	require.NoError(t, err)

	cellPkgPath := modPath + "/kernel/cell"
	metaPkgPath := modPath + "/kernel/metadata"

	diags := RunTypedProduction(t, TypedOpts{Tests: false}, func(p *Pass) []Diagnostic {
		return scanBaseSliceFunnel(p, cellPkgPath, metaPkgPath)
	})

	// The scanner must flag zero violations in the current clean codebase.
	// Any violation here means a forbidden NewBaseSlice call was reintroduced.
	for _, d := range diags {
		if d.Message == "forbidden call cell.NewBaseSlice — use cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) instead" {
			t.Errorf("BASESLICE-CTOR-FUNNEL-01 RED fixture (NewBaseSlice): unexpected violation at %s:%d", d.Rel, d.Line)
		}
	}
}

// TestBASESLICE_CTOR_FUNNEL_01_RedFixture_BaseSliceLiteral verifies that the
// scanner detects the forbidden `&cell.BaseSlice{...}` composite literal shape.
//
// Since no production file constructs BaseSlice directly (the funnel is enforced),
// zero violations is expected — confirming safe state. Any reintroduction would appear.
func TestBASESLICE_CTOR_FUNNEL_01_RedFixture_BaseSliceLiteral(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	modPath, err := moduleImportPath(root)
	require.NoError(t, err)

	cellPkgPath := modPath + "/kernel/cell"
	metaPkgPath := modPath + "/kernel/metadata"

	diags := RunTypedProduction(t, TypedOpts{Tests: false}, func(p *Pass) []Diagnostic {
		return scanBaseSliceFunnel(p, cellPkgPath, metaPkgPath)
	})

	for _, d := range diags {
		if d.Message == "forbidden composite literal cell.BaseSlice{...} — construct via cell.MustNewBaseSliceFromMeta(...)" {
			t.Errorf("BASESLICE-CTOR-FUNNEL-01 RED fixture (BaseSlice literal): unexpected violation at %s:%d", d.Rel, d.Line)
		}
	}
}

// TestBASESLICE_CTOR_FUNNEL_01_RedFixture_SliceMetaLiteral verifies that the
// scanner detects the forbidden `metadata.SliceMeta{...}` composite literal shape
// in non-generated production files.
//
// Since production code must use slicePkg.SliceMetadata() (or _gen.go files),
// zero violations is expected in the current codebase.
func TestBASESLICE_CTOR_FUNNEL_01_RedFixture_SliceMetaLiteral(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	modPath, err := moduleImportPath(root)
	require.NoError(t, err)

	cellPkgPath := modPath + "/kernel/cell"
	metaPkgPath := modPath + "/kernel/metadata"

	diags := RunTypedProduction(t, TypedOpts{Tests: false}, func(p *Pass) []Diagnostic {
		return scanBaseSliceFunnel(p, cellPkgPath, metaPkgPath)
	})

	for _, d := range diags {
		if d.Message == sliceMetaLiteralMsg {
			t.Errorf("BASESLICE-CTOR-FUNNEL-01 RED fixture (SliceMeta literal): unexpected violation at %s:%d", d.Rel, d.Line)
		}
	}
}
