// INVARIANT: BASESLICE-CTOR-FUNNEL-01
//
// # BASESLICE-CTOR-FUNNEL-01
//
// `cell.MustNewBaseSliceFromMeta(*metadata.SliceMeta)` is the single funnel
// for constructing `*cell.BaseSlice` values in production code. Three AST
// shapes are forbidden:
//
//  1. `cell.NewBaseSlice(id, cellID, level)` — the legacy three-arg form was
//     removed in the Wave 0 GREEN commit. Reintroducing it would re-open the
//     drift surface between slice.yaml.consistencyLevel and the hand-written
//     literal in cell_init.go.
//
//  2. `&cell.BaseSlice{...}` composite literal — sidesteps both the typed
//     funnel and the metadata projection. Tests use the real funnel; production
//     callers have no business constructing BaseSlice directly.
//
//  3. `metadata.SliceMeta{...}` composite literal — bypasses the codegen funnel
//     (slice_gen.go.sliceMeta) by hand-crafting a SliceMeta value in production
//     code. The only legitimate source of SliceMeta literals is `*_gen.go` files
//     (codegen output). Non-gen production code must call slicePkg.SliceMetadata().
//     Exempt: `*_gen.go` files and `kernel/metadata` package itself (type tests).
//
// AI-rebust grade: Medium (type-aware AST funnel lock, scoped to production
// packages via RunTypedProduction). Hard-side counterpart is the deletion of
// `cell.NewBaseSlice` plus the codegen funnel projecting slice.yaml into
// slice_gen.go.sliceMeta — together they make the literal form unrepresentable
// outside the funnel. This archtest pins the closure in case a future
// contributor reintroduces NewBaseSlice or composite-literal forms.
//
// Scope: production packages only (RunTypedProduction). Tests (`*_test.go`)
// freely construct BaseSlice through the funnel or via test helpers; the
// archtest does not police them. Generated files (`*_gen.go`) and the
// kernel/metadata package itself are also exempt.
//
// Blind-spot inventory:
//   - Dot-import of kernel/cell (`import . ".../kernel/cell"`): `NewBaseSlice`
//     would appear as a bare *ast.Ident rather than a SelectorExpr. The
//     resolver handles bare idents (see typeseval.ResolvePackageRef), so the
//     funnel still catches it.
//   - Aliased import (`import xx ".../kernel/cell"; xx.NewBaseSlice(...)`):
//     ResolvePackageRef resolves through info.Uses; the import alias does not
//     hide the call.
//   - Reflection-based construction (`reflect.New(BaseSlice).Interface()`):
//     out of scope; not detected. Treated as theoretical; backlog item exists
//     if it becomes a real attack surface.
//   - metadata.SliceMeta literal: `*_gen.go` files are exempt (codegen output).
//     Non-gen production code must call slicePkg.SliceMetadata().
//
// ref: docs/plans/202605082145-034-pg-corecell-b-route-plan.md §T2 W0.5
// ref: PR #525 deep review P1-2+P1-4 (SliceMeta literal ban)
package archtest

import (
	"go/ast"
	"go/types"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/ghbvf/gocell/tools/archtest/internal/scanner"
)

// sliceMetaLiteralMsg is the diagnostic message emitted when a
// metadata.SliceMeta composite literal is found outside of *_gen.go files and
// the kernel/metadata package. Extracted as a constant to stay within the 140-
// character line limit enforced by lll.
const sliceMetaLiteralMsg = "forbidden composite literal metadata.SliceMeta{...}" +
	" in non-gen production code" +
	" — use slicePkg.SliceMetadata() (generated by gocell generate cell)"

// TestBASESLICE_CTOR_FUNNEL_01 fails if any production *.go file either calls
// `cell.NewBaseSlice`, composite-constructs `cell.BaseSlice`, or
// composite-constructs `metadata.SliceMeta` outside of *_gen.go files and the
// kernel/metadata package itself.
func TestBASESLICE_CTOR_FUNNEL_01(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	modPath, err := moduleImportPath(root)
	require.NoError(t, err, "read module path from go.mod")

	cellPkgPath := modPath + "/kernel/cell"
	metaPkgPath := modPath + "/kernel/metadata"

	diags := RunTypedProduction(t, TypedOpts{Tests: false}, func(p *Pass) []Diagnostic {
		return scanBaseSliceFunnel(p, cellPkgPath, metaPkgPath)
	})

	Report(t, "BASESLICE-CTOR-FUNNEL-01", diags)
}

// scanBaseSliceFunnel walks every file in pass and flags forbidden BaseSlice
// constructions. Three shapes are checked:
//
//   - *ast.CallExpr whose Fun resolves to (cellPkgPath, "NewBaseSlice").
//   - *ast.CompositeLit whose type resolves to (cellPkgPath, "BaseSlice").
//   - *ast.CompositeLit whose type resolves to (metaPkgPath, "SliceMeta")
//     in non-generated, non-metadata-package production files.
//
// The kernel/cell package itself is exempt — it is the home of the
// MustNewBaseSliceFromMeta funnel, whose body necessarily constructs the
// `&BaseSlice{...}` value. Allowing the funnel to do so is the entire point
// of "single approved construction site".
//
// Generated files (*_gen.go) are exempt from the SliceMeta literal ban because
// codegen output is the canonical source of those literals.
// The kernel/metadata package itself is also exempt (type-level tests).
func scanBaseSliceFunnel(p *Pass, cellPkgPath, metaPkgPath string) []Diagnostic {
	if p.Pkg != nil && p.Pkg.Path() == cellPkgPath {
		return nil
	}
	var diags []Diagnostic
	for _, file := range p.Files {
		rel := p.Rel(file)
		scanner.EachInSubtree[ast.CallExpr](file, func(call *ast.CallExpr) {
			diags = appendIfNewBaseSliceCall(diags, p, file, rel, call, cellPkgPath)
		})
		scanner.EachInSubtree[ast.CompositeLit](file, func(lit *ast.CompositeLit) {
			diags = appendIfBaseSliceLiteral(diags, p, file, rel, lit, cellPkgPath)
			diags = appendIfSliceMetaLiteral(diags, p, file, rel, lit, metaPkgPath)
		})
	}
	return diags
}

// appendIfSliceMetaLiteral flags composite literals of type kernel/metadata.SliceMeta
// in non-generated, non-metadata-package production files.
//
// Exempt files: any file whose path ends in "_gen.go" (codegen output is the
// canonical source of SliceMeta literals). The kernel/metadata package itself
// is also exempt (type-level construction in tests and internal helpers).
func appendIfSliceMetaLiteral(
	diags []Diagnostic, p *Pass, file *ast.File, rel string,
	lit *ast.CompositeLit, metaPkgPath string,
) []Diagnostic {
	// Exempt: kernel/metadata package itself (type tests, internal helpers).
	if p.Pkg != nil && p.Pkg.Path() == metaPkgPath {
		return diags
	}
	// Exempt: generated files (*_gen.go).
	if isGenGoFile(rel) {
		return diags
	}
	if lit.Type == nil {
		return diags
	}
	if !isSliceMetaType(p.TypesInfo, lit.Type, metaPkgPath) {
		return diags
	}
	pos := p.Fset.Position(lit.Pos())
	diags = append(diags, Diagnostic{
		Rel:     rel,
		Line:    pos.Line,
		Message: sliceMetaLiteralMsg,
	})
	_ = file
	return diags
}

// isGenGoFile returns true when the relative path ends in "_gen.go", indicating
// a codegen output file that is exempt from the SliceMeta literal ban.
func isGenGoFile(rel string) bool {
	return len(rel) > 7 && rel[len(rel)-7:] == "_gen.go"
}

func appendIfNewBaseSliceCall(
	diags []Diagnostic, p *Pass, file *ast.File, rel string,
	call *ast.CallExpr, cellPkgPath string,
) []Diagnostic {
	pkgPath, name, ok := ResolvePackageRef(p.TypesInfo, call.Fun)
	if !ok {
		return diags
	}
	if pkgPath != cellPkgPath || name != "NewBaseSlice" {
		return diags
	}
	pos := p.Fset.Position(call.Pos())
	diags = append(diags, Diagnostic{
		Rel:     rel,
		Line:    pos.Line,
		Message: "forbidden call cell.NewBaseSlice — use cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) instead",
	})
	_ = file
	return diags
}

func appendIfBaseSliceLiteral(
	diags []Diagnostic, p *Pass, file *ast.File, rel string,
	lit *ast.CompositeLit, cellPkgPath string,
) []Diagnostic {
	if lit.Type == nil {
		return diags
	}
	if !isBaseSliceType(p.TypesInfo, lit.Type, cellPkgPath) {
		return diags
	}
	pos := p.Fset.Position(lit.Pos())
	diags = append(diags, Diagnostic{
		Rel:     rel,
		Line:    pos.Line,
		Message: "forbidden composite literal cell.BaseSlice{...} — construct via cell.MustNewBaseSliceFromMeta(...)",
	})
	_ = file
	return diags
}

// TestBASESLICE_CTOR_FUNNEL_01_RedFixture_BaseSliceLiteral asserts that the
// scanner catches the forbidden `&cell.BaseSlice{}` composite literal shape
// (Shape 2) as defined in the fixture at
// tools/archtest/internal/basesliceredfixture/base_slice_literal.go.
//
// # Why a RED fixture is required
//
// The production scan (TestBASESLICE_CTOR_FUNNEL_01) asserts zero violations.
// Without a known-positive counterpart, a broken scanner silently passes
// everything. This test loads the fixture package under the archtest_fixture
// build tag — which contains a deliberate &cell.BaseSlice{} literal — and
// asserts the scanner fires at least once, proving the detection path works.
//
// # Fixture shape
//
//	var redBaseSliceLiteral = &cell.BaseSlice{}  // in base_slice_literal.go
//
// This is a *ast.CompositeLit with type resolving to (kernel/cell, "BaseSlice").
// The scanner must hit appendIfBaseSliceLiteral and emit a diagnostic.
func TestBASESLICE_CTOR_FUNNEL_01_RedFixture_BaseSliceLiteral(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	modPath, err := moduleImportPath(root)
	require.NoError(t, err, "read module path from go.mod")

	cellPkgPath := modPath + "/kernel/cell"
	metaPkgPath := modPath + "/kernel/metadata"

	diags := RunTyped(t,
		TypedOpts{Tests: false, Tags: []string{"archtest_fixture"}},
		[]string{"./tools/archtest/internal/basesliceredfixture/..."},
		func(p *Pass) []Diagnostic {
			return scanBaseSliceFunnel(p, cellPkgPath, metaPkgPath)
		},
	)

	for _, d := range diags {
		t.Logf("RED fixture hit: %s:%d %s", d.Rel, d.Line, d.Message)
	}

	var hitCount int
	for _, d := range diags {
		if d.Message == "forbidden composite literal cell.BaseSlice{...} — construct via cell.MustNewBaseSliceFromMeta(...)" {
			hitCount++
		}
	}
	if hitCount == 0 {
		t.Errorf("BASESLICE-CTOR-FUNNEL-01 RED fixture (BaseSlice literal): " +
			"scanner found 0 hits; expected ≥ 1 from base_slice_literal.go — " +
			"the detector appendIfBaseSliceLiteral may be broken")
	}
}

// TestBASESLICE_CTOR_FUNNEL_01_RedFixture_SliceMetaLiteral asserts that the
// scanner catches the forbidden `metadata.SliceMeta{...}` composite literal
// shape (Shape 3) as defined in the fixture at
// tools/archtest/internal/basesliceredfixture/slice_meta_literal.go.
//
// # Why a RED fixture is required
//
// The production scan (TestBASESLICE_CTOR_FUNNEL_01) asserts zero violations.
// Without a known-positive counterpart, a broken scanner silently passes
// everything. This test loads the fixture package under the archtest_fixture
// build tag — which contains a deliberate metadata.SliceMeta{...} literal in a
// non-gen file — and asserts the scanner fires at least once.
//
// # Fixture shape
//
//	var redSliceMetaLiteral = metadata.SliceMeta{
//	    ID: "red-fixture-slice", BelongsToCell: "red-fixture-cell", ConsistencyLevel: "L1",
//	}  // in slice_meta_literal.go (not a *_gen.go file, so not exempt)
//
// This is a *ast.CompositeLit with type resolving to (kernel/metadata, "SliceMeta")
// in a non-gen file. The scanner must hit appendIfSliceMetaLiteral.
func TestBASESLICE_CTOR_FUNNEL_01_RedFixture_SliceMetaLiteral(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	modPath, err := moduleImportPath(root)
	require.NoError(t, err, "read module path from go.mod")

	cellPkgPath := modPath + "/kernel/cell"
	metaPkgPath := modPath + "/kernel/metadata"

	diags := RunTyped(t,
		TypedOpts{Tests: false, Tags: []string{"archtest_fixture"}},
		[]string{"./tools/archtest/internal/basesliceredfixture/..."},
		func(p *Pass) []Diagnostic {
			return scanBaseSliceFunnel(p, cellPkgPath, metaPkgPath)
		},
	)

	for _, d := range diags {
		t.Logf("RED fixture hit: %s:%d %s", d.Rel, d.Line, d.Message)
	}

	var hitCount int
	for _, d := range diags {
		if d.Message == sliceMetaLiteralMsg {
			hitCount++
		}
	}
	if hitCount == 0 {
		t.Errorf("BASESLICE-CTOR-FUNNEL-01 RED fixture (SliceMeta literal): " +
			"scanner found 0 hits; expected ≥ 1 from slice_meta_literal.go — " +
			"the detector appendIfSliceMetaLiteral may be broken")
	}
}

// TestBASESLICE_CTOR_FUNNEL_01_GreenProduction asserts that the production
// codebase currently has zero BASESLICE-CTOR-FUNNEL-01 violations.
//
// This is the canonical GREEN baseline. It is separate from
// TestBASESLICE_CTOR_FUNNEL_01 (which uses RunTypedProduction) so the two RED
// fixture tests above (which use RunTyped with archtest_fixture tags) share the
// same test file and make the RED+GREEN coverage pair easy to review together.
//
// A pass here + a fail in the RED fixture tests above means the scanner is
// broken. A fail here means a new violation was introduced.
func TestBASESLICE_CTOR_FUNNEL_01_GreenProduction(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	modPath, err := moduleImportPath(root)
	require.NoError(t, err, "read module path from go.mod")

	cellPkgPath := modPath + "/kernel/cell"
	metaPkgPath := modPath + "/kernel/metadata"

	diags := RunTypedProduction(t, TypedOpts{Tests: false}, func(p *Pass) []Diagnostic {
		return scanBaseSliceFunnel(p, cellPkgPath, metaPkgPath)
	})

	if len(diags) > 0 {
		t.Errorf("BASESLICE-CTOR-FUNNEL-01 production GREEN: expected 0 violations, got %d:\n%v",
			len(diags), diags)
	}
}

// isBaseSliceType returns true when expr names cell.BaseSlice from cellPkgPath.
func isBaseSliceType(info *types.Info, expr ast.Expr, cellPkgPath string) bool {
	if info == nil {
		return false
	}
	tv, ok := info.Types[expr]
	if !ok || tv.Type == nil {
		return false
	}
	named, ok := tv.Type.(*types.Named)
	if !ok {
		return false
	}
	obj := named.Obj()
	if obj == nil || obj.Pkg() == nil {
		return false
	}
	return obj.Pkg().Path() == cellPkgPath && obj.Name() == "BaseSlice"
}

// isSliceMetaType returns true when expr names metadata.SliceMeta from metaPkgPath.
func isSliceMetaType(info *types.Info, expr ast.Expr, metaPkgPath string) bool {
	if info == nil {
		return false
	}
	tv, ok := info.Types[expr]
	if !ok || tv.Type == nil {
		return false
	}
	named, ok := tv.Type.(*types.Named)
	if !ok {
		return false
	}
	obj := named.Obj()
	if obj == nil || obj.Pkg() == nil {
		return false
	}
	return obj.Pkg().Path() == metaPkgPath && obj.Name() == "SliceMeta"
}
