// CODEGEN-CELL-GEN-01..04 — invariant gates for K#04 codegen output.
//
// These gates protect the generator's contract on cells that have opted
// into codegen (the "enabled" set). Until K#04 PR-4 finishes the rollout,
// the enabled set is a small whitelist; uncodegenned cells are skipped to
// keep the build green during the staged migration.
//
// Whitelist policy: the whitelist below is the explicit, code-checked
// technical debt for K#04. PR-4 (the migration PR that flips every
// remaining cell) MUST replace the slice with a wildcard policy
// ("every cell with goStructName set is enabled"); this comment exists
// so the cleanup is impossible to forget.
//
// Gate IDs:
//
//	CODEGEN-CELL-GEN-01           Enabled cell directory has cell_gen.go and
//	                               cell.yaml declares listeners + each child slice
//	                               declares routeMounts (or has empty mounts but
//	                               at least one of {routeMounts, subscribes}).
//	CODEGEN-CELL-GEN-02           cell_gen.go starts with the canonical gocell
//	                               generated header.
//	CODEGEN-USER-FILE-OVERLAP-01   cell.go in the same package must NOT define
//	                               func (c *<StructName>) Init — Init is owned
//	                               by cell_gen.go after migration.
//	CODEGEN-MARKER-NONE-01         No "// +cell:" / "// +slice:" marker comments
//	                               in the source tree (K#05 reserves marker
//	                               syntax; staging marker code under K#04 would
//	                               split the path into a yaml + marker dual mode).
//
// ref: docs/plans/202605011500-029-master-roadmap.md K#04
package archtest

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/ghbvf/gocell/kernel/metadata"
)

const (
	codegenGenHeader         = "// Code generated by gocell generate cell. DO NOT EDIT."
	codegenMarkerCellPrefix  = "// +cell:"
	codegenMarkerSlicePrefix = "// +slice:"
)

// codegenEnabledCells is the explicit whitelist of cells that have opted
// into K#04 codegen for PR-1. Each entry is the value of
// CellMeta.Dir (the directory segment, e.g. "ordercell") so the gate
// matches against parsed metadata, not filesystem paths.
//
// PR-4 of the K#04 path will replace this with a wildcard policy. Until
// then, the whitelist is the load-bearing record of which cells the gate
// enforces.
var codegenEnabledCells = map[string]bool{
	"ordercell": true,
}

// TestCodegenCellGen01_EnabledCellHasGen verifies CODEGEN-CELL-GEN-01.
// For every enabled cell: the cell directory must contain cell_gen.go,
// cell.yaml must declare goStructName + at least one listener, and each
// child slice with routeMounts must reference a declared listener.
func TestCodegenCellGen01_EnabledCellHasGen(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	project := mustParseProject(t, root)

	for _, cell := range project.Cells {
		if !codegenEnabledCells[cell.Dir] {
			continue
		}
		dir := filepath.Join(root, filepath.Dir(cell.File))
		genPath := filepath.Join(dir, "cell_gen.go")
		if _, err := os.Stat(genPath); err != nil {
			t.Errorf("CODEGEN-CELL-GEN-01: cell %q is enabled but missing %s; run `gocell generate cell %s`",
				cell.ID, genPath, cell.ID)
			continue
		}
		if cell.GoStructName == "" {
			t.Errorf("CODEGEN-CELL-GEN-01: cell %q is enabled but cell.yaml lacks goStructName", cell.ID)
		}
		if len(cell.Listeners) == 0 {
			// allow zero listeners only when no slice declares routeMounts
			if hasAnyRouteMount(project, cell.ID) {
				t.Errorf("CODEGEN-CELL-GEN-01: cell %q has slice routeMounts but cell.yaml declares no listeners", cell.ID)
			}
		}
	}
}

// TestCodegenCellGen02_GeneratedHeader verifies CODEGEN-CELL-GEN-02. Every
// existing cell_gen.go (regardless of whitelist) must start with the
// canonical gocell-generated header.
func TestCodegenCellGen02_GeneratedHeader(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	files := findGeneratedCellFiles(t, root)
	for _, f := range files {
		content, err := os.ReadFile(f) //nolint:gosec // archtest scans repo paths it discovered itself
		if err != nil {
			t.Fatalf("CODEGEN-CELL-GEN-02: read %s: %v", f, err)
		}
		first := firstLine(content)
		if !strings.HasPrefix(first, codegenGenHeader) {
			t.Errorf("CODEGEN-CELL-GEN-02: %s does not start with %q (got %q)", f, codegenGenHeader, first)
		}
	}
}

// TestCodegenUserFileOverlap01 verifies CODEGEN-USER-FILE-OVERLAP-01. For
// each cell directory containing cell_gen.go, every other .go file in the
// same package must NOT define func (c *<StructName>) Init.
func TestCodegenUserFileOverlap01(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	project := mustParseProject(t, root)

	for _, cell := range project.Cells {
		dir := filepath.Join(root, filepath.Dir(cell.File))
		genPath := filepath.Join(dir, "cell_gen.go")
		if _, err := os.Stat(genPath); err != nil {
			continue // only check cells that have a generated file
		}
		if cell.GoStructName == "" {
			continue
		}
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatalf("CODEGEN-USER-FILE-OVERLAP-01: read dir %s: %v", dir, err)
		}
		for _, e := range entries {
			name := e.Name()
			if e.IsDir() || !strings.HasSuffix(name, ".go") {
				continue
			}
			if name == "cell_gen.go" || strings.HasSuffix(name, "_test.go") {
				continue
			}
			path := filepath.Join(dir, name)
			if hasInitMethod(t, path, cell.GoStructName) {
				t.Errorf("CODEGEN-USER-FILE-OVERLAP-01: %s defines func (c *%s) Init — Init is owned by cell_gen.go; "+
					"move business init logic into func (c *%s) initInternal", path, cell.GoStructName, cell.GoStructName)
			}
		}
	}
}

// TestCodegenMarkerNone01 verifies CODEGEN-MARKER-NONE-01. The K#04 PR-1
// stage forbids marker comments — they are reserved for K#05.
func TestCodegenMarkerNone01(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	violations := scanForMarkerComments(t, root)
	for _, v := range violations {
		t.Errorf("CODEGEN-MARKER-NONE-01: marker comment found at %s — K#04 stage forbids // +cell: / // +slice: markers (reserved for K#05)", v)
	}
}

// --- helpers ---------------------------------------------------------------

func mustParseProject(t *testing.T, root string) *metadata.ProjectMeta {
	t.Helper()
	p, err := metadata.NewParser(root).Parse()
	if err != nil {
		t.Fatalf("metadata parse failed: %v", err)
	}
	return p
}

func hasAnyRouteMount(p *metadata.ProjectMeta, cellID string) bool {
	for _, s := range p.Slices {
		if s.BelongsToCell != cellID {
			continue
		}
		if len(s.RouteMounts) > 0 {
			return true
		}
	}
	return false
}

// findGeneratedCellFiles walks cells/ and examples/*/cells/ collecting
// all cell_gen.go files. Excludes vendor / worktrees / testdata.
func findGeneratedCellFiles(t *testing.T, root string) []string {
	t.Helper()
	var found []string
	roots := []string{
		filepath.Join(root, "cells"),
		filepath.Join(root, "examples"),
	}
	for _, scanRoot := range roots {
		_ = filepath.WalkDir(scanRoot, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				// Skip unreadable subtrees rather than aborting the gate
				// (e.g. transient permission issues on CI).
				return nil //nolint:nilerr // walk continues past unreadable entries by design
			}
			if d.IsDir() {
				switch d.Name() {
				case "vendor", "worktrees", "testdata", ".git", "node_modules":
					return filepath.SkipDir
				}
				return nil
			}
			if d.Name() == "cell_gen.go" {
				found = append(found, path)
			}
			return nil
		})
	}
	sort.Strings(found)
	return found
}

// firstLine returns the first line of content (without trailing newline),
// or the entire content when no newline is present.
func firstLine(content []byte) string {
	if i := strings.IndexByte(string(content), '\n'); i >= 0 {
		return string(content[:i])
	}
	return string(content)
}

// hasInitMethod reports whether file at path declares
// `func (c *<structName>) Init(...)`.
func hasInitMethod(t *testing.T, path string, structName string) bool {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		// Treat parse failure as non-violation (build-test will catch it).
		return false
	}
	for _, decl := range f.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Recv == nil || len(fd.Recv.List) == 0 || fd.Name == nil {
			continue
		}
		if fd.Name.Name != "Init" {
			continue
		}
		if receiverTypeName(fd.Recv.List[0].Type) == structName {
			return true
		}
	}
	return false
}

// scanForMarkerComments walks the source tree and reports any line whose
// trimmed text starts with codegenMarkerCellPrefix or codegenMarkerSlicePrefix.
// Excludes vendor / worktrees / .git / node_modules / testdata / archtest fixtures
// (the archtest fixtures are deliberate ground-truth cases for other gates).
func scanForMarkerComments(t *testing.T, root string) []string {
	t.Helper()
	var hits []string
	skipDirs := map[string]bool{
		"vendor": true, "worktrees": true, "testdata": true,
		".git": true, "node_modules": true,
	}
	_ = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			// Skip unreadable entry; gate is best-effort and the build/test
			// step will surface real permission issues.
			return nil //nolint:nilerr // walk continues past unreadable entries by design
		}
		if d.IsDir() {
			if skipDirs[d.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		// Skip this archtest file itself — its constants reference the
		// marker prefixes but as string literals, not comments.
		if filepath.Base(path) == "codegen_cell_gen_test.go" {
			return nil
		}
		content, err := os.ReadFile(path) //nolint:gosec // archtest scans repo paths it discovered itself
		if err != nil {
			// Same best-effort policy: unreadable file does not fail the gate.
			return nil //nolint:nilerr // walk continues past unreadable entries by design
		}
		for i, line := range strings.Split(string(content), "\n") {
			trim := strings.TrimSpace(line)
			if strings.HasPrefix(trim, codegenMarkerCellPrefix) ||
				strings.HasPrefix(trim, codegenMarkerSlicePrefix) {
				hits = append(hits, filepath.ToSlash(path)+":"+strconv.Itoa(i+1))
			}
		}
		return nil
	})
	sort.Strings(hits)
	return hits
}
