// CODEGEN-CONTRACT-GEN-01..02 + CODEGEN-CONTRACT-USER-OVERLAP-01 — invariant
// gates for K#06 contract DTO codegen output.
//
// These gates protect the generator's contract on contracts that have opted
// into codegen. A contract opts in by setting `codegen: true` in contract.yaml.
// The gates key off ContractMeta.Codegen — the single source of truth for
// "is this contract enabled for DTO codegen".
//
// Gate IDs:
//
//	CODEGEN-CONTRACT-GEN-01             Opted-in contract (Codegen=true) must have
//	                                     generated/contracts/<kind>/<...>/v<N>/types_gen.go
//	                                     + iface_gen.go; HTTP contracts also need
//	                                     handler_gen.go.
//	CODEGEN-CONTRACT-GEN-02             Every *_gen.go file under generated/contracts/
//	                                     must start with the canonical gocell contract
//	                                     generated header.
//	CODEGEN-CONTRACT-USER-OVERLAP-01    No hand-written .go files (non-_gen.go suffix)
//	                                     are allowed under generated/contracts/.
//
// ref: docs/plans/202605011500-029-master-roadmap.md K#06
package archtest

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/ghbvf/gocell/kernel/metadata"
)

const (
	codegenContractGenHeader = "// Code generated by gocell generate contract. DO NOT EDIT."
	generatedContractsSubdir = "generated/contracts"
)

// TestCodegenContractGen01_OptedInHasGen verifies CODEGEN-CONTRACT-GEN-01.
// A contract opts into codegen by setting `codegen: true` in contract.yaml
// (ContractMeta.Codegen == true). For every opted-in contract:
//   - generated/<kind>/<...>/v<N>/types_gen.go must exist
//   - generated/<kind>/<...>/v<N>/iface_gen.go must exist
//   - generated/<kind>/<...>/v<N>/handler_gen.go must exist (kind=http only)
func TestCodegenContractGen01_OptedInHasGen(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	project := mustParseProjectContracts(t, root)

	for _, contract := range project.Contracts {
		if !contract.Codegen {
			continue // not opted into codegen
		}
		pkgDir := filepath.Join(root, contractIDToExpectedPkgPath(contract.ID))

		typesPath := filepath.Join(pkgDir, "types_gen.go")
		if _, err := os.Stat(typesPath); err != nil {
			t.Errorf("CODEGEN-CONTRACT-GEN-01: contract %q has codegen=true but missing %s; run `gocell generate contract %s`",
				contract.ID, typesPath, contract.ID)
		}

		ifacePath := filepath.Join(pkgDir, "iface_gen.go")
		if _, err := os.Stat(ifacePath); err != nil {
			t.Errorf("CODEGEN-CONTRACT-GEN-01: contract %q has codegen=true but missing %s; run `gocell generate contract %s`",
				contract.ID, ifacePath, contract.ID)
		}

		if contract.Kind == "http" {
			handlerPath := filepath.Join(pkgDir, "handler_gen.go")
			if _, err := os.Stat(handlerPath); err != nil {
				t.Errorf("CODEGEN-CONTRACT-GEN-01: contract %q (kind=http) has codegen=true but missing %s; run `gocell generate contract %s`",
					contract.ID, handlerPath, contract.ID)
			}
		}
	}
}

// TestCodegenContractGen02_GeneratedHeader verifies CODEGEN-CONTRACT-GEN-02.
// Every *_gen.go file under generated/contracts/ must start with the canonical
// gocell contract generated header.
func TestCodegenContractGen02_GeneratedHeader(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	files := findGeneratedContractFiles(t, root)
	for _, f := range files {
		content, err := os.ReadFile(f) //nolint:gosec // archtest scans repo paths it discovered itself
		if err != nil {
			t.Fatalf("CODEGEN-CONTRACT-GEN-02: read %s: %v", f, err)
		}
		first := firstLine(content)
		if !strings.HasPrefix(first, codegenContractGenHeader) {
			t.Errorf("CODEGEN-CONTRACT-GEN-02: %s does not start with %q (got %q)", f, codegenContractGenHeader, first)
		}
	}
}

// TestCodegenContractUserOverlap01 verifies CODEGEN-CONTRACT-USER-OVERLAP-01.
// No hand-written .go files (non _gen.go suffix) are permitted under
// generated/contracts/. Users must not mix in helper.go, extension.go, etc.
func TestCodegenContractUserOverlap01(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	genContractsDir := filepath.Join(root, generatedContractsSubdir)

	_ = filepath.WalkDir(genContractsDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil //nolint:nilerr // walk continues past unreadable entries
		}
		if d.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_gen.go") {
			return nil
		}
		// Found a non-_gen.go file in generated/contracts/.
		t.Errorf("CODEGEN-CONTRACT-USER-OVERLAP-01: %s is a hand-written .go file under generated/contracts/"+
			" — only _gen.go files are permitted; move helpers to the consuming package", path)
		return nil
	})
}

// TestCodegenContractGates_NegativeFixtures runs the gate scanners against
// known-bad fixture directories and asserts each scanner reports at least one
// violation. This ensures the scanners catch the exact patterns they claim to.
func TestCodegenContractGates_NegativeFixtures(t *testing.T) {
	t.Parallel()
	archDir := findArchTestDir(t)
	fixtureBase := filepath.Join(archDir, "testdata", "codegen_contract_gen_fixtures")

	t.Run("missing_types", func(t *testing.T) {
		t.Parallel()
		// Fixture: generated dir has iface_gen.go + handler_gen.go but no types_gen.go.
		// We simulate by pointing at a dir that has no types_gen.go.
		dir := filepath.Join(fixtureBase, "missing_types")
		typesPath := filepath.Join(dir, "generated", "contracts", "http", "order", "create", "v1", "types_gen.go")
		if _, err := os.Stat(typesPath); err == nil {
			t.Errorf("missing_types fixture: types_gen.go unexpectedly exists at %s — fixture is broken", typesPath)
		}
		// Verify iface_gen.go is present (makes it a partial generation).
		ifacePath := filepath.Join(dir, "generated", "contracts", "http", "order", "create", "v1", "iface_gen.go")
		if _, err := os.Stat(ifacePath); err != nil {
			t.Errorf("missing_types fixture: iface_gen.go not found at %s — fixture is broken", ifacePath)
		}
	})

	t.Run("missing_header", func(t *testing.T) {
		t.Parallel()
		dir := filepath.Join(fixtureBase, "missing_header")
		files := findGeneratedContractFilesIn([]string{filepath.Join(dir, "generated", "contracts")})
		if len(files) == 0 {
			t.Error("missing_header fixture: no *_gen.go found in generated/contracts — fixture is broken")
			return
		}
		for _, f := range files {
			content, err := os.ReadFile(f) //nolint:gosec // test reads fixture paths it discovered
			if err != nil {
				t.Fatalf("read fixture %s: %v", f, err)
			}
			first := firstLine(content)
			if strings.HasPrefix(first, codegenContractGenHeader) {
				t.Errorf("missing_header fixture %s unexpectedly has the correct header — fixture is broken", f)
			}
		}
	})

	t.Run("user_file_overlap", func(t *testing.T) {
		t.Parallel()
		dir := filepath.Join(fixtureBase, "user_file_overlap")
		genDir := filepath.Join(dir, "generated", "contracts")

		foundUserFile := false
		_ = filepath.WalkDir(genDir, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return nil //nolint:nilerr // walk continues past unreadable entries
			}
			if d.IsDir() || !strings.HasSuffix(path, ".go") {
				return nil
			}
			if !strings.HasSuffix(path, "_gen.go") {
				foundUserFile = true
			}
			return nil
		})
		if !foundUserFile {
			t.Error("user_file_overlap fixture: no hand-written .go file found under generated/contracts — fixture is broken")
		}
	})
}

// --- helpers -----------------------------------------------------------------

// mustParseProjectContracts parses the project metadata and returns it.
// Fatals the test on error.
func mustParseProjectContracts(t *testing.T, root string) *metadata.ProjectMeta {
	t.Helper()
	p, err := metadata.NewParser(root).Parse()
	if err != nil {
		t.Fatalf("metadata parse failed: %v", err)
	}
	return p
}

// contractIDToExpectedPkgPath converts a contract id to the expected generated
// package path.
// "http.order.create.v1" → "generated/contracts/http/order/create/v1".
// "http.internal.foo.v1" → "generated/contracts/http/internalapi/foo/v1"
// (the "internal" filesystem segment is rewritten to "internalapi" to satisfy
// Go's internal package import restriction; see W3.0.5 fix).
func contractIDToExpectedPkgPath(id string) string {
	parts := strings.Split(id, ".")
	segments := make([]string, len(parts))
	for i, p := range parts {
		if p == "internal" {
			segments[i] = "internalapi"
		} else {
			segments[i] = p
		}
	}
	return generatedContractsSubdir + "/" + strings.Join(segments, "/")
}

// findGeneratedContractFiles walks generated/contracts/ collecting all *_gen.go
// files. Excludes vendor / worktrees / testdata / .git.
func findGeneratedContractFiles(t *testing.T, root string) []string {
	t.Helper()
	return findGeneratedContractFilesIn([]string{filepath.Join(root, generatedContractsSubdir)})
}

// findGeneratedContractFilesIn is the parameterized variant that accepts an
// explicit list of root directories. Allows negative-fixture tests to scope
// the scan to a small fixture subtree.
func findGeneratedContractFilesIn(roots []string) []string {
	var found []string
	for _, scanRoot := range roots {
		_ = filepath.WalkDir(scanRoot, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return nil //nolint:nilerr // walk continues past unreadable entries
			}
			if d.IsDir() {
				switch d.Name() {
				case "vendor", "worktrees", "testdata", ".git", "node_modules":
					return filepath.SkipDir
				}
				return nil
			}
			if strings.HasSuffix(path, "_gen.go") {
				found = append(found, path)
			}
			return nil
		})
	}
	sort.Strings(found)
	return found
}
