// INVARIANT: CODEGEN-LOCALPREFIX-SEALED-01
//
// # CODEGEN-LOCALPREFIX-SEALED-01
//
// Invariant: the process-global goimports knob `imports.LocalPrefix`
// (golang.org/x/tools/imports) may be assigned in exactly ONE place —
// tools/codegen/render.go (processImports). Every other write is forbidden.
//
// Why: render.go derives the module-local import prefix from the modulePath
// passed positionally to FormatGoSource/Render (#1083 — so generated files
// group local imports the way the *consuming* repo's golangci-lint gate
// expects). If any other site assigned imports.LocalPrefix it could pin the
// global to a stale/framework value, silently regrouping generated bytes and
// defeating the per-call module-awareness. Sealing the write to render.go is
// the upstream half of the funnel; the downstream half is the type system:
// FormatGoSource/Render require modulePath as a positional argument, so
// "format without a module path" is a compile error (no setter, no default).
//
// AI-robust (funnel, double-locked):
//   - Downstream Hard: modulePath is a required positional arg on the single
//     formatter outlet — omission is unrepresentable (compile error), mirroring
//     CLOCK-POSITIONAL-INJECTION-01.
//   - Upstream Hard: this archtest makes any `imports.LocalPrefix = …` write
//     outside the sanctioned render.go callsite fail CI. Combined, the funnel
//     has no bypass: you cannot reach the global except through render.go, and
//     you cannot reach render.go's formatter without supplying a module path.
//
// Blind-spot self-check: detector form-uniqueness is validated by
// TestCODEGEN_LOCALPREFIX_SEALED_01_DetectsForeignWrite, which parses a
// synthetic non-render file containing `imports.LocalPrefix = x` and asserts
// the detector flags it — proving the rule is not vacuously passing. Forms NOT
// covered by the selector-match detector (and asserted absent in production by
// the main scan returning the render.go write as the sole match): dot-imported
// `. "golang.org/x/tools/imports"` followed by a bare `LocalPrefix = x`
// assignment. No production file dot-imports the goimports package; if one ever
// does, extend allowedLocalPrefixWriteFile handling accordingly.
package archtest

import (
	"go/ast"
	"go/parser"
	"go/token"
	"testing"
)

// allowedLocalPrefixWriteFile is the single sanctioned writer of the
// imports.LocalPrefix process-global. Relocating the write requires updating
// this constant in lockstep.
const allowedLocalPrefixWriteFile = "tools/codegen/render.go"

// goimportsPkgPath is the canonical import path whose LocalPrefix global is sealed.
const goimportsPkgPath = "golang.org/x/tools/imports"

// TestCODEGEN_LOCALPREFIX_SEALED_01 scans Go files under tools/ and cmd/ for
// assignments to imports.LocalPrefix and fails on any outside render.go.
func TestCODEGEN_LOCALPREFIX_SEALED_01(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	diags := Run(t, DirsScope(root, []string{"tools", "cmd"}), func(p *Pass) []Diagnostic {
		var out []Diagnostic
		for _, f := range p.Files {
			rel := p.Rel(f)
			if rel == allowedLocalPrefixWriteFile {
				continue
			}
			out = append(out, findLocalPrefixWrites(p.Fset, f, rel)...)
		}
		return out
	})
	Report(t, "CODEGEN-LOCALPREFIX-SEALED-01", diags)
}

// TestCODEGEN_LOCALPREFIX_SEALED_01_DetectsForeignWrite is the reverse
// self-check: it proves the detector is not vacuous by feeding it a synthetic
// file that writes imports.LocalPrefix from a non-render path and asserting a
// diagnostic is produced.
func TestCODEGEN_LOCALPREFIX_SEALED_01_DetectsForeignWrite(t *testing.T) {
	t.Parallel()
	src := `package foo

import "golang.org/x/tools/imports"

func bypass() {
	imports.LocalPrefix = "github.com/evil/override"
}
`
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "tools/foo/foo.go", src, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse synthetic source: %v", err)
	}
	hits := findLocalPrefixWrites(fset, f, "tools/foo/foo.go")
	if len(hits) != 1 {
		t.Fatalf("detector should flag exactly one foreign imports.LocalPrefix write, got %d: %+v", len(hits), hits)
	}

	// And it must NOT flag a write under an aliased import the same way unless
	// the selector resolves — confirm the alias path also works.
	aliasSrc := `package foo

import goi "golang.org/x/tools/imports"

func bypass() { goi.LocalPrefix = "x" }
`
	af, err := parser.ParseFile(fset, "tools/foo/alias.go", aliasSrc, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse aliased source: %v", err)
	}
	if got := findLocalPrefixWrites(fset, af, "tools/foo/alias.go"); len(got) != 1 {
		t.Fatalf("detector should resolve aliased imports.LocalPrefix write, got %d", len(got))
	}
}

// findLocalPrefixWrites returns a diagnostic for each assignment to
// <importsAlias>.LocalPrefix in f, where importsAlias is the local name f binds
// golang.org/x/tools/imports to. Returns nil when f does not import the package.
func findLocalPrefixWrites(fset *token.FileSet, f *ast.File, rel string) []Diagnostic {
	alias, ok := importsAlias(f)
	if !ok {
		return nil
	}
	var out []Diagnostic
	EachInSubtree[ast.AssignStmt](f, func(a *ast.AssignStmt) {
		for _, lhs := range a.Lhs {
			sel, isSel := lhs.(*ast.SelectorExpr)
			if !isSel || sel.Sel == nil || sel.Sel.Name != "LocalPrefix" {
				continue
			}
			ident, isIdent := sel.X.(*ast.Ident)
			if !isIdent || ident.Name != alias {
				continue
			}
			out = append(out, Diagnostic{
				Rel:  rel,
				Line: fset.Position(sel.Pos()).Line,
				Message: "assignment to imports.LocalPrefix outside " + allowedLocalPrefixWriteFile +
					"; the goimports local-prefix global is sealed — generated import grouping " +
					"must derive from the modulePath arg threaded through codegen.FormatGoSource (#1083)",
			})
		}
	})
	return out
}

// importsAlias returns the local name f binds golang.org/x/tools/imports to
// ("imports" by default, or the explicit alias) and whether the package is
// imported at all. A dot-import returns ("", false) — see the package doc
// blind-spot note.
func importsAlias(f *ast.File) (string, bool) {
	for _, imp := range f.Imports {
		if imp.Path == nil || imp.Path.Value != `"`+goimportsPkgPath+`"` {
			continue
		}
		if imp.Name == nil {
			return "imports", true
		}
		if imp.Name.Name == "." || imp.Name.Name == "_" {
			return "", false
		}
		return imp.Name.Name, true
	}
	return "", false
}
