package archtest

// INVARIANT: ARCHTEST-MODULE-PATH-FUNNEL-01
//
// module_path_funnel_test.go — the migration-convergence ratchet for M3
// (docs/architecture/202605281200-adr-cell-development-external-repo.md §R1/M3).
//
// Goal: make every archtest rule module-path-agnostic so an external Cell repo
// can run it against its own module. A rule's reference to a GoCell PLATFORM
// symbol path must be derived from the single sanctioned const
// [PlatformModulePath] (external.go) — NOT a bare "github.com/ghbvf/gocell…"
// string literal — so (a) a module rename updates exactly one place and (b)
// "no rule hardcodes the platform path" becomes machine-checkable.
//
// # Two detectors
//
//	1. BARE LITERAL (AST, build-tag-agnostic): firstBarePlatformLiteralLine scans
//	   every tools/archtest file (DirsScope, IncludeTests) for a STRING literal
//	   whose value is, or is a child of, PlatformModulePath. Offenders are gated
//	   by a FROZEN BASELINE (testdata/module_path_funnel.baseline) — see below.
//	2. RECONSTRUCTION (typed const-eval, #1304): collectPlatformReconstructions
//	   loads the top-level ./tools/archtest package (Typed, Tests:true) and folds
//	   every `+` BinaryExpr via go/types constant folding (EvaluateConstString).
//	   A chain that folds to a bare platform value is a HARD violation (never
//	   baselined — reconstruction is obfuscation, not legacy backlog), UNLESS its
//	   provenance reaches the sanctioned PlatformModulePath const — directly
//	   (PlatformModulePath+"/x") or transitively through same-package derived
//	   consts (const p = PlatformModulePath+"/a"; const q = p+"/b") — in which
//	   case it is exempt.
//
// # Frozen baseline (bare-literal ratchet)
//
// The baseline records the CURRENT set of files that still contain a bare
// platform-path literal (the migration backlog) and asserts two directions:
//
//   - A NEW file introducing a bare literal → not in baseline → CI red
//     (regression: a new rule hardcoded the path instead of using PlatformModulePath).
//   - A migrated file (literal removed) still listed in baseline → CI red,
//     forcing the author to delete it from the baseline (the ratchet-down step).
//
// Unlike a golden, the baseline is NEVER regenerated by -update — it is a
// monotone ceiling (ArchUnit's FreezingArchRule / ViolationStore pattern:
// fail-on-new, no auto-grow). ref: TNG/ArchUnit freeze/FreezingArchRule.java.
//
// MIGRATION TERMINAL STATE REACHED (#1302 complete, #1304): the baseline is now
// EMPTY. Direction 1 fails ANY offender (none is baselined); Direction 2 has no
// entries. The funnel therefore operates as a PURE BAN — no exception escape, no
// -update launder path. This is the strongest UPSTREAM form the rule's shape can
// reach; see the AI-robust rating for why it is still Medium (not Hard).
//
// # AI-robust rating (funnel double-lock — two honest axes)
//
//   - DOWNSTREAM Hard (detection robustness). The typed reconstruction detector
//     closes the realistic evasion vectors via go/types constant folding +
//     object-identity exemption (alias-proof, same-value-forge-proof):
//       · bare literal / literal-fragment `+` chain  — folded & flagged;
//       · const-of-const fragment chain (residual a)  — folded & flagged (#1304);
//       · cross-package const fragment    (residual b) — folded & flagged (#1304);
//       · sanctioned PlatformModulePath+"/x" + derived consts (q = p+"/b" where
//         p = PlatformModulePath+"/a") — exempt by PROVENANCE: a leaf operand
//         resolves (info.Uses → *types.Const) to PlatformModulePath, traced
//         transitively through same-package const RHS. Matched by const object
//         identity (name + declaring package path), NOT by string value, so a
//         same-VALUE forgery in another package, or a cross-package fragment
//         whose RHS is not visible here, is still flagged.
//     RESIDUAL (c), PERMANENT CEILING — honestly stated, NOT Hard: a path
//     reconstructed via RUNTIME string ops (strings.Join / fmt.Sprintf / []byte)
//     is not a compile-time constant, so go/types cannot fold it and the detector
//     cannot reach it. Closing it needs SSA/dataflow, beyond archtest's ceiling;
//     such deliberate obfuscation would not survive review. This is a permanent
//     won't-do (no upgrade issue), same family as #851 / #893 / #1282 / #1424.
//
//   - UPSTREAM Medium (NOT Hard) — permanent Go ceiling. Go cannot make "an
//     author writes a bare platform literal in arbitrary source" inexpressible:
//     the ban is enforced at CI test time (an archtest), not at compile time. The
//     empty baseline removes the exception escape (the strongest achievable
//     upstream form), but the axis stays Medium — type-system Hard is unreachable
//     for a "do not write this string value" rule. Do NOT relabel the empty-
//     baseline pure ban as "Hard" (the pre-#1304 godoc did; corrected here).
//
// # Blind spots (declared) + reverse self-checks
//
//	(a) const-of-const fragment reconstruction — COVERED (#1304) by the typed
//	    detector. RED self-check: modulepathfunnelfixture/red_const_of_const.go.
//	(b) cross-package const fragment reconstruction — COVERED (#1304). RED
//	    self-check: modulepathfunnelfixture/red_cross_pkg.go.
//	(c) runtime string ops (strings.Join / fmt.Sprintf / []byte) — NOT covered;
//	    permanent ceiling (see DOWNSTREAM residual above). GREEN self-check:
//	    modulepathfunnelfixture/green_runtime_ops.go asserts it is NOT flagged,
//	    documenting the honest boundary (not a vacuity miss).
//	(d) build-tagged rule files — the typed reconstruction scan runs under the
//	    DEFAULT build config. The only build-tagged files in package archtest are
//	    two //go:build !windows rule files, which DO compile under the default
//	    config on the Linux/macOS CI where archtest runs, so they are covered.
//	    archtest_fixture-tagged files are test scaffolding (not rules) and are
//	    excluded; the bare-literal firstBare scan still covers them AST-wise,
//	    build-tag-agnostically. No FlatNonDefaultTags() double-scan is needed
//	    (no tagged rule file would be missed).
//	    The sanctioned-exemption is additionally exercised by the MAIN scan: 369
//	    real PlatformModulePath+"/…" derivations live in funnel scope (real-source
//	    AST capture); the main rule staying green proves all are exempted.

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

const barePlatformLiteralMsg = "bare \"" + PlatformModulePath +
	"\" string literal — derive platform symbol paths from PlatformModulePath " +
	"(see external.go / ARCHTEST-MODULE-PATH-FUNNEL-01)"

// platformReconstructionMsg is the diagnostic for a `+` chain that go/types folds
// to a bare platform value without a sanctioned PlatformModulePath operand.
const platformReconstructionMsg = "platform module path reconstructed from " +
	"const fragments (const-of-const / cross-package const) — derive it from " +
	"PlatformModulePath (see external.go / ARCHTEST-MODULE-PATH-FUNNEL-01)"

// modulePathFunnelSanctioned is the one file permitted to contain the bare
// platform-path literal: external.go, which declares PlatformModulePath.
const modulePathFunnelSanctioned = "tools/archtest/external.go"

// platformModulePathConstName is the identifier the reconstruction exemption
// recognizes as the sanctioned platform-path source.
const platformModulePathConstName = "PlatformModulePath"

// platformModulePathDeclPkgPath is the import path of the package that DECLARES
// PlatformModulePath (external.go, package archtest). It is DERIVED from the
// sanctioned const itself — never a bare literal — so it is itself exempt when
// the rule scans its own file, keeping the exemption self-consistent.
const platformModulePathDeclPkgPath = PlatformModulePath + "/tools/archtest"

// TestArchtestModulePathFunnel enforces ARCHTEST-MODULE-PATH-FUNNEL-01. The bare-
// literal detector (firstBarePlatformLiteralLine) gates offenders by the frozen
// baseline (now empty = pure ban). The typed reconstruction sub-check
// (no-reconstruction) closes the const-of-const / cross-package residual.
func TestArchtestModulePathFunnel(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	// IncludeTests: today's rule logic lives in *_test.go; the funnel must see
	// it. testdata/ is skipped by DirsScope's default skip set; internal/ and
	// the sanctioned site are excluded by inFunnelScope.
	scope := DirsScope(root, []string{"tools/archtest"}, IncludeTests())

	// offenders: rel path -> first line carrying a bare platform literal.
	offenders := make(map[string]int)
	_ = Run(t, AST(scope), func(p *Pass) []Diagnostic {
		for _, f := range p.Files {
			rel := p.Rel(f)
			if !inFunnelScope(rel) {
				continue
			}
			if line, ok := firstBarePlatformLiteralLine(p.Fset, f); ok {
				offenders[rel] = line
			}
		}
		return nil
	})

	const baselineRel = "testdata/module_path_funnel.baseline"
	baseline := readModulePathBaseline(t,
		filepath.Join(root, "tools", "archtest", baselineRel))

	// Direction 1 (fail-on-new, pure ban): an offender absent from the frozen
	// baseline is a NEW regression — no -update can launder it in. With the
	// baseline empty (#1302 terminal state), this fails ANY bare literal.
	for rel, line := range offenders {
		if !baseline[rel] {
			t.Errorf("ARCHTEST-MODULE-PATH-FUNNEL-01: %s:%d: %s\n"+
				"(NEW bare literal — not in the frozen %s; derive it from "+
				"PlatformModulePath, do not hand-add it to the baseline)",
				rel, line, barePlatformLiteralMsg, baselineRel)
		}
	}
	// Direction 2 (ratchet-down): a baseline file that no longer offends must be
	// deleted from the baseline, so the ceiling only shrinks.
	for rel := range baseline {
		if _, still := offenders[rel]; !still {
			t.Errorf("ARCHTEST-MODULE-PATH-FUNNEL-01: %s no longer contains a bare platform "+
				"literal — delete it from %s (ratchet-down)", rel, baselineRel)
		}
	}

	// Typed reconstruction sub-check: closes the declared residual (a)
	// const-of-const and (b) cross-package const via go/types constant folding,
	// with an object-identity exemption for the sanctioned PlatformModulePath
	// operand. Loads only the top-level ./tools/archtest package (rule files);
	// the internal/ fixture packages and archtest_fixture scaffolding are not in
	// this package, so they are not scanned here (the RED fixtures are exercised
	// by TestModulePathFunnel_TypedReconstruction instead).
	t.Run("no-reconstruction", func(t *testing.T) {
		t.Parallel()
		sawTestFile := false
		diags := Run(t, Typed(TypedOpts{Tests: true}, []string{"./tools/archtest"}),
			func(p *Pass) []Diagnostic {
				if p.Pkg == nil || p.TypesInfo == nil {
					return nil
				}
				for _, f := range p.Files {
					if strings.HasSuffix(p.Rel(f), "_test.go") {
						sawTestFile = true
					}
				}
				return collectPlatformReconstructions(p, func(rel string) bool {
					return !inFunnelScope(rel)
				})
			})
		require.True(t, sawTestFile,
			"ARCHTEST-MODULE-PATH-FUNNEL-01 no-reconstruction scope regression: "+
				"Tests:true must surface *_test.go (rule files are archtest test "+
				"files); a Tests:false scope would make the reconstruction check "+
				"vacuously green — see function godoc.")
		Report(t, "ARCHTEST-MODULE-PATH-FUNNEL-01", diags)
	})
}

// collectPlatformReconstructions folds every `+` BinaryExpr in p (a typed Pass)
// via go/types constant folding and flags those that reconstruct a bare platform
// value WITHOUT a sanctioned PlatformModulePath operand. skip(rel) excludes files
// from the scan (nil = scan all). Runtime string ops (strings.Join etc.) are not
// constants, so EvaluateConstString returns false and they are out of reach — the
// permanent residual (c).
func collectPlatformReconstructions(p *Pass, skip func(rel string) bool) []Diagnostic {
	if p.Pkg == nil || p.TypesInfo == nil {
		return nil
	}
	constRHS := buildPackageConstRHS(p)
	var diags []Diagnostic
	for _, f := range p.Files {
		rel := p.Rel(f)
		if skip != nil && skip(rel) {
			continue
		}
		EachInSubtree[ast.BinaryExpr](f, func(be *ast.BinaryExpr) {
			if be.Op != token.ADD {
				return
			}
			v, ok := EvaluateConstString(p.TypesInfo, be)
			if !ok || !isBarePlatformValue(v) {
				return
			}
			if hasSanctionedPlatformOperand(p.TypesInfo, be, constRHS, map[*types.Const]bool{}) {
				return
			}
			diags = append(diags, diagAt(rel, p.Fset.Position(be.Pos()).Line,
				platformReconstructionMsg))
		})
	}
	return diags
}

// buildPackageConstRHS maps every same-package const object to the AST of its
// declared value, so [hasSanctionedPlatformOperand] can trace provenance through
// derived consts (const x = PlatformModulePath + "/a"; const y = x + "/b").
// Grouped/iota consts without an explicit value at their index are skipped.
// Cross-package consts are absent from the map (their RHS is in another package's
// files), which is exactly why a cross-package fragment stays a violation.
func buildPackageConstRHS(p *Pass) map[*types.Const]ast.Expr {
	m := make(map[*types.Const]ast.Expr)
	for _, f := range p.Files {
		EachInSubtree[ast.GenDecl](f, func(gd *ast.GenDecl) {
			if gd.Tok != token.CONST {
				return
			}
			EachInChildren[ast.ValueSpec](gd, func(vs *ast.ValueSpec) {
				for i, name := range vs.Names {
					if i >= len(vs.Values) {
						continue
					}
					if c, ok := p.TypesInfo.Defs[name].(*types.Const); ok {
						m[c] = vs.Values[i]
					}
				}
			})
		})
	}
	return m
}

// hasSanctionedPlatformOperand reports whether expr's provenance reaches the
// sanctioned PlatformModulePath const. A `+` chain whose value derives —
// directly or transitively through same-package derived consts — from
// PlatformModulePath is a sanctioned derivation and is exempt, even though it
// folds to a platform-prefixed value. A reconstruction from fragments that never
// touch PlatformModulePath (literal fragments, an unrelated const-of-const, or a
// cross-package const whose RHS is not visible here) is NOT exempt. visited
// guards against pathological cycles (illegal in Go, but cheap insurance).
func hasSanctionedPlatformOperand(info *types.Info, expr ast.Expr,
	constRHS map[*types.Const]ast.Expr, visited map[*types.Const]bool,
) bool {
	switch e := expr.(type) {
	case *ast.ParenExpr:
		return hasSanctionedPlatformOperand(info, e.X, constRHS, visited)
	case *ast.BinaryExpr:
		return hasSanctionedPlatformOperand(info, e.X, constRHS, visited) ||
			hasSanctionedPlatformOperand(info, e.Y, constRHS, visited)
	case *ast.Ident:
		return constOperandSanctioned(info, info.Uses[e], constRHS, visited)
	case *ast.SelectorExpr:
		return constOperandSanctioned(info, info.Uses[e.Sel], constRHS, visited)
	}
	return false
}

// constOperandSanctioned reports whether the const obj is — or transitively
// (through its same-package RHS) derives from — the sanctioned PlatformModulePath
// const. A const whose RHS is not visible here (cross-package, or no explicit
// value) terminates the trace as NOT sanctioned.
func constOperandSanctioned(info *types.Info, obj types.Object,
	constRHS map[*types.Const]ast.Expr, visited map[*types.Const]bool,
) bool {
	c, ok := obj.(*types.Const)
	if !ok || c.Pkg() == nil {
		return false
	}
	if isPlatformModulePathConst(c) {
		return true
	}
	if visited[c] {
		return false
	}
	rhs, ok := constRHS[c]
	if !ok {
		return false
	}
	visited[c] = true
	return hasSanctionedPlatformOperand(info, rhs, constRHS, visited)
}

// isPlatformModulePathConst reports whether obj is THE sanctioned
// PlatformModulePath const — matched by NAME + declaring PACKAGE PATH (object
// identity), not by string value. A same-value const declared elsewhere has a
// different package path and is therefore NOT exempt (forge-proof); an import
// alias resolves to the same object and is therefore still exempt (alias-proof).
func isPlatformModulePathConst(obj types.Object) bool {
	c, ok := obj.(*types.Const)
	if !ok || c.Pkg() == nil {
		return false
	}
	return c.Name() == platformModulePathConstName &&
		c.Pkg().Path() == platformModulePathDeclPkgPath
}

// inFunnelScope reports whether a repo-relative path is within the funnel's scan
// scope: under tools/archtest/, but not the internal/ loader primitives, not
// testdata/, and not the sanctioned PlatformModulePath declaration site.
func inFunnelScope(rel string) bool {
	return strings.HasPrefix(rel, "tools/archtest/") &&
		!strings.HasPrefix(rel, "tools/archtest/internal/") &&
		!strings.Contains(rel, "/testdata/") &&
		rel != modulePathFunnelSanctioned
}

// readModulePathBaseline reads the frozen migration baseline: one repo-relative
// path per line, blank lines and `#` comments ignored. A missing file fails loud
// (the baseline is a required, checked-in artifact).
func readModulePathBaseline(t *testing.T, path string) map[string]bool {
	t.Helper()
	data, err := os.ReadFile(path) //nolint:gosec // test-derived path under module root
	if err != nil {
		t.Fatalf("ARCHTEST-MODULE-PATH-FUNNEL-01: read baseline %s: %v", path, err)
	}
	out := make(map[string]bool)
	for _, ln := range strings.Split(string(data), "\n") {
		ln = strings.TrimSpace(ln)
		if ln == "" || strings.HasPrefix(ln, "#") {
			continue
		}
		out[ln] = true
	}
	return out
}

// firstBarePlatformLiteralLine returns the source line of the first STRING
// literal in f (excluding import-spec paths) whose unquoted value is, or is a
// child path of, PlatformModulePath, and whether any was found. Import-spec
// paths are excluded because importing a GoCell package is normal Go, not the
// hardcoding this funnel targets; the sanctioned PlatformModulePath+"/x" form is
// invisible because its fragment literal is "/x" (no platform prefix).
func firstBarePlatformLiteralLine(fset *token.FileSet, f *ast.File) (int, bool) {
	importLits := make(map[*ast.BasicLit]bool, len(f.Imports))
	for _, imp := range f.Imports {
		if imp.Path != nil {
			importLits[imp.Path] = true
		}
	}
	lit, found := FindFirstInSubtree[ast.BasicLit](f, func(lit *ast.BasicLit) bool {
		if lit.Kind != token.STRING || importLits[lit] {
			return false
		}
		val, err := strconv.Unquote(lit.Value)
		if err != nil {
			return false
		}
		return isBarePlatformValue(val)
	})
	if !found {
		return 0, false
	}
	return fset.Position(lit.Pos()).Line, true
}

// isBarePlatformValue reports whether v is the platform module path itself or a
// child path of it — i.e. a value that directly hardcodes the platform path.
// Genuine FRAGMENTS (e.g. "github.com/ghbvf/", which is a prefix of, not prefixed
// by, the path) are NOT bare values and are the reconstruction detector's domain.
func isBarePlatformValue(v string) bool {
	return v == PlatformModulePath || strings.HasPrefix(v, PlatformModulePath+"/")
}

// TestModulePathFunnel_TypedReconstruction is the RED/GREEN reverse self-check for
// the typed reconstruction detector (#1304). It loads the fixture package
// (modulepathfunnelfixture, build tag archtest_fixture) and asserts which FILES
// collectPlatformReconstructions flags: the two typed-only reconstructions (a)/(b)
// MUST be flagged; the sanctioned derivation, the unrelated concat, and the
// runtime-ops residual (c) MUST NOT be flagged.
func TestModulePathFunnel_TypedReconstruction(t *testing.T) {
	t.Parallel()
	const fixturePattern = "./tools/archtest/internal/modulepathfunnelfixture/..."
	var diags []Diagnostic
	_ = Run(t, Fixture(FixtureOpts{Tests: false}, []string{fixturePattern}),
		func(p *Pass) []Diagnostic {
			diags = append(diags, collectPlatformReconstructions(p, nil)...)
			return nil
		})

	flagged := make(map[string]bool)
	for _, d := range diags {
		flagged[filepath.Base(d.Rel)] = true
	}

	// RED — typed-only reconstructions MUST be flagged (anti-vacuity).
	require.True(t, flagged["red_const_of_const.go"],
		"residual (a) const-of-const reconstruction must be flagged by the typed detector")
	require.True(t, flagged["red_cross_pkg.go"],
		"residual (b) cross-package const reconstruction must be flagged by the typed detector")
	// GREEN — exemption + negative controls MUST NOT be flagged.
	require.False(t, flagged["green_sanctioned.go"],
		"sanctioned PlatformModulePath derivation must be exempt (object identity)")
	require.False(t, flagged["green_unrelated.go"],
		"non-platform concat must not be flagged")
	require.False(t, flagged["green_runtime_ops.go"],
		"runtime string ops are the permanent residual (c) — not statically foldable, by design")
}

// TestFirstBarePlatformLiteralLine_partition pins the partition between the two
// detection mechanisms, so excluding bare-value literals from the reconstruction
// detector can NEVER hide a hardcode:
//
//   - A bare-VALUE literal (or a const whose RHS is that literal) is caught HERE
//     at its literal site → it lands in offenders/baseline. So the hardcode is
//     always tracked at its literal site, never silently lost.
//   - A FRAGMENT-only reconstruction (no single operand is a bare value) is NOT
//     caught here — it is the typed reconstruction detector's domain
//     (collectPlatformReconstructions), which now covers const-of-const and
//     cross-package const (residuals (a)/(b), #1304).
//
// Together the two are exhaustive over compile-time-constant forms. The only
// uncovered form is the documented PERMANENT residual (c): runtime string ops,
// which are not constants and which neither detector can reach.
func TestFirstBarePlatformLiteralLine_partition(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name      string
		src       string
		wantFound bool
	}{
		{
			"bare-value-const-used-in-concat",
			"package p\nconst full = \"github.com/ghbvf/gocell\"\nvar _ = full + \"/x\"\n", true,
		},
		{
			"bare-literal-child-path",
			"package p\nvar _ = \"github.com/ghbvf/gocell/pkg/x\"\n", true,
		},
		{"only-fragments-no-bare", // reconstruction detector's job, not firstBare's
			"package p\nconst a = \"github.com/\"\nconst b = \"ghbvf/gocell\"\nvar _ = a + b\n", false},
		{
			"gocell-import-path-excluded",
			"package p\nimport _ \"github.com/ghbvf/gocell/pkg/errcode\"\n", false,
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			t.Parallel()
			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, c.name+".go", c.src, 0)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if _, found := firstBarePlatformLiteralLine(fset, f); found != c.wantFound {
				t.Errorf("firstBarePlatformLiteralLine found=%v, want %v", found, c.wantFound)
			}
		})
	}
}
