package archtest

// INVARIANT: ARCHTEST-MODULE-PATH-FUNNEL-01
//
// module_path_funnel_test.go — the migration-convergence ratchet for M3
// (docs/architecture/202605281200-adr-cell-development-external-repo.md §R1/M3).
//
// Goal: make every archtest rule module-path-agnostic so an external Cell repo
// can run it against its own module. A rule's reference to a GoCell PLATFORM
// symbol path must be derived from the single sanctioned const
// [PlatformModulePath] (external.go) — NOT a bare "github.com/ghbvf/gocell…"
// string literal — so (a) a module rename updates exactly one place and (b)
// "no rule hardcodes the platform path" becomes machine-checkable.
//
// This ratchet records the CURRENT set of files that still contain a bare
// platform-path literal (the migration backlog) in a checked-in FROZEN BASELINE
// (testdata/module_path_funnel.baseline) and asserts two directions:
//
//   - A NEW file introducing a bare literal → not in baseline → CI red
//     (regression: a new rule hardcoded the path instead of using PlatformModulePath).
//   - A migrated file (literal removed) still listed in baseline → CI red,
//     forcing the author to delete it from the baseline (the ratchet-down step).
//
// Unlike a golden, the baseline is NEVER regenerated by -update — it is a
// monotone ceiling. As rules migrate (M3 PR-2..N) the author hand-shrinks it;
// when it reaches empty the funnel becomes a pure ban (no file outside
// external.go may contain the literal) — the Hard terminal state. This is
// ArchUnit's FreezingArchRule / ViolationStore pattern: freeze the current
// violations, fail only on new ones, shrink as they are fixed — with store
// growth forbidden (no auto-refreeze).
// ref: ArchUnit FreezingArchRule (TextFileBasedViolationStore, fail-on-new,
// no auto-grow).
//
// # AI-robust rating (funnel double-lock)
//
//   - Downstream Hard (realistic vectors): a bare "github.com/ghbvf/gocell[/…]"
//     STRING literal is detected by AST BasicLit prefix match; a `+` chain that
//     reconstructs the path from FRAGMENTS — string literals AND same-package
//     string-literal consts (flattenPlatformConcat + constMap) — is caught by the
//     no-fragment-split self-check, any fragment count. The SANCTIONED escape
//     PlatformModulePath+"/pkg/x" is invisible because PlatformModulePath is
//     declared in the excluded external.go, so it is unresolvable and the chain is
//     dropped. Form-uniqueness, no string-anchor / comment-allowlist.
//   - Downstream residual (NOT Hard — adversarial, honestly stated): a path
//     reconstructed via a const-of-const (`const x = y` where y is itself a
//     const), a cross-package const selector, or runtime string ops
//     (strings.Join / fmt.Sprintf / []byte) is NOT resolved by the AST-only
//     flatten and escapes the self-check. The honest claim is therefore Hard for
//     the realistic forms (bare literal / literal-fragment / same-package
//     const-fragment), NOT an absolute downstream Hard. Closing the residual needs
//     typed const-eval (types.Info constant folding) with a PlatformModulePath-
//     operand exception — blocked today because the rules live in _test.go (needs
//     test-variant typed loading) and a naive EvaluateConstString would false-flag
//     the sanctioned PlatformModulePath+"/x" form. Tracked by #1304. These forms
//     are deliberate obfuscation that would not survive review.
//   - Upstream Medium: Go cannot prevent a package-internal author from writing
//     a bare string literal. The frozen baseline is the backstop, but — unlike a
//     golden — it is NEVER rewritten by -update: a new bare literal fails CI
//     (offenders ⊄ baseline) with no -update launder path; the only way to admit
//     one is a hand-edit of the frozen baseline, a visible review-first diff. The
//     Hard upgrade is the terminal empty-baseline pure ban, reached when
//     migration completes (#1302) — Hard-ization tracked by #1304.
//
// # Blind spots (declared) + reverse self-checks
//
//	(a) Fragment-split reconstruction: "github.com/ghbvf/" + "gocell/pkg/x", or
//	    const fragments a+b+c. The reverse self-check below
//	    (TestArchtestModulePathFunnel/no-fragment-split) catches this by flattening
//	    a `+` chain whose operands are string literals or same-package
//	    string-literal consts (flattenPlatformConcat), any fragment count, and
//	    prefix-checking the join; the sanctioned PlatformModulePath+"/x" stays
//	    invisible (PlatformModulePath's external.go declaration is excluded from
//	    constMap → unresolvable). RESIDUAL (adversarial, NOT covered): const-of-
//	    const, cross-package const, or runtime string ops — see the downstream
//	    residual rating above; typed-const-eval closure tracked by #1304.
//	(b) Build-tagged files (//go:build x): Run is AST-only and parses every
//	    file regardless of build tags, so tagged rule files ARE scanned — not a
//	    blind spot here (unlike type-loading rules).

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

const barePlatformLiteralMsg = "bare \"" + PlatformModulePath +
	"\" string literal — derive platform symbol paths from PlatformModulePath " +
	"(see external.go / ARCHTEST-MODULE-PATH-FUNNEL-01)"

// modulePathFunnelSanctioned is the one file permitted to contain the bare
// platform-path literal: external.go, which declares PlatformModulePath.
const modulePathFunnelSanctioned = "tools/archtest/external.go"

// TestArchtestModulePathFunnel enforces ARCHTEST-MODULE-PATH-FUNNEL-01: the set
// of tools/archtest files containing a bare PlatformModulePath literal must be a
// SUBSET of the frozen baseline (testdata/module_path_funnel.baseline, the
// migration backlog), AND every baseline entry must still be an offender. The
// baseline is hand-maintained and shrink-only — never regenerated by -update —
// so a new bare literal cannot be laundered into it. Migrate a file by removing
// its literal (derive from PlatformModulePath) and deleting its baseline line.
func TestArchtestModulePathFunnel(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	// IncludeTests: today's rule logic lives in *_test.go; the funnel must see
	// it. testdata/ is skipped by DirsScope's default skip set; internal/ and
	// the sanctioned site are excluded by inFunnelScope.
	scope := DirsScope(root, []string{"tools/archtest"}, IncludeTests())

	// offenders: rel path -> first line carrying a bare platform literal.
	offenders := make(map[string]int)
	_ = Run(t, scope, func(p *Pass) []Diagnostic {
		for _, f := range p.Files {
			rel := p.Rel(f)
			if !inFunnelScope(rel) {
				continue
			}
			if line, ok := firstBarePlatformLiteralLine(p.Fset, f); ok {
				offenders[rel] = line
			}
		}
		return nil
	})

	const baselineRel = "testdata/module_path_funnel.baseline"
	baseline := readModulePathBaseline(t,
		filepath.Join(root, "tools", "archtest", baselineRel))

	// Direction 1 (fail-on-new, Hard): an offender absent from the frozen
	// baseline is a NEW regression — no -update can launder it in.
	for rel, line := range offenders {
		if !baseline[rel] {
			t.Errorf("ARCHTEST-MODULE-PATH-FUNNEL-01: %s:%d: %s\n"+
				"(NEW bare literal — not in the frozen %s; derive it from "+
				"PlatformModulePath, do not hand-add it to the baseline)",
				rel, line, barePlatformLiteralMsg, baselineRel)
		}
	}
	// Direction 2 (ratchet-down): a baseline file that no longer offends must be
	// deleted from the baseline, so the ceiling only shrinks.
	for rel := range baseline {
		if _, still := offenders[rel]; !still {
			t.Errorf("ARCHTEST-MODULE-PATH-FUNNEL-01: %s no longer contains a bare platform "+
				"literal — delete it from %s (ratchet-down)", rel, baselineRel)
		}
	}

	// Reverse self-check for declared blind spot (a): a `+` chain that
	// reconstructs the platform path from FRAGMENTS would evade the per-literal
	// scan. flattenPlatformConcat resolves each operand as a string literal OR a
	// same-package string-literal const (constMap), so it catches both
	//   "github.com/" + "ghbvf/" + "gocell"            (literal fragments)
	//   const a,b,c = …; _ = a + b + c                 (literal-const fragments)
	// The sanctioned PlatformModulePath+"/x" form stays invisible because
	// PlatformModulePath is declared in external.go, which is excluded from
	// constMap (inFunnelScope), so it is unresolvable → the chain is dropped.
	// Residual (adversarial) blind spot: a const defined via another const/ident,
	// a cross-package const, or runtime string ops — see godoc.
	t.Run("no-fragment-split", func(t *testing.T) {
		var splits []string
		_ = Run(t, scope, func(p *Pass) []Diagnostic {
			constMap := make(map[string]string)
			for _, f := range p.Files {
				if inFunnelScope(p.Rel(f)) {
					collectStringLiteralConsts(f, constMap)
				}
			}
			for _, f := range p.Files {
				rel := p.Rel(f)
				if !inFunnelScope(rel) {
					continue
				}
				EachInSubtree[ast.BinaryExpr](f, func(be *ast.BinaryExpr) {
					if be.Op != token.ADD {
						return
					}
					if joined, ok := flattenPlatformConcat(be, constMap); ok &&
						strings.HasPrefix(joined, PlatformModulePath) {
						splits = append(splits, rel)
					}
				})
			}
			return nil
		})
		if len(splits) > 0 {
			t.Errorf("ARCHTEST-MODULE-PATH-FUNNEL-01: fragment-split platform literal in %v "+
				"(use PlatformModulePath)", splits)
		}
	})
}

// inFunnelScope reports whether a repo-relative path is within the funnel's scan
// scope: under tools/archtest/, but not the internal/ loader primitives, not
// testdata/, and not the sanctioned PlatformModulePath declaration site.
func inFunnelScope(rel string) bool {
	return strings.HasPrefix(rel, "tools/archtest/") &&
		!strings.HasPrefix(rel, "tools/archtest/internal/") &&
		!strings.Contains(rel, "/testdata/") &&
		rel != modulePathFunnelSanctioned
}

// readModulePathBaseline reads the frozen migration baseline: one repo-relative
// path per line, blank lines and `#` comments ignored. A missing file fails loud
// (the baseline is a required, checked-in artifact).
func readModulePathBaseline(t *testing.T, path string) map[string]bool {
	t.Helper()
	data, err := os.ReadFile(path) //nolint:gosec // test-derived path under module root
	if err != nil {
		t.Fatalf("ARCHTEST-MODULE-PATH-FUNNEL-01: read baseline %s: %v", path, err)
	}
	out := make(map[string]bool)
	for _, ln := range strings.Split(string(data), "\n") {
		ln = strings.TrimSpace(ln)
		if ln == "" || strings.HasPrefix(ln, "#") {
			continue
		}
		out[ln] = true
	}
	return out
}

// firstBarePlatformLiteralLine returns the source line of the first STRING
// literal in f (excluding import-spec paths) whose unquoted value is, or is a
// child path of, PlatformModulePath, and whether any was found. Import-spec
// paths are excluded because importing a GoCell package is normal Go, not the
// hardcoding this funnel targets; the sanctioned PlatformModulePath+"/x" form is
// invisible because its fragment literal is "/x" (no platform prefix).
func firstBarePlatformLiteralLine(fset *token.FileSet, f *ast.File) (int, bool) {
	importLits := make(map[*ast.BasicLit]bool, len(f.Imports))
	for _, imp := range f.Imports {
		if imp.Path != nil {
			importLits[imp.Path] = true
		}
	}
	lit, found := FindFirstInSubtree[ast.BasicLit](f, func(lit *ast.BasicLit) bool {
		if lit.Kind != token.STRING || importLits[lit] {
			return false
		}
		val, err := strconv.Unquote(lit.Value)
		if err != nil {
			return false
		}
		return isBarePlatformValue(val)
	})
	if !found {
		return 0, false
	}
	return fset.Position(lit.Pos()).Line, true
}

// isBarePlatformValue reports whether v is the platform module path itself or a
// child path of it — i.e. a value that directly hardcodes the platform path
// (the bare-literal violation [firstBarePlatformLiteralLine] catches). Genuine
// FRAGMENTS (e.g. "github.com/ghbvf/", which is a prefix of, not prefixed by,
// the path) are NOT bare values and are the fragment-split self-check's domain.
func isBarePlatformValue(v string) bool {
	return v == PlatformModulePath || strings.HasPrefix(v, PlatformModulePath+"/")
}

// collectStringLiteralConsts records every `const NAME = "literal"` (string
// BasicLit RHS) declared in f into dst (NAME -> unquoted value), including
// function-local consts. Only string-LITERAL consts are collected; a const
// whose RHS is another ident/expr is deliberately left unresolvable, so
// flattenPlatformConcat cannot follow const-of-const chains (documented
// adversarial residual). Walks via the scanner funnel (SCANNER-FRAMEWORK-USAGE).
func collectStringLiteralConsts(f *ast.File, dst map[string]string) {
	EachInSubtree[ast.GenDecl](f, func(gd *ast.GenDecl) {
		if gd.Tok != token.CONST {
			return
		}
		EachInChildren[ast.ValueSpec](gd, func(vs *ast.ValueSpec) {
			for i, name := range vs.Names {
				if i >= len(vs.Values) {
					continue
				}
				// Only genuine FRAGMENTS seed the map: a const whose value is itself
				// a bare platform value is a direct violation handled by
				// firstBarePlatformLiteralLine; resolving it here would re-flag its
				// every concatenation as a (redundant) split.
				if v, ok := stringLitVal(vs.Values[i]); ok && !isBarePlatformValue(v) {
					dst[name.Name] = v
				}
			}
		})
	})
}

// flattenPlatformConcat resolves a `+` expression tree to its constant string
// value, returning the value and true when EVERY leaf operand is either a string
// literal or a same-package string-literal const found in constMap. Any other
// operand (a const-of-const ident, a cross-package selector, the sanctioned
// PlatformModulePath ident — whose external.go declaration is excluded from
// constMap — a call, etc.) makes the whole chain unresolvable → ("", false), so
// the sanctioned derivation stays invisible while literal AND literal-const
// fragment splits are caught. The unresolvable cases are the documented
// adversarial residual blind spot (typed-const-eval upgrade tracked by #1304).
func flattenPlatformConcat(expr ast.Expr, constMap map[string]string) (string, bool) {
	switch e := expr.(type) {
	case *ast.BasicLit:
		// A literal operand that is itself a bare platform value is a direct
		// violation (firstBarePlatformLiteralLine's job), NOT a fragment — drop
		// the chain so the self-check does not redundantly re-report it.
		if v, ok := stringLitVal(e); ok && !isBarePlatformValue(v) {
			return v, true
		}
		return "", false
	case *ast.Ident:
		v, ok := constMap[e.Name]
		return v, ok
	case *ast.BinaryExpr:
		if e.Op != token.ADD {
			return "", false
		}
		l, lok := flattenPlatformConcat(e.X, constMap)
		r, rok := flattenPlatformConcat(e.Y, constMap)
		if !lok || !rok {
			return "", false
		}
		return l + r, true
	}
	return "", false
}

// stringLitVal returns the unquoted value of a STRING basic literal expression.
func stringLitVal(expr ast.Expr) (string, bool) {
	lit, ok := expr.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	v, err := strconv.Unquote(lit.Value)
	if err != nil {
		return "", false
	}
	return v, true
}

// TestFlattenPlatformConcat is the RED/GREEN unit check for the const-fragment
// closure: a `+` chain reconstructing the platform path from string-literal
// consts (the const-ident evasion) is resolved and flagged, while the sanctioned
// PlatformModulePath-derived form (PlatformModulePath absent from constMap) stays
// unresolvable and invisible. Documents the residual: a const-of-const ident
// (not in constMap) leaves the chain unresolvable (adversarial, #1304).
func TestFlattenPlatformConcat(t *testing.T) {
	t.Parallel()
	constMap := map[string]string{
		"a":      "github.com/",
		"b":      "ghbvf/",
		"c":      "gocell",
		"tail":   "ghbvf/gocell",
		"viaRef": "", // simulates a const-of-const: present but unresolved value
	}
	cases := []struct {
		name        string
		expr        string
		wantFlagged bool
	}{
		{"all-literal", `"github.com/" + "ghbvf/" + "gocell"`, true},
		{"all-const", `a + b + c`, true},
		{"mixed-literal-const", `"github.com/" + tail`, true},
		{"sanctioned-derivation", `PlatformModulePath + "/pkg/x"`, false}, // not in constMap
		{"unrelated", `"foo" + "bar"`, false},
		{"const-of-const-residual", `viaRef + "ghbvf/gocell"`, false},                // viaRef value empty → no path
		{"direct-bare-literal-in-concat", `"github.com/ghbvf/gocell" + "/x"`, false}, // direct violation, firstBare's job
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			t.Parallel()
			expr, err := parser.ParseExpr(c.expr)
			if err != nil {
				t.Fatalf("parse %q: %v", c.expr, err)
			}
			joined, ok := flattenPlatformConcat(expr, constMap)
			flagged := ok && strings.HasPrefix(joined, PlatformModulePath)
			if flagged != c.wantFlagged {
				t.Errorf("flattenPlatformConcat(%q) joined=%q ok=%v flagged=%v, want %v",
					c.expr, joined, ok, flagged, c.wantFlagged)
			}
		})
	}
}

// TestFirstBarePlatformLiteralLine_partition pins the partition between the two
// detection mechanisms, so excluding bare-value consts/literals from the
// fragment self-check (isBarePlatformValue) can NEVER hide a hardcode:
//
//   - A bare-value const (collected only when its RHS is a single string
//     literal) is dropped from the fragment constMap, BUT its declaration's
//     literal is still caught HERE → it lands in offenders/baseline. So the
//     hardcode is always tracked at its literal site, never silently lost.
//   - A fragment-only file (no single operand is a bare value) is NOT caught
//     here — it is the no-fragment-split self-check's domain.
//
// Together the two are exhaustive over string-literal forms: every reconstruction
// using a bare-value operand has that operand's literal caught by firstBare; every
// reconstruction from genuine fragments is caught by the self-check. The only
// uncovered form is the documented adversarial residual (const-of-const etc., #1304).
func TestFirstBarePlatformLiteralLine_partition(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name      string
		src       string
		wantFound bool
	}{
		{"bare-value-const-used-in-concat",
			"package p\nconst full = \"github.com/ghbvf/gocell\"\nvar _ = full + \"/x\"\n", true},
		{"bare-literal-child-path",
			"package p\nvar _ = \"github.com/ghbvf/gocell/pkg/x\"\n", true},
		{"only-fragments-no-bare", // self-check's job, not firstBare's
			"package p\nconst a = \"github.com/\"\nconst b = \"ghbvf/gocell\"\nvar _ = a + b\n", false},
		{"gocell-import-path-excluded",
			"package p\nimport _ \"github.com/ghbvf/gocell/pkg/errcode\"\n", false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			t.Parallel()
			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, c.name+".go", c.src, 0)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if _, found := firstBarePlatformLiteralLine(fset, f); found != c.wantFound {
				t.Errorf("firstBarePlatformLiteralLine found=%v, want %v", found, c.wantFound)
			}
		})
	}
}
