package archtest

// INVARIANT: ARCHTEST-MODULE-PATH-FUNNEL-01
//
// module_path_funnel_test.go — the migration-convergence ratchet for M3
// (docs/architecture/202605281200-adr-cell-development-external-repo.md §R1/M3).
//
// Goal: make every archtest rule module-path-agnostic so an external Cell repo
// can run it against its own module. A rule's reference to a GoCell PLATFORM
// symbol path must be derived from the single sanctioned const
// [PlatformModulePath] (external.go) — NOT a bare "github.com/ghbvf/gocell…"
// string literal — so (a) a module rename updates exactly one place and (b)
// "no rule hardcodes the platform path" becomes machine-checkable.
//
// This ratchet records the CURRENT set of files that still contain a bare
// platform-path literal (the migration backlog) in a checked-in FROZEN BASELINE
// (testdata/module_path_funnel.baseline) and asserts two directions:
//
//   - A NEW file introducing a bare literal → not in baseline → CI red
//     (regression: a new rule hardcoded the path instead of using PlatformModulePath).
//   - A migrated file (literal removed) still listed in baseline → CI red,
//     forcing the author to delete it from the baseline (the ratchet-down step).
//
// Unlike a golden, the baseline is NEVER regenerated by -update — it is a
// monotone ceiling. As rules migrate (M3 PR-2..N) the author hand-shrinks it;
// when it reaches empty the funnel becomes a pure ban (no file outside
// external.go may contain the literal) — the Hard terminal state. This is
// ArchUnit's FreezingArchRule / ViolationStore pattern: freeze the current
// violations, fail only on new ones, shrink as they are fixed — with store
// growth forbidden (no auto-refreeze).
// ref: ArchUnit FreezingArchRule (TextFileBasedViolationStore, fail-on-new,
// no auto-grow).
//
// # AI-robust rating (funnel double-lock)
//
//   - Downstream Hard: a bare "github.com/ghbvf/gocell[/…]" STRING literal is
//     detected by AST form (BasicLit prefix match), and an all-string-literal
//     `+` chain that reconstructs the path (any fragment count) is caught by the
//     no-fragment-split self-check. The SANCTIONED escape — PlatformModulePath +
//     "/pkg/x" — is by construction invisible (its fragment is "/pkg/x", and the
//     chain includes the PlatformModulePath Ident so it is not all-literal), so
//     the migrated form is never a false positive and the bare form is always
//     caught. Form-uniqueness, no string-anchor / comment-allowlist.
//   - Upstream Medium: Go cannot prevent a package-internal author from writing
//     a bare string literal. The frozen baseline is the backstop, but — unlike a
//     golden — it is NEVER rewritten by -update: a new bare literal fails CI
//     (offenders ⊄ baseline) with no -update launder path; the only way to admit
//     one is a hand-edit of the frozen baseline, a visible review-first diff. The
//     Hard upgrade is the terminal empty-baseline pure ban, reached when
//     migration completes (#1302) — Hard-ization tracked by #1304.
//
// # Blind spots (declared) + reverse self-checks
//
//	(a) Fragment-split literal: "github.com/ghbvf/" + "gocell/pkg/x". The reverse
//	    self-check below (TestArchtestModulePathFunnel/no-fragment-split) catches
//	    this by flattening ANY all-string-literal `+` chain (N≥2 fragments) and
//	    prefix-checking the join; the sanctioned PlatformModulePath+"/x" form
//	    stays invisible because PlatformModulePath is an Ident, not a literal, so
//	    the chain is not all-literal (an EvaluateConstString upgrade would instead
//	    false-flag that sanctioned form). Residual blind spot: a path assembled by
//	    runtime string ops (strings.Join / fmt.Sprintf / []byte) — implausible for
//	    a const symbol path, equally invisible to const-eval, and would not
//	    survive review.
//	(b) Build-tagged files (//go:build x): Run is AST-only and parses every
//	    file regardless of build tags, so tagged rule files ARE scanned — not a
//	    blind spot here (unlike type-loading rules).

import (
	"go/ast"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

const barePlatformLiteralMsg = "bare \"" + PlatformModulePath +
	"\" string literal — derive platform symbol paths from PlatformModulePath " +
	"(see external.go / ARCHTEST-MODULE-PATH-FUNNEL-01)"

// modulePathFunnelSanctioned is the one file permitted to contain the bare
// platform-path literal: external.go, which declares PlatformModulePath.
const modulePathFunnelSanctioned = "tools/archtest/external.go"

// TestArchtestModulePathFunnel enforces ARCHTEST-MODULE-PATH-FUNNEL-01: the set
// of tools/archtest files containing a bare PlatformModulePath literal must be a
// SUBSET of the frozen baseline (testdata/module_path_funnel.baseline, the
// migration backlog), AND every baseline entry must still be an offender. The
// baseline is hand-maintained and shrink-only — never regenerated by -update —
// so a new bare literal cannot be laundered into it. Migrate a file by removing
// its literal (derive from PlatformModulePath) and deleting its baseline line.
func TestArchtestModulePathFunnel(t *testing.T) {
	t.Parallel()
	root := findModuleRoot(t)
	// IncludeTests: today's rule logic lives in *_test.go; the funnel must see
	// it. testdata/ is skipped by DirsScope's default skip set; internal/ and
	// the sanctioned site are excluded by inFunnelScope.
	scope := DirsScope(root, []string{"tools/archtest"}, IncludeTests())

	// offenders: rel path -> first line carrying a bare platform literal.
	offenders := make(map[string]int)
	_ = Run(t, scope, func(p *Pass) []Diagnostic {
		for _, f := range p.Files {
			rel := p.Rel(f)
			if !inFunnelScope(rel) {
				continue
			}
			if line, ok := firstBarePlatformLiteralLine(p.Fset, f); ok {
				offenders[rel] = line
			}
		}
		return nil
	})

	const baselineRel = "testdata/module_path_funnel.baseline"
	baseline := readModulePathBaseline(t,
		filepath.Join(root, "tools", "archtest", baselineRel))

	// Direction 1 (fail-on-new, Hard): an offender absent from the frozen
	// baseline is a NEW regression — no -update can launder it in.
	for rel, line := range offenders {
		if !baseline[rel] {
			t.Errorf("ARCHTEST-MODULE-PATH-FUNNEL-01: %s:%d: %s\n"+
				"(NEW bare literal — not in the frozen %s; derive it from "+
				"PlatformModulePath, do not hand-add it to the baseline)",
				rel, line, barePlatformLiteralMsg, baselineRel)
		}
	}
	// Direction 2 (ratchet-down): a baseline file that no longer offends must be
	// deleted from the baseline, so the ceiling only shrinks.
	for rel := range baseline {
		if _, still := offenders[rel]; !still {
			t.Errorf("ARCHTEST-MODULE-PATH-FUNNEL-01: %s no longer contains a bare platform "+
				"literal — delete it from %s (ratchet-down)", rel, baselineRel)
		}
	}

	// Reverse self-check for declared blind spot (a): an all-string-literal `+`
	// chain that reconstructs the platform path would evade the per-literal scan.
	// Flatten ANY such chain (any fragment count) and prefix-check the join; the
	// sanctioned PlatformModulePath+"/x" form stays invisible because the chain
	// includes the PlatformModulePath Ident (not all-literal).
	t.Run("no-fragment-split", func(t *testing.T) {
		var splits []string
		_ = Run(t, scope, func(p *Pass) []Diagnostic {
			for _, f := range p.Files {
				rel := p.Rel(f)
				if !inFunnelScope(rel) {
					continue
				}
				EachInSubtree[ast.BinaryExpr](f, func(be *ast.BinaryExpr) {
					if be.Op != token.ADD {
						return
					}
					if joined, allLits := concatStringLiterals(be); allLits &&
						strings.HasPrefix(joined, PlatformModulePath) {
						splits = append(splits, rel)
					}
				})
			}
			return nil
		})
		if len(splits) > 0 {
			t.Errorf("ARCHTEST-MODULE-PATH-FUNNEL-01: fragment-split platform literal in %v "+
				"(use PlatformModulePath)", splits)
		}
	})
}

// inFunnelScope reports whether a repo-relative path is within the funnel's scan
// scope: under tools/archtest/, but not the internal/ loader primitives, not
// testdata/, and not the sanctioned PlatformModulePath declaration site.
func inFunnelScope(rel string) bool {
	return strings.HasPrefix(rel, "tools/archtest/") &&
		!strings.HasPrefix(rel, "tools/archtest/internal/") &&
		!strings.Contains(rel, "/testdata/") &&
		rel != modulePathFunnelSanctioned
}

// readModulePathBaseline reads the frozen migration baseline: one repo-relative
// path per line, blank lines and `#` comments ignored. A missing file fails loud
// (the baseline is a required, checked-in artifact).
func readModulePathBaseline(t *testing.T, path string) map[string]bool {
	t.Helper()
	data, err := os.ReadFile(path) //nolint:gosec // test-derived path under module root
	if err != nil {
		t.Fatalf("ARCHTEST-MODULE-PATH-FUNNEL-01: read baseline %s: %v", path, err)
	}
	out := make(map[string]bool)
	for _, ln := range strings.Split(string(data), "\n") {
		ln = strings.TrimSpace(ln)
		if ln == "" || strings.HasPrefix(ln, "#") {
			continue
		}
		out[ln] = true
	}
	return out
}

// firstBarePlatformLiteralLine returns the source line of the first STRING
// literal in f (excluding import-spec paths) whose unquoted value is, or is a
// child path of, PlatformModulePath, and whether any was found. Import-spec
// paths are excluded because importing a GoCell package is normal Go, not the
// hardcoding this funnel targets; the sanctioned PlatformModulePath+"/x" form is
// invisible because its fragment literal is "/x" (no platform prefix).
func firstBarePlatformLiteralLine(fset *token.FileSet, f *ast.File) (int, bool) {
	importLits := make(map[*ast.BasicLit]bool, len(f.Imports))
	for _, imp := range f.Imports {
		if imp.Path != nil {
			importLits[imp.Path] = true
		}
	}
	lit, found := FindFirstInSubtree[ast.BasicLit](f, func(lit *ast.BasicLit) bool {
		if lit.Kind != token.STRING || importLits[lit] {
			return false
		}
		val, err := strconv.Unquote(lit.Value)
		if err != nil {
			return false
		}
		return val == PlatformModulePath || strings.HasPrefix(val, PlatformModulePath+"/")
	})
	if !found {
		return 0, false
	}
	return fset.Position(lit.Pos()).Line, true
}

// concatStringLiterals flattens a `+` expression tree, returning the
// concatenated value and true ONLY when every leaf operand is a string literal
// (no identifiers, calls, etc.). A chain that includes the PlatformModulePath
// const Ident therefore returns false — the sanctioned derivation is invisible,
// while a pure-literal reconstruction of any fragment count is caught.
func concatStringLiterals(expr ast.Expr) (string, bool) {
	switch e := expr.(type) {
	case *ast.BasicLit:
		return stringLitVal(e)
	case *ast.BinaryExpr:
		if e.Op != token.ADD {
			return "", false
		}
		l, lok := concatStringLiterals(e.X)
		r, rok := concatStringLiterals(e.Y)
		if !lok || !rok {
			return "", false
		}
		return l + r, true
	}
	return "", false
}

// stringLitVal returns the unquoted value of a STRING basic literal expression.
func stringLitVal(expr ast.Expr) (string, bool) {
	lit, ok := expr.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	v, err := strconv.Unquote(lit.Value)
	if err != nil {
		return "", false
	}
	return v, true
}
