// INVARIANT: PROJECTION-APPLY-HOOK-FUNNEL-01
//
// PROJECTION-APPLY-HOOK-FUNNEL-01 — Coordinator.Subscribe caller allowlist.
//
// kernel/projection.Coordinator.Subscribe registers an Apply hook with the
// cell.Registrar. This is the per-projection wiring callsite; it must only
// appear in:
//
//   - kernel/projection/ itself (the method body calls reg.Subscribe internally)
//   - _test.go files (tests of the Coordinator API — explicitly allowed)
//   - the cellgen projection wiring file cell_gen.go ONLY (basename == cell_gen.go
//     AND the "gocell generate cell" DO-NOT-EDIT banner) — PR-04 introduces these;
//     it is the only legitimate production callsite outside kernel/projection.
//     Sibling generated files (healthz_gen.go / slice_gen.go) carry the IDENTICAL
//     banner but are NOT sanctioned Subscribe callsites and are scanned like any
//     other file (F6: marker-only matching was too broad).
//
// Any other production callsite bypasses the PR-04 cellgen funnel (which
// will derive Coordinator.Subscribe calls from slice.yaml contractUsages) and
// constitutes a hand-rolled wiring that diverges from the single source of
// truth.
//
// PR-01 status: genuinely-green active guard (NOT t.Skip). Zero external
// callsites exist today, so the rule vacuously passes. It fires immediately
// if any hand-written callsite appears before PR-04 cellgen lands.
//
// # AI-robust grading (Funnel 双向锁评级)
//
//   - Downstream: Medium archtest caller allowlist. Go has no type-system
//     mechanism to restrict who calls a public method (Go visibility applies
//     to packages, not callers), so this is the strongest achievable form
//     for a method-call restriction. Archtest enforcement is CI fail-closed.
//   - Upstream: Medium. The allowlist is enforced by this archtest; a direct
//     call compiles but is caught by CI. Hard upstream requires PR-04's
//     cellgen-only sealed token (a generated-code marker injected at
//     compile time that only cellgen can produce). Tracked in gh issue #1100.
//
// Because both sides are Medium, this is NOT yet a closed-loop Hard funnel.
// gh issue #1100 tracks the PR-04 Hard-ization path (sealed token argument
// that only cellgen can produce → downstream Hard, upstream Hard at compile
// time for production callers).
//
// # Blind spots (forms *types.Info / ResolveMethodCall cannot see)
//
//   - B1. Function-value / method-expression indirection:
//     `f := coord.Subscribe; f(ctx, spec, id, apply)` — the CallExpr's Fun is
//     an *ast.Ident resolving to a *types.Var, not a *types.Func, so
//     ResolveMethodCall returns (nil, false) and the call is invisible to R1.
//     Reverse self-check TestProjectionApplyHookFunnel01_ReverseBlindSpot_NoFuncValue
//     asserts no production code holds a Coordinator.Subscribe function value.
//
//   - B2. Wrapper method indirection: a wrapper struct that embeds *Coordinator
//     and calls Subscribe inside its own method body — the wrapper's callsite
//     IS caught (it's a direct method call on the embedded receiver), but the
//     wrapper struct itself could be in a non-allowlisted package. Covered by
//     the regular rule scan; not a blind spot.
//
//   - B3. Dot-import: `import . "…/projection"` — ResolveMethodCall handles dot-import
//     via *types.Info.Uses, so this form is caught. Not a blind spot.
//
// ref: tools/archtest/healthz_invariants_test.go (HEALTHZ-WRITE-01/A2 caller-allowlist pattern)
// ref: docs/architecture/202605261620-adr-cqrs-projection-lifecycle-harness.md §3 PR-01
package archtest

import (
	"bufio"
	"fmt"
	"go/ast"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/ghbvf/gocell/tools/internal/prodscan"
)

const (
	projectionCoordPkgPath    = "github.com/ghbvf/gocell/kernel/projection"
	projectionCoordTypeName   = "Coordinator"
	projectionSubscribeMethod = "Subscribe"
)

// projectionCellgenMarkerLine is the DO NOT EDIT marker emitted by
// gocell generate cell into cell_gen.go files.
const projectionCellgenMarkerLine = "// Code generated by gocell generate cell. DO NOT EDIT."

// projectionApplyHookFileHasCellgenMarker reports whether the file at absPath
// contains the cellgen DO NOT EDIT marker line.
func projectionApplyHookFileHasCellgenMarker(absPath string) bool {
	f, err := os.Open(absPath) //nolint:gosec // archtest-internal module-root relative path
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		if strings.TrimSpace(scanner.Text()) == projectionCellgenMarkerLine {
			return true
		}
	}
	return false
}

// isProjectionSubscribeCall reports whether call is a method call to
// (*kernel/projection.Coordinator).Subscribe resolved via *types.Info.Selections.
func isProjectionSubscribeCall(call *ast.CallExpr, info *types.Info) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != projectionSubscribeMethod {
		return false
	}
	fn, ok := ResolveMethodCall(info, sel)
	if !ok || fn == nil {
		return false
	}
	if fn.Pkg() == nil || fn.Pkg().Path() != projectionCoordPkgPath {
		return false
	}
	if fn.Name() != projectionSubscribeMethod {
		return false
	}
	// Verify receiver is *Coordinator (not some other type named Subscribe).
	sig, ok := fn.Type().(*types.Signature)
	if !ok {
		return false
	}
	recv := sig.Recv()
	if recv == nil {
		return false
	}
	recvT := recv.Type()
	if ptr, ok := recvT.(*types.Pointer); ok {
		recvT = ptr.Elem()
	}
	named, ok := recvT.(*types.Named)
	if !ok {
		return false
	}
	return named.Obj().Pkg() != nil &&
		named.Obj().Pkg().Path() == projectionCoordPkgPath &&
		named.Obj().Name() == projectionCoordTypeName
}

// isProjectionApplyHookAllowed reports whether the file at the given rel path
// and abs path is in the allowed set for Coordinator.Subscribe calls:
//   - kernel/projection package itself (where the method is defined and used internally)
//   - _test.go files (tests of the Coordinator API)
//   - the cellgen projection wiring file: ONLY cell_gen.go bearing the
//     "gocell generate cell" DO-NOT-EDIT banner.
//
// The marker alone is INSUFFICIENT (F6): `gocell generate cell` stamps the
// identical banner into cell_gen.go, healthz_gen.go, and slice_gen.go, so a
// marker-only check would green-light a Subscribe call in any of them. Only the
// projection-derived cell_gen.go is the sanctioned production callsite (PR-04),
// so the allowlist requires basename == "cell_gen.go" AND the marker (defense in
// depth — basename pins the producer, marker pins it as generated).
func isProjectionApplyHookAllowed(rel, absPath string) bool {
	// _test.go files are explicitly allowed.
	if strings.HasSuffix(rel, "_test.go") {
		return true
	}
	// kernel/projection/ itself (the method definition and any internal calls).
	if strings.HasPrefix(rel, "kernel/projection/") {
		return true
	}
	// cellgen projection wiring: cell_gen.go ONLY, bearing the DO-NOT-EDIT marker.
	// Sibling generated files (healthz_gen.go / slice_gen.go) share the banner but
	// are NOT sanctioned Subscribe callsites — they fall through and are scanned.
	if filepath.Base(rel) == "cell_gen.go" && projectionApplyHookFileHasCellgenMarker(absPath) {
		return true
	}
	return false
}

// TestProjectionApplyHookFunnel01 enforces PROJECTION-APPLY-HOOK-FUNNEL-01:
// Coordinator.Subscribe must only be called from the kernel/projection package
// itself, from _test.go files, or from cellgen-generated files. Any other
// production callsite is a violation.
//
// PR-01 status: genuinely-green (zero external callsites). The rule actively
// guards against hand-written callsites before PR-04 cellgen lands.
//
// # Blind spots (forms ResolveMethodCall cannot see)
//
//   - B1. Function-value form (`f := coord.Subscribe; f(...)`): Fun resolves
//     to *types.Var, not *types.Func — isProjectionSubscribeCall returns false.
//     Covered by TestProjectionApplyHookFunnel01_ReverseBlindSpot_NoFuncValue.
//
//   - B2. Wrapper/delegation: a wrapper type that embeds *Coordinator and calls
//     Subscribe inside its own exported method — the call IS caught by this rule
//     since it is a direct SelectorExpr call on the embedded receiver. Not a
//     blind spot; no production wrapper exists (confirmed vacuously).
func TestProjectionApplyHookFunnel01(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip("skipping packages.Load-based archtest in -short mode")
	}

	root := findModuleRoot(t)
	allPatterns := prodscan.Patterns(root)

	var diags []Diagnostic

	_ = RunTyped(t, TypedOpts{Tests: false, Tags: FlatNonDefaultTags()}, allPatterns,
		func(p *Pass) []Diagnostic {
			if p.Pkg == nil || p.TypesInfo == nil {
				return nil
			}
			for _, f := range p.Files {
				// NOTE: do NOT blanket-skip generated files (p.IsGenerated) here —
				// that would exempt healthz_gen.go / slice_gen.go too. Generated-file
				// scoping is decided solely by isProjectionApplyHookAllowed, which
				// allows ONLY cell_gen.go (F6). This matches the reverse-fixture scan.
				rel := p.Rel(f)
				absPath := p.Abs(f)
				if isProjectionApplyHookAllowed(rel, absPath) {
					continue
				}
				EachInSubtree[ast.CallExpr](f, func(call *ast.CallExpr) {
					if !isProjectionSubscribeCall(call, p.TypesInfo) {
						return
					}
					diags = append(diags, Diagnostic{
						Rel:  rel,
						Line: p.Fset.Position(call.Pos()).Line,
						Message: fmt.Sprintf(
							"PROJECTION-APPLY-HOOK-FUNNEL-01: Coordinator.Subscribe called "+
								"from non-allowlisted file %s (line %d). "+
								"Only kernel/projection/ itself, _test.go files, and cellgen "+
								"DO-NOT-EDIT generated files may call Coordinator.Subscribe. "+
								"PR-04 cellgen will derive these calls from slice.yaml "+
								"contractUsages — hand-writing them bypasses the single source "+
								"of truth. Tracked in gh issue #1100.",
							rel, p.Fset.Position(call.Pos()).Line,
						),
					})
				})
			}
			return nil
		})

	sort.Slice(diags, func(i, j int) bool {
		if diags[i].Rel != diags[j].Rel {
			return diags[i].Rel < diags[j].Rel
		}
		return diags[i].Line < diags[j].Line
	})
	Report(t, "PROJECTION-APPLY-HOOK-FUNNEL-01", diags)
}

// TestProjectionApplyHookFunnel01_ReverseFixture loads the synthetic violation
// fixture and asserts the rule fires on the rogue callsite.
func TestProjectionApplyHookFunnel01_ReverseFixture(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip("skipping packages.Load-based archtest in -short mode")
	}

	root := findModuleRoot(t)
	fixtureDir := filepath.Join(root, "tools", "archtest", "testdata", "projection_apply_hook_violate")

	var diags []Diagnostic

	_ = RunTypedDir(t, fixtureDir, TypedOpts{Tests: false}, []string{"./..."},
		func(p *Pass) []Diagnostic {
			if p.Pkg == nil || p.TypesInfo == nil {
				return nil
			}
			for _, f := range p.Files {
				rel := p.Rel(f)
				absPath := p.Abs(f)
				if isProjectionApplyHookAllowed(rel, absPath) {
					continue
				}
				EachInSubtree[ast.CallExpr](f, func(call *ast.CallExpr) {
					if !isProjectionSubscribeCall(call, p.TypesInfo) {
						return
					}
					diags = append(diags, Diagnostic{
						Rel:     rel,
						Line:    p.Fset.Position(call.Pos()).Line,
						Message: "PROJECTION-APPLY-HOOK-FUNNEL-01: rogue Coordinator.Subscribe callsite",
					})
				})
			}
			return nil
		})

	assert.NotEmpty(t, diags,
		"PROJECTION-APPLY-HOOK-FUNNEL-01 reverse fixture: expected ≥1 diagnostic for "+
			"rogue Coordinator.Subscribe call; rule logic is broken or fixture is missing the violation")
}

// TestProjectionApplyHookFunnel01_ReverseFixture_GeneratedScope (F6) asserts the
// allowlist distinguishes the sanctioned cellgen projection output (cell_gen.go)
// from sibling generated files (healthz_gen.go / slice_gen.go) that carry the
// IDENTICAL "gocell generate cell" DO-NOT-EDIT banner. A marker-only check would
// green-light a Coordinator.Subscribe call in any of them; the tightened
// allowlist (basename == cell_gen.go AND marker) must ALLOW the call in
// cell_gen.go and FIRE on the same call in healthz_gen.go.
func TestProjectionApplyHookFunnel01_ReverseFixture_GeneratedScope(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip("skipping packages.Load-based archtest in -short mode")
	}

	root := findModuleRoot(t)
	fixtureDir := filepath.Join(root, "tools", "archtest", "testdata", "projection_apply_hook_violate")

	var diags []Diagnostic

	_ = RunTypedDir(t, fixtureDir, TypedOpts{Tests: false}, []string{"./..."},
		func(p *Pass) []Diagnostic {
			if p.Pkg == nil || p.TypesInfo == nil {
				return nil
			}
			for _, f := range p.Files {
				rel := p.Rel(f)
				absPath := p.Abs(f)
				if isProjectionApplyHookAllowed(rel, absPath) {
					continue
				}
				EachInSubtree[ast.CallExpr](f, func(call *ast.CallExpr) {
					if !isProjectionSubscribeCall(call, p.TypesInfo) {
						return
					}
					diags = append(diags, Diagnostic{
						Rel:  rel,
						Line: p.Fset.Position(call.Pos()).Line,
					})
				})
			}
			return nil
		})

	var firedHealthz, firedCellGen bool
	for _, d := range diags {
		switch filepath.Base(d.Rel) {
		case "healthz_gen.go":
			firedHealthz = true
		case "cell_gen.go":
			firedCellGen = true
		}
	}
	assert.True(t, firedHealthz,
		"F6: Coordinator.Subscribe in a marker-bearing healthz_gen.go MUST fire — "+
			"sibling generated files share the cellgen banner but are not sanctioned callsites")
	assert.False(t, firedCellGen,
		"F6: Coordinator.Subscribe in the sanctioned cell_gen.go must be allowed (no diagnostic)")
}

// TestProjectionApplyHookFunnel01_ReverseBlindSpot_NoFuncValue (blind spot B1)
// asserts no production non-test file holds a Coordinator.Subscribe function
// value (method expression `coord.Subscribe` assigned to a variable, not called).
// Such a value would escape R1's direct-CallExpr callee resolution.
func TestProjectionApplyHookFunnel01_ReverseBlindSpot_NoFuncValue(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip("skipping archtest in -short mode")
	}

	root := findModuleRoot(t)
	allPatterns := prodscan.Patterns(root)

	var violations []string

	_ = RunTyped(t, TypedOpts{Tests: false, Tags: FlatNonDefaultTags()}, allPatterns,
		func(p *Pass) []Diagnostic {
			if p.Pkg == nil || p.TypesInfo == nil {
				return nil
			}
			// calleePos records positions of Ident/Sel that are in callee position
			// of a direct Coordinator.Subscribe call — these are legitimate.
			calleePos := make(map[interface{}]struct{})
			for _, f := range p.Files {
				EachInSubtree[ast.CallExpr](f, func(call *ast.CallExpr) {
					sel, ok := call.Fun.(*ast.SelectorExpr)
					if !ok || sel.Sel.Name != projectionSubscribeMethod {
						return
					}
					fn, ok := ResolveMethodCall(p.TypesInfo, sel)
					if !ok || fn == nil {
						return
					}
					if fn.Pkg() == nil || fn.Pkg().Path() != projectionCoordPkgPath {
						return
					}
					calleePos[sel.Sel] = struct{}{}
				})
			}

			for _, f := range p.Files {
				rel := p.Rel(f)
				if strings.HasSuffix(rel, "_test.go") {
					continue
				}
				if strings.HasPrefix(rel, "kernel/projection/") {
					continue
				}
				EachInSubtree[ast.SelectorExpr](f, func(sel *ast.SelectorExpr) {
					if sel.Sel.Name != projectionSubscribeMethod {
						return
					}
					// If already in callee position, skip.
					if _, isCallee := calleePos[sel.Sel]; isCallee {
						return
					}
					fn, ok := ResolveMethodCall(p.TypesInfo, sel)
					if !ok || fn == nil {
						return
					}
					if fn.Pkg() == nil || fn.Pkg().Path() != projectionCoordPkgPath {
						return
					}
					violations = append(violations, fmt.Sprintf(
						"%s:%d: Coordinator.Subscribe used as function value (not a direct call) "+
							"— would escape PROJECTION-APPLY-HOOK-FUNNEL-01 detection (blind spot B1)",
						rel, p.Fset.Position(sel.Sel.Pos()).Line,
					))
				})
			}
			return nil
		})

	assert.Empty(t, violations,
		"blind spot B1: no production non-test file outside kernel/projection/ should hold "+
			"a Coordinator.Subscribe function value")
}
