package archtest

// INVARIANT: REQUIRED-DEP-NIL-GUARD-01
//
// required_dep_nil_guard_test.go — Hard funnel for Service.validateRequired
// generated by tools/codegen/requireddepsgen.
//
// Single source = Service struct field gocell:"required" tag.
// Derived       = service_required_gen.go::validateRequired().
// Callsite      = NewXxx calls validateRequired() post-options, exactly once.
// Downstream ban = service.go may NOT contain hand-written validation.IsNilInterface.
//
// Rules:
//   A1 [TestRequiredDepNilGuard_A1_GeneratorOutputGroundTruth]
//      service_required_gen.go required-field count must match service.go.
//      Production scan gated by REQUIRED_DEP_FUNNEL_PRODUCTION_SCAN env until
//      Batch A/B/C/D service migrations land.
//   A2 [TestRequiredDepNilGuard_A2_CallsiteUniqueness]
//      Every NewXxx(*Service, error) in a slice must call validateRequired()
//      exactly once, after any options loop.
//   A3 [TestRequiredDepNilGuard_A3_HandwrittenIsNilInterfaceBan]
//      service.go (non-gen files) must not call validation.IsNilInterface.
//   A4 [TestRequiredDepNilGuard_A4_TagValueWhitelist]
//      gocell struct tag values must be in {"", "required"}.
//
// Blind spots (A2+A3 scan coverage gaps; each has a reverse self-test):
//
//   B1 [TestRequiredDepNilGuard_BlindSpot_B1_NoReflectNilCheck]
//      reflect.ValueOf(s.X).IsNil() on a required field bypasses A3.
//   B2 [TestRequiredDepNilGuard_BlindSpot_B2_NoDirectNilCompare]
//      s.X == nil / s.X != nil on a required field bypasses A3.
//      Exception: NewXxx body (OUTBOX-SERVICE-01 carve-out) and *_gen.go files.
//   B3 [TestRequiredDepNilGuard_BlindSpot_B3_NoIndirectIsNilInterfaceRef]
//      Function-value / pointer / method-value references to IsNilInterface
//      bypass the callsite-form check in A3.
//   B4 [TestRequiredDepNilGuard_BlindSpot_B4_NoExternalNilGuardHelper]
//      Service calling a helper named MustNotBeNil/RequireNonNil/AssertNonNil
//      bypasses A3.
//   B5 [TestRequiredDepNilGuard_BlindSpot_B5_NoValidateRequiredMethodValueLeak]
//      validateRequired used as a method value (s.validateRequired) outside
//      direct call position bypasses A2 counting.

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

)

// requiredDepNilGuardRule is the rule ID for diagnostic messages.
const requiredDepNilGuardRule = "REQUIRED-DEP-NIL-GUARD-01"

// validationPkgPath is the canonical import path of pkg/validation.
const validationPkgPath = "github.com/ghbvf/gocell/pkg/validation"

// isNilInterfaceFunc is the name of the banned helper function.
const isNilInterfaceFunc = "IsNilInterface"

// nilGuardHelperBanList is the list of external helper names banned in
// service.go (B4 blind-spot: bypassing A3 via a wrapper function).
var nilGuardHelperBanList = []string{
	"MustNotBeNil",
	"RequireNonNil",
	"AssertNonNil",
	"CheckNotNil",
}

// --- A1: Generator Ground Truth ---

// TestRequiredDepNilGuard_A1_GeneratorOutputGroundTruth verifies that
// service_required_gen.go is consistent with service.go required field count.
//
// Production scan is gated by REQUIRED_DEP_FUNNEL_PRODUCTION_SCAN env var
// until Batch A/B/C/D service migrations land. The fixture sub-test is always
// active and verifies the A1 detection logic against red_stale_generator.
func TestRequiredDepNilGuard_A1_GeneratorOutputGroundTruth(t *testing.T) {
	t.Run("fixture_red_stale_generator", func(t *testing.T) {
		root := findModuleRoot(t)
		fixtureDir := filepath.Join(root, "tools", "archtest", "testdata",
			"required_dep_nil_guard_fixtures", "red_stale_generator")
		diags := runA1Check(t, root, fixtureDir)
		goldenPath := filepath.Join(fixtureDir, "diag.golden")
		AssertGolden(t, goldenPath, diags)
	})

	t.Run("production_scan", func(t *testing.T) {
		// TODO: enable after Batch A/B/C/D service migrations land
		// (all cells/*/slices/*/service_required_gen.go committed).
		if os.Getenv("REQUIRED_DEP_FUNNEL_PRODUCTION_SCAN") == "" {
			t.Skip("production gen files land in Batch A/B/C/D migrations; " +
				"set REQUIRED_DEP_FUNNEL_PRODUCTION_SCAN=1 after migration to enable")
		}
		root := findModuleRoot(t)
		slicePaths := discoverSlicePaths(t, root)
		var allDiags []Diagnostic
		for _, sp := range slicePaths {
			allDiags = append(allDiags, runA1Check(t, root, sp)...)
		}
		Report(t, requiredDepNilGuardRule+"-A1", allDiags)
	})
}

// runA1Check runs the A1 staleness check for a single slice directory.
// It counts required fields in service.go and guards in service_required_gen.go.
func runA1Check(t *testing.T, modRoot, sliceDir string) []Diagnostic {
	t.Helper()
	svcFile := filepath.Join(sliceDir, "service.go")
	genFile := filepath.Join(sliceDir, "service_required_gen.go")

	fset := token.NewFileSet()
	svcAST, err := parser.ParseFile(fset, svcFile, nil, 0)
	if err != nil {
		return nil // not a service.go slice
	}
	requiredCount := countRequiredFields(svcAST)
	if requiredCount == 0 {
		return nil // no required fields, gen file irrelevant
	}

	genContent, err := os.ReadFile(genFile) //nolint:gosec // path is test-derived
	if err != nil {
		rel := requiredDepSlashRel(modRoot, svcFile)
		return []Diagnostic{{
			Rel:     rel,
			Line:    1,
			Message: fmt.Sprintf("REQUIRED-DEP-NIL-GUARD-01-A1: service_required_gen.go missing; run gocell generate required-deps (%s)", requiredDepNilGuardRule),
		}}
	}

	// Compare required field count in service.go vs IsNilInterface/nil check count in gen file.
	genCount := countGenGuards(genContent)
	if genCount != requiredCount {
		rel := requiredDepSlashRel(modRoot, svcFile)
		return []Diagnostic{{
			Rel:  rel,
			Line: 1,
			Message: fmt.Sprintf(
				"REQUIRED-DEP-NIL-GUARD-01-A1: service_required_gen.go is stale; "+
					"required field count mismatch: service.go has %d required field(s) but gen guards %d (%s)",
				requiredCount, genCount, requiredDepNilGuardRule),
		}}
	}
	return nil
}

// countRequiredFields counts struct fields tagged gocell:"required" in the AST file.
func countRequiredFields(file *ast.File) int {
	count := 0
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "Service" {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, f := range st.Fields.List {
				if f.Tag == nil {
					continue
				}
				raw := strings.Trim(f.Tag.Value, "`")
				if reflect.StructTag(raw).Get("gocell") == "required" {
					count += len(f.Names)
					if len(f.Names) == 0 {
						count++ // embedded field
					}
				}
			}
		}
	}
	return count
}

// countGenGuards counts the number of per-field guard blocks in the generated
// file content. The generator emits exactly one guard per required field:
//   - interface-typed fields: `if validation.IsNilInterface(s.X) {`
//   - pointer-typed fields:   `if s.X == nil {`
//
// We count both patterns separately and sum them.
func countGenGuards(content []byte) int {
	isNilCount := bytes.Count(content, []byte("validation.IsNilInterface(s."))
	ptrCount := bytes.Count(content, []byte("\n\tif s.")) // pointer fields: "if s.X == nil"
	return isNilCount + ptrCount
}

// discoverSlicePaths returns all cells/*/slices/*/ directories with a service.go.
func discoverSlicePaths(t *testing.T, modRoot string) []string {
	t.Helper()
	patterns := []string{
		filepath.Join(modRoot, "cells", "*", "slices", "*"),
		filepath.Join(modRoot, "examples", "*", "cells", "*", "slices", "*"),
	}
	var result []string
	seen := make(map[string]struct{})
	for _, pat := range patterns {
		matches, err := filepath.Glob(pat)
		require.NoError(t, err, "glob %s", pat)
		for _, dir := range matches {
			if _, err := os.Stat(filepath.Join(dir, "service.go")); err != nil {
				continue
			}
			if _, ok := seen[dir]; !ok {
				seen[dir] = struct{}{}
				result = append(result, dir)
			}
		}
	}
	return result
}

// requiredDepSlashRel returns the module-relative slash path for absPath.
func requiredDepSlashRel(modRoot, absPath string) string {
	rel, err := filepath.Rel(modRoot, absPath)
	if err != nil {
		return absPath
	}
	return filepath.ToSlash(rel)
}

// --- A2: Callsite Uniqueness ---

// TestRequiredDepNilGuard_A2_CallsiteUniqueness verifies that every
// NewXxx(*Service, error) function calls validateRequired() exactly once,
// after any options loop.
//
// Production scan gated by REQUIRED_DEP_FUNNEL_PRODUCTION_SCAN.
// Fixture sub-test verifies logic against red_missing_callsite.
func TestRequiredDepNilGuard_A2_CallsiteUniqueness(t *testing.T) {
	for _, fix := range []string{"green_basic", "red_missing_callsite"} {
		fix := fix
		t.Run("fixture_"+fix, func(t *testing.T) {
			root := findModuleRoot(t)
			fixtureDir := filepath.Join(root, "tools", "archtest", "testdata",
				"required_dep_nil_guard_fixtures", fix)
			pattern := "./tools/archtest/testdata/required_dep_nil_guard_fixtures/" + fix
			diags := RunTypedFixture(t, FixtureOpts{}, []string{pattern}, func(p *Pass) []Diagnostic {
				if p.TypesInfo == nil {
					return nil
				}
				var out []Diagnostic
				for _, file := range p.Files {
					out = append(out, scanA2(p, file)...)
				}
				return out
			})
			goldenPath := filepath.Join(fixtureDir, "diag.golden")
			AssertGolden(t, goldenPath, diags)
		})
	}

	t.Run("production_scan", func(t *testing.T) {
		if os.Getenv("REQUIRED_DEP_FUNNEL_PRODUCTION_SCAN") == "" {
			t.Skip("production scan gated; set REQUIRED_DEP_FUNNEL_PRODUCTION_SCAN=1 after migration")
		}
		diags := RunTypedProduction(t, TypedOpts{}, func(p *Pass) []Diagnostic {
			if p.TypesInfo == nil {
				return nil
			}
			var out []Diagnostic
			for _, file := range p.Files {
				rel := p.Rel(file)
				if !isServiceGoForScan(rel) {
					continue
				}
				out = append(out, scanA2(p, file)...)
			}
			return out
		})
		Report(t, requiredDepNilGuardRule+"-A2", diags)
	})
}

// scanA2 scans one file for A2 violations: NewXxx functions returning (*Service, error)
// that do not call validateRequired() exactly once.
func scanA2(p *Pass, file *ast.File) []Diagnostic {
	var out []Diagnostic
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv != nil || fn.Body == nil {
			continue
		}
		if !isNewServiceConstructor(fn) {
			continue
		}
		count := countValidateRequiredCalls(fn.Body, p.TypesInfo)
		if count != 1 {
			out = append(out, Diagnostic{
				Rel:  p.Rel(file),
				Line: p.Fset.Position(fn.Pos()).Line,
				Message: fmt.Sprintf(
					"REQUIRED-DEP-NIL-GUARD-01-A2: NewService does not call validateRequired() (%s)",
					requiredDepNilGuardRule),
			})
		}
	}
	return out
}

// isNewServiceConstructor returns true when fn is a top-level function whose
// name starts with "New" and whose return list ends with error.
func isNewServiceConstructor(fn *ast.FuncDecl) bool {
	if !strings.HasPrefix(fn.Name.Name, "New") {
		return false
	}
	results := fn.Type.Results
	if results == nil || len(results.List) == 0 {
		return false
	}
	last := results.List[len(results.List)-1]
	ident, ok := last.Type.(*ast.Ident)
	return ok && ident.Name == "error"
}

// countValidateRequiredCalls counts how many times validateRequired() is called
// as a method on a receiver within body.
func countValidateRequiredCalls(body *ast.BlockStmt, info *types.Info) int {
	count := 0
	EachInSubtree[ast.CallExpr](body, func(call *ast.CallExpr) {
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel == nil || sel.Sel.Name != "validateRequired" {
			return
		}
		if info != nil {
			if fn, ok := info.Selections[sel]; ok {
				if fn.Obj().Name() == "validateRequired" {
					count++
				}
				return
			}
		}
		// AST-only fallback
		count++
	})
	return count
}

// isServiceGoForScan returns true for service.go files in slice directories
// that should be scanned by the production A2 rule.
func isServiceGoForScan(rel string) bool {
	if strings.HasSuffix(rel, "_gen.go") {
		return false
	}
	if !strings.HasSuffix(rel, "/service.go") {
		return false
	}
	return strings.Contains(rel, "/slices/") || strings.Contains(rel, "/internal/")
}

// --- A3: Hand-written IsNilInterface Ban ---

// TestRequiredDepNilGuard_A3_HandwrittenIsNilInterfaceBan verifies that no
// hand-written service.go (non-gen file) calls validation.IsNilInterface.
//
// Production scan gated by REQUIRED_DEP_FUNNEL_PRODUCTION_SCAN.
// Fixture sub-test verifies logic against red_handwritten_guard.
func TestRequiredDepNilGuard_A3_HandwrittenIsNilInterfaceBan(t *testing.T) {
	for _, fix := range []string{"green_basic", "red_handwritten_guard"} {
		fix := fix
		t.Run("fixture_"+fix, func(t *testing.T) {
			root := findModuleRoot(t)
			fixtureDir := filepath.Join(root, "tools", "archtest", "testdata",
				"required_dep_nil_guard_fixtures", fix)
			pattern := "./tools/archtest/testdata/required_dep_nil_guard_fixtures/" + fix
			diags := RunTypedFixture(t, FixtureOpts{}, []string{pattern}, func(p *Pass) []Diagnostic {
				if p.TypesInfo == nil {
					return nil
				}
				var out []Diagnostic
				for _, file := range p.Files {
					rel := p.Rel(file)
					// Skip generated files — A3 only applies to hand-written service.go.
					if strings.HasSuffix(rel, "_gen.go") {
						continue
					}
					out = append(out, scanA3(p, file)...)
				}
				return out
			})
			goldenPath := filepath.Join(fixtureDir, "diag.golden")
			AssertGolden(t, goldenPath, diags)
		})
	}

	t.Run("production_scan", func(t *testing.T) {
		if os.Getenv("REQUIRED_DEP_FUNNEL_PRODUCTION_SCAN") == "" {
			t.Skip("production scan gated; set REQUIRED_DEP_FUNNEL_PRODUCTION_SCAN=1 after migration")
		}
		diags := RunTypedProduction(t, TypedOpts{}, func(p *Pass) []Diagnostic {
			if p.TypesInfo == nil {
				return nil
			}
			var out []Diagnostic
			for _, file := range p.Files {
				rel := p.Rel(file)
				if !isHandWrittenServiceFile(rel) {
					continue
				}
				out = append(out, scanA3(p, file)...)
			}
			return out
		})
		Report(t, requiredDepNilGuardRule+"-A3", diags)
	})
}

// scanA3 scans one file for A3 violations: calls to validation.IsNilInterface.
func scanA3(p *Pass, file *ast.File) []Diagnostic {
	var out []Diagnostic
	EachInSubtree[ast.CallExpr](file, func(call *ast.CallExpr) {
		if !isIsNilInterfaceCallee(call.Fun, p.TypesInfo) {
			return
		}
		out = append(out, Diagnostic{
			Rel:  p.Rel(file),
			Line: p.Fset.Position(call.Pos()).Line,
			Message: fmt.Sprintf(
				"REQUIRED-DEP-NIL-GUARD-01-A3: hand-written validation.IsNilInterface call in service.go "+
					"bypasses generated funnel (%s)", requiredDepNilGuardRule),
		})
	})
	return out
}

// isIsNilInterfaceCallee reports whether funExpr refers to validation.IsNilInterface.
func isIsNilInterfaceCallee(funExpr ast.Expr, info *types.Info) bool {
	sel, ok := funExpr.(*ast.SelectorExpr)
	if !ok || sel.Sel == nil || sel.Sel.Name != isNilInterfaceFunc {
		return false
	}
	if info != nil {
		obj := info.Uses[sel.Sel]
		if obj == nil {
			return false
		}
		fn, ok := obj.(*types.Func)
		if !ok || fn.Pkg() == nil {
			return false
		}
		return fn.Pkg().Path() == validationPkgPath
	}
	// AST-only fallback
	xIdent, ok := sel.X.(*ast.Ident)
	return ok && xIdent.Name == "validation"
}

// isHandWrittenServiceFile returns true for service.go files that are NOT generated.
func isHandWrittenServiceFile(rel string) bool {
	if strings.HasSuffix(rel, "_gen.go") {
		return false
	}
	return strings.HasSuffix(rel, "/service.go") &&
		(strings.Contains(rel, "/slices/") || strings.Contains(rel, "/internal/"))
}

// --- A4: Tag Value Whitelist ---

// TestRequiredDepNilGuard_A4_TagValueWhitelist verifies that all gocell struct
// tag values in production source are in {"", "required"}. Any typo (e.g.
// "requied") is caught.
func TestRequiredDepNilGuard_A4_TagValueWhitelist(t *testing.T) {
	root := findModuleRoot(t)
	scope := ModuleScope(root)
	diags := Run(t, scope, func(p *Pass) []Diagnostic {
		var out []Diagnostic
		for _, file := range p.Files {
			rel := p.Rel(file)
			if strings.HasPrefix(rel, "tools/") ||
				strings.HasPrefix(rel, "generated/") ||
				strings.HasPrefix(rel, "vendor/") {
				continue
			}
			out = append(out, scanA4(p, file)...)
		}
		return out
	})
	Report(t, requiredDepNilGuardRule+"-A4", diags)
}

// scanA4 scans one file for A4 violations: unknown gocell tag values.
func scanA4(p *Pass, file *ast.File) []Diagnostic {
	var out []Diagnostic
	EachInSubtree[ast.StructType](file, func(st *ast.StructType) {
		for _, field := range st.Fields.List {
			if field.Tag == nil {
				continue
			}
			raw := strings.Trim(field.Tag.Value, "`")
			val := reflect.StructTag(raw).Get("gocell")
			if val == "" || val == "required" {
				continue
			}
			out = append(out, Diagnostic{
				Rel:  p.Rel(file),
				Line: p.Fset.Position(field.Pos()).Line,
				Message: fmt.Sprintf(
					"REQUIRED-DEP-NIL-GUARD-01-A4: unknown gocell tag value %q (allowed: \"\", \"required\") (%s)",
					val, requiredDepNilGuardRule),
			})
		}
	})
	return out
}

// --- B1: No reflect nil check on required field ---

// TestRequiredDepNilGuard_BlindSpot_B1_NoReflectNilCheck is the reverse
// self-test for B1: asserts production code does not use reflect.ValueOf(s.X).IsNil()
// on fields of Service structs. This form bypasses A3's IsNilInterface check.
func TestRequiredDepNilGuard_BlindSpot_B1_NoReflectNilCheck(t *testing.T) {
	root := findModuleRoot(t)
	scope := ModuleScope(root)
	diags := Run(t, scope, func(p *Pass) []Diagnostic {
		var out []Diagnostic
		for _, file := range p.Files {
			rel := p.Rel(file)
			if !isHandWrittenServiceFile(rel) {
				continue
			}
			out = append(out, scanB1ReflectNilCheck(p, file)...)
		}
		return out
	})
	assert.Empty(t, diags,
		"B1 blind-spot: reflect.ValueOf(s.X).IsNil() on Service fields bypasses A3; use generated validateRequired() instead")
}

// scanB1ReflectNilCheck detects reflect.ValueOf(x).IsNil() call chains.
func scanB1ReflectNilCheck(p *Pass, file *ast.File) []Diagnostic {
	var out []Diagnostic
	EachInSubtree[ast.CallExpr](file, func(call *ast.CallExpr) {
		// Match: <expr>.IsNil()
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "IsNil" {
			return
		}
		// Check if receiver is reflect.ValueOf(...)
		inner, ok := sel.X.(*ast.CallExpr)
		if !ok {
			return
		}
		innerSel, ok := inner.Fun.(*ast.SelectorExpr)
		if !ok || innerSel.Sel.Name != "ValueOf" {
			return
		}
		xIdent, ok := innerSel.X.(*ast.Ident)
		if !ok || xIdent.Name != "reflect" {
			return
		}
		out = append(out, Diagnostic{
			Rel:  p.Rel(file),
			Line: p.Fset.Position(call.Pos()).Line,
			Message: "B1: reflect.ValueOf(s.X).IsNil() in service.go bypasses generated validateRequired() funnel",
		})
	})
	return out
}

// --- B2: No direct nil compare on required fields ---

// TestRequiredDepNilGuard_BlindSpot_B2_NoDirectNilCompare is the reverse
// self-test for B2: asserts that no hand-written service.go (non-gen file)
// contains a validateRequired() method body with raw `s.X == nil` comparisons.
// The generated validateRequired() always uses validation.IsNilInterface for
// interface-typed fields; a hand-written replacement using == nil would
// miss typed-nil values. This check scans only within validateRequired bodies
// in non-gen service files to avoid false positives from unrelated nil checks.
func TestRequiredDepNilGuard_BlindSpot_B2_NoDirectNilCompare(t *testing.T) {
	root := findModuleRoot(t)
	scope := ModuleScope(root)
	diags := Run(t, scope, func(p *Pass) []Diagnostic {
		var out []Diagnostic
		for _, file := range p.Files {
			rel := p.Rel(file)
			// Only check non-gen service files.
			if !isHandWrittenServiceFile(rel) {
				continue
			}
			out = append(out, scanB2ValidateRequiredBody(p, file)...)
		}
		return out
	})
	assert.Empty(t, diags,
		"B2 blind-spot: hand-written validateRequired() in service.go uses s.X == nil; "+
			"use validation.IsNilInterface to handle typed-nil interface values")
}

// scanB2ValidateRequiredBody checks if any hand-written validateRequired method
// uses raw == nil instead of validation.IsNilInterface.
func scanB2ValidateRequiredBody(p *Pass, file *ast.File) []Diagnostic {
	var out []Diagnostic
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Body == nil || fn.Name.Name != "validateRequired" {
			continue
		}
		// Found a validateRequired method — check for raw nil comparisons.
		EachInSubtree[ast.BinaryExpr](fn.Body, func(be *ast.BinaryExpr) {
			if be.Op.String() != "==" && be.Op.String() != "!=" {
				return
			}
			if !hasNilOperand(be) || !hasSelectorOperand(be) {
				return
			}
			out = append(out, Diagnostic{
				Rel:  p.Rel(file),
				Line: p.Fset.Position(be.Pos()).Line,
				Message: "B2: validateRequired() uses raw s.X == nil; use validation.IsNilInterface for interface fields",
			})
		})
	}
	return out
}

// hasNilOperand returns true if either side of the binary expression is nil.
func hasNilOperand(be *ast.BinaryExpr) bool {
	isNilIdent := func(e ast.Expr) bool {
		ident, ok := e.(*ast.Ident)
		return ok && ident.Name == "nil"
	}
	return isNilIdent(be.X) || isNilIdent(be.Y)
}

// hasSelectorOperand returns true if either side is a selector expression (s.field).
func hasSelectorOperand(be *ast.BinaryExpr) bool {
	_, lOK := be.X.(*ast.SelectorExpr)
	_, rOK := be.Y.(*ast.SelectorExpr)
	return lOK || rOK
}

// --- B3: No indirect IsNilInterface reference ---

// TestRequiredDepNilGuard_BlindSpot_B3_NoIndirectIsNilInterfaceRef verifies
// that every reference to validation.IsNilInterface in the module appears in
// direct call position (CallExpr.Fun), not as a function value / pointer.
// Generated files are allowlisted (they are the sanctioned call sites).
func TestRequiredDepNilGuard_BlindSpot_B3_NoIndirectIsNilInterfaceRef(t *testing.T) {
	seen := make(map[string]struct{})
	var violations []Diagnostic

	scan := func(p *Pass) []Diagnostic {
		if p.TypesInfo == nil {
			return nil
		}
		for _, file := range p.Files {
			rel := p.Rel(file)
			if strings.HasPrefix(rel, "tools/archtest/testdata/") {
				continue
			}
			violations = append(violations, scanB3IndirectRef(p, file, rel, seen)...)
		}
		return nil
	}
	_ = RunTyped(t, TypedOpts{}, []string{"./..."}, scan)
	_ = RunTyped(t, TypedOpts{Tags: ProductionFlatTags()}, []string{"./..."}, scan)

	sort.Slice(violations, func(i, j int) bool {
		if violations[i].Rel != violations[j].Rel {
			return violations[i].Rel < violations[j].Rel
		}
		return violations[i].Line < violations[j].Line
	})
	assert.Empty(t, violations,
		"B3: validation.IsNilInterface must only appear in direct call position; "+
			"indirect references bypass A3 form-uniqueness check")
}

// scanB3IndirectRef finds non-call-position references to IsNilInterface.
func scanB3IndirectRef(p *Pass, file *ast.File, rel string, seen map[string]struct{}) []Diagnostic {
	var out []Diagnostic
	// Collect all direct-call Ident positions (these are allowed).
	legalCallFun := make(map[*ast.Ident]struct{})
	EachInSubtree[ast.CallExpr](file, func(call *ast.CallExpr) {
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel == nil {
			return
		}
		if isIsNilInterfaceIdentObj(p.TypesInfo.Uses[sel.Sel]) {
			legalCallFun[sel.Sel] = struct{}{}
		}
	})
	// Check all Uses for IsNilInterface outside legal positions.
	for ident, obj := range p.TypesInfo.Uses {
		if !isIsNilInterfaceIdentObj(obj) {
			continue
		}
		identFile := p.Fset.Position(ident.Pos()).Filename
		if identFile != p.Abs(file) {
			continue
		}
		if _, ok := legalCallFun[ident]; ok {
			continue
		}
		// Generated files allowed.
		if strings.HasSuffix(rel, "_gen.go") {
			continue
		}
		key := fmt.Sprintf("%s:%d", rel, p.Fset.Position(ident.Pos()).Line)
		if _, dup := seen[key]; dup {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, Diagnostic{
			Rel:  rel,
			Line: p.Fset.Position(ident.Pos()).Line,
			Message: "B3: indirect reference to validation.IsNilInterface; only direct call is permitted",
		})
	}
	return out
}

// isIsNilInterfaceIdentObj reports whether obj is validation.IsNilInterface.
func isIsNilInterfaceIdentObj(obj types.Object) bool {
	if obj == nil {
		return false
	}
	fn, ok := obj.(*types.Func)
	if !ok || fn.Pkg() == nil {
		return false
	}
	return fn.Pkg().Path() == validationPkgPath && fn.Name() == isNilInterfaceFunc
}

// --- B4: No external nil guard helper funnel ---

// TestRequiredDepNilGuard_BlindSpot_B4_NoExternalNilGuardHelper verifies that
// service.go files do not call common nil-guard helper wrappers that could
// bypass A3. Ban list: MustNotBeNil, RequireNonNil, AssertNonNil, CheckNotNil.
func TestRequiredDepNilGuard_BlindSpot_B4_NoExternalNilGuardHelper(t *testing.T) {
	root := findModuleRoot(t)
	scope := ModuleScope(root)
	diags := Run(t, scope, func(p *Pass) []Diagnostic {
		var out []Diagnostic
		for _, file := range p.Files {
			rel := p.Rel(file)
			if !isHandWrittenServiceFile(rel) {
				continue
			}
			out = append(out, scanB4NilGuardHelper(p, file)...)
		}
		return out
	})
	assert.Empty(t, diags,
		"B4: service.go calls a banned nil-guard helper (MustNotBeNil/RequireNonNil/AssertNonNil/CheckNotNil); "+
			"use generated validateRequired() instead")
}

// scanB4NilGuardHelper detects calls to banned nil-guard helper functions.
func scanB4NilGuardHelper(p *Pass, file *ast.File) []Diagnostic {
	var out []Diagnostic
	EachInSubtree[ast.CallExpr](file, func(call *ast.CallExpr) {
		name := calleeSimpleName(call)
		for _, banned := range nilGuardHelperBanList {
			if name == banned {
				out = append(out, Diagnostic{
					Rel:  p.Rel(file),
					Line: p.Fset.Position(call.Pos()).Line,
					Message: fmt.Sprintf(
						"B4: banned nil-guard helper %q in service.go bypasses generated validateRequired() funnel",
						name),
				})
				return
			}
		}
	})
	return out
}

// calleeSimpleName returns the simple function/method name from a call expression.
func calleeSimpleName(call *ast.CallExpr) string {
	switch fn := call.Fun.(type) {
	case *ast.Ident:
		return fn.Name
	case *ast.SelectorExpr:
		return fn.Sel.Name
	}
	return ""
}

// --- B5: No validateRequired method value leak ---

// TestRequiredDepNilGuard_BlindSpot_B5_NoValidateRequiredMethodValueLeak
// verifies that validateRequired is only referenced in direct call position
// (s.validateRequired()), not as a method value (s.validateRequired without
// parens). Method value usage would bypass A2's count-based detection.
func TestRequiredDepNilGuard_BlindSpot_B5_NoValidateRequiredMethodValueLeak(t *testing.T) {
	seen := make(map[string]struct{})
	var violations []Diagnostic

	scan := func(p *Pass) []Diagnostic {
		if p.TypesInfo == nil {
			return nil
		}
		for _, file := range p.Files {
			rel := p.Rel(file)
			if strings.HasPrefix(rel, "tools/") ||
				strings.HasPrefix(rel, "generated/") {
				continue
			}
			violations = append(violations, scanB5MethodValueLeak(p, file, rel, seen)...)
		}
		return nil
	}
	_ = RunTyped(t, TypedOpts{}, []string{"./..."}, scan)
	_ = RunTyped(t, TypedOpts{Tags: ProductionFlatTags()}, []string{"./..."}, scan)

	sort.Slice(violations, func(i, j int) bool {
		if violations[i].Rel != violations[j].Rel {
			return violations[i].Rel < violations[j].Rel
		}
		return violations[i].Line < violations[j].Line
	})
	assert.Empty(t, violations,
		"B5: validateRequired must only appear in direct call (s.validateRequired()); "+
			"method-value usage bypasses A2 counting")
}

// scanB5MethodValueLeak finds validateRequired Sel references not in call position.
func scanB5MethodValueLeak(p *Pass, file *ast.File, rel string, seen map[string]struct{}) []Diagnostic {
	var out []Diagnostic
	// Collect all direct-call positions.
	legalCalls := make(map[*ast.Ident]struct{})
	EachInSubtree[ast.CallExpr](file, func(call *ast.CallExpr) {
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if ok && sel.Sel != nil && sel.Sel.Name == "validateRequired" {
			legalCalls[sel.Sel] = struct{}{}
		}
	})
	// Find all SelectorExpr with Sel.Name == "validateRequired".
	EachInSubtree[ast.SelectorExpr](file, func(sel *ast.SelectorExpr) {
		if sel.Sel == nil || sel.Sel.Name != "validateRequired" {
			return
		}
		if _, ok := legalCalls[sel.Sel]; ok {
			return
		}
		// Skip the method declaration itself.
		key := fmt.Sprintf("%s:%d", rel, p.Fset.Position(sel.Sel.Pos()).Line)
		if _, dup := seen[key]; dup {
			return
		}
		seen[key] = struct{}{}
		out = append(out, Diagnostic{
			Rel:  rel,
			Line: p.Fset.Position(sel.Sel.Pos()).Line,
			Message: "B5: validateRequired used as method value (not direct call); bypasses A2 count check",
		})
	})
	return out
}
