// Code generated by gocell generate required-deps. DO NOT EDIT.

package sessionlogin

import (
	"github.com/ghbvf/gocell/framework/pkg/errcode"
	"github.com/ghbvf/gocell/framework/pkg/validation"
)

// validateRequired verifies every required dependency on the Service struct
// is present and non-typed-nil. Generated from gocell:"required" struct field
// tags; do not edit by hand.
func (s *Service) validateRequired() error {
	if validation.IsNilInterface(s.userRepo) {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"sessionlogin.NewService: userRepo required")
	}
	if validation.IsNilInterface(s.sessionStore) {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"sessionlogin.NewService: sessionStore required")
	}
	if validation.IsNilInterface(s.txRunner) {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"sessionlogin.NewService: txRunner required")
	}
	if validation.IsNilInterface(s.emitter) {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"sessionlogin.NewService: emitter required")
	}
	return nil
}
