// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/config/publish/v1/contract.yaml

/** http.config.publish.v1.request */
export interface Request {
  key: string;
}

/** http.config.publish.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  id: string;
  configId: string;
  version: number;
  value: string;
  sensitive: boolean;
  publishedAt?: string;
}
