// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/iotdevice/cells/devicecell/slices/deviceregister/slice.yaml

package deviceregister

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "deviceregister",
	BelongsToCell:    "devicecell",
	ConsistencyLevel: "L4",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "http.device.register.v1", Role: "serve"},
		{Contract: "event.device-registered.v1", Role: "publish"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.deviceregister.service",
		},
		Contract: []string{
			"contract.http.device.register.v1.serve",
			"contract.event.device-registered.v1.publish",
		},
	},
	AllowedFiles: []string{
		"examples/iotdevice/cells/devicecell/slices/deviceregister/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta }
