// Code generated by gocell generate contract. DO NOT EDIT.
// source: examples/todoorder/contracts/http/order/create/v1/contract.yaml

/** http.order.create.v1.request */
export interface Request {
  item: string;
}

/** http.order.create.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  id: string;
  item: string;
  status: string;
}
