package healthz

import (
	"regexp"

	"github.com/ghbvf/gocell/framework/pkg/errcode"
	"github.com/ghbvf/gocell/framework/pkg/panicregister"
)

// ProbeName is the typed name for every healthz probe: adapter
// dependency-availability probes ("<x>_ready"), framework probes
// ("config_watcher", "config_drift", "outbox_failopen_rate_<cell>"), and
// cellgen cell-repo probes ("<cell>_repo_ready").
//
// Authoring path is split by ownership:
//
//   - Adapter dependency probes (e.g. postgres_ready) declare typed const at
//     the adapter's own package level (e.g. `const ProbeReady ProbeName =
//     "postgres_ready"` in adapters/postgres). The const becomes the single
//     truth for the probe name.
//
//   - Framework probes (config_watcher, config_drift) are typed const in this
//     package — see [ConfigWatcherProbeName] / [ConfigDriftProbeName].
//
//   - Cell-repo probes are typed const generated by cellgen into
//     `cells/<cell>/healthz_gen.go` (e.g. `const ProbeRepoReady ProbeName =
//     "configcore_repo_ready"`).
//
//   - Composed runtime names (where part of the name comes from runtime data,
//     e.g. "outbox_failopen_rate_<cell>") flow through a typed constructor
//     such as [EmitterFailOpenProbeName] — never via raw string concat at the
//     callsite.
//
// Hand-written `reg.RegisterReadiness(ProbeName(...), ...)` casts of arbitrary
// strings are rejected by archtest PROBENAME-SEALED-FUNNEL-01 (downstream A2:
// callsite must resolve to declared *types.Const; upstream A1: const must be
// declared in a sanctioned package; A3: any string-conversion at the callsite
// fails closed). Composed-name constructors are the only sanctioned path for
// runtime data to enter the typed-name funnel.
//
// ref: kubernetes/apimachinery `pkg/util/validation/validation.go::IsDNS1123Label`
// (runtime validator-shape on bare string — closest open-source analog;
// gocell tightens this to type-system + CI-time double-lock).
type ProbeName string

// String returns the underlying name as a plain string. It exists so
// `slog.Attr` and `fmt.Sprintf("%s", ...)` carry the literal probe name
// without revealing the typed nature in formatted output.
func (p ProbeName) String() string { return string(p) }

// probeNamePattern enforces snake_case (lowercase ASCII + digits + underscores),
// no leading digit, no consecutive underscores, no hyphens, no whitespace.
// The trailing "_ready" suffix is NOT enforced here — that overlay applies
// only to adapter dependency probes and is checked by
// archtest PROBENAME-SEALED-FUNNEL-01/A1 (adapter package-set overlay).
//
// Framework probes (`config_watcher`, `outbox_failopen_rate_<cell>`) and cell
// repo probes (`<cell>_repo_ready`) all satisfy this base pattern.
var probeNamePattern = regexp.MustCompile(`^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$`)

// probeNameMaxLen aligns with the Kubernetes DNS-1123 label cap (63) plus a
// one-character margin. Composed-name budgets fit comfortably: the longest
// runtime concat is EmitterFailOpenProbeName = "outbox_failopen_rate_" (21)
// + cellID; pkg/scaffoldid.IdentifierPattern caps cellID at 32 chars, so the
// worst-case composed value is 21+32=53 < 64. Choosing 64 (rather than 48)
// keeps a comfortable margin while staying within every downstream metric
// backend's label budget (Prometheus 1024, OTel 256).
//
// ref: kubernetes/apimachinery pkg/util/validation/validation.go::IsDNS1123Label
//
//	(label max 63); pkg/scaffoldid.IdentifierPattern (cellID max 32).
const probeNameMaxLen = 64

// NewProbeName validates s and returns a typed [ProbeName]. It is the only
// sanctioned runtime entry point — composed-name constructors call this with
// a literal+runtime concatenation, and tests use [MustProbeName] (panic
// variant) so the validation regex governs every test fixture too.
//
// Returns [errcode.ErrValidationFailed] when s is empty, exceeds
// probeNameMaxLen runes (64), contains uppercase letters, hyphens,
// whitespace, double-underscores, or starts with a digit.
func NewProbeName(s string) (ProbeName, error) {
	if s == "" {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: probe name must not be empty")
	}
	if len(s) > probeNameMaxLen {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: probe name exceeds length budget",
			errcode.WithDetails(
				errcode.PublicInt("max", probeNameMaxLen),
				errcode.PublicInt("got", len(s)),
			))
	}
	if !probeNamePattern.MatchString(s) {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: probe name must match snake_case lowercase regex",
			errcode.WithDetails(errcode.PublicString("name", s)))
	}
	return ProbeName(s), nil
}

// MustProbeName is the panic variant of [NewProbeName] for sites where an
// invalid name is a programmer error rather than a runtime condition. It is
// intended for use in any *_test.go file (any package) and the kernel/healthz
// internals; production callers outside kernel/healthz are rejected by archtest
// PROBENAME-SEALED-FUNNEL-01/A4b (caller allowlist).
//
// It routes through [panicregister.Approved] so the kernel recovery layer
// classifies the panic correctly. Production code that needs to validate a
// runtime-supplied string must use [NewProbeName] (returns an error) instead
// of MustProbeName (panics), to avoid availability risk when a runtime
// input source supplies unexpected characters.
func MustProbeName(s string) ProbeName {
	name, err := NewProbeName(s)
	if err != nil {
		panic(panicregister.Approved("healthz-probe-name-invalid",
			errcode.Assertion("healthz.MustProbeName(%q): %v", s, err)))
	}
	return name
}

// ConfigWatcherProbeName is the framework probe registered when a config
// watcher is active. Declared here (not in `runtime/bootstrap`) so the
// kernel layer owns the typed const set and bootstrap consumes it.
const ConfigWatcherProbeName ProbeName = "config_watcher"

// ConfigDriftProbeName is the framework probe registered when config supports
// generation-tracked drift detection.
const ConfigDriftProbeName ProbeName = "config_drift"

// EventRouterProbeName is the framework probe registered by the bootstrap event
// router, indicating the event routing layer is alive. Declared here so that
// bootstrap consumes a typed const rather than calling MustProbeName with a
// literal — archtest PROBENAME-SEALED-FUNNEL-01/A4b enforces that MustProbeName
// has zero production callers outside kernel/healthz and *_test.go.
const EventRouterProbeName ProbeName = "event_router"

const emitterFailOpenProbeNamePrefix = "outbox_failopen_rate_"

// EmitterFailOpenProbeName composes the typed probe name for the outbox
// direct-emitter fail-open-rate probe scoped to cellID. The cellID is
// validated against the full [NewProbeName] shape (so an invalid cellID
// such as "Bad-Cell" yields an error here, surfacing at emitter
// construction rather than per-probe invocation).
//
// This is the SOLE sanctioned composed-name constructor for emitter
// probes — bare `"outbox_failopen_rate_" + cellID` concat at callsites is
// rejected by archtest PROBENAME-SEALED-FUNNEL-01/A5.
func EmitterFailOpenProbeName(cellID string) (ProbeName, error) {
	if cellID == "" {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: emitter probe cellID must not be empty")
	}
	return NewProbeName(emitterFailOpenProbeNamePrefix + cellID)
}

// relayOperationProbeBases is the CLOSED set of base names RelayInstanceProbeName
// accepts — the three outbox relay operation probes. Values mirror
// runtime/outbox.{ProbePoll,ProbeReclaim,ProbeCleanup}; healthz cannot import
// runtime/outbox (import cycle), so they are mirrored here and kept honest
// fail-closed: a relay base rename in runtime/outbox makes the composer reject
// the new name (relay registration then fails fast, caught by the bootstrap
// fan-out tests), never silently composing a stale name.
var relayOperationProbeBases = map[ProbeName]struct{}{
	"outbox_relay_poll":    {},
	"outbox_relay_reclaim": {},
	"outbox_relay_cleanup": {},
}

// RelayInstanceProbeName composes the instance-scoped variant of an outbox
// relay operation probe (base MUST be one of outbox_relay_poll / _reclaim /
// _cleanup — enforced against a closed allowlist) for a fanned-out relay that is
// NOT the colocated default infra instance, so N relays expose globally-distinct
// probe names (#2152 PR-1). The colocated default keeps the bare base name
// (operations contract unchanged); only additional instances get the
// "<base>_<instanceID>" suffix.
//
// base is validated against relayOperationProbeBases so this relay-specific
// constructor cannot mint a misleading "outbox_relay_*"-shaped name from an
// arbitrary ProbeName. instanceID is the deduplicated infra instance id (a
// lowercase snake_case identifier minted by the composition root), validated
// against the full [NewProbeName] shape via the composed result, so an invalid
// id surfaces at relay registration rather than per-probe invocation. This is
// the SOLE sanctioned composed-name constructor for relay-instance probes — a
// sibling of EmitterFailOpenProbeName / ProjectionStoreReadyProbeName /
// SagaTailerReadyProbeName.
//
// Budget: longest relay base "outbox_relay_cleanup" (20) + "_" + instanceID
// (≤32, runtime/bootstrap.infraInstanceIDMaxLen) = ≤53 < probeNameMaxLen (64).
func RelayInstanceProbeName(base ProbeName, instanceID string) (ProbeName, error) {
	if _, ok := relayOperationProbeBases[base]; !ok {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: relay instance probe base must be an outbox relay operation probe (outbox_relay_poll/reclaim/cleanup)")
	}
	if instanceID == "" {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: relay instance probe id must not be empty")
	}
	return NewProbeName(string(base) + "_" + instanceID)
}

// postgresPoolProbeBases is the CLOSED set of base names PoolInstanceProbeName
// accepts — the postgres serving-pool readiness probes. Values mirror
// adapters/postgres.{ProbeReady, ProbeIndexesValidReady, ProbeAppRoleRestrictedReady};
// healthz cannot import adapters/postgres (import direction), so they are mirrored
// here and kept honest fail-closed: a pool probe rename in adapters/postgres makes
// the composer reject the new name (split pool registration then fails fast, caught
// by the bootstrap fan-out tests), never silently composing a stale name.
var postgresPoolProbeBases = map[ProbeName]struct{}{
	"postgres_ready":                     {},
	"postgres_indexes_valid_ready":       {},
	"postgres_app_role_restricted_ready": {},
}

// PoolInstanceProbeName composes the instance-scoped variant of a postgres
// serving-pool readiness probe (base MUST be one of postgres_ready /
// postgres_indexes_valid_ready / postgres_app_role_restricted_ready — enforced
// against a closed allowlist) for a fanned-out per-cell pool that is NOT the
// colocated default infra instance, so N pools expose globally-distinct probe
// names (#2341). The colocated default keeps the bare base name (operations
// contract unchanged); only additional split instances get the
// "<base>_<instanceID>" suffix. This is the SOLE sanctioned composed-name
// constructor for per-instance pool probes — a sibling of RelayInstanceProbeName.
//
// Budget: longest pool base "postgres_app_role_restricted_ready" (34) + "_" +
// instanceID = ≤67 for a 32-char id, so a >29-char instanceID overflows
// probeNameMaxLen (64) and NewProbeName fails fast at pool registration. Real
// instance ids are cell IDs (≤~12 chars), well within budget.
func PoolInstanceProbeName(base ProbeName, instanceID string) (ProbeName, error) {
	if _, ok := postgresPoolProbeBases[base]; !ok {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: pool instance probe base must be a postgres serving-pool readiness probe "+
				"(postgres_ready / postgres_indexes_valid_ready / postgres_app_role_restricted_ready)")
	}
	if instanceID == "" {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: pool instance probe id must not be empty")
	}
	return NewProbeName(string(base) + "_" + instanceID)
}

// remoteCellReadyProbeNameSuffix is the terminal segment of the cross-cell
// remote-peer readiness probe name ("<cellID>_remote_ready"). It is a
// dependency-availability probe (the remote peer's listener is TCP-reachable),
// so it carries the "_ready" suffix per observability.md.
const remoteCellReadyProbeNameSuffix = "_remote_ready"

// RemoteCellReadyProbeName composes the typed probe name for a split-topology
// remote-peer readiness probe scoped to targetCellID: "<cellID>_remote_ready"
// (#2251 P2.7). It is registered by celltransport.Resolve's remote branch so a
// peer that becomes unreachable degrades the consuming cell's /readyz (lets ops
// shed traffic) without killing liveness.
//
// The cellID is validated against the full [NewProbeName] shape, so an invalid
// cellID surfaces at transport-resolution time rather than per-probe invocation.
// Budget: suffix "_remote_ready" (13) + cellID (≤32, pkg/scaffoldid cap) = ≤45 < 64.
//
// This is the SOLE sanctioned composed-name constructor for remote-peer
// readiness probes — bare `cellID + "_remote_ready"` concat at callsites is
// rejected by archtest PROBENAME-SEALED-FUNNEL-01 (A2 cast-ban + A4 NewProbeName
// caller-allowlist), the same closure as [EmitterFailOpenProbeName].
func RemoteCellReadyProbeName(targetCellID string) (ProbeName, error) {
	if targetCellID == "" {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: remote-cell readiness probe targetCellID must not be empty")
	}
	return NewProbeName(targetCellID + remoteCellReadyProbeNameSuffix)
}

// projectionProbeNameInfix forms the fixed middle segment shared by all
// projection probe names: "<cellID>_projection_<projectionID>_…".
// Length = len("_projection_") = 12.
const projectionProbeNameInfix = "_projection_"

// projectionStoreReadySuffix and projectionLagSuffix are the terminal segments
// of the two projection probe names, per observability.md conventions:
//   - "…_store_ready": dependency-availability probe (_ready suffix required)
//   - "…_lag": operational-health probe (no _ready suffix — same convention as
//     outbox_relay_poll / outbox_relay_reclaim / outbox_relay_cleanup)
const (
	projectionStoreReadySuffix = "_store_ready"
	projectionLagSuffix        = "_lag"
)

// ProjectionStoreReadyProbeName composes the typed probe name for the
// projection store-readiness probe:
// "<cellID>_projection_<projectionID>_store_ready". This is a dependency-
// availability probe (storage reachable); the "_ready" suffix is required per
// observability.md.
//
// Budget: fixed infix "_projection_" (12) + suffix "_store_ready" (12) = 24
// chars. So len(cellID)+len(projectionID) must be ≤ 40 (64 − 24).
// NewProbeName fail-fast on overflow.
//
// This is one of the TWO sole-sanctioned composed-name constructors for
// projection probes. The composed-name closure is: A2 cast-ban + A4
// NewProbeName caller-allowlist (kernel/healthz/probename.go) + sole
// constructors (here and ProjectionLagProbeName) — Hard up+downstream.
// No A5-style prefix scan is needed (A2+A4 already prevent any bypass).
func ProjectionStoreReadyProbeName(cellID, projectionID string) (ProbeName, error) {
	if cellID == "" || projectionID == "" {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: projection probe cellID and projectionID must not be empty")
	}
	return NewProbeName(cellID + projectionProbeNameInfix + projectionID + projectionStoreReadySuffix)
}

// ProjectionLagProbeName composes the typed probe name for the projection
// replay-lag probe: "<cellID>_projection_<projectionID>_lag". This is an
// operational-health probe (read-model staleness); per observability.md it
// does NOT carry the "_ready" suffix — same convention as
// outbox_relay_poll / outbox_relay_reclaim.
//
// Budget: fixed infix "_projection_" (12) + suffix "_lag" (4) = 16 chars.
// So len(cellID)+len(projectionID) must be ≤ 48 (64 − 16).
// NewProbeName fail-fast on overflow.
//
// This is one of the TWO sole-sanctioned composed-name constructors for
// projection probes. See ProjectionStoreReadyProbeName for the closure note.
func ProjectionLagProbeName(cellID, projectionID string) (ProbeName, error) {
	if cellID == "" || projectionID == "" {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: projection probe cellID and projectionID must not be empty")
	}
	return NewProbeName(cellID + projectionProbeNameInfix + projectionID + projectionLagSuffix)
}

// sagaTailerProbeNameInfix forms the fixed middle segment of the saga-journal
// Tailer readiness probe name: "<cellID>_saga_tailer_<projectionID>_ready".
// sagaTailerReadySuffix is the terminal "_ready" segment (dependency-
// availability probe per observability.md).
const (
	sagaTailerProbeNameInfix = "_saga_tailer_" // len 13
	sagaTailerReadySuffix    = "_ready"        // len 6
)

// SagaTailerReadyProbeName composes the typed probe name for the saga-journal
// projection Tailer readiness probe:
// "<cellID>_saga_tailer_<projectionID>_ready". This is a dependency-availability
// probe (Tailer running + journal/checkpoint storage reachable); the "_ready"
// suffix is required per observability.md.
//
// It is per-(cellID, projectionID) — like the projection store-ready/lag probe
// names — so multiple Tailers in one process register distinct probe names
// (a static name would fail-fast on duplicate registration). Tailer replay-lag
// is exposed as a metric gauge (tailer.Observer.ObserveLag), not a second probe.
//
// Budget: fixed infix "_saga_tailer_" (13) + suffix "_store_ready"-equivalent
// "_ready" (6) = 19 chars. So len(cellID)+len(projectionID) must be ≤ 45 (64 − 19).
// NewProbeName fail-fast on overflow.
//
// Sole-sanctioned constructor for the saga Tailer readiness probe; routes
// through the NewProbeName A4 caller-allowlist (PROBENAME-SEALED-FUNNEL-01).
func SagaTailerReadyProbeName(cellID, projectionID string) (ProbeName, error) {
	if cellID == "" || projectionID == "" {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: saga tailer probe cellID and projectionID must not be empty")
	}
	return NewProbeName(cellID + sagaTailerProbeNameInfix + projectionID + sagaTailerReadySuffix)
}
