// Package orderstatus implements the orderstatus slice: querying the saga
// terminal state for an order via GET /api/v1/orders/{id}.
//
// The slice queries the in-memory OrderRepository to confirm the order exists,
// then loads the journal event log to derive the saga status projection:
//
//	accepted     — order enrolled but no terminal journal event yet
//	running      — forward steps in progress (KindStepCompleted seen)
//	succeeded    — saga reached KindSagaSucceeded
//	compensated  — saga reached KindSagaCompensated
//	failed       — saga reached KindSagaFailed / KindSagaExpired / KindSagaCompensationFailed
//
// Status mapping is a deterministic fold of journal events — no separate
// projection store is required for demo mode.
package orderstatus

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/ghbvf/gocell/examples/orderfulfillment/cells/orderfulfillmentcell/internal/ports"
	orderstatusgen "github.com/ghbvf/gocell/generated/contracts/http/orderfulfillment/orderstatus/v1"
	"github.com/ghbvf/gocell/kernel/clock"
	"github.com/ghbvf/gocell/kernel/saga/journal"
	"github.com/ghbvf/gocell/pkg/idutil"
	"github.com/ghbvf/gocell/pkg/validation"
)

// Status values are the generated closed value-set from the orderstatus response
// schema (orderstatusgen.ResponseDataStatus*, #1935) — the schema enum is the single
// source, so the wire status vocabulary cannot drift from this derivation.

// Option configures the orderstatus Service.
type Option func(*Service)

// WithOrderRepository sets the order repository used to confirm order existence.
// Typed-nil inputs are not stored; the factory will fail-fast if the repo
// remains unset.
func WithOrderRepository(r ports.OrderRepository) Option {
	return func(s *Service) {
		if !validation.IsNilInterface(r) {
			s.orders = r
		}
	}
}

// WithJournal sets the saga journal for loading instance event history.
// Typed-nil inputs are not stored; the factory will fail-fast if the journal
// remains unset.
func WithJournal(j journal.Reader) Option {
	return func(s *Service) {
		if !validation.IsNilInterface(j) {
			s.journal = j
		}
	}
}

// WithLogger sets the structured logger. A nil value is a silent noop.
func WithLogger(l *slog.Logger) Option {
	return func(s *Service) {
		if l != nil {
			s.logger = l
		}
	}
}

// Service implements the order status query business logic.
// Required fields are tagged gocell:"required"; validateRequired() is
// generated by `gocell generate required-deps`.
type Service struct {
	orders  ports.OrderRepository `gocell:"required"`
	journal journal.Reader        `gocell:"required"`
	clock   clock.Clock
	logger  *slog.Logger
}

// NewService creates an orderstatus Service. Returns an error if required
// dependencies (orders, journal) are nil.
func NewService(clk clock.Clock, opts ...Option) (*Service, error) {
	clock.MustHaveClock(clk, "orderstatus.NewService")
	s := &Service{
		clock:  clk,
		logger: slog.Default(),
	}
	for _, o := range opts {
		o(s)
	}
	if err := s.validateRequired(); err != nil {
		return nil, err
	}
	return s, nil
}

// GetOrderStatus returns the saga status for the given order ID.
// Returns ErrOrderNotFound (KindNotFound) when the order does not exist.
//
// Status semantics:
//   - accepted: the order exists, the journal has been enqueued, and no
//     forward step event has been recorded yet (Load returns an empty slice).
//   - running / succeeded / compensated / failed: derived from the event log.
//
// A KindNotFound error from Load indicates the saga was never enqueued for an
// order that does exist — an orphan order caused by a failed Enqueue call.
// This is a data-consistency anomaly and is reported as an error rather than
// silently treated as "accepted", because masking it would hide enrollment
// bugs (e.g. a network partition between the order write and the journal
// Enqueue call).
func (s *Service) GetOrderStatus(ctx context.Context, orderID string) (orderstatusgen.ResponseDataStatus, error) {
	// Confirm the order exists — returns ErrOrderNotFound if absent.
	if _, err := s.orders.GetByID(ctx, orderID); err != nil {
		return "", fmt.Errorf("orderstatus: get order: %w", err)
	}

	events, err := s.journal.Load(ctx, idutil.SafeID(orderID))
	if err != nil {
		// The order exists but the journal has no record for it: this is an
		// orphan order (Enqueue failed after the order was persisted). Report
		// an error rather than silently returning "accepted" — the caller
		// should investigate or retry enrollment.
		return "", fmt.Errorf("orderstatus: load journal: %w", err)
	}

	status := s.deriveStatus(events)
	s.logger.Info(
		"orderstatus: status derived",
		slog.String("order_id", orderID),
		slog.String("status", string(status)),
	)
	return status, nil
}

// deriveStatus folds the journal event log into a status string.
// The last terminal event wins; if no terminal event, a forward step indicator
// determines accepted vs running.
//
// All eleven EventKind values are explicitly listed:
//   - Terminal kinds (KindSagaSucceeded / KindSagaCompensated / KindSagaFailed /
//     KindSagaExpired / KindSagaCompensationFailed) return the corresponding
//     status immediately.
//   - Non-terminal kinds (KindStepStarted / KindStepCompleted / KindStepFailed /
//     KindStepCompensated / KindCompensationStarted / KindStepCompensationFailed)
//     all set sawStep=true — they confirm the saga is active (running or
//     compensating), so the derived status is "running" rather than "accepted".
//
// The default branch is an out-of-range defensive guard: it should be
// unreachable with the current EventKind set. SAGA-STATUS-FANOUT-COVERAGE-01
// does not guard this consumer-side switch, so a runtime Warn is the required
// fallback for any future EventKind added without updating this switch.
func (s *Service) deriveStatus(events []journal.Event) orderstatusgen.ResponseDataStatus {
	var sawStep bool
	for _, ev := range events {
		switch ev.Kind {
		case journal.KindSagaSucceeded:
			return orderstatusgen.ResponseDataStatusSucceeded
		case journal.KindSagaCompensated:
			return orderstatusgen.ResponseDataStatusCompensated
		case journal.KindSagaFailed, journal.KindSagaExpired, journal.KindSagaCompensationFailed:
			return orderstatusgen.ResponseDataStatusFailed
		case journal.KindStepStarted, journal.KindStepCompleted,
			journal.KindStepFailed, journal.KindStepCompensated,
			journal.KindCompensationStarted, journal.KindStepCompensationFailed:
			sawStep = true
		default:
			s.logger.Warn(
				"orderstatus: unrecognized journal event kind",
				slog.String("kind", ev.Kind.String()),
			)
		}
	}
	if sawStep {
		return orderstatusgen.ResponseDataStatusRunning
	}
	return orderstatusgen.ResponseDataStatusAccepted
}
