// Package orderstatus implements the orderstatus slice: the CQRS read model
// for order-saga status, populated by HandleOrderEvent (saga-journal projection
// Apply handler) and queried by GetOrderStatus (HTTP GET).
//
// Status semantics:
//
//	accepted     — order exists AND saga enrollment is guaranteed (PlaceOrder
//	               only returns 202 after a successful/idempotent Enqueue, and
//	               idempotent retries self-heal enrollment) but the projection
//	               Tailer has not yet applied any saga event for it (no read-model
//	               row); this is the eventual-consistency gap between Enqueue and
//	               the first Tailer tick.
//	running      — at least one forward or compensation step event seen.
//	succeeded    — saga reached KindSagaSucceeded (terminal, absorbing).
//	compensated  — saga reached KindSagaCompensated (terminal, absorbing).
//	failed       — saga reached KindSagaFailed / KindSagaExpired /
//	               KindSagaCompensationFailed (terminal, absorbing).
//
// The read model is built incrementally via HandleOrderEvent; GetOrderStatus
// is a point-in-time read of the read model.
package orderstatus

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"

	"github.com/ghbvf/gocell/examples/orderfulfillment/cells/orderfulfillmentcell/internal/ports"
	"github.com/ghbvf/gocell/examples/orderfulfillment/cells/orderfulfillmentcell/internal/projection"
	"github.com/ghbvf/gocell/framework/kernel/cellvocab"
	"github.com/ghbvf/gocell/framework/kernel/clock"
	"github.com/ghbvf/gocell/framework/kernel/outbox"
	"github.com/ghbvf/gocell/framework/kernel/saga/journal"
	"github.com/ghbvf/gocell/framework/kernel/saga/sagaprojection"
	"github.com/ghbvf/gocell/framework/pkg/validation"
	orderstatusgen "github.com/ghbvf/gocell/generated/contracts/http/orderfulfillment/orderstatus/v1"
)

// Option configures the orderstatus Service.
type Option func(*Service)

// WithOrderRepository sets the order repository used to confirm order existence.
// Typed-nil inputs are not stored; the factory will fail-fast if the repo
// remains unset.
func WithOrderRepository(r ports.OrderRepository) Option {
	return func(s *Service) {
		if !validation.IsNilInterface(r) {
			s.orders = r
		}
	}
}

// WithOrderStatusReadModel injects the CQRS read model that the projection Apply
// handler writes to and GetOrderStatus reads from.
// Typed-nil inputs are not stored; the factory will fail-fast if the model
// remains unset.
func WithOrderStatusReadModel(rm projection.OrderStatusReadModel) Option {
	return func(s *Service) {
		if !validation.IsNilInterface(rm) {
			s.readModel = rm
		}
	}
}

// WithLogger sets the structured logger. A nil value is a silent noop.
func WithLogger(l *slog.Logger) Option {
	return func(s *Service) {
		if l != nil {
			s.logger = l
		}
	}
}

// Service implements the order status query and projection apply business logic.
// Required fields are tagged gocell:"required"; validateRequired() is
// generated by `gocell generate required-deps`.
type Service struct {
	orders    ports.OrderRepository           `gocell:"required"`
	readModel projection.OrderStatusReadModel `gocell:"required"`
	clock     clock.Clock
	logger    *slog.Logger
}

// NewService creates an orderstatus Service. Returns an error if required
// dependencies (orders, readModel) are nil.
func NewService(clk clock.Clock, opts ...Option) (*Service, error) {
	clock.MustHaveClock(clk, "orderstatus.NewService")
	s := &Service{
		clock:  clk,
		logger: slog.Default(),
	}
	for _, o := range opts {
		o(s)
	}
	if err := s.validateRequired(); err != nil {
		return nil, err
	}
	return s, nil
}

// GetOrderStatus returns the saga status for the given order ID.
// Returns ErrOrderNotFound (KindNotFound) when the order does not exist.
//
// Status semantics:
//   - accepted: the order exists AND saga enrollment is guaranteed (PlaceOrder
//     only returns 202 after a successful or idempotent Enqueue, and idempotent
//     retries self-heal enrollment — see placeorder.Service.PlaceOrder F4) AND
//     the projection Tailer has not yet applied any saga event for it (no
//     read-model row). This is the eventual-consistency gap between Enqueue and
//     the first Tailer tick. An order created but whose PlaceOrder returned an
//     error (no 202) was never enrolled; the client received an error, not this
//     status, so a no-row order reaching this point is always enrolled.
//   - running / succeeded / compensated / failed: from the read model.
func (s *Service) GetOrderStatus(ctx context.Context, orderID string) (orderstatusgen.ResponseDataStatus, error) {
	// Confirm the order exists — returns ErrOrderNotFound if absent.
	if _, err := s.orders.GetByID(ctx, orderID); err != nil {
		return "", fmt.Errorf("orderstatus: get order: %w", err)
	}

	status, found, err := s.readModel.Get(ctx, orderID)
	if err != nil {
		return "", fmt.Errorf("orderstatus: read model get: %w", err)
	}
	if !found {
		// Order exists but projection has not yet applied any saga event —
		// the saga was enrolled (Enqueue), but the Tailer hasn't ticked yet.
		// Return "accepted" to signal "enrolled but no status yet".
		return orderstatusgen.ResponseDataStatusAccepted, nil
	}

	s.logger.Debug(
		"orderstatus: status derived",
		slog.String("order_id", orderID),
		slog.String("status", string(status)),
	)
	return status, nil
}

// HandleOrderEvent is the saga-journal projection Apply handler.
// It decodes the SagaEventEnvelope from the event payload, folds the kind into
// the current read-model status, and upserts the result.
//
// Bad payload / unknown kind / malformed EventID → outbox.PermanentError. A
// permanent apply error HALTS the Tailer's checkpoint advance (fail-closed — the
// poison event blocks the projection until operator intervention); it does NOT
// route to a DLX (the saga-journal Tailer has no dead-letter path, unlike the
// outbox ConsumerBase). See runtime/saga/tailer.commitEvent: a non-nil apply
// error aborts the apply+advance transaction so the checkpoint never moves past
// the poison event.
// Read-model write errors → transient error (retried by the Tailer next tick).
func (s *Service) HandleOrderEvent(ctx context.Context, event cellvocab.ProjectionEvent) error {
	// Decode the SagaEventEnvelope from the event payload.
	var env sagaprojection.SagaEventEnvelope
	if err := json.Unmarshal(event.Payload(), &env); err != nil {
		return outbox.NewPermanentError(fmt.Errorf(
			"orderstatus: decode saga event envelope: %w", err,
		))
	}

	// Map string kind label back to typed EventKind.
	kind, ok := journal.ParseEventKind(env.Kind)
	if !ok {
		return outbox.NewPermanentError(fmt.Errorf(
			"orderstatus: unknown saga event kind %q in envelope; reject as permanent", env.Kind,
		))
	}

	// Extract orderID from EventID: "saga-journal:<globalSeq>@<instanceID>".
	// In orderfulfillment the instanceID equals the orderID (single saga
	// definition). A malformed EventID is a producer-side defect: return a
	// permanent error so the Tailer HALTS its checkpoint advance at this poison
	// event (fail-closed — see HandleOrderEvent godoc).
	_, orderID, err := sagaprojection.ParseSagaJournalEventID(event.EventID())
	if err != nil {
		return outbox.NewPermanentError(fmt.Errorf(
			"orderstatus: malformed EventID %q: %w", event.EventID(), err,
		))
	}

	// Read current status (zero = no row yet), fold, and upsert.
	cur, _, rdErr := s.readModel.Get(ctx, orderID)
	if rdErr != nil {
		return fmt.Errorf("orderstatus: read model get for %s: %w", orderID, rdErr)
	}
	next, foldErr := projection.FoldStatus(cur, kind)
	if foldErr != nil {
		// FoldStatus only fails on unknown kind — already validated above.
		// foldErr is already an *outbox.PermanentError; %w preserves the permanent marker.
		return fmt.Errorf("orderstatus: fold status for %s kind=%s: %w", orderID, env.Kind, foldErr)
	}
	if upsertErr := s.readModel.Upsert(ctx, orderID, next); upsertErr != nil {
		return fmt.Errorf("orderstatus: read model upsert for %s: %w", orderID, upsertErr)
	}

	s.logger.Debug(
		"orderstatus: applied saga event",
		slog.String("order_id", orderID),
		slog.String("kind", env.Kind),
		slog.String("status", string(next)),
	)
	return nil
}
