// Package orderstatus implements the orderstatus slice: querying the saga
// terminal state for an order via GET /api/v1/orders/{id}.
//
// The slice queries the in-memory OrderRepository to confirm the order exists,
// then loads the journal event log to derive the saga status projection:
//
//	accepted     — order enrolled but no terminal journal event yet
//	running      — forward steps in progress (KindStepCompleted seen)
//	succeeded    — saga reached KindSagaSucceeded
//	compensated  — saga reached KindSagaCompensated
//	failed       — saga reached KindSagaFailed / KindSagaExpired / KindSagaCompensationFailed
//
// Status mapping is a deterministic fold of journal events — no separate
// projection store is required for demo mode.
package orderstatus

import (
	"context"
	"fmt"
	"log/slog"

	"errors"

	"github.com/ghbvf/gocell/examples/orderfulfillment/cells/orderfulfillmentcell/internal/ports"
	"github.com/ghbvf/gocell/kernel/clock"
	"github.com/ghbvf/gocell/kernel/saga/journal"
	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/idutil"
	"github.com/ghbvf/gocell/pkg/validation"
)

// Status string values returned over the wire.
const (
	StatusAccepted    = "accepted"    // enrolled but no terminal event yet
	StatusRunning     = "running"     // forward steps started
	StatusSucceeded   = "succeeded"   // KindSagaSucceeded
	StatusCompensated = "compensated" // KindSagaCompensated
	StatusFailed      = "failed"      // KindSagaFailed / Expired / CompensationFailed
)

// Option configures the orderstatus Service.
type Option func(*Service)

// WithOrderRepository sets the order repository used to confirm order existence.
// Typed-nil inputs are not stored; the factory will fail-fast if the repo
// remains unset.
func WithOrderRepository(r ports.OrderRepository) Option {
	return func(s *Service) {
		if !validation.IsNilInterface(r) {
			s.orders = r
		}
	}
}

// WithJournal sets the saga journal for loading instance event history.
// Typed-nil inputs are not stored; the factory will fail-fast if the journal
// remains unset.
func WithJournal(j journal.JournalCore) Option {
	return func(s *Service) {
		if !validation.IsNilInterface(j) {
			s.journal = j
		}
	}
}

// WithLogger sets the structured logger. A nil value is a silent noop.
func WithLogger(l *slog.Logger) Option {
	return func(s *Service) {
		if l != nil {
			s.logger = l
		}
	}
}

// Service implements the order status query business logic.
// Required fields are tagged gocell:"required"; validateRequired() is
// generated by `gocell generate required-deps`.
type Service struct {
	orders  ports.OrderRepository `gocell:"required"`
	journal journal.JournalCore   `gocell:"required"`
	clock   clock.Clock
	logger  *slog.Logger
}

// NewService creates an orderstatus Service. Returns an error if required
// dependencies (orders, journal) are nil.
func NewService(clk clock.Clock, opts ...Option) (*Service, error) {
	clock.MustHaveClock(clk, "orderstatus.NewService")
	s := &Service{
		clock:  clk,
		logger: slog.Default(),
	}
	for _, o := range opts {
		o(s)
	}
	if err := s.validateRequired(); err != nil {
		return nil, err
	}
	return s, nil
}

// GetOrderStatus returns the saga status for the given order ID.
// Returns ErrOrderNotFound (KindNotFound) when the order does not exist.
func (s *Service) GetOrderStatus(ctx context.Context, orderID string) (string, error) {
	// Confirm the order exists — returns ErrOrderNotFound if absent.
	if _, err := s.orders.GetByID(ctx, orderID); err != nil {
		return "", fmt.Errorf("orderstatus: get order: %w", err)
	}

	events, err := s.journal.Load(ctx, idutil.SafeID(orderID))
	if err != nil {
		// Journal returns ErrSagaNotFound when the instance has not yet been
		// enrolled (e.g. the order was just created but the saga coordinator has
		// not yet processed it). Treat as "accepted" (enrolled but not started).
		var ec *errcode.Error
		if errors.As(err, &ec) && ec.Kind == errcode.KindNotFound {
			return StatusAccepted, nil
		}
		return "", fmt.Errorf("orderstatus: load journal: %w", err)
	}

	status := deriveStatus(events)
	s.logger.Debug("orderstatus: status derived",
		slog.String("order_id", orderID),
		slog.String("status", status),
	)
	return status, nil
}

// deriveStatus folds the journal event log into a status string.
// The last terminal event wins; if no terminal event, a forward step indicator
// determines accepted vs running.
func deriveStatus(events []journal.Event) string {
	var sawStep bool
	for _, ev := range events {
		switch ev.Kind {
		case journal.KindSagaSucceeded:
			return StatusSucceeded
		case journal.KindSagaCompensated:
			return StatusCompensated
		case journal.KindSagaFailed, journal.KindSagaExpired, journal.KindSagaCompensationFailed:
			return StatusFailed
		case journal.KindStepCompleted, journal.KindStepStarted:
			sawStep = true
		}
	}
	if sawStep {
		return StatusRunning
	}
	return StatusAccepted
}

