// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/demo/cells/democell/slices/hello/slice.yaml

package hello

import (
	"github.com/ghbvf/gocell/framework/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "hello",
	BelongsToCell:    "democell",
	ConsistencyLevel: "L0",
	Lifecycle:        "experimental",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "http.demo.hello.v1", Role: "serve"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.hello.service",
		},
		Contract: []string{
			"contract.http.demo.hello.v1.serve",
		},
	},
	AllowedFiles: []string{
		"examples/demo/cells/democell/slices/hello/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }
