// Package sessionlogin implements the session-login slice: password-based login
// with JWT issuance.
package sessionlogin

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"golang.org/x/crypto/bcrypt"

	"github.com/ghbvf/gocell/cells/accesscore/internal/domain"
	"github.com/ghbvf/gocell/cells/accesscore/internal/dto"
	"github.com/ghbvf/gocell/cells/accesscore/internal/ports"
	"github.com/ghbvf/gocell/cells/accesscore/internal/sessionmint"
	"github.com/ghbvf/gocell/kernel/outbox"
	"github.com/ghbvf/gocell/kernel/persistence"
	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/validation"
	"github.com/ghbvf/gocell/runtime/auth"
	"github.com/google/uuid"
)

// sessionIDPrefix is the prefix applied to every session ID generated by this
// slice. Kept as a single constant so Login and IssueForUser stay in lockstep
// when the format needs to evolve.
const sessionIDPrefix = "sess-"

// TokenPair holds the issued access and refresh tokens.
type TokenPair struct {
	AccessToken           string
	RefreshToken          string
	ExpiresAt             time.Time
	SessionID             string
	PasswordResetRequired bool
}

// Option configures a session-login Service.
type Option func(*Service)

// WithEmitter sets the event emitter.
func WithEmitter(e outbox.Emitter) Option {
	return func(s *Service) {
		if e != nil {
			s.emitter = e
		}
	}
}

// WithTxManager sets the TxRunner for transactional guarantees (L2 atomicity).
func WithTxManager(tx persistence.TxRunner) Option {
	return func(s *Service) { s.txRunner = persistence.RunnerOrNoop(tx) }
}

// Service implements password login with JWT issuance.
type Service struct {
	userRepo    ports.UserRepository
	sessionRepo ports.SessionRepository
	roleRepo    ports.RoleRepository
	txRunner    persistence.TxRunner
	emitter     outbox.Emitter
	issuer      *auth.JWTIssuer
	logger      *slog.Logger
}

// NewService creates a session-login Service.
// The audience for issued tokens is carried inside issuer (set from Registry at
// construction time via config.NewJWTIssuerFromRegistry). This slice does not
// cache or re-read the audience — issuer.Issue with nil Audience falls back to
// the issuer's configured default (S31 audience deduplication).
func NewService(
	userRepo ports.UserRepository,
	sessionRepo ports.SessionRepository,
	roleRepo ports.RoleRepository,
	issuer *auth.JWTIssuer,
	logger *slog.Logger,
	opts ...Option,
) *Service {
	s := &Service{
		userRepo:    userRepo,
		sessionRepo: sessionRepo,
		roleRepo:    roleRepo,
		txRunner:    persistence.NoopTxRunner{},
		emitter:     outbox.NewNoopEmitter(),
		issuer:      issuer,
		logger:      logger,
	}
	for _, o := range opts {
		o(s)
	}
	return s
}

// LoginInput holds login parameters.
type LoginInput struct {
	Username string
	Password string
}

// Login authenticates a user and returns a JWT token pair.
func (s *Service) Login(ctx context.Context, input LoginInput) (*TokenPair, error) {
	if err := validation.RequireNotBlank(errcode.ErrAuthLoginInvalidInput,
		validation.F("username", input.Username),
		validation.F("password", input.Password),
	); err != nil {
		return nil, err
	}

	user, err := s.userRepo.GetByUsername(ctx, input.Username)
	if err != nil {
		return nil, errcode.New(errcode.ErrAuthLoginFailed, "invalid credentials")
	}

	if user.IsLocked() {
		return nil, errcode.New(errcode.ErrAuthUserLocked, "account is locked")
	}

	if err := bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(input.Password)); err != nil {
		return nil, errcode.New(errcode.ErrAuthLoginFailed, "invalid credentials")
	}

	sessionID := sessionIDPrefix + uuid.NewString()
	minted, err := sessionmint.Mint(ctx, sessionmint.Deps{
		Issuer:   s.issuer,
		RoleRepo: s.roleRepo,
	}, sessionmint.Request{
		UserID:                user.ID,
		SessionID:             sessionID,
		PasswordResetRequired: user.PasswordResetRequired,
	})
	if err != nil {
		s.logger.Error("session-login: token issuance failed",
			slog.Any("error", err), slog.String("user_id", user.ID))
		return nil, err
	}

	session, err := domain.NewSession(user.ID, minted.AccessToken, minted.RefreshToken, minted.ExpiresAt)
	if err != nil {
		return nil, fmt.Errorf("session-login: create session: %w", err)
	}
	session.ID = sessionID

	if err := s.persistSession(ctx, session, user.ID); err != nil {
		return nil, err
	}

	s.logger.Info("user logged in",
		slog.String("user_id", user.ID), slog.String("session_id", session.ID))
	return &TokenPair{
		AccessToken:           minted.AccessToken,
		RefreshToken:          minted.RefreshToken,
		ExpiresAt:             minted.ExpiresAt,
		SessionID:             sessionID,
		PasswordResetRequired: user.PasswordResetRequired,
	}, nil
}

// persistSession writes the session and emits the outbox entry.
func (s *Service) persistSession(ctx context.Context, session *domain.Session, userID string) error {
	do := func(txCtx context.Context) error {
		if err := s.sessionRepo.Create(txCtx, session); err != nil {
			return fmt.Errorf("session-login: persist session: %w", err)
		}
		return outbox.Emit(txCtx, s.emitter, dto.TopicSessionCreated, dto.SessionCreatedEvent{
			SessionID: session.ID,
			UserID:    userID,
		})
	}
	return s.txRunner.RunInTx(ctx, do)
}

// IssueForUser issues a fresh token pair for a user by ID. It re-fetches the
// user and their roles so the returned tokens reflect the current state (e.g.
// after ChangePassword clears PasswordResetRequired). Used by identitymanage
// ChangePassword to issue a replacement token pair without forcing a re-login.
//
// A new Session record is persisted to sessionRepo so that sessionvalidate can
// look up the session by its sid claim and enforce revocation/expiry. Without
// this step, sessionvalidate.enforceSessionState fails with "not found" → 401
// on the very next authenticated request (root cause of PR#183 round-2 CI failure).
//
// Returns dto.TokenPair (internal/dto, value not pointer) so this method
// implements the identitymanage.TokenIssuer interface without a cross-slice
// import (F-ARCH-1). Value type makes (nil, nil) unrepresentable.
func (s *Service) IssueForUser(ctx context.Context, userID string) (dto.TokenPair, error) {
	user, err := s.userRepo.GetByID(ctx, userID)
	if err != nil {
		return dto.TokenPair{}, fmt.Errorf("session-login: IssueForUser get user: %w", err)
	}

	sessionID := sessionIDPrefix + uuid.NewString()
	minted, err := sessionmint.Mint(ctx, sessionmint.Deps{
		Issuer:   s.issuer,
		RoleRepo: s.roleRepo,
	}, sessionmint.Request{
		UserID:                userID,
		SessionID:             sessionID,
		PasswordResetRequired: user.PasswordResetRequired,
	})
	if err != nil {
		s.logger.Error("session-login: IssueForUser token issuance failed",
			slog.Any("error", err), slog.String("user_id", userID))
		return dto.TokenPair{}, err
	}

	// Persist the session so sessionvalidate can look it up by sid claim.
	// Without this, the token carries a sessionID that has no backing row, and
	// every subsequent request fails with 401 (session not found).
	session, err := domain.NewSession(userID, minted.AccessToken, minted.RefreshToken, minted.ExpiresAt)
	if err != nil {
		return dto.TokenPair{}, fmt.Errorf("session-login: IssueForUser create session: %w", err)
	}
	session.ID = sessionID
	if err := s.sessionRepo.Create(ctx, session); err != nil {
		return dto.TokenPair{}, fmt.Errorf("session-login: IssueForUser persist session: %w", err)
	}

	s.logger.Info("session-login: IssueForUser issued new session",
		slog.String("user_id", userID), slog.String("session_id", sessionID))

	return dto.TokenPair{
		AccessToken:           minted.AccessToken,
		RefreshToken:          minted.RefreshToken,
		ExpiresAt:             minted.ExpiresAt,
		SessionID:             sessionID,
		PasswordResetRequired: user.PasswordResetRequired,
	}, nil
}
