// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/accesscore/slices/sessionlogin/slice.yaml

package sessionlogin

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "sessionlogin",
	BelongsToCell:    "accesscore",
	ConsistencyLevel: "L2",
	Lifecycle:        "asset",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "http.auth.login.v1", Role: "serve"},
		{Contract: "event.session.created.v1", Role: "publish"},
		{Contract: "event.user.locked.v1", Role: "publish"},
		{Contract: "event.user.unlocked.v1", Role: "publish"},
		{Contract: "http.config.get.v1", Role: "call"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.sessionlogin.service",
		},
		Contract: []string{
			"contract.http.auth.login.v1.serve",
			"contract.event.session.created.v1.publish",
			"contract.event.user.locked.v1.publish",
			"contract.event.user.unlocked.v1.publish",
		},
		Waivers: []metadata.WaiverMeta{
			{Contract: "http.config.get.v1", Owner: "platform-team", Reason: "只读配置调用，集成测试已覆盖；waiver 由 #1467 续期解阻塞 develop CI，补测试还债见 #1472", ExpiresAt: "2026-09-01"},
		},
	},
	AllowedFiles: []string{
		"cells/accesscore/slices/sessionlogin/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }
