// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/event/deviceidentity/cert-revoked/v1/contract.yaml

/** event.deviceidentity.cert-revoked.v1.payload */
export interface Payload {
  deviceId: string;
  tenantId?: string;
  certRef: PayloadCertRef;
  reason: PayloadReason;
  revokedAt: string;
  actorId: string;
}

/** PayloadReason enumerates the closed value-set for the reason field. */
export type PayloadReason = 'unspecified' | 'keyCompromise' | 'caCompromise' | 'affiliationChanged' | 'superseded' | 'cessationOfOperation' | 'certificateHold' | 'privilegeWithdrawn' | 'aaCompromise';

/** deviceidentity.certificateIdentity */
export interface PayloadCertRef {
  issuer: string;
  serial: string;
}

/** event.deviceidentity.cert-revoked.v1.headers */
export interface Headers {
  eventId: string;
}
