// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/event/deviceidentity/cert-issued/v1/contract.yaml

/** event.deviceidentity.cert-issued.v1.payload */
export interface Payload {
  deviceId: string;
  tenantId?: string;
  certRef: PayloadCertRef;
  epoch: number;
  notBefore: string;
  notAfter: string;
  action: PayloadAction;
  actorId: string;
}

/** PayloadAction enumerates the closed value-set for the action field. */
export type PayloadAction = 'enrolled' | 'renewed';

/** deviceidentity.certificateIdentity */
export interface PayloadCertRef {
  issuer: string;
  serial: string;
}

/** event.deviceidentity.cert-issued.v1.headers */
export interface Headers {
  eventId: string;
}
