// Code generated by gocell generate required-deps. DO NOT EDIT.

package registrywrite

import (
	"github.com/ghbvf/gocell/framework/pkg/errcode"
)

// validateRequired verifies every required dependency on the Service struct
// is present and non-typed-nil. Generated from gocell:"required" struct field
// tags; do not edit by hand.
func (s *Service) validateRequired() error {
	if s.registrar == nil {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"registrywrite.NewService: registrar required")
	}
	return nil
}
