// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/accesscore/slices/sessionvalidate/slice.yaml

package sessionvalidate

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "sessionvalidate",
	BelongsToCell:    "accesscore",
	ConsistencyLevel: "L0",
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.sessionvalidate.service",
		},
	},
	AllowedFiles: []string{
		"cells/accesscore/slices/sessionvalidate/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta }
