// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/auth/user/unlock/v1/contract.yaml

/** http.auth.user.unlock.v1.request */
export interface Request {
  id: string;
}

/** http.auth.user.unlock.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  status: string;
}
