package assembly

import (
	"errors"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/ghbvf/gocell/framework/kernel/metadata"
	"github.com/ghbvf/gocell/framework/kernel/metadata/metadatatest"
	ecErr "github.com/ghbvf/gocell/framework/pkg/errcode"
)

// buildModulesTestProject creates a ProjectMeta with 3 cells that all have
// GoStructName set, suitable for GenerateModulesGen tests.
func buildModulesTestProject() *metadata.ProjectMeta {
	return &metadata.ProjectMeta{
		Cells: map[string]*metadata.CellMeta{
			metadatatest.CellIDAccessCore: {
				ID:           metadatatest.CellIDAccessCore,
				GoStructName: metadata.MustNewGoIdentifier("AccessCore"),
			},
			metadatatest.CellIDAuditCore: {
				ID:           metadatatest.CellIDAuditCore,
				GoStructName: metadata.MustNewGoIdentifier("AuditCore"),
			},
			metadatatest.CellIDConfigCore: {
				ID:           metadatatest.CellIDConfigCore,
				GoStructName: metadata.MustNewGoIdentifier("ConfigCore"),
			},
		},
		Slices:    make(map[string]*metadata.SliceMeta),
		Contracts: make(map[string]*metadata.ContractMeta),
		Journeys:  make(map[string]*metadata.JourneyMeta),
		Assemblies: map[string]*metadata.AssemblyMeta{
			"corebundle": {
				ID: "corebundle",
				Cells: []metadata.AssemblyCellRef{
					{ID: metadatatest.CellIDAccessCore},
					{ID: metadatatest.CellIDAuditCore},
					{ID: metadatatest.CellIDConfigCore},
				},
			},
		},
	}
}

// ---------------------------------------------------------------------------
// GenerateModulesGen tests
// ---------------------------------------------------------------------------

func TestGenerateModulesGen_Corebundle(t *testing.T) {
	project := buildModulesTestProject()
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)

	content := string(out)
	// Generated file marker
	assert.Contains(t, content, "// Code generated by ")
	assert.Contains(t, content, "DO NOT EDIT")
	// Package declaration
	assert.Contains(t, content, "package main")
	// Function signature
	assert.Contains(t, content, "func generatedCellModules() []CellModule")
	// All three module struct literals
	assert.Contains(t, content, "AccessCoreModule{}")
	assert.Contains(t, content, "AuditCoreModule{}")
	assert.Contains(t, content, "ConfigCoreModule{}")
	// Empty union (no cell declares requires) is byte-inert: no capability import,
	// no generatedCapabilities(). The function is emitted iff the union is
	// non-empty — an assembly whose cells require nothing has no provisioner to
	// call it, so emitting a dead generatedCapabilities() (+ unused-looking import)
	// would only pollute non-provisioning assemblies (e.g. examples). #855 F2.
	assert.NotContains(t, content, "runtime/capability")
	assert.NotContains(t, content, "generatedCapabilities")
}

// TestGenerateModulesGen_DerivesCapabilitiesFromCellRequires exercises the
// non-empty branch under Design Y (#855): the assembly capability set is the
// sorted, de-duplicated union of its cells' `requires`. Input order is
// irrelevant (sorted output) and a capability required by multiple cells emits
// exactly one const (dedup).
func TestGenerateModulesGen_DerivesCapabilitiesFromCellRequires(t *testing.T) {
	project := buildModulesTestProject()
	// Unsorted input + cross-cell duplicate of postgres → output must be the
	// sorted union {postgres, redis} with postgres emitted once.
	project.Cells["accesscore"].Requires = []string{"redis", "postgres"}
	project.Cells["auditcore"].Requires = []string{"postgres"}
	project.Cells["configcore"].Requires = []string{"postgres"}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)

	content := string(out)
	assert.Contains(t, content, `import "github.com/ghbvf/gocell/framework/runtime/capability"`)
	assert.Contains(t, content, "func generatedCapabilities() []capability.Kind")
	assert.Contains(t, content, "capability.Postgres")
	assert.Contains(t, content, "capability.Redis")
	// Deterministic alphabetical order regardless of per-cell input order.
	assert.Less(t,
		indexOfStr(content, "capability.Postgres"),
		indexOfStr(content, "capability.Redis"),
		"derived capabilities must be sorted (postgres before redis)")
	// Dedup: postgres required by all three cells must appear exactly once.
	assert.Equal(t, 1, strings.Count(content, "capability.Postgres"),
		"postgres required by multiple cells must emit a single const")
}

// TestCapabilityConstNamesMatchCapabilityEnum locks the capabilityConstNames
// map key set to metadata.CapabilityEnum (single source). Adding a capability to
// the enum without a matching const-name entry (or vice versa) fails here in CI,
// closing the gap between the codegen const-name table and the
// governance/schema enum that TestSchemaConstantsMatchSchemaLiterals already
// pins to cell.schema.json.
func TestCapabilityConstNamesMatchCapabilityEnum(t *testing.T) {
	keys := make([]string, 0, len(capabilityConstNames))
	for k, v := range capabilityConstNames {
		assert.NotEmpty(t, v, "capabilityConstNames[%q] must map to a non-empty const name", k)
		keys = append(keys, k)
	}
	sort.Strings(keys)
	want := append([]string(nil), metadata.CapabilityEnum...)
	sort.Strings(want)
	assert.Equal(t, want, keys,
		"capabilityConstNames key set must equal metadata.CapabilityEnum (single source)")
}

// TestGenerateModulesGen_RabbitMQAndSingle covers the single-capability path
// (sort/dedup with len 1) and the rabbitmq → capability.RabbitMQ const mapping
// — the enum member with no provider yet, whose codegen path is otherwise
// uncovered. The generated const must still emit (provisioning fails later at
// provisionCapabilities' default branch, by design).
func TestGenerateModulesGen_RabbitMQAndSingle(t *testing.T) {
	project := buildModulesTestProject()
	project.Cells["accesscore"].Requires = []string{"rabbitmq"}
	// auditcore / configcore leave Requires nil — union is the single {rabbitmq}.
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)

	content := string(out)
	assert.Contains(t, content, "func generatedCapabilities() []capability.Kind")
	assert.Contains(t, content, "capability.RabbitMQ")
	assert.Equal(t, 1, strings.Count(content, "capability.RabbitMQ"))
	assert.NotContains(t, content, "capability.Postgres")
	assert.NotContains(t, content, "capability.Redis")
}

// TestGenerateModulesGen_UnknownCapability verifies the codegen-time guard:
// a cell `requires` value absent from capabilityConstNames fails with
// ErrMetadataInvalid rather than emitting an undefined capability const. The
// closed enum's validation-time enforcement is FMT-36 (gocell validate); this
// test only locks the generator's own fail-rather-than-emit-garbage behavior.
func TestGenerateModulesGen_UnknownCapability(t *testing.T) {
	project := buildModulesTestProject()
	project.Cells["accesscore"].Requires = []string{"bogus-capability"}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	_, err := gen.GenerateModulesGen("corebundle")
	require.Error(t, err)

	var ec *ecErr.Error
	require.True(t, errors.As(err, &ec), "error must be an errcode.Error, got: %T", err)
	assert.Equal(t, ecErr.ErrMetadataInvalid, ec.Code)
	assert.Contains(t, strings.ToLower(ec.Message), "capability",
		"error message should mention capability, got: %q", ec.Message)
}

func TestGenerateModulesGen_AssemblyNotFound(t *testing.T) {
	project := buildModulesTestProject()
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	_, err := gen.GenerateModulesGen("nonexistent")
	require.Error(t, err)

	var ec *ecErr.Error
	require.True(t, errors.As(err, &ec))
	assert.Equal(t, ecErr.ErrAssemblyNotFound, ec.Code)
}

func TestGenerateModulesGen_CellMissingGoStructName(t *testing.T) {
	project := buildModulesTestProject()
	// Override accesscore to have empty GoStructName
	project.Cells[metadatatest.CellIDAccessCore] = &metadata.CellMeta{
		ID: metadatatest.CellIDAccessCore,
		// GoStructName left at zero value to trigger the missing-name error.
	}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	_, err := gen.GenerateModulesGen("corebundle")
	require.Error(t, err)

	var ec *ecErr.Error
	require.True(t, errors.As(err, &ec))
	assert.Equal(t, ecErr.ErrMetadataInvalid, ec.Code)
	// Message is a const literal; it must mention GoStructName so the error
	// is self-describing without the Internal field.
	assert.Contains(t, ec.Message, "GoStructName")
}

// TestGenerateModulesGen_UnknownCellRef verifies that when an assembly references
// a cell ID that is not registered in project.Cells, GenerateModulesGen returns
// an errcode.Error with code ErrMetadataInvalid and a message containing "unknown"
// or "not found".
func TestGenerateModulesGen_UnknownCellRef(t *testing.T) {
	project := buildModulesTestProject()
	// Add assembly with an unregistered cell ID.
	project.Assemblies["ghostbundle"] = &metadata.AssemblyMeta{
		ID:    "ghostbundle",
		Cells: []metadata.AssemblyCellRef{{ID: metadatatest.CellIDAccessCore}, {ID: metadatatest.NewCellID("ghostcellnotregistered")}},
	}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	_, err := gen.GenerateModulesGen("ghostbundle")
	require.Error(t, err)

	var ec *ecErr.Error
	require.True(t, errors.As(err, &ec), "error must be an errcode.Error, got: %T", err)
	assert.Equal(t, ecErr.ErrMetadataInvalid, ec.Code)
	// Message must contain "unknown" or "not found" so the error is self-describing.
	msgLower := strings.ToLower(ec.Message)
	assert.True(t, strings.Contains(msgLower, "unknown") || strings.Contains(msgLower, "not found"),
		"error message should contain 'unknown' or 'not found', got: %q", ec.Message)
}

func TestGenerateModulesGen_PreservesCellsOrder(t *testing.T) {
	project := buildModulesTestProject()
	// Declare assembly with cells in bb, aa, cc order
	project.Cells[metadatatest.CellIDBB] = &metadata.CellMeta{ID: metadatatest.CellIDBB, GoStructName: metadata.MustNewGoIdentifier("B")}
	project.Cells[metadatatest.CellIDAA] = &metadata.CellMeta{ID: metadatatest.CellIDAA, GoStructName: metadata.MustNewGoIdentifier("A")}
	project.Cells[metadatatest.CellIDCC] = &metadata.CellMeta{ID: metadatatest.CellIDCC, GoStructName: metadata.MustNewGoIdentifier("C")}
	project.Assemblies["ordered"] = &metadata.AssemblyMeta{
		ID:    "ordered",
		Cells: []metadata.AssemblyCellRef{{ID: metadatatest.CellIDBB}, {ID: metadatatest.CellIDAA}, {ID: metadatatest.CellIDCC}},
	}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("ordered")
	require.NoError(t, err)

	content := string(out)
	// B must appear before A, A before C
	posB := indexOfStr(content, "BModule{}")
	posA := indexOfStr(content, "AModule{}")
	posC := indexOfStr(content, "CModule{}")

	assert.Less(t, posB, posA, "BModule must come before AModule")
	assert.Less(t, posA, posC, "AModule must come before CModule")
}

// TestGenerateModulesGen_CompositionForm covers the composition.CellModule
// codegen branch (Build.CompositionAPI = true), which corebundle uses. Unlike
// the legacy form (local *Module struct literals), this branch emits aliased
// imports into cellmodules/<cellID> and Module() call expressions through
// runtime/composition.CellModule. The import alias and path both carry the
// cellmodules/ segment (the composition-root layer), and module calls preserve
// assembly cell order for deterministic output (the order is NOT
// runtime-significant — the former auditcore→accesscore BootstrapLedgerStore
// handoff was removed in #1423; cross-cell wiring is now event-driven).
func TestGenerateModulesGen_CompositionForm(t *testing.T) {
	project := buildModulesTestProject()
	asm := project.Assemblies["corebundle"]
	asm.Build.CompositionAPI = true
	// Order configcore, auditcore, accesscore to assert the call list preserves
	// assembly (not sorted) order.
	asm.Cells = []metadata.AssemblyCellRef{
		{ID: metadatatest.CellIDConfigCore},
		{ID: metadatatest.CellIDAuditCore},
		{ID: metadatatest.CellIDAccessCore},
	}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)

	content := string(out)
	assert.Contains(t, content, "// Code generated by ")
	assert.Contains(t, content, "DO NOT EDIT")
	assert.Contains(t, content, "package main")
	// Composition form: returns []composition.CellModule, not []CellModule.
	assert.Contains(t, content, "func generatedCellModules() []composition.CellModule")
	assert.Contains(t, content, `"github.com/ghbvf/gocell/framework/runtime/composition"`)
	// Aliased imports + Module() calls live under the cellmodules/ layer.
	assert.Contains(t, content, `cellmodulesaccesscore "github.com/ghbvf/gocell/cellmodules/accesscore"`)
	assert.Contains(t, content, `cellmodulesauditcore "github.com/ghbvf/gocell/cellmodules/auditcore"`)
	assert.Contains(t, content, `cellmodulesconfigcore "github.com/ghbvf/gocell/cellmodules/configcore"`)
	assert.Contains(t, content, "cellmodulesaccesscore.Module()")
	assert.Contains(t, content, "cellmodulesauditcore.Module()")
	assert.Contains(t, content, "cellmodulesconfigcore.Module()")
	// No legacy local-struct form.
	assert.NotContains(t, content, "AccessCoreModule{}")
	// Zero-capability composition form: the runtime/capability import and the
	// generatedCapabilities() block must both be omitted. The import is gated on
	// the same {{if .Capabilities}} as the function; emitting it unconditionally
	// (the pre-fix template bug) would produce an unused import that fails to
	// compile for any compositionAPI assembly whose cells require nothing.
	assert.NotContains(t, content, "runtime/capability")
	assert.NotContains(t, content, "generatedCapabilities")
	// Module calls preserve assembly cell order (configcore, auditcore, accesscore).
	posConfig := indexOfStr(content, "cellmodulesconfigcore.Module()")
	posAudit := indexOfStr(content, "cellmodulesauditcore.Module()")
	posAccess := indexOfStr(content, "cellmodulesaccesscore.Module()")
	assert.Less(t, posConfig, posAudit, "configcore.Module() must precede auditcore.Module()")
	assert.Less(t, posAudit, posAccess, "auditcore.Module() must precede accesscore.Module()")
}

// TestGenerateModulesGen_CompositionFormWithCapabilities exercises the
// composition branch together with the non-empty capability union, so the
// generated file carries both the cellmodules/ aliased imports and the
// generatedCapabilities() block (capability import + sorted const list).
func TestGenerateModulesGen_CompositionFormWithCapabilities(t *testing.T) {
	project := buildModulesTestProject()
	asm := project.Assemblies["corebundle"]
	asm.Build.CompositionAPI = true
	project.Cells["accesscore"].Requires = []string{"redis", "postgres"}
	project.Cells["auditcore"].Requires = []string{"postgres"}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)

	content := string(out)
	assert.Contains(t, content, "func generatedCellModules() []composition.CellModule")
	assert.Contains(t, content, "func generatedCapabilities() []capability.Kind")
	assert.Contains(t, content, "capability.Postgres")
	assert.Contains(t, content, "capability.Redis")
	assert.Less(t,
		indexOfStr(content, "capability.Postgres"),
		indexOfStr(content, "capability.Redis"),
		"derived capabilities must be sorted (postgres before redis)")
	assert.Equal(t, 1, strings.Count(content, "capability.Postgres"),
		"postgres required by multiple cells must emit a single const")
}

// TestGenerateModulesGen_CompositionUnknownCellRef verifies the composition
// branch's own unknown-cell guard (distinct call site from the legacy branch).
func TestGenerateModulesGen_CompositionUnknownCellRef(t *testing.T) {
	project := buildModulesTestProject()
	project.Assemblies["ghostcomp"] = &metadata.AssemblyMeta{
		ID:    "ghostcomp",
		Build: metadata.BuildMeta{CompositionAPI: true},
		Cells: []metadata.AssemblyCellRef{{ID: metadatatest.CellIDAccessCore}, {ID: metadatatest.NewCellID("ghostcellnotregistered")}},
	}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	_, err := gen.GenerateModulesGen("ghostcomp")
	require.Error(t, err)

	var ec *ecErr.Error
	require.True(t, errors.As(err, &ec), "error must be an errcode.Error, got: %T", err)
	assert.Equal(t, ecErr.ErrMetadataInvalid, ec.Code)
}

// indexOfStr returns the byte position of substr in s, or -1 if not found.
func indexOfStr(s, substr string) int {
	for i := range len(s) - len(substr) + 1 {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}

// ---------------------------------------------------------------------------
// generatedPostgresCells — codegen function tests (#1964 per-cell PG seam)
// ---------------------------------------------------------------------------

// TestGenerateModulesGen_CompositionForm_PostgresCellsEmitted verifies that the
// composition form emits generatedPostgresCells() listing only the cells that
// declare `requires: [postgres]`, sorted alphabetically, deduplicated.
func TestGenerateModulesGen_CompositionForm_PostgresCellsEmitted(t *testing.T) {
	project := buildModulesTestProject()
	asm := project.Assemblies["corebundle"]
	asm.Build.CompositionAPI = true
	// accesscore requires postgres + redis; auditcore requires postgres only;
	// configcore requires postgres only. Expected sorted output: accesscore, auditcore, configcore.
	project.Cells["accesscore"].Requires = []string{"redis", "postgres"}
	project.Cells["auditcore"].Requires = []string{"postgres"}
	project.Cells["configcore"].Requires = []string{"postgres"}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)
	content := string(out)

	// The function must be emitted.
	assert.Contains(t, content, "func generatedPostgresCells() []string")
	// All three postgres-requiring cells must appear.
	assert.Contains(t, content, `"accesscore"`)
	assert.Contains(t, content, `"auditcore"`)
	assert.Contains(t, content, `"configcore"`)
	// Sorted: accesscore < auditcore < configcore.
	posAccess := indexOfStr(content, `"accesscore"`)
	posAudit := indexOfStr(content, `"auditcore"`)
	posConfig := indexOfStr(content, `"configcore"`)
	assert.Less(t, posAccess, posAudit, "accesscore must precede auditcore (sorted)")
	assert.Less(t, posAudit, posConfig, "auditcore must precede configcore (sorted)")
}

// TestGenerateModulesGen_CompositionForm_NoPostgresCells verifies that when no
// cell in the assembly requires postgres, generatedPostgresCells() is still
// emitted (always, like generatedProjectionSourceTopics) but returns nil.
func TestGenerateModulesGen_CompositionForm_NoPostgresCells(t *testing.T) {
	project := buildModulesTestProject()
	asm := project.Assemblies["corebundle"]
	asm.Build.CompositionAPI = true
	// No cell requires postgres in this fixture.
	// (all cells have empty Requires from buildModulesTestProject)
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)
	content := string(out)

	// Function must always be emitted.
	assert.Contains(t, content, "func generatedPostgresCells() []string")
	// When empty, must return nil.
	assert.Contains(t, content, "return nil")
}

// TestGenerateModulesGen_CompositionForm_PartialPostgresCells verifies that only
// postgres-requiring cells appear (redis-only cells are excluded).
func TestGenerateModulesGen_CompositionForm_PartialPostgresCells(t *testing.T) {
	project := buildModulesTestProject()
	asm := project.Assemblies["corebundle"]
	asm.Build.CompositionAPI = true
	// accesscore requires redis only; auditcore requires postgres.
	project.Cells["accesscore"].Requires = []string{"redis"}
	project.Cells["auditcore"].Requires = []string{"postgres"}
	// configcore: no requires
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "func generatedPostgresCells() []string")
	assert.Contains(t, content, `"auditcore"`)
	// accesscore does NOT require postgres — must not appear in postgres list.
	// (It may appear in module imports, so we check the function body specifically.)
	pgFnIdx := indexOfStr(content, "func generatedPostgresCells()")
	if pgFnIdx < 0 {
		t.Fatal("generatedPostgresCells() not found")
	}
	pgFnBody := content[pgFnIdx:]
	assert.NotContains(t, pgFnBody[:strings.Index(pgFnBody, "}")+1], `"accesscore"`,
		"accesscore does not require postgres and must not appear in generatedPostgresCells()")
}

// ---------------------------------------------------------------------------
// generatedBrokerCells — codegen function tests (#2365 broker-cell derivation)
// ---------------------------------------------------------------------------

// addBrokerTestContract registers a contract with an explicit resolved Transports
// set. The parser guarantees every contract has a non-empty Transports after
// parsing (event/command default to amqp — defaultTransportsForKind); the hand-
// built test project honors that invariant explicitly.
func addBrokerTestContract(p *metadata.ProjectMeta, id, kind, transport string) {
	p.Contracts[id] = &metadata.ContractMeta{ID: id, Kind: kind, Transports: []string{transport}}
}

// addBrokerTestSlice registers a single-usage slice belonging to cellID that uses
// contractID in the given role.
func addBrokerTestSlice(p *metadata.ProjectMeta, sliceID, cellID, contractID, role string) {
	p.Slices[sliceID] = &metadata.SliceMeta{
		ID:             sliceID,
		BelongsToCell:  cellID,
		ContractUsages: []metadata.ContractUsage{{Contract: contractID, Role: role}},
	}
}

// brokerCellsFnBody returns the source span of the generatedBrokerCells() function
// body so assertions can scope to it (cell IDs also appear in module imports).
func brokerCellsFnBody(t *testing.T, content string) string {
	t.Helper()
	idx := indexOfStr(content, "func generatedBrokerCells()")
	if idx < 0 {
		t.Fatal("generatedBrokerCells() not found")
	}
	body := content[idx:]
	end := strings.Index(body, "}")
	if end < 0 {
		t.Fatal("generatedBrokerCells() body not closed")
	}
	return body[:end+1]
}

// TestGenerateModulesGen_CompositionForm_BrokerCellsEmitted verifies the composition
// form emits generatedBrokerCells() listing the cells that produce OR consume an
// amqp-transported (broker) contract, sorted, and excluding http-only cells. A cell
// is a broker cell by its contractUsages' contract transport — NOT by a role subset
// (publish AND subscribe both count) nor by cell.yaml requires.
func TestGenerateModulesGen_CompositionForm_BrokerCellsEmitted(t *testing.T) {
	project := buildModulesTestProject()
	asm := project.Assemblies["corebundle"]
	asm.Build.CompositionAPI = true
	// One amqp-transported event contract + one non-broker http contract.
	addBrokerTestContract(project, "event.session.created.v1", "event", "amqp")
	addBrokerTestContract(project, "http.auth.login.v1", "http", "http")
	// accesscore PUBLISHES the event → broker cell.
	addBrokerTestSlice(project, "sessionlogin", "accesscore", "event.session.created.v1", "publish")
	// auditcore SUBSCRIBES the event → broker cell (proves subscribe counts too).
	addBrokerTestSlice(project, "auditappend", "auditcore", "event.session.created.v1", "subscribe")
	// configcore only SERVES http → NOT a broker cell (soundness / anti-vacuity).
	addBrokerTestSlice(project, "configserve", "configcore", "http.auth.login.v1", "serve")
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "func generatedBrokerCells() []string")
	body := brokerCellsFnBody(t, content)
	assert.Contains(t, body, `"accesscore"`, "publisher of an amqp event is a broker cell")
	assert.Contains(t, body, `"auditcore"`, "subscriber of an amqp event is a broker cell")
	assert.NotContains(t, body, `"configcore"`, "http-only cell is NOT a broker cell")
	assert.Less(t, strings.Index(body, `"accesscore"`), strings.Index(body, `"auditcore"`),
		"broker cells must be sorted (accesscore before auditcore)")
}

// TestGenerateModulesGen_CompositionForm_NoBrokerCells verifies generatedBrokerCells()
// is ALWAYS emitted (like generatedPostgresCells) and returns nil when no cell uses
// an amqp-transported contract.
func TestGenerateModulesGen_CompositionForm_NoBrokerCells(t *testing.T) {
	project := buildModulesTestProject()
	asm := project.Assemblies["corebundle"]
	asm.Build.CompositionAPI = true
	// Only a non-broker http contract; no amqp usage anywhere.
	addBrokerTestContract(project, "http.auth.login.v1", "http", "http")
	addBrokerTestSlice(project, "configserve", "configcore", "http.auth.login.v1", "serve")
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "func generatedBrokerCells() []string")
	assert.Contains(t, brokerCellsFnBody(t, content), "return nil",
		"no amqp-transported usage → broker cells nil")
}

// ---------------------------------------------------------------------------
// generatedFrameworkServedContracts — codegen function tests (#2037)
// ---------------------------------------------------------------------------

// TestGenerateModulesGen_CompositionForm_FrameworkServedContracts_WithContracts verifies
// that when assembly.yaml declares frameworkContracts, the composition form emits
// generatedFrameworkServedContracts() returning them sorted.
func TestGenerateModulesGen_CompositionForm_FrameworkServedContracts_WithContracts(t *testing.T) {
	project := buildModulesTestProject()
	asm := project.Assemblies["corebundle"]
	asm.Build.CompositionAPI = true
	// Intentionally unsorted to verify output is sorted.
	asm.FrameworkContracts = []string{"http.devicestate.v1", "http.deviceidentity.v1"}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)
	content := string(out)

	// Function must be emitted.
	assert.Contains(t, content, "func generatedFrameworkServedContracts() []string")
	// Both contract IDs must appear.
	assert.Contains(t, content, `"http.deviceidentity.v1"`)
	assert.Contains(t, content, `"http.devicestate.v1"`)
	// Sorted: deviceidentity < devicestate alphabetically.
	posIdentity := indexOfStr(content, `"http.deviceidentity.v1"`)
	posState := indexOfStr(content, `"http.devicestate.v1"`)
	assert.Less(t, posIdentity, posState,
		"http.deviceidentity.v1 must precede http.devicestate.v1 (sorted output)")
}

// TestGenerateModulesGen_CompositionForm_FrameworkServedContracts_Empty verifies that
// when assembly.yaml declares no frameworkContracts, generatedFrameworkServedContracts()
// is still ALWAYS emitted (like generatedPostgresCells / generatedProjectionSourceTopics)
// but returns nil.
func TestGenerateModulesGen_CompositionForm_FrameworkServedContracts_Empty(t *testing.T) {
	project := buildModulesTestProject()
	asm := project.Assemblies["corebundle"]
	asm.Build.CompositionAPI = true
	// No FrameworkContracts declared.
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)
	content := string(out)

	// Function must always be emitted.
	assert.Contains(t, content, "func generatedFrameworkServedContracts() []string")
	// When empty, must return nil.
	fnIdx := indexOfStr(content, "func generatedFrameworkServedContracts()")
	require.GreaterOrEqual(t, fnIdx, 0, "generatedFrameworkServedContracts() not found")
	fnBody := content[fnIdx:]
	// Find the closing brace of the function.
	closeBrace := strings.Index(fnBody, "\n}")
	if closeBrace < 0 {
		t.Fatal("could not find closing brace of generatedFrameworkServedContracts()")
	}
	body := fnBody[:closeBrace+2]
	assert.Contains(t, body, "return nil",
		"empty frameworkContracts must emit 'return nil'")
}

// TestGenerateModulesGen_CompositionForm_FrameworkServedContracts_Sorted verifies that
// multiple framework contracts are always emitted sorted regardless of input order,
// mirroring the generatedPostgresCells sorted guarantee.
func TestGenerateModulesGen_CompositionForm_FrameworkServedContracts_Sorted(t *testing.T) {
	project := buildModulesTestProject()
	asm := project.Assemblies["corebundle"]
	asm.Build.CompositionAPI = true
	// Three entries, intentionally reverse-sorted.
	asm.FrameworkContracts = []string{"http.zzz.v1", "http.aaa.v1", "http.mmm.v1"}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "func generatedFrameworkServedContracts() []string")
	// Verify strict sort order: aaa < mmm < zzz.
	posAAA := indexOfStr(content, `"http.aaa.v1"`)
	posMMM := indexOfStr(content, `"http.mmm.v1"`)
	posZZZ := indexOfStr(content, `"http.zzz.v1"`)
	assert.Less(t, posAAA, posMMM, "http.aaa.v1 must precede http.mmm.v1 (sorted)")
	assert.Less(t, posMMM, posZZZ, "http.mmm.v1 must precede http.zzz.v1 (sorted)")
}
