// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/config/flags/evaluate/v1/contract.yaml

/** http.config.flags.evaluate.v1.request */
export interface Request {
  key: string;
  subject: string;
}

/** http.config.flags.evaluate.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  key: string;
  enabled: boolean;
}
