// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/configcore/cell.yaml

package configcore

import (
	"github.com/ghbvf/gocell/kernel/cell"
	"github.com/ghbvf/gocell/kernel/healthz"
)

// ProbeRepoReady is the canonical readiness probe name for the configcore cell's
// primary repository. The "_ready" suffix is required by the READYZ-PROBE-NAMING-01
// convention.
const ProbeRepoReady = "configcore_repo_ready"

// RegisterRepoReady registers a healthz.RepoProber implementation as the
// cell-level repository readiness probe on the given Registry. This is the
// sole sanctioned entry point — handwritten cell code must NOT call
// reg.Healthz() directly (locked by HEALTHZ-TYPED-REGISTER-01).
//
// Emitter health probes are NOT generated per-cell: they go through the shared
// kernel funnel cell.RegisterEmitterHealthProbes(reg, emitter), which handles
// the healthz.ProbeSet assertion and typed-nil guard in one place.
func RegisterRepoReady(reg cell.Registrar, p healthz.RepoProber) error {
	return reg.Healthz().Register(healthz.NewProbe(ProbeRepoReady, p.RepoReady))
}
