// Code generated by gocell generate cell. DO NOT EDIT.

package projection_apply_hook_violate

import (
	"context"

	"github.com/ghbvf/gocell/kernel/contractspec"
	"github.com/ghbvf/gocell/kernel/outbox"
	"github.com/ghbvf/gocell/kernel/projection"
)

// generatedCellSubscribe models the SANCTIONED cellgen projection wiring: a
// Coordinator.Subscribe call inside cell_gen.go bearing the cellgen DO-NOT-EDIT
// banner. PROJECTION-APPLY-HOOK-FUNNEL-01 must ALLOW this (no diagnostic) — it is
// the single legitimate production callsite (PR-04). Paired with healthz_gen.go
// to prove the allowlist distinguishes cell_gen.go from sibling generated files.
func generatedCellSubscribe(coord *projection.Coordinator) {
	var apply projection.Apply = func(_ context.Context, _ outbox.Entry) error { return nil }
	_ = coord.Subscribe(context.Background(), contractspec.ContractSpec{
		ID:        "event.test.v1",
		Kind:      "event",
		Transport: "amqp",
		Topic:     "test.v1",
	}, apply)
}
