// Code generated by gocell generate cell. DO NOT EDIT.

package projection_apply_hook_violate

import (
	"context"

	"github.com/ghbvf/gocell/kernel/contractspec"
	"github.com/ghbvf/gocell/kernel/projection"
)

// generatedCellSubscribe models a VIOLATION under Option A (PR-04a): a
// Coordinator.Subscribe call inside cell_gen.go. Under Option A cellgen emits the
// record-only reg.RegisterProjection (not Coordinator.Subscribe); the only
// sanctioned Subscribe callsite is the bootstrap drain
// (runtime/bootstrap/phases_projection.go). PROJECTION-APPLY-HOOK-FUNNEL-01 must
// therefore FIRE on this call — no generated file is a sanctioned callsite.
func generatedCellSubscribe(coord *projection.Coordinator) {
	var apply projection.Apply = func(_ context.Context, _ projection.ProjectionEvent) error { return nil }
	_ = coord.Subscribe(context.Background(), contractspec.ContractSpec{
		ID:        "event.test.v1",
		Kind:      "event",
		Transport: "amqp",
		Topic:     "test.v1",
	}, apply)
}
