// Code generated by gocell generate cell. DO NOT EDIT.

package projection_apply_hook_violate

import (
	"context"

	"github.com/ghbvf/gocell/kernel/contractspec"
	"github.com/ghbvf/gocell/kernel/outbox"
	"github.com/ghbvf/gocell/kernel/projection"
)

// generatedHealthzSubscribe models the F6 VIOLATION: a sibling generated file
// (healthz_gen.go) carries the IDENTICAL "gocell generate cell" DO-NOT-EDIT
// banner as the sanctioned cell_gen.go, but is NOT a legitimate
// Coordinator.Subscribe callsite. A marker-only allowlist would wrongly permit
// this; PROJECTION-APPLY-HOOK-FUNNEL-01 must FIRE here (basename != cell_gen.go).
func generatedHealthzSubscribe(coord *projection.Coordinator) {
	var apply projection.Apply = func(_ context.Context, _ outbox.Entry) error { return nil }
	// VIOLATION: Coordinator.Subscribe from a non-cell_gen generated file.
	_ = coord.Subscribe(context.Background(), contractspec.ContractSpec{
		ID:        "event.test.v1",
		Kind:      "event",
		Transport: "amqp",
		Topic:     "test.v1",
	}, apply)
}
