// Package generatedcatalog emits the build-time package dependency catalog.
package generatedcatalog

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	kerneldepgraph "github.com/ghbvf/gocell/kernel/depgraph"
)

const (
	// CorebundlePath is the checked-in generated package graph consumed by
	// cmd/corebundle.
	CorebundlePath = "cmd/corebundle/catalog_gen.go"
	// CorebundlePackage is the Go package name for CorebundlePath.
	CorebundlePackage = "main"
)

// EmitFile produces a gofmt'd Go source file containing generatedPackageGraph
// as a typed *kerneldepgraph.Graph literal built via kerneldepgraph.FromNodes.
// The output is deterministic: it contains source provenance, but no wall-clock
// timestamp.
func EmitFile(pkg, modulePath string, g *kerneldepgraph.Graph) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "// Code generated by gocell generate catalog. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// source: %s\n", modulePath)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import kerneldepgraph %q\n\n", modulePath+"/kernel/depgraph")

	pkgs := make([]*kerneldepgraph.Node, len(g.Packages))
	copy(pkgs, g.Packages)
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].ID < pkgs[j].ID })

	fmt.Fprintf(&b, "// generatedPackageGraph is the build-time package dependency graph.\n")
	fmt.Fprintf(&b, "// Rebuild with: go generate ./cmd/corebundle/\n")
	fmt.Fprintf(&b, "var generatedPackageGraph = func() *kerneldepgraph.Graph {\n")
	fmt.Fprintf(&b, "\tnodes := []*kerneldepgraph.Node{\n")

	for _, n := range pkgs {
		fmt.Fprintf(&b, "\t\t{\n")
		fmt.Fprintf(&b, "\t\t\tID:    %s,\n", goString(n.ID))
		fmt.Fprintf(&b, "\t\t\tLayer: %s,\n", goString(n.Layer))
		if n.CellID != "" {
			fmt.Fprintf(&b, "\t\t\tCellID: %s,\n", goString(n.CellID))
		}
		if n.SliceID != "" {
			fmt.Fprintf(&b, "\t\t\tSliceID: %s,\n", goString(n.SliceID))
		}
		if n.TestOnly {
			fmt.Fprintf(&b, "\t\t\tTestOnly: true,\n")
		}
		imports := append([]string(nil), n.Imports...)
		sort.Strings(imports)
		fmt.Fprintf(&b, "\t\t\tImports: %s,\n", goStringSlice(imports))
		fmt.Fprintf(&b, "\t\t},\n")
	}

	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn kerneldepgraph.FromNodes(%s, nodes)\n", goString(g.Module))
	fmt.Fprintf(&b, "}()\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w (source:\n%s)", err, b.String())
	}
	return formatted, nil
}

func goString(s string) string {
	return fmt.Sprintf("%q", s)
}

func goStringSlice(ss []string) string {
	if len(ss) == 0 {
		return "[]string{}"
	}
	var sb strings.Builder
	sb.WriteString("[]string{")
	for i, s := range ss {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%q", s)
	}
	sb.WriteString("}")
	return sb.String()
}
