// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/todoorder/cells/ordercell/slices/orderprojectionrebuild/slice.yaml

package orderprojectionrebuild

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "orderprojectionrebuild",
	BelongsToCell:    "ordercell",
	ConsistencyLevel: "L3",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "http.order.projection-rebuild.v1", Role: "serve"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.orderprojectionrebuild.handler",
		},
		Contract: []string{
			"contract.http.order.projection-rebuild.v1.serve",
		},
	},
	AllowedFiles: []string{
		"examples/todoorder/cells/ordercell/slices/orderprojectionrebuild/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }
