// Code generated by gocell generate required-deps. DO NOT EDIT.

package configreceive

// validateRequired verifies every required dependency on the Service struct
// is present and non-typed-nil. Generated from gocell:"required" struct field
// tags; do not edit by hand.
func (s *Service) validateRequired() error {
	return nil
}
