// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/auth/decide/v1/contract.yaml

/** http.auth.decide.v1.request */
export interface Request {
  action: string;
  resource?: string;
}

/** http.auth.decide.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  allowed: boolean;
}
