// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/webhookdemo/cells/hooks/cell.yaml

package hooks

import (
	"context"
	"fmt"

	"github.com/ghbvf/gocell/kernel/cell"
	"github.com/ghbvf/gocell/kernel/metadata"
	webhook "github.com/ghbvf/gocell/kernel/webhook"
)

var _ cell.Cell = (*HooksCell)(nil)

// cellMeta is the canonical metadata literal projected from cell.yaml.
// loadCellMetadata returns the package-scope pointer; cell.go's constructor
// passes it to cell.MustNewBaseCell which deep-copies the value so callers
// cannot mutate the generated literal.
var cellMeta = &metadata.CellMeta{
	ID:               "hooks",
	Type:             "edge",
	ConsistencyLevel: "L1",
	Lifecycle:        "experimental",
	Owner:            metadata.OwnerMeta{Team: "examples", Role: "webhook-owner"},
	Schema:           metadata.SchemaMeta{Primary: "webhook_deliveries"},
	Verify: metadata.CellVerifyMeta{Smoke: []string{
		"smoke.hooks.startup",
	}},
	GoStructName: metadata.MustNewGoIdentifier("HooksCell"),
}

func loadCellMetadata() *metadata.CellMeta { return cellMeta.Clone() }

//nolint:gocognit // generated code: complexity intrinsic to cell's subscribe count
func (c *HooksCell) Init(ctx context.Context, reg cell.Registrar) error {
	if err := c.BaseCell.Init(ctx, reg); err != nil {
		return err
	}
	// initInternal: hand-written init hook (permanent K#04 convention; implement in cell.go)
	if err := c.initInternal(ctx, reg); err != nil {
		return err
	}

	if err := reg.RegisterWebhookReceiver(webhook.ReceiverSpec{
		ContractID:       "webhook.demo.events.v1",
		SourceID:         "demosource",
		CellID:           "hooks",
		PathPattern:      "/api/webhooks/demo/events",
		DeliveryIDHeader: "Webhook-Delivery-Id",
		TimestampHeader:  "Webhook-Timestamp",
		SignatureHeader:  "Webhook-Signature",
		ToleranceSeconds: 300,
		MaxBodyBytes:     1048576,
	}, c.eventreceiveSvc.HandleEvent); err != nil {
		return fmt.Errorf("hooks: webhook-receive webhook.demo.events.v1: %w", err)
	}

	return nil
}
