// Code generated by gocell generate contract. DO NOT EDIT.
// source: examples/todoorder/contracts/event/order-created/v1/contract.yaml

package v1

import (
	"context"

	"github.com/ghbvf/gocell/kernel/outbox"
)

// Handler is the business interface that subscribers of event.order-created.v1 must implement.
type Handler interface {
	HandleOrderCreated(ctx context.Context, entry outbox.Entry, payload *Payload) outbox.HandleResult
}
