// Code generated by gocell generate contract. DO NOT EDIT.
// source: examples/todoorder/contracts/http/order/list/v1/contract.yaml

package list

import (
	"net/http"
	"strconv"

	"github.com/ghbvf/gocell/kernel/cell"
	"github.com/ghbvf/gocell/kernel/wrapper"
	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/httputil"
	"github.com/ghbvf/gocell/runtime/auth"
)

var contractSpec = wrapper.ContractSpec{
	ID:        "http.order.list.v1",
	Kind:      "http",
	Transport: "http",
	Method:    "GET",
	Path:      "/api/v1/orders/",
}

// HTTPHandler wires HTTP decode/encode + auth.Mount for http.order.list.v1.
type HTTPHandler struct {
	svc    Service
	policy auth.Policy
}

// NewHTTPHandler creates an HTTPHandler for http.order.list.v1.
// policy may be nil — auth.Mount treats nil as "no per-route authorization guard";
// use auth.PublicPolicy for unauthenticated public endpoints or supply a real policy.
func NewHTTPHandler(svc Service, policy auth.Policy) *HTTPHandler {
	return &HTTPHandler{svc: svc, policy: policy}
}

// ServeHTTP implements http.Handler so *HTTPHandler can be used directly in tests
// and as an http.Handler argument without wrapping.
func (h *HTTPHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.handle(w, r)
}

// RegisterRoutes mounts the handler on mux via auth.Mount.
func (h *HTTPHandler) RegisterRoutes(mux cell.RouteHandler) error {
	return auth.Mount(mux, auth.Route{
		Contract: contractSpec,
		Handler:  h,
		Policy:   h.policy,
	})
}

func (h *HTTPHandler) handle(w http.ResponseWriter, r *http.Request) {
	req := &Request{}
	req.Cursor = r.URL.Query().Get("cursor")
	if req.Cursor != "" && len(req.Cursor) > 4096 {
		httputil.WriteDomainError(r.Context(), w, errcode.New(errcode.ErrValidationFailed, "cursor: value too long"))
		return
	}
	if raw := r.URL.Query().Get("limit"); raw != "" {
		v, err := strconv.ParseInt(raw, 10, 64)
		if err != nil {
			httputil.WriteDomainError(r.Context(), w, errcode.New(errcode.ErrValidationFailed, "limit: must be an integer"))
			return
		}
		if v < 1 {
			httputil.WriteDomainError(r.Context(), w, errcode.New(errcode.ErrValidationFailed, "limit: value below minimum"))
			return
		}
		if v > 500 {
			httputil.WriteDomainError(r.Context(), w, errcode.New(errcode.ErrValidationFailed, "limit: value above maximum"))
			return
		}
		req.Limit = v
	}
	resp, err := h.svc.List(r.Context(), req)
	if err != nil {
		httputil.WriteDomainError(r.Context(), w, err)
		return
	}
	httputil.WriteJSON(w, 200, resp)
}
