// Code generated by gocell generate contract. DO NOT EDIT.
// source: examples/todoorder/contracts/http/order/create/v1/contract.yaml

package create

import (
	"net/http"

	"github.com/ghbvf/gocell/kernel/cell"
	"github.com/ghbvf/gocell/kernel/wrapper"
	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/httputil"
	"github.com/ghbvf/gocell/runtime/auth"
)

var contractSpec = wrapper.ContractSpec{
	ID:        "http.order.create.v1",
	Kind:      "http",
	Transport: "http",
	Method:    "POST",
	Path:      "/api/v1/orders/",
}

// Handler wires HTTP decode/encode + auth.Mount for http.order.create.v1.
type Handler struct {
	svc    Service
	policy auth.Policy
}

// NewHandler creates a Handler for http.order.create.v1.
// policy may be nil — auth.Mount treats nil as "no per-route authorization guard";
// use auth.PublicPolicy for unauthenticated public endpoints or supply a real policy.
func NewHandler(svc Service, policy auth.Policy) *Handler {
	return &Handler{svc: svc, policy: policy}
}

// ServeHTTP implements http.Handler so *Handler can be used directly in tests
// and as an http.Handler argument without wrapping.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.handle(w, r)
}

// RegisterRoutes mounts the handler on mux via auth.Mount.
func (h *Handler) RegisterRoutes(mux cell.RouteHandler) error {
	return auth.Mount(mux, auth.Route{
		Contract: contractSpec,
		Handler:  h,
		Policy:   h.policy,
	})
}

func (h *Handler) handle(w http.ResponseWriter, r *http.Request) {
	req := &Request{}
	if err := httputil.DecodeJSONStrict(r, req, httputil.DefaultDecodeJSONLimit); err != nil {
		httputil.WriteError(r.Context(), w, err)
		return
	}
	if len(req.Item) < 1 {
		httputil.WriteError(r.Context(), w, errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed, "item: value too short"))
		return
	}
	if len(req.Item) > 256 {
		httputil.WriteError(r.Context(), w, errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed, "item: value too long"))
		return
	}
	resp, err := h.svc.Create(r.Context(), req)
	if err != nil {
		httputil.WriteError(r.Context(), w, err)
		return
	}
	httputil.WriteJSON(w, 201, resp)
}
