// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/event/policy/updated/v1/contract.yaml

/** event.policy.updated.v1.payload */
export interface Payload {
  policyId: string;
  version: number;
  action: string;
  actorId: string;
}

/** event.policy.updated.v1.headers */
export interface Headers {
  eventId: string;
}
