// Code generated by gocell generate cell. DO NOT EDIT.
// Source: corecells/accesscore/slices/sessionverifyrpc/slice.yaml

package sessionverifyrpc

import (
	"github.com/ghbvf/gocell/framework/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "sessionverifyrpc",
	BelongsToCell:    "accesscore",
	ConsistencyLevel: "L0",
	Lifecycle:        "asset",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "grpc.auth.session.verify.v1", Role: "serve"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.sessionverifyrpc.server",
		},
		Contract: []string{
			"contract.grpc.auth.session.verify.v1.serve",
		},
	},
	AllowedFiles: []string{
		"corecells/accesscore/slices/sessionverifyrpc/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }
