-- Migration 064: add a monotonic global position column `global_seq` to
-- saga_events for the PG-backed GlobalReader + SagaJournalSource replay
-- conformance (EPIC #1630, Batch 1 / PR-PG).
--
-- Why a dedicated IDENTITY column (not derived):
--   journal.GlobalReader requires a stable, monotonic, 1-based global order
--   across ALL saga instances. saga_events has only (instance_id, version)
--   which is per-instance, not global. A GENERATED ALWAYS AS IDENTITY column
--   gives a durable, strictly increasing value assigned at INSERT time and
--   preserved across process restarts. Gaps are allowed (the GlobalReader
--   interface does not mandate contiguity for the PG backend; the conformance
--   suite verifies contiguous serial appends only when using a single
--   connection, which is the PG IDENTITY semantics under txid ordering).
--
-- Writer is unchanged:
--   The existing insertEvent query lists explicit columns and omits global_seq;
--   GENERATED ALWAYS AS IDENTITY means PostgreSQL auto-assigns the value.
--   No writer change is needed.
--
-- Backfill note:
--   ADD COLUMN GENERATED ALWAYS AS IDENTITY backfills existing rows in heap
--   order (not guaranteed = version order). This is moot pre-GA — CI/e2e run
--   on fresh template DBs with no production saga data.
--
--   FUTURE GA DEPLOYMENT WARNING: if this migration runs against a database
--   that already has saga_events rows (e.g. a non-empty staging or production
--   database at GA time), the heap-order backfill means global_seq values will
--   NOT match event order. Any SagaJournalSource that relies on global_seq for
--   causal ordering will observe out-of-order events for pre-migration rows.
--   Such a deployment MUST either:
--     (a) archive / truncate saga_events before running this migration (preferred
--         when a full replay from a clean state is acceptable), OR
--     (b) run a post-migration backfill that reassigns global_seq in correct
--         event order:
--           ALTER TABLE saga_events ALTER COLUMN global_seq SET GENERATED BY DEFAULT;
--           UPDATE saga_events SET global_seq = sub.rn
--             FROM (SELECT instance_id, version,
--                          ROW_NUMBER() OVER (ORDER BY created_at, instance_id, version) AS rn
--                   FROM saga_events) sub
--             WHERE saga_events.instance_id = sub.instance_id
--               AND saga_events.version = sub.version;
--           ALTER TABLE saga_events ALTER COLUMN global_seq SET GENERATED ALWAYS;
--           SELECT setval(pg_get_serial_sequence('saga_events','global_seq'),
--                         (SELECT MAX(global_seq) FROM saga_events));
--   Do NOT add a hard RAISE EXCEPTION guard here — it would break dev/test
--   databases that legitimately have saga rows pre-GA.
--
-- No CONCURRENTLY for the index: this runs as part of the ordered migration
-- set; pre-v1.0 has no live production table to avoid locking. CONCURRENTLY
-- also cannot run inside a transactional DDL block.
--
-- ref: adapters/postgres/migrations/049_outbox_entries_seq.sql
-- ref: adapters/postgres/migrations/040_create_saga_tables.sql

-- +goose Up
ALTER TABLE saga_events
    ADD COLUMN global_seq BIGINT GENERATED ALWAYS AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS idx_saga_events_global_seq ON saga_events (global_seq);

-- +goose Down
-- WARNING: dropping `global_seq` removes the GlobalReader stream position
-- source; every SagaJournalSource (projection replay) loses its monotonic
-- ordering basis and PGJournal no longer satisfies journal.GlobalReader.
-- Destructive-down gate is enforced in Go (Migrator.Down + DestructiveDownPermit); see issue #1248.

DROP INDEX IF EXISTS idx_saga_events_global_seq;

ALTER TABLE saga_events
    DROP COLUMN IF EXISTS global_seq;
