// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/iotdevice/cells/devicecell/slices/devicebootstrap/slice.yaml

package devicebootstrap

import (
	"context"

	"github.com/ghbvf/gocell/framework/kernel/metadata"

	"github.com/ghbvf/gocell/framework/kernel/outbox"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "devicebootstrap",
	BelongsToCell:    "devicecell",
	ConsistencyLevel: "L4",
	Lifecycle:        "experimental",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "event.device-registered.v1", Role: "subscribe", Handler: "HandleDeviceRegistered"},
		{Contract: "command.devicecommand.enqueue.v1", Role: "invoke"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.devicebootstrap.service",
		},
		Contract: []string{
			"contract.event.device-registered.v1.subscribe",
		},
		Waivers: []metadata.WaiverMeta{
			{Contract: "command.devicecommand.enqueue.v1", Owner: "examples", Reason: "invoke is a declaration-only role (no cellgen derivation, no executable broker contract test); the command emit is covered by the slice unit test asserting the emitted entry's routing topic + idempotency metadata.", ExpiresAt: "2026-12-31"},
		},
	},
	AllowedFiles: []string{
		"examples/iotdevice/cells/devicecell/slices/devicebootstrap/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }

// eventHandlerService documents the handler methods devicebootstrap's service
// must provide so that cell_gen.go's reg.Subscribe call is typed. The interface
// is intentionally unexported to avoid colliding with a concrete Service struct.
// Build-time safety comes from the c.<field>.<method>(...) invocations in
// cell_gen.go — Go rejects compilation if the method is missing or renamed.
type eventHandlerService interface {
	// HandleDeviceRegistered handles event.device-registered.v1.
	HandleDeviceRegistered(ctx context.Context, e outbox.Entry) outbox.HandleResult
}
