// Code generated by gocell generate contract. DO NOT EDIT.
// source: examples/iotdevice/contracts/command/devicecommand/enqueue/v1/contract.yaml

/** command.devicecommand.enqueue.v1.request */
export interface Request {
  deviceId: string;
  commandType: string;
  payload: string;
}

/** command.devicecommand.enqueue.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  id: string;
  deviceId: string;
  commandType: string;
  payload: string;
  status: string;
  attempt: number;
  createdAt: string;
  sentAt?: string;
  deliveredAt?: string;
  completedAt?: string;
}
