package codegen_test

import (
	"bytes"
	"testing"

	"github.com/ghbvf/gocell/tools/codegen"
)

// TestFormatGoSource_GroupsByModulePath proves the formatter groups
// module-local imports by the modulePath argument, not a hardcoded framework
// literal (#1083). An external repo's own packages must land in the local
// import block so the consuming repo's golangci-lint gate does not re-shuffle
// the generated bytes.
func TestFormatGoSource_GroupsByModulePath(t *testing.T) {
	t.Parallel()

	// Imports deliberately span stdlib / third-party / two distinct module roots.
	src := []byte(`package demo

import (
	"fmt"
	"github.com/stretchr/testify/assert"
	"github.com/ghbvf/gocell/kernel/clock"
	"github.com/acme/svc/internal/widget"
)

func F(t assert.TestingT) {
	fmt.Println("hi")
	_ = clock.Real()
	_ = widget.New()
	assert.True(t, true)
}
`)

	t.Run("external module groups its own imports last", func(t *testing.T) {
		t.Parallel()
		out, err := codegen.FormatGoSource("github.com/acme/svc", "demo.go", src)
		if err != nil {
			t.Fatalf("FormatGoSource: %v", err)
		}
		// With modulePath = github.com/acme/svc, the acme import is local (last
		// block) and the framework import is third-party — so the third-party
		// block contains BOTH testify and ghbvf, then a blank line, then acme.
		want := `import (
	"fmt"

	"github.com/ghbvf/gocell/kernel/clock"
	"github.com/stretchr/testify/assert"

	"github.com/acme/svc/internal/widget"
)`
		if !bytes.Contains(out, []byte(want)) {
			t.Errorf("acme module imports not grouped as local.\n--- want substring\n%s\n--- got\n%s", want, out)
		}
	})

	t.Run("framework module groups its own imports last", func(t *testing.T) {
		t.Parallel()
		out, err := codegen.FormatGoSource("github.com/ghbvf/gocell", "demo.go", src)
		if err != nil {
			t.Fatalf("FormatGoSource: %v", err)
		}
		want := `import (
	"fmt"

	"github.com/acme/svc/internal/widget"
	"github.com/stretchr/testify/assert"

	"github.com/ghbvf/gocell/kernel/clock"
)`
		if !bytes.Contains(out, []byte(want)) {
			t.Errorf("ghbvf module imports not grouped as local.\n--- want substring\n%s\n--- got\n%s", want, out)
		}
	})

	t.Run("empty modulePath is fail-closed", func(t *testing.T) {
		t.Parallel()
		_, err := codegen.FormatGoSource("", "demo.go", src)
		if err == nil {
			t.Fatal("expected error for empty modulePath, got nil")
		}
	})
}
