package codegen_test

import (
	"bytes"
	"sync"
	"testing"

	"github.com/ghbvf/gocell/tools/codegen"
)

// TestFormatGoSource_GroupsByModulePath proves the formatter groups
// module-local imports by the modulePath argument, not a hardcoded framework
// literal (#1083). An external repo's own packages must land in the local
// import block so the consuming repo's golangci-lint gate does not re-shuffle
// the generated bytes.
func TestFormatGoSource_GroupsByModulePath(t *testing.T) {
	t.Parallel()

	// Imports deliberately span stdlib / third-party / two distinct module roots.
	src := []byte(`package demo

import (
	"fmt"
	"github.com/stretchr/testify/assert"
	"github.com/ghbvf/gocell/kernel/clock"
	"github.com/acme/svc/internal/widget"
)

func F(t assert.TestingT) {
	fmt.Println("hi")
	_ = clock.Real()
	_ = widget.New()
	assert.True(t, true)
}
`)

	t.Run("external module groups its own imports last", func(t *testing.T) {
		t.Parallel()
		out, err := codegen.FormatGoSource("github.com/acme/svc", "demo.go", src)
		if err != nil {
			t.Fatalf("FormatGoSource: %v", err)
		}
		// With modulePath = github.com/acme/svc, the acme import is local (last
		// block) and the framework import is third-party — so the third-party
		// block contains BOTH testify and ghbvf, then a blank line, then acme.
		want := `import (
	"fmt"

	"github.com/ghbvf/gocell/kernel/clock"
	"github.com/stretchr/testify/assert"

	"github.com/acme/svc/internal/widget"
)`
		if !bytes.Contains(out, []byte(want)) {
			t.Errorf("acme module imports not grouped as local.\n--- want substring\n%s\n--- got\n%s", want, out)
		}
	})

	t.Run("framework module groups its own imports last", func(t *testing.T) {
		t.Parallel()
		out, err := codegen.FormatGoSource("github.com/ghbvf/gocell", "demo.go", src)
		if err != nil {
			t.Fatalf("FormatGoSource: %v", err)
		}
		want := `import (
	"fmt"

	"github.com/acme/svc/internal/widget"
	"github.com/stretchr/testify/assert"

	"github.com/ghbvf/gocell/kernel/clock"
)`
		if !bytes.Contains(out, []byte(want)) {
			t.Errorf("ghbvf module imports not grouped as local.\n--- want substring\n%s\n--- got\n%s", want, out)
		}
	})

	t.Run("empty modulePath is fail-closed", func(t *testing.T) {
		t.Parallel()
		_, err := codegen.FormatGoSource("", "demo.go", src)
		if err == nil {
			t.Fatal("expected error for empty modulePath, got nil")
		}
	})
}

// TestFormatGoSource_ConcurrentModulePaths stresses the importsMu mutex: many
// goroutines format concurrently, each with a DIFFERENT module path, and each
// must see ITS OWN module's import grouped locally. Run under -race to catch a
// regression where the imports.LocalPrefix global is read by goroutine A after
// goroutine B overwrote it. (render.go importsMu godoc invariant.)
func TestFormatGoSource_ConcurrentModulePaths(t *testing.T) {
	t.Parallel()
	mods := []string{
		"github.com/acme/alpha",
		"github.com/acme/bravo",
		"github.com/ghbvf/gocell",
		"example.com/charlie",
	}
	const iterations = 30
	var wg sync.WaitGroup
	errCh := make(chan error, len(mods)*iterations)
	for _, mod := range mods {
		for i := 0; i < iterations; i++ {
			wg.Add(1)
			go func(mod string) {
				defer wg.Done()
				// Source imports stdlib + the goroutine's OWN module package.
				src := []byte("package demo\n\nimport (\n\t\"fmt\"\n\t\"" + mod + "/widget\"\n)\n\nfunc F() { fmt.Println(widget.Name) }\n")
				out, err := codegen.FormatGoSource(mod, "demo.go", src)
				if err != nil {
					errCh <- err
					return
				}
				// The module's own import must be grouped in the local block:
				// preceded by a blank line separating it from the stdlib block.
				if !bytes.Contains(out, []byte("\n\n\t\""+mod+"/widget\"")) {
					errCh <- &groupingError{mod: mod, out: string(out)}
				}
			}(mod)
		}
	}
	wg.Wait()
	close(errCh)
	for err := range errCh {
		t.Error(err)
	}
}

type groupingError struct {
	mod string
	out string
}

func (e *groupingError) Error() string {
	return "module " + e.mod + " import not grouped locally under concurrent formatting:\n" + e.out
}
