package codegen_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/ghbvf/gocell/tools/codegen"
)

const generatedHeader = "// Code generated by gocell generate test. DO NOT EDIT.\n\npackage demo\n"

func TestWrite_NewFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "out.go")

	res, err := codegen.Write(codegen.WriteOptions{
		Path:     path,
		Content:  []byte(generatedHeader),
		RepoRoot: dir,
	})
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	if res.Action != codegen.ActionWritten {
		t.Errorf("Action = %q, want %q", res.Action, codegen.ActionWritten)
	}
	got, _ := os.ReadFile(path)
	if string(got) != generatedHeader {
		t.Errorf("file contents mismatch")
	}
}

func TestWrite_UnchangedExistingFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "out.go")
	if err := os.WriteFile(path, []byte(generatedHeader), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := codegen.Write(codegen.WriteOptions{
		Path:     path,
		Content:  []byte(generatedHeader),
		RepoRoot: dir,
	})
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	if res.Action != codegen.ActionUnchanged {
		t.Errorf("Action = %q, want %q", res.Action, codegen.ActionUnchanged)
	}
}

func TestWrite_DryRunNewFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "out.go")

	res, err := codegen.Write(codegen.WriteOptions{
		Path:     path,
		Content:  []byte(generatedHeader),
		RepoRoot: dir,
		DryRun:   true,
	})
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	if res.Action != codegen.ActionWouldWrite {
		t.Errorf("Action = %q, want %q", res.Action, codegen.ActionWouldWrite)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Errorf("DryRun should not create file; stat err = %v", err)
	}
}

func TestWrite_VerifyDriftMissingFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "missing.go")

	res, err := codegen.Write(codegen.WriteOptions{
		Path:     path,
		Content:  []byte(generatedHeader),
		RepoRoot: dir,
		Verify:   true,
	})
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	if res.Action != codegen.ActionDrifted {
		t.Errorf("Action = %q, want %q", res.Action, codegen.ActionDrifted)
	}
}

func TestWrite_VerifyDriftMismatch(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "out.go")
	old := generatedHeader + "// old line\n"
	if err := os.WriteFile(path, []byte(old), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := codegen.Write(codegen.WriteOptions{
		Path:     path,
		Content:  []byte(generatedHeader + "// new line\n"),
		RepoRoot: dir,
		Verify:   true,
	})
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	if res.Action != codegen.ActionDrifted {
		t.Errorf("Action = %q, want %q", res.Action, codegen.ActionDrifted)
	}
}

func TestWrite_VerifyMatchReturnsUnchanged(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "out.go")
	if err := os.WriteFile(path, []byte(generatedHeader), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := codegen.Write(codegen.WriteOptions{
		Path:     path,
		Content:  []byte(generatedHeader),
		RepoRoot: dir,
		Verify:   true,
	})
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	if res.Action != codegen.ActionUnchanged {
		t.Errorf("Action = %q, want %q", res.Action, codegen.ActionUnchanged)
	}
}

func TestWrite_RefuseOverwriteUserFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "user.go")
	if err := os.WriteFile(path, []byte("// hand-written user file\npackage demo\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	_, err := codegen.Write(codegen.WriteOptions{
		Path:     path,
		Content:  []byte(generatedHeader),
		RepoRoot: dir,
	})
	if err == nil {
		t.Fatal("expected refusal to overwrite non-generated file")
	}
}

func TestWrite_PathOutsideRepoRoot(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	outside := filepath.Join(dir, "..", "escape.go")

	_, err := codegen.Write(codegen.WriteOptions{
		Path:     outside,
		Content:  []byte(generatedHeader),
		RepoRoot: dir,
	})
	if err == nil {
		t.Fatal("expected path-traversal refusal")
	}
}

func TestWrite_EmptyPathError(t *testing.T) {
	t.Parallel()
	_, err := codegen.Write(codegen.WriteOptions{Content: []byte(generatedHeader)})
	if err == nil {
		t.Fatal("expected error for empty Path")
	}
}

func TestWrite_CreatesParentDirs(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "nested", "deep", "out.go")

	res, err := codegen.Write(codegen.WriteOptions{
		Path:     path,
		Content:  []byte(generatedHeader),
		RepoRoot: dir,
	})
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	if res.Action != codegen.ActionWritten {
		t.Errorf("Action = %q, want %q", res.Action, codegen.ActionWritten)
	}
	got, _ := os.ReadFile(path)
	if string(got) != generatedHeader {
		t.Errorf("file contents mismatch after parent-dir creation")
	}
}
