// Code generated by gocell generate required-deps. DO NOT EDIT.

package featureflag

import (
	"github.com/ghbvf/gocell/pkg/errcode"
)

// validateRequired verifies every required dependency on the Service struct
// is present and non-typed-nil. Generated from gocell:"required" struct field
// tags; do not edit by hand.
func (s *Service) validateRequired() error {
	if s.codec == nil {
		return errcode.New(errcode.KindInternal, errcode.ErrCellMissingCodec,
			"featureflag: cursor codec is required")
	}
	return nil
}
