// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/configcore/slices/featureflag/slice.yaml

package featureflag

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "featureflag",
	BelongsToCell:    "configcore",
	ConsistencyLevel: "L0",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "http.config.flags.list.v1", Role: "serve"},
		{Contract: "http.config.flags.get.v1", Role: "serve"},
		{Contract: "http.config.flags.evaluate.v1", Role: "serve"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.featureflag.service",
		},
		Contract: []string{
			"contract.http.config.flags.list.v1.serve",
			"contract.http.config.flags.get.v1.serve",
			"contract.http.config.flags.evaluate.v1.serve",
		},
	},
	AllowedFiles: []string{
		"cells/configcore/slices/featureflag/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }
