// Code generated by gocell generate contract. DO NOT EDIT.
// source: examples/iotdevice/contracts/http/device/register/v1/contract.yaml

/** http.device.register.v1.request */
export interface Request {
  name: string;
}

/** http.device.register.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  id: string;
  name: string;
  status: string;
}
