// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/admin/health/cells/v1/contract.yaml

/** http.admin.health.cells.v1.request */
export interface Request {
}

/** http.admin.health.cells.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  overall: string;
  cells: ResponseDataCellsItem[];
  adapters: ResponseDataAdaptersItem[];
}

export interface ResponseDataCellsItem {
  id: string;
  live: boolean;
  ready: boolean;
  status: string;
  deps: ResponseDataCellsItemDepsItem[];
}

export interface ResponseDataCellsItemDepsItem {
  name: string;
  status: string;
  durationMs: number;
}

export interface ResponseDataAdaptersItem {
  name: string;
  status: string;
  durationMs: number;
}
