// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/orderfulfillment/cells/orderfulfillmentcell/cell.yaml

package orderfulfillmentcell

import (
	"github.com/ghbvf/gocell/framework/kernel/cell"
	"github.com/ghbvf/gocell/framework/kernel/healthz"
)

// ProbeRepoReady is the canonical readiness probe name for the orderfulfillmentcell cell's
// primary repository. The "_ready" suffix is required by the PROBENAME-SEALED-FUNNEL-01
// convention.
const ProbeRepoReady healthz.ProbeName = "orderfulfillmentcell_repo_ready"

// RegisterReadiness registers a healthz.RepoProber implementation as the
// cell-level repository readiness probe on the given Registrar. This is the
// sole sanctioned entry point — handwritten cell code must NOT call
// reg.RegisterReadiness directly with a bare string (locked by
// PROBENAME-SEALED-FUNNEL-01).
//
// Emitter health probes are NOT generated per-cell: they go through the shared
// kernel funnel cell.RegisterEmitterHealthProbes(reg, emitter), which handles
// the healthz.ProbeSet assertion and typed-nil guard in one place.
func RegisterReadiness(reg cell.Registrar, p healthz.RepoProber) error {
	return reg.RegisterReadiness(ProbeRepoReady, healthz.ProberFunc(p.RepoReady))
}
