// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/iotdevice/cells/devicecell/slices/devicecertrenewal/slice.yaml

package devicecertrenewal

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "devicecertrenewal",
	BelongsToCell:    "devicecell",
	ConsistencyLevel: "L4",
	Lifecycle:        "experimental",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "command.devicecommand.enqueue.v1", Role: "invoke"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.devicecertrenewal.reconciler",
		},
		Waivers: []metadata.WaiverMeta{
			{Contract: "command.devicecommand.enqueue.v1", Owner: "examples", Reason: "invoke is a declaration-only role (no cellgen derivation, no executable broker contract test); the reconciler emit is covered by the slice unit test asserting the emitted entry's routing topic + idempotency metadata.", ExpiresAt: "2026-12-31"},
		},
	},
	AllowedFiles: []string{
		"examples/iotdevice/cells/devicecell/slices/devicecertrenewal/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }
