// Code generated by gocell generate contract. DO NOT EDIT.
// source: examples/iotdevice/contracts/http/device/command/dequeue/v1/contract.yaml

/** http.device.command.dequeue.v1.request */
export interface Request {
  id: string;
  cursor?: string;
  limit?: number;
}

/** http.device.command.dequeue.v1.response */
export interface Response {
  data: ResponseDataItem[];
  nextCursor: string;
  hasMore: boolean;
}

export interface ResponseDataItem {
  id: string;
  deviceId: string;
  commandType: string;
  payload: string;
  status: string;
  attempt: number;
  createdAt: string;
  sentAt?: string;
  deliveredAt?: string;
  completedAt?: string;
}
