// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/registry/contract/retire/v1/contract.yaml

/** http.registry.contract.retire.v1.request */
export interface Request {
  id: string;
  reason?: string;
}

/** http.registry.contract.retire.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  id: string;
  kind: string;
  state: string;
  submitter: string;
  approver?: string;
  createdAt: string;
  updatedAt: string;
}
