// Code generated by gocell generate cell. DO NOT EDIT.
// Source: corecells/accesscore/slices/sessionprojection/slice.yaml

package sessionprojection

import (
	"github.com/ghbvf/gocell/framework/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "sessionprojection",
	BelongsToCell:    "accesscore",
	ConsistencyLevel: "L3",
	Lifecycle:        "experimental",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "event.session.created.v1", Role: "subscribe", Handler: "HandleSessionCreated", Projection: "session_registry", OnReset: "ResetSessionRegistry", ProjectionSource: "outbox"},
		{Contract: "projection.session.registry-summary.v1", Role: "provide"},
		{Contract: "http.session.registry-summary.v1", Role: "serve"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.sessionprojection.service",
		},
		Contract: []string{
			"contract.event.session.created.v1.subscribe",
			"contract.projection.session.registry-summary.v1.provide",
			"contract.http.session.registry-summary.v1.serve",
		},
	},
	AllowedFiles: []string{
		"corecells/accesscore/slices/sessionprojection/**",
		"corecells/accesscore/internal/sessionprojection/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }
