package appender_test

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/ghbvf/gocell/cells/auditcore/internal/appender"
	"github.com/ghbvf/gocell/kernel/clock"
	"github.com/ghbvf/gocell/kernel/clock/clockmock"
	"github.com/ghbvf/gocell/kernel/outbox"
	"github.com/ghbvf/gocell/kernel/persistence"
	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/idutil"
	"github.com/ghbvf/gocell/pkg/tenant"
	"github.com/ghbvf/gocell/pkg/testutil/testtime"
	"github.com/ghbvf/gocell/runtime/audit/ledger"
)

// mustScan reconstructs a sealed outbox.Entry from an EntryScan, defaulting the
// timestamps so plain {ID,EventType,Payload} scans validate. Tests that assert
// on specific timestamps (CreatedAt fallback, OccurredAt mapping) build the
// EntryScan with explicit times and must NOT route through this defaulting path.
func mustScan(t *testing.T, s outbox.EntryScan) outbox.Entry {
	t.Helper()
	if s.OccurredAt.IsZero() {
		s.OccurredAt = time.Now().UTC()
	}
	if s.CreatedAt.IsZero() {
		s.CreatedAt = s.OccurredAt
	}
	e, err := s.ToEntry()
	require.NoError(t, err)
	return e
}

type failingStore struct {
	ledger.Store
	err error
}

func (f *failingStore) Append(_ context.Context, _ *ledger.Entry) error { return f.err }

type directRunner struct{}

var _ persistence.TxRunner = directRunner{}

func (directRunner) RunInTx(ctx context.Context, fn func(context.Context) error) error {
	return fn(ctx)
}

func newTestProtocol(t testing.TB) *ledger.Protocol {
	t.Helper()
	ns, err := ledger.ParseNamespaceID("auditcore")
	require.NoError(t, err)
	p, err := ledger.NewProtocol(
		ns,
		[]byte("test-hmac-key-32bytes-long!!!!!!!"),
		ledger.WithRestartRecovery(ledger.RestartRecoveryStrictTailVerify{}),
		ledger.WithIdempotency(ledger.IdempotencyContentFingerprint{}),
	)
	require.NoError(t, err)
	return p
}

func mustJSON(t testing.TB, v any) []byte {
	t.Helper()
	b, err := json.Marshal(v)
	require.NoError(t, err)
	return b
}

func newSpec(t *testing.T, name string, mode appender.ActorMode) appender.Spec {
	t.Helper()
	return appender.MustNewSpec(name, mode)
}

func newService(t *testing.T, spec appender.Spec, store ledger.Store, p *ledger.Protocol, opts ...appender.Option) *appender.Service {
	t.Helper()
	defaultOpts := []appender.Option{appender.WithTxManager(persistence.WrapForCell(directRunner{}))}
	svc, err := appender.NewService(spec, store, p, slog.Default(), clock.Real(), append(defaultOpts, opts...)...)
	require.NoError(t, err)
	return svc
}

// TestNewService_TxRunnerRequired covers the OUTBOX-SERVICE-01 fail-fast on
// nil TxRunner contract.
func TestNewService_TxRunnerRequired(t *testing.T) {
	p := newTestProtocol(t)
	store, err := ledger.NewMemStore(p, clock.Real())
	require.NoError(t, err)
	spec := newSpec(t, "auditappenduser", appender.ActorAcceptUserFallback)

	_, err = appender.NewService(spec, store, p, slog.Default(), clock.Real())
	require.Error(t, err)
	var ec *errcode.Error
	require.ErrorAs(t, err, &ec)
	assert.Equal(t, errcode.ErrCellInvalidConfig, ec.Code)
	// Const-literal message (MESSAGE-CONST-LITERAL-01); generated by
	// validateRequired() from gocell:"required" struct tag — no WithDetails.
	assert.Equal(t, "auditappender: TxRunner required; use WithTxManager", ec.Message)
}

// TestActorExtraction is the strategy decision table for the two ActorMode
// branches. ActorAcceptUserFallback (user/config/session): actorId > userId.
// ActorRequireExplicit (role): actorId only.
func TestActorExtraction(t *testing.T) {
	cases := []struct {
		name        string
		spec        appender.Spec
		payload     map[string]any
		wantAck     bool
		wantActorID string
	}{
		{
			name:        "fallback_actorId_only",
			spec:        appender.MustNewSpec("auditappenduser", appender.ActorAcceptUserFallback),
			payload:     map[string]any{"actorId": "admin-1"},
			wantAck:     true,
			wantActorID: "admin-1",
		},
		{
			name:        "fallback_userId_only",
			spec:        appender.MustNewSpec("auditappenduser", appender.ActorAcceptUserFallback),
			payload:     map[string]any{"userId": "usr-1"},
			wantAck:     true,
			wantActorID: "usr-1",
		},
		{
			name:        "fallback_both_prefers_actorId",
			spec:        appender.MustNewSpec("auditappenduser", appender.ActorAcceptUserFallback),
			payload:     map[string]any{"actorId": "admin-1", "userId": "usr-1"},
			wantAck:     true,
			wantActorID: "admin-1",
		},
		{
			name:    "fallback_neither_rejects",
			spec:    appender.MustNewSpec("auditappenduser", appender.ActorAcceptUserFallback),
			payload: map[string]any{"username": "alice"},
			wantAck: false,
		},
		{
			name:        "explicit_actorId_only_accepts",
			spec:        appender.MustNewSpec("auditappendrole", appender.ActorRequireExplicit),
			payload:     map[string]any{"actorId": "admin-1", "userId": "usr-1"},
			wantAck:     true,
			wantActorID: "admin-1",
		},
		{
			name:    "explicit_userId_only_rejects",
			spec:    appender.MustNewSpec("auditappendrole", appender.ActorRequireExplicit),
			payload: map[string]any{"userId": "usr-1"},
			wantAck: false,
		},
		{
			name:    "explicit_neither_rejects",
			spec:    appender.MustNewSpec("auditappendrole", appender.ActorRequireExplicit),
			payload: map[string]any{"foo": "bar"},
			wantAck: false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			p := newTestProtocol(t)
			store, err := ledger.NewMemStore(p, clock.Real())
			require.NoError(t, err)
			svc := newService(t, tc.spec, store, p)

			entry := mustScan(t, outbox.EntryScan{
				ID:        "evt-" + tc.name,
				EventType: "event.test.v1",
				Payload:   mustJSON(t, tc.payload),
			})
			result := svc.HandleEvent(context.Background(), entry)
			if tc.wantAck {
				assert.Equal(t, outbox.DispositionAck, result.Disposition)
				tail, err := store.Tail(context.Background())
				require.NoError(t, err)
				assert.EqualValues(t, 1, tail.EntryCount)
				return
			}
			assert.Equal(t, outbox.DispositionReject, result.Disposition)
			var permErr *outbox.PermanentError
			require.ErrorAs(t, result.Err, &permErr)
		})
	}
}

func TestService_HandleEvent_InvalidJSON_Reject(t *testing.T) {
	p := newTestProtocol(t)
	store, err := ledger.NewMemStore(p, clock.Real())
	require.NoError(t, err)
	spec := newSpec(t, "auditappenduser", appender.ActorAcceptUserFallback)
	svc := newService(t, spec, store, p)

	entry := mustScan(t, outbox.EntryScan{
		ID:        "evt-bad-json",
		EventType: "event.user.created.v1",
		Payload:   []byte("{invalid json}"),
	})
	result := svc.HandleEvent(context.Background(), entry)
	assert.Equal(t, outbox.DispositionReject, result.Disposition)
	var permErr *outbox.PermanentError
	require.ErrorAs(t, result.Err, &permErr)
}

func TestService_HandleEvent_AppendFails_Requeue(t *testing.T) {
	sentinel := fmt.Errorf("db unavailable")
	p := newTestProtocol(t)
	realStore, err := ledger.NewMemStore(p, clock.Real())
	require.NoError(t, err)
	spec := newSpec(t, "auditappenduser", appender.ActorAcceptUserFallback)
	svc := newService(t, spec, &failingStore{Store: realStore, err: sentinel}, p)

	entry := mustScan(t, outbox.EntryScan{
		ID:        "evt-fail",
		EventType: "event.user.created.v1",
		Payload:   mustJSON(t, map[string]any{"userId": "usr-1", "actorId": "admin-1"}),
	})
	result := svc.HandleEvent(context.Background(), entry)
	assert.Equal(t, outbox.DispositionRequeue, result.Disposition)
	assert.ErrorIs(t, result.Err, sentinel)

	var permErr *outbox.PermanentError
	assert.False(t, errors.As(result.Err, &permErr), "transient persist error must NOT be PermanentError")
}

// TestService_HandleEvent_AppendFails_Classified verifies the disposition
// 收口: a positively-classified transient store error is Requeued (retry),
// while a positively-permanent error short-circuits to Reject → DLX instead
// of blind-Requeuing and burning the whole retry budget.
func TestService_HandleEvent_AppendFails_Classified(t *testing.T) {
	cases := []struct {
		name        string
		storeErr    error
		wantDisp    outbox.Disposition
		wantPermErr bool
	}{
		{
			name: "transient WrapInfra (PG serialization) → Requeue",
			storeErr: errcode.WrapInfra(errcode.Code("ERR_ADAPTER_PG_QUERY"),
				"serialization failure", errors.New("40001")),
			wantDisp: outbox.DispositionRequeue,
		},
		{
			name: "positively-permanent validation error → Reject → DLX",
			storeErr: errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
				"audit schema drift", errcode.WithCategory(errcode.CategoryValidation)),
			wantDisp:    outbox.DispositionReject,
			wantPermErr: true,
		},
		{
			// context.Canceled is infra (IsInfraError true) and NOT transient
			// → predicate !IsTransient && !IsInfraError == false → Requeue.
			// Locks the fail-closed direction: a future change to the
			// predicate that drops the IsInfraError clause would wrongly
			// Reject canceled-context store failures.
			name:     "context.Canceled (infra, not transient) → Requeue",
			storeErr: context.Canceled,
			wantDisp: outbox.DispositionRequeue,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			p := newTestProtocol(t)
			realStore, err := ledger.NewMemStore(p, clock.Real())
			require.NoError(t, err)
			spec := newSpec(t, "auditappenduser", appender.ActorAcceptUserFallback)
			svc := newService(t, spec, &failingStore{Store: realStore, err: tc.storeErr}, p)

			entry := mustScan(t, outbox.EntryScan{
				ID:        "evt-cls",
				EventType: "event.user.created.v1",
				Payload:   mustJSON(t, map[string]any{"userId": "usr-1", "actorId": "admin-1"}),
			})
			result := svc.HandleEvent(context.Background(), entry)
			assert.Equal(t, tc.wantDisp, result.Disposition)

			var permErr *outbox.PermanentError
			assert.Equal(t, tc.wantPermErr, errors.As(result.Err, &permErr))
		})
	}
}

// TestService_HandleEvent_DuplicateReplay_Ack verifies the idempotent-replay
// contract: redelivering the same entry (same content/EventID fingerprint)
// makes ledger.Append return errcode.ErrAuditLedgerAlreadyExists, which the
// handler must treat as an idempotent SUCCESS → Ack (not Requeue, not DLX).
func TestService_HandleEvent_DuplicateReplay_Ack(t *testing.T) {
	p := newTestProtocol(t)
	realStore, err := ledger.NewMemStore(p, clock.Real())
	require.NoError(t, err)
	spec := newSpec(t, "auditappenduser", appender.ActorAcceptUserFallback)
	svc := newService(t, spec, realStore, p)

	entry := mustScan(t, outbox.EntryScan{
		ID:        "evt-dup",
		EventType: "event.user.created.v1",
		Payload:   mustJSON(t, map[string]any{"userId": "usr-1", "actorId": "admin-1"}),
	})

	first := svc.HandleEvent(context.Background(), entry)
	require.Equal(t, outbox.DispositionAck, first.Disposition, "first append must succeed")

	// Redelivery of the identical entry → ErrAuditLedgerAlreadyExists → Ack.
	second := svc.HandleEvent(context.Background(), entry)
	assert.Equal(t, outbox.DispositionAck, second.Disposition,
		"idempotent replay must Ack, not Requeue/Reject")
	var permErr *outbox.PermanentError
	assert.False(t, errors.As(second.Err, &permErr),
		"idempotent replay must not be a PermanentError")
}

// TestService_HandleEvent_Happy verifies the full happy path: ledger.Append +
// outbox.Emit run inside the same RunInTx block (L2 OutboxFact pattern). We
// observe the emit by injecting a recording emitter.
func TestService_HandleEvent_Happy(t *testing.T) {
	p := newTestProtocol(t)
	store, err := ledger.NewMemStore(p, clock.Real())
	require.NoError(t, err)
	rec := &recordingEmitter{}
	spec := newSpec(t, "auditappendsession", appender.ActorAcceptUserFallback)
	svc := newService(t, spec, store, p, appender.WithEmitter(outbox.WrapEmitterForCell(rec)))

	entry := mustScan(t, outbox.EntryScan{
		ID:        "evt-happy",
		EventType: "event.session.created.v1",
		Payload:   mustJSON(t, map[string]any{"actorId": "user-1", "userId": "user-1"}),
	})
	result := svc.HandleEvent(context.Background(), entry)
	require.Equal(t, outbox.DispositionAck, result.Disposition)

	tail, err := store.Tail(context.Background())
	require.NoError(t, err)
	assert.EqualValues(t, 1, tail.EntryCount)
	require.Len(t, rec.emitted, 1, "L2 OutboxFact: one outbox.Emit per Append")
	assert.Equal(t, "event.audit.appended.v1", rec.emitted[0].topic)
}

// TestHandleEvent_PrincipalFieldMapping verifies the #1229 B8 invariant: the
// Principal family (subject/tenant/session) and Observability.CorrelationID
// carried on the outbox envelope map onto the orthogonal ledger.Entry columns,
// OccurredAt is propagated, and ActorID is still sourced from the DOMAIN payload
// (actorId), NOT from the request-context principal. Distinct columns, distinct
// authoritative sources.
func TestHandleEvent_PrincipalFieldMapping(t *testing.T) {
	p := newTestProtocol(t)
	inner, err := ledger.NewMemStore(p, clock.Real())
	require.NoError(t, err)
	cap := &captureStore{Store: inner}
	spec := newSpec(t, "auditappenduser", appender.ActorAcceptUserFallback)
	svc := newService(t, spec, cap, p)

	occ := time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	e, err := outbox.EntryScan{
		ID:         "evt-princ",
		EventType:  "event.user.created.v1",
		Payload:    mustJSON(t, map[string]any{"actorId": "actor-1", "userId": "usr-1"}),
		OccurredAt: occ,
		CreatedAt:  occ,
		Principal: outbox.PrincipalMetadata{
			SubjectID: idutil.SafeID("subj-1"),
			TenantID:  idutil.SafeID("tenant-1"),
			SessionID: idutil.SafeID("sess-1"),
		},
		Observability: outbox.ObservabilityMetadata{CorrelationID: idutil.SafeID("corr-1")},
	}.ToEntry()
	require.NoError(t, err)

	result := svc.HandleEvent(context.Background(), e)
	require.Equal(t, outbox.DispositionAck, result.Disposition,
		"HandleEvent must Ack a valid entry; err=%v", result.Err)
	require.Len(t, cap.appended, 1, "must have appended exactly one ledger entry")

	got := cap.appended[0]
	assert.Equal(t, "subj-1", got.SubjectID, "SubjectID must map from Principal.SubjectID")
	assert.Equal(t, "tenant-1", got.TenantID, "TenantID must map from Principal.TenantID")
	assert.Equal(t, "sess-1", got.SessionID, "SessionID must map from Principal.SessionID")
	assert.Equal(t, "corr-1", got.CorrelationID,
		"CorrelationID must map from Observability.CorrelationID via sealed read-model")
	assert.True(t, got.OccurredAt.Equal(occ), "OccurredAt must propagate from entry.OccurredAt()")
	// B8: actor stays the domain payload actor, NOT the request-context subject.
	assert.Equal(t, "actor-1", got.ActorID,
		"ActorID must be sourced from the payload actor, not the principal subject")
}

// TestHandleEvent_TraceIDFromEnvelope verifies that when an outbox entry carries
// an observability envelope with a TraceID (and CorrelationID), the appended
// ledger.Entry has TraceID and CorrelationID equal to those envelope values.
//
// Both fields are derived via correlation.New (the sealed read-model constructor)
// so neither can be fabricated from caller input — this is the SOLE sanctioned
// injection site locked by AUDIT-TRACE-ID-WRITE-CALLER-01 (later batch).
func TestHandleEvent_TraceIDFromEnvelope(t *testing.T) {
	p := newTestProtocol(t)
	inner, err := ledger.NewMemStore(p, clock.Real())
	require.NoError(t, err)
	cap := &captureStore{Store: inner}
	spec := newSpec(t, "auditappenduser", appender.ActorAcceptUserFallback)
	svc := newService(t, spec, cap, p)

	occ := time.Date(2026, 3, 15, 10, 0, 0, 0, time.UTC)
	const wantTraceID = "4bf92f3577b34da6a3ce929d0e0e4736"
	const wantCorrID = "01bf32e31d93d713"
	e, err := outbox.EntryScan{
		ID:         "evt-trace-id",
		EventType:  "event.user.created.v1",
		Payload:    mustJSON(t, map[string]any{"actorId": "actor-1"}),
		OccurredAt: occ,
		CreatedAt:  occ,
		Observability: outbox.ObservabilityMetadata{
			TraceID:       idutil.SafeID(wantTraceID),
			CorrelationID: idutil.SafeID(wantCorrID),
		},
	}.ToEntry()
	require.NoError(t, err)

	result := svc.HandleEvent(context.Background(), e)
	require.Equal(t, outbox.DispositionAck, result.Disposition,
		"HandleEvent must Ack a valid entry; err=%v", result.Err)
	require.Len(t, cap.appended, 1, "must have appended exactly one ledger entry")

	got := cap.appended[0]
	assert.Equal(t, wantTraceID, got.TraceID,
		"TraceID must be derived from Observability.TraceID via correlation.New")
	assert.Equal(t, wantCorrID, got.CorrelationID,
		"CorrelationID must be derived from Observability.CorrelationID via correlation.New")

	// Round-trip: confirm TraceID survives the full Append lifecycle and is
	// readable via GetBySeq (not just captured pre-persist in cap.appended).
	appenderVis, _ := tenant.NewRowVisibility(tenant.RowScopeTenant, "")
	roundTrip, err := cap.GetBySeq(context.Background(), appenderVis, got.SeqNo)
	require.NoError(t, err, "GetBySeq round-trip after Append must succeed")
	assert.Equal(t, wantTraceID, roundTrip.TraceID,
		"TraceID must survive full Append lifecycle (GetBySeq round-trip)")
	assert.Equal(t, wantCorrID, roundTrip.CorrelationID,
		"CorrelationID must survive full Append lifecycle (GetBySeq round-trip)")
}

// TestHandleEvent_TenantIDPersistedCleanly pins the epic #1337 PR-2a closure of
// #1289: tenant-scoped audit isolation now lands at the QUERY layer
// (AuditFilters.TenantID mandatory scope), so a non-empty principal.TenantID is
// no longer a security gap — it flows cleanly through the appender. The
// INV-SINGLE-TENANT-ONLY tripwire (formerly an Error-level alarm) is RETIRED:
// the appender persists tenant_id and emits NO tripwire log, because cross-tenant
// reads are prevented downstream by the tenant-scoped query, not by an upstream
// write-time alarm. The audit record is still appended (compliance evidence is
// never dropped).
func TestHandleEvent_TenantIDPersistedCleanly(t *testing.T) {
	p := newTestProtocol(t)
	inner, err := ledger.NewMemStore(p, clock.Real())
	require.NoError(t, err)
	cap := &captureStore{Store: inner}
	spec := newSpec(t, "auditappenduser", appender.ActorAcceptUserFallback)

	epoch := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	fc := clockmock.New(epoch)
	svc, buf := newServiceWithLogBuf(t, spec, cap, p, fc)

	entry, err := outbox.EntryScan{
		ID:         "evt-tenant-persist",
		EventType:  "event.user.created.v1",
		Payload:    mustJSON(t, map[string]any{"actorId": "actor-1"}),
		CreatedAt:  epoch,
		OccurredAt: epoch,
		Principal:  outbox.PrincipalMetadata{TenantID: idutil.SafeID("tenant-a")},
	}.ToEntry()
	require.NoError(t, err)

	result := svc.HandleEvent(context.Background(), entry)
	require.Equal(t, outbox.DispositionAck, result.Disposition,
		"tenant-bearing event must be appended, never dropped")
	require.Len(t, cap.appended, 1, "audit record must be appended")
	assert.Equal(t, "tenant-a", cap.appended[0].TenantID,
		"principal.TenantID must persist to the audit row for query-time isolation")

	// The retired tripwire must NOT fire: tenant now flows cleanly.
	logs := buf.String()
	assert.NotContains(t, logs, "INV-SINGLE-TENANT-ONLY",
		"the single-tenant tripwire is retired (PR-2a); tenant flows cleanly, no alarm")
}

// recordingEmitter captures every Emit call. Implements outbox.Emitter.
type recordingEmitter struct {
	emitted []emittedRecord
}

type emittedRecord struct {
	topic   string
	payload []byte
}

func (r *recordingEmitter) Emit(_ context.Context, entry outbox.Entry) error {
	r.emitted = append(r.emitted, emittedRecord{topic: entry.EventType(), payload: entry.Payload()})
	return nil
}

// captureStore wraps a ledger.Store and records every Append call so tests
// can inspect the ledger.Entry that was actually written.
type captureStore struct {
	ledger.Store
	appended []*ledger.Entry
}

func (c *captureStore) Append(ctx context.Context, e *ledger.Entry) error {
	c.appended = append(c.appended, e)
	return c.Store.Append(ctx, e)
}

// newServiceWithLogBuf constructs a Service using a fakeClock and a JSON slog buffer
// so tests can inspect Warn-level log output.
func newServiceWithLogBuf(
	t *testing.T, spec appender.Spec, store ledger.Store, p *ledger.Protocol, fc *clockmock.FakeClock,
) (*appender.Service, *bytes.Buffer) {
	t.Helper()
	buf := &bytes.Buffer{}
	logger := slog.New(slog.NewJSONHandler(buf, &slog.HandlerOptions{Level: slog.LevelDebug}))
	svc, err := appender.NewService(spec, store, p, logger, fc, appender.WithTxManager(persistence.WrapForCell(directRunner{})))
	require.NoError(t, err)
	return svc, buf
}

// TestHandleEvent_UsesEntryCreatedAt asserts that the ledger.Entry.Timestamp is
// set to outbox.Entry.CreatedAt (the event's original creation time), NOT to
// clk.Now() at handle time.
//
// F-02 RED: current implementation uses s.clk.Now(); after the fix it must use
// entry.CreatedAt so that audit timestamps faithfully represent when the business
// event occurred, not when it was picked up by the relay.
func TestHandleEvent_UsesEntryCreatedAt(t *testing.T) {
	p := newTestProtocol(t)
	inner, err := ledger.NewMemStore(p, clock.Real())
	require.NoError(t, err)
	cap := &captureStore{Store: inner}
	spec := newSpec(t, "auditappenduser", appender.ActorAcceptUserFallback)

	epoch := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	fc := clockmock.New(epoch)
	// Advance the fake clock so clk.Now() ≠ entry.CreatedAt
	fc.Advance(testtime.D10min)

	t1 := epoch // original event creation time, before clock advance
	// Build directly via EntryScan (not mustScan) so CreatedAt is pinned to t1
	// rather than defaulted: tsForLedger reads CreatedAt and the assertion below
	// requires Timestamp == t1. OccurredAt is also t1 (non-zero, validates).
	entry, err := outbox.EntryScan{
		ID:         "evt-created-at",
		EventType:  "event.user.created.v1",
		Payload:    mustJSON(t, map[string]any{"actorId": "actor-1"}),
		CreatedAt:  t1,
		OccurredAt: t1,
	}.ToEntry()
	require.NoError(t, err)

	svc, _ := newServiceWithLogBuf(t, spec, cap, p, fc)
	result := svc.HandleEvent(context.Background(), entry)
	require.Equal(t, outbox.DispositionAck, result.Disposition,
		"HandleEvent must succeed for valid entry")
	require.Len(t, cap.appended, 1, "must have appended exactly one entry")

	gotTS := cap.appended[0].Timestamp
	// F-02 assertion: must use entry.CreatedAt, not clk.Now()
	if !gotTS.Equal(t1) {
		t.Errorf("Timestamp mismatch: got %v, want entry.CreatedAt=%v (clk.Now()=%v); "+
			"F-02: HandleEvent must use entry.CreatedAt, not clk.Now()",
			gotTS, t1, fc.Now())
	}
}

// TestHandleEvent_ZeroCreatedAt_FallbackToClk_LogsWarn asserts that when
// outbox.Entry.CreatedAt is zero, the service falls back to clk.Now() AND
// emits a Warn-level log record.
//
// F-02 RED: current implementation uses clk.Now() unconditionally (no fallback
// branch, no Warn log). After the fix: zero CreatedAt → Warn + clk.Now().
func TestHandleEvent_ZeroCreatedAt_FallbackToClk_LogsWarn(t *testing.T) {
	p := newTestProtocol(t)
	inner, err := ledger.NewMemStore(p, clock.Real())
	require.NoError(t, err)
	cap := &captureStore{Store: inner}
	spec := newSpec(t, "auditappenduser", appender.ActorAcceptUserFallback)

	epoch := time.Date(2026, 1, 1, 12, 0, 0, 0, time.UTC)
	fc := clockmock.New(epoch)

	// Build directly via EntryScan (not mustScan) so CreatedAt stays ZERO,
	// exercising the tsForLedger fallback (zero CreatedAt → Warn + clk.Now()).
	// OccurredAt must be non-zero for ToEntry validation, so it carries epoch.
	entry, err := outbox.EntryScan{
		ID:         "evt-zero-created-at",
		EventType:  "event.user.created.v1",
		Payload:    mustJSON(t, map[string]any{"actorId": "actor-1"}),
		OccurredAt: epoch, // non-zero; CreatedAt left zero to trigger fallback
	}.ToEntry()
	require.NoError(t, err)

	svc, buf := newServiceWithLogBuf(t, spec, cap, p, fc)
	result := svc.HandleEvent(context.Background(), entry)
	require.Equal(t, outbox.DispositionAck, result.Disposition,
		"HandleEvent must still succeed when CreatedAt is zero")
	require.Len(t, cap.appended, 1)

	// Timestamp must fall back to clk.Now()
	gotTS := cap.appended[0].Timestamp
	if !gotTS.Equal(epoch) {
		t.Errorf("fallback Timestamp: got %v, want clk.Now()=%v", gotTS, epoch)
	}

	// F-02: must emit a Warn-level log when falling back
	logOutput := buf.String()
	if !strings.Contains(logOutput, "WARN") && !strings.Contains(logOutput, "warn") {
		t.Errorf("expected Warn-level log for zero CreatedAt fallback; got log output: %s", logOutput)
	}
}
