//go:build ignore_path_query_length_archtest_fixtures

// Code generated by gocell generate contract. DO NOT EDIT.
// source: testdata/path_query_length_validation_fixtures/two_path_params_one_missing/contract.yaml

// Negative fixture: TWO path params, both declared with maxLength=256:
//   - "id"     has BOTH min/max length checks (correct).
//   - "cmdId"  has NO length check at all (regression).
//
// The legacy file-level fallback `hasLenCheck && hasParamRef` would FALSE-PASS
// for "cmdId" because:
//   1. The file contains a len(v) BinaryExpr (from the "id" block) →
//      hasLenCheck = true.
//   2. The file contains the string literal "cmdId" (in r.PathValue("cmdId")) →
//      hasParamRef = true.
// Both flags are global/file-level so the absence of any len() compare
// associated with cmdId goes undetected.
//
// Param-scoped scanner must reject "cmdId" (require min AND max checks
// inside the same block where r.PathValue("cmdId") appears).

package twopathparams

import (
	"net/http"
)

type Request struct {
	ID    string
	CmdID string
}

type Handler struct{}

func (h *Handler) handle(w http.ResponseWriter, r *http.Request) {
	req := &Request{}
	{
		v := r.PathValue("id")
		if len(v) < 1 {
			http.Error(w, "id: invalid", http.StatusBadRequest)
			return
		}
		if len(v) > 256 {
			http.Error(w, "id: invalid", http.StatusBadRequest)
			return
		}
		req.ID = v
	}
	{
		v := r.PathValue("cmdId")
		req.CmdID = v
	}
	_ = req
	_ = w
}
