// Code generated by gocell generate contract. DO NOT EDIT.
// source: examples/iotdevice/contracts/http/device/list/v1/contract.yaml

/** http.device.list.v1.request */
export interface Request {
  cursor?: string;
  limit?: number;
}

/** http.device.list.v1.response */
export interface Response {
  data: ResponseDataItem[];
  nextCursor: string;
  hasMore: boolean;
}

export interface ResponseDataItem {
  id: string;
  name: string;
  status: string;
  lastSeen: string;
}
