// Package sharedschema derives byte-identical mirror copies of the shared
// error envelope schema from its single canonical source.
//
// # Purpose
//
// contracts/shared/errors/error-response-v1.schema.json is the single
// source-of-truth for the GoCell HTTP error response envelope.  Several
// sub-trees in the repository (example projects, contract test fixtures)
// need a local copy of that file to validate against; those copies are
// declared in [Mirrors] and regenerated by [Generate] / verified by [Verify].
//
// # AI-robust grade
//
//   - Upstream: Medium — the A1 reverse-enum archtest
//     (SHARED-SCHEMA-MIRROR-FUNNEL-01) detects new rogue copies at CI time;
//     the Go type system cannot prevent creating a JSON file.
//     gh issue #954 tracks Hard-ening this side.
//
//   - Downstream: Medium — the A2 caller-allowlist archtest restricts
//     Headerless usage to this package; the WriteOptions struct field is
//     exported so it cannot be sealed at compile time.
//     Same gh issue #954 tracks upgrading to a
//     typed-funnel construction pattern that seals the escape-hatch.
//
// # Symbols
//
//   - [Mirrors]   — manifest: canonical path → []destination root prefixes
//   - [Generate]  — write byte-identical mirror copies (or dry-run preview)
//   - [Verify]    — report destination paths whose content has drifted
//
// archtest ID: SHARED-SCHEMA-MIRROR-FUNNEL-01
// ADR ref: docs/architecture/202605250900-adr-shared-error-schema-mirror-codegen.md
// Hard-ening tracking: gh issue #954
package sharedschema

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/ghbvf/gocell/tools/codegen"
)

// Mirrors maps each canonical schema path (module-relative, slash-separated)
// to the list of destination root prefixes where a byte-identical copy must
// exist.  The destination file path is:
//
//	<repoRoot>/<destRoot>/<canonicalRel>
//
// The key is the canonical path; callers must not add entries here without
// also deleting any existing copy that would otherwise become an undeclared
// fork (caught by archtest SHARED-SCHEMA-MIRROR-FUNNEL-01 A1).
var Mirrors = map[string][]string{
	"contracts/shared/errors/error-response-v1.schema.json": {
		"examples/iotdevice",
		"examples/todoorder",
		"tests/contracttest/testdata",
	},
}

// Generate reads each canonical schema file from root and writes byte-identical
// copies to every declared mirror destination.  When dryRun is true no files
// are written; the returned written list still contains the paths that would
// have been written.
//
// written contains module-relative slash paths for every file that was
// actually written (ActionWritten) or would have been written (ActionWouldWrite
// when dryRun=true).  Already-up-to-date mirrors (ActionUnchanged) are omitted.
// The slice is sorted for deterministic output.
func Generate(root string, dryRun bool) (written []string, err error) {
	if err := eachMirror(root, func(canonicalRel, destRel, destAbs string) error {
		canonical, readErr := readCanonical(root, canonicalRel)
		if readErr != nil {
			return readErr
		}
		// codegen.Write → pathsafe.WriteFileForce creates the destination's
		// parent directories via the platform secure-mkdir funnel; no separate
		// os.MkdirAll here (SCAFFOLD-WRITE-FUNNEL-01 bans direct os.MkdirAll).
		res, writeErr := codegen.Write(codegen.WriteOptions{
			Path:       destAbs,
			Content:    canonical,
			RepoRoot:   root,
			Headerless: true,
			DryRun:     dryRun,
		})
		if writeErr != nil {
			return fmt.Errorf("sharedschema: write mirror %s: %w", destRel, writeErr)
		}
		if res.Action == codegen.ActionWritten || res.Action == codegen.ActionWouldWrite {
			written = append(written, filepath.ToSlash(destRel))
		}
		return nil
	}); err != nil {
		return nil, err
	}
	sort.Strings(written)
	return written, nil
}

// Verify checks that every declared mirror destination is byte-identical to
// the canonical source.  It returns the module-relative slash paths of every
// destination that differs (or is missing).  An empty drifted slice means all
// mirrors are in sync.  The slice is sorted for deterministic output.
func Verify(root string) (drifted []string, err error) {
	if err := eachMirror(root, func(canonicalRel, destRel, destAbs string) error {
		canonical, readErr := readCanonical(root, canonicalRel)
		if readErr != nil {
			return readErr
		}
		res, writeErr := codegen.Write(codegen.WriteOptions{
			Path:       destAbs,
			Content:    canonical,
			RepoRoot:   root,
			Headerless: true,
			Verify:     true,
		})
		if writeErr != nil {
			return fmt.Errorf("sharedschema: verify mirror %s: %w", destRel, writeErr)
		}
		if res.Action == codegen.ActionDrifted {
			drifted = append(drifted, filepath.ToSlash(destRel))
		}
		return nil
	}); err != nil {
		return nil, err
	}
	sort.Strings(drifted)
	return drifted, nil
}

// readCanonical reads the canonical schema bytes from root/canonicalRel.
// The path is constructed from the manifest key, which is a static string
// constant — not user input — so the G304 taint is a false positive.
func readCanonical(root, canonicalRel string) ([]byte, error) {
	p := filepath.Join(root, filepath.FromSlash(canonicalRel))
	b, err := os.ReadFile(p) //nolint:gosec // G304: path is derived from the static Mirrors manifest, not user input
	if err != nil {
		return nil, fmt.Errorf("sharedschema: read canonical %s: %w", canonicalRel, err)
	}
	return b, nil
}

// eachMirror iterates over all (canonicalRel, destRoot) pairs declared in
// [Mirrors] and invokes fn with:
//
//   - canonicalRel: module-relative slash path of the canonical file
//   - destRel:      module-relative slash path of the destination file
//     (destRoot + "/" + canonicalRel)
//   - destAbs:      absolute path of the destination file
//
// Iteration order is sorted by canonicalRel then destRoot for determinism.
// eachMirror returns the first error returned by fn.
func eachMirror(root string, fn func(canonicalRel, destRel, destAbs string) error) error {
	canonicals := make([]string, 0, len(Mirrors))
	for k := range Mirrors {
		canonicals = append(canonicals, k)
	}
	sort.Strings(canonicals)

	for _, canonicalRel := range canonicals {
		destRoots := append([]string(nil), Mirrors[canonicalRel]...)
		sort.Strings(destRoots)
		for _, destRoot := range destRoots {
			destRel := destRoot + "/" + canonicalRel
			destAbs := filepath.Join(root, filepath.FromSlash(destRel))
			if err := fn(canonicalRel, destRel, destAbs); err != nil {
				return err
			}
		}
	}
	return nil
}
