// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/auditcore/cell.yaml

package auditcore

import (
	"github.com/ghbvf/gocell/kernel/cell"
	"github.com/ghbvf/gocell/kernel/healthz"
)

// ProbeRepoReady is the canonical readiness probe name for the auditcore cell's
// primary repository. The "_ready" suffix is required by the READYZ-PROBE-NAMING-01
// convention.
const ProbeRepoReady = "auditcore_repo_ready"

// RegisterRepoReady registers a healthz.RepoProber implementation as the
// cell-level repository readiness probe on the given Registry. This is the
// sole sanctioned entry point — handwritten cell code must NOT call
// reg.Healthz() directly (locked by HEALTHZ-TYPED-REGISTER-01).
func RegisterRepoReady(reg cell.Registry, p healthz.RepoProber) error {
	return reg.Healthz().Register(healthz.NewProbe(ProbeRepoReady, p.RepoReady))
}

// RegisterEmitterProbes registers all probes exposed by a healthz.ProbeSet
// (typically outbox.DirectEmitter) on the given Registry. This is the sole
// sanctioned entry point for emitter probes — handwritten cell code must NOT
// call reg.Healthz() directly (locked by HEALTHZ-TYPED-REGISTER-01).
// A nil ProbeSet is silently ignored.
func RegisterEmitterProbes(reg cell.Registry, ps healthz.ProbeSet) error {
	if ps == nil {
		return nil
	}
	for _, p := range ps.Probes() {
		if err := reg.Healthz().Register(p); err != nil {
			return err
		}
	}
	return nil
}
