package assembly

import (
	"errors"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/ghbvf/gocell/kernel/metadata"
	ecErr "github.com/ghbvf/gocell/pkg/errcode"
)

// buildModulesTestProject creates a ProjectMeta with 3 cells that all have
// GoStructName set, suitable for GenerateModulesGen tests.
func buildModulesTestProject() *metadata.ProjectMeta {
	return &metadata.ProjectMeta{
		Cells: map[string]*metadata.CellMeta{
			"accesscore": {
				ID:           "accesscore",
				GoStructName: metadata.MustNewGoIdentifier("AccessCore"),
			},
			"auditcore": {
				ID:           "auditcore",
				GoStructName: metadata.MustNewGoIdentifier("AuditCore"),
			},
			"configcore": {
				ID:           "configcore",
				GoStructName: metadata.MustNewGoIdentifier("ConfigCore"),
			},
		},
		Slices:    make(map[string]*metadata.SliceMeta),
		Contracts: make(map[string]*metadata.ContractMeta),
		Journeys:  make(map[string]*metadata.JourneyMeta),
		Assemblies: map[string]*metadata.AssemblyMeta{
			"corebundle": {
				ID:    "corebundle",
				Cells: []string{"accesscore", "auditcore", "configcore"},
			},
		},
	}
}

// ---------------------------------------------------------------------------
// GenerateModulesGen tests
// ---------------------------------------------------------------------------

func TestGenerateModulesGen_Corebundle(t *testing.T) {
	project := buildModulesTestProject()
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)

	content := string(out)
	// Generated file marker
	assert.Contains(t, content, "// Code generated by ")
	assert.Contains(t, content, "DO NOT EDIT")
	// Package declaration
	assert.Contains(t, content, "package main")
	// Function signature
	assert.Contains(t, content, "func generatedCellModules() []CellModule")
	// All three module struct literals
	assert.Contains(t, content, "AccessCoreModule{}")
	assert.Contains(t, content, "AuditCoreModule{}")
	assert.Contains(t, content, "ConfigCoreModule{}")
	// Empty-capabilities path is byte-inert: no capability import, no
	// generatedCapabilities(). Locks the {{- if .Capabilities}} else-branch so
	// assemblies that declare no capabilities stay identical to the
	// pre-capabilities form.
	assert.NotContains(t, content, "runtime/capability")
	assert.NotContains(t, content, "generatedCapabilities")
}

// TestGenerateModulesGen_DerivesCapabilitiesFromCellRequires exercises the
// non-empty branch under Design Y (#855): the assembly capability set is the
// sorted, de-duplicated union of its cells' `requires`. Input order is
// irrelevant (sorted output) and a capability required by multiple cells emits
// exactly one const (dedup).
func TestGenerateModulesGen_DerivesCapabilitiesFromCellRequires(t *testing.T) {
	project := buildModulesTestProject()
	// Unsorted input + cross-cell duplicate of postgres → output must be the
	// sorted union {postgres, redis} with postgres emitted once.
	project.Cells["accesscore"].Requires = []string{"redis", "postgres"}
	project.Cells["auditcore"].Requires = []string{"postgres"}
	project.Cells["configcore"].Requires = []string{"postgres"}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)

	content := string(out)
	assert.Contains(t, content, `import "github.com/ghbvf/gocell/runtime/capability"`)
	assert.Contains(t, content, "func generatedCapabilities() []capability.Kind")
	assert.Contains(t, content, "capability.Postgres")
	assert.Contains(t, content, "capability.Redis")
	// Deterministic alphabetical order regardless of per-cell input order.
	assert.Less(t,
		indexOfStr(content, "capability.Postgres"),
		indexOfStr(content, "capability.Redis"),
		"derived capabilities must be sorted (postgres before redis)")
	// Dedup: postgres required by all three cells must appear exactly once.
	assert.Equal(t, 1, strings.Count(content, "capability.Postgres"),
		"postgres required by multiple cells must emit a single const")
}

// TestCapabilityConstNamesMatchCapabilityEnum locks the capabilityConstNames
// map key set to metadata.CapabilityEnum (single source). Adding a capability to
// the enum without a matching const-name entry (or vice versa) fails here in CI,
// closing the gap between the codegen const-name table and the
// governance/schema enum that TestSchemaConstantsMatchSchemaLiterals already
// pins to cell.schema.json.
func TestCapabilityConstNamesMatchCapabilityEnum(t *testing.T) {
	keys := make([]string, 0, len(capabilityConstNames))
	for k, v := range capabilityConstNames {
		assert.NotEmpty(t, v, "capabilityConstNames[%q] must map to a non-empty const name", k)
		keys = append(keys, k)
	}
	sort.Strings(keys)
	want := append([]string(nil), metadata.CapabilityEnum...)
	sort.Strings(want)
	assert.Equal(t, want, keys,
		"capabilityConstNames key set must equal metadata.CapabilityEnum (single source)")
}

// TestGenerateModulesGen_RabbitMQAndSingle covers the single-capability path
// (sort/dedup with len 1) and the rabbitmq → capability.RabbitMQ const mapping
// — the enum member with no provider yet, whose codegen path is otherwise
// uncovered. The generated const must still emit (provisioning fails later at
// provisionCapabilities' default branch, by design).
func TestGenerateModulesGen_RabbitMQAndSingle(t *testing.T) {
	project := buildModulesTestProject()
	project.Cells["accesscore"].Requires = []string{"rabbitmq"}
	// auditcore / configcore leave Requires nil — union is the single {rabbitmq}.
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("corebundle")
	require.NoError(t, err)

	content := string(out)
	assert.Contains(t, content, "func generatedCapabilities() []capability.Kind")
	assert.Contains(t, content, "capability.RabbitMQ")
	assert.Equal(t, 1, strings.Count(content, "capability.RabbitMQ"))
	assert.NotContains(t, content, "capability.Postgres")
	assert.NotContains(t, content, "capability.Redis")
}

// TestGenerateModulesGen_UnknownCapability verifies the codegen-time guard:
// a cell `requires` value absent from capabilityConstNames fails with
// ErrMetadataInvalid rather than emitting an undefined capability const. The
// closed enum's validation-time enforcement is FMT-36 (gocell validate); this
// test only locks the generator's own fail-rather-than-emit-garbage behavior.
func TestGenerateModulesGen_UnknownCapability(t *testing.T) {
	project := buildModulesTestProject()
	project.Cells["accesscore"].Requires = []string{"bogus-capability"}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	_, err := gen.GenerateModulesGen("corebundle")
	require.Error(t, err)

	var ec *ecErr.Error
	require.True(t, errors.As(err, &ec), "error must be an errcode.Error, got: %T", err)
	assert.Equal(t, ecErr.ErrMetadataInvalid, ec.Code)
	assert.Contains(t, strings.ToLower(ec.Message), "capability",
		"error message should mention capability, got: %q", ec.Message)
}

func TestGenerateModulesGen_AssemblyNotFound(t *testing.T) {
	project := buildModulesTestProject()
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	_, err := gen.GenerateModulesGen("nonexistent")
	require.Error(t, err)

	var ec *ecErr.Error
	require.True(t, errors.As(err, &ec))
	assert.Equal(t, ecErr.ErrAssemblyNotFound, ec.Code)
}

func TestGenerateModulesGen_CellMissingGoStructName(t *testing.T) {
	project := buildModulesTestProject()
	// Override accesscore to have empty GoStructName
	project.Cells["accesscore"] = &metadata.CellMeta{
		ID: "accesscore",
		// GoStructName left at zero value to trigger the missing-name error.
	}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	_, err := gen.GenerateModulesGen("corebundle")
	require.Error(t, err)

	var ec *ecErr.Error
	require.True(t, errors.As(err, &ec))
	assert.Equal(t, ecErr.ErrMetadataInvalid, ec.Code)
	// Message is a const literal; it must mention GoStructName so the error
	// is self-describing without the Internal field.
	assert.Contains(t, ec.Message, "GoStructName")
}

// TestGenerateModulesGen_UnknownCellRef verifies that when an assembly references
// a cell ID that is not registered in project.Cells, GenerateModulesGen returns
// an errcode.Error with code ErrMetadataInvalid and a message containing "unknown"
// or "not found".
func TestGenerateModulesGen_UnknownCellRef(t *testing.T) {
	project := buildModulesTestProject()
	// Add assembly with an unregistered cell ID.
	project.Assemblies["ghostbundle"] = &metadata.AssemblyMeta{
		ID:    "ghostbundle",
		Cells: []string{"accesscore", "ghost-cell-not-registered"},
	}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	_, err := gen.GenerateModulesGen("ghostbundle")
	require.Error(t, err)

	var ec *ecErr.Error
	require.True(t, errors.As(err, &ec), "error must be an errcode.Error, got: %T", err)
	assert.Equal(t, ecErr.ErrMetadataInvalid, ec.Code)
	// Message must contain "unknown" or "not found" so the error is self-describing.
	msgLower := strings.ToLower(ec.Message)
	assert.True(t, strings.Contains(msgLower, "unknown") || strings.Contains(msgLower, "not found"),
		"error message should contain 'unknown' or 'not found', got: %q", ec.Message)
}

func TestGenerateModulesGen_PreservesCellsOrder(t *testing.T) {
	project := buildModulesTestProject()
	// Declare assembly with cells in b, a, c order
	project.Cells["b"] = &metadata.CellMeta{ID: "b", GoStructName: metadata.MustNewGoIdentifier("B")}
	project.Cells["a"] = &metadata.CellMeta{ID: "a", GoStructName: metadata.MustNewGoIdentifier("A")}
	project.Cells["c"] = &metadata.CellMeta{ID: "c", GoStructName: metadata.MustNewGoIdentifier("C")}
	project.Assemblies["ordered"] = &metadata.AssemblyMeta{
		ID:    "ordered",
		Cells: []string{"b", "a", "c"},
	}
	gen := NewGenerator(project, "github.com/ghbvf/gocell", "")

	out, err := gen.GenerateModulesGen("ordered")
	require.NoError(t, err)

	content := string(out)
	// B must appear before A, A before C
	posB := indexOfStr(content, "BModule{}")
	posA := indexOfStr(content, "AModule{}")
	posC := indexOfStr(content, "CModule{}")

	assert.Less(t, posB, posA, "BModule must come before AModule")
	assert.Less(t, posA, posC, "AModule must come before CModule")
}

// indexOfStr returns the byte position of substr in s, or -1 if not found.
func indexOfStr(s, substr string) int {
	for i := range len(s) - len(substr) + 1 {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
