// Code generated by gocell generate cell. DO NOT EDIT.

package ordercell

import (
	"context"

	"github.com/ghbvf/gocell/kernel/cell"
)

var _ cell.Cell = (*OrderCell)(nil)

func (c *OrderCell) Init(ctx context.Context, reg cell.Registry) error {
	if err := c.BaseCell.Init(ctx, reg); err != nil {
		return err
	}
	if err := c.initInternal(ctx, reg); err != nil {
		return err
	}

	reg.RouteGroup(cell.RouteGroup{
		Listener: cell.PrimaryListener,
		Prefix:   "/api/v1",
		Register: func(mux cell.RouteMux) error {
			var firstErr error
			captureErr := func(err error) {
				if err != nil && firstErr == nil {
					firstErr = err
				}
			}
			mux.Route("/orders", func(s cell.RouteMux) {
				captureErr(c.createHandler.RegisterRoutes(s))
				captureErr(c.queryHandler.RegisterRoutes(s))
			})
			return firstErr
		},
	})

	return nil
}
