// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/config/flags/delete/v1/contract.yaml

/** http.config.flags.delete.v1.request */
export interface Request {
  key: string;
  expectedVersion: number;
}

/** http.config.flags.delete.v1.response */
export interface Response {
}
