// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/policy/delete/v1/contract.yaml

/** http.policy.delete.v1.request */
export interface Request {
  id: string;
  expectedVersion: number;
}

/** http.policy.delete.v1.response */
export interface Response {
}
