// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/config/update/v1/contract.yaml

/** http.config.update.v1.request */
export interface Request {
  key: string;
  value: string;
  expectedVersion: number;
}

/** http.config.update.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  id: string;
  key: string;
  value: string;
  sensitive: boolean;
  version: number;
  createdAt: string;
  updatedAt: string;
}
