// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/auth/setup/admin/v1/contract.yaml

/** http.auth.setup.admin.v1.request */
export interface Request {
  username: string;
  email: string;
  password: string;
}

/** http.auth.setup.admin.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  id: string;
  username: string;
  email: string;
  createdAt: string;
}
