// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/event/session/revoked/v1/contract.yaml

/** event.session.revoked.v1.payload */
export interface Payload {
  sessionId: string;
  userId: string;
}

/** event.session.revoked.v1.headers */
export interface Headers {
  eventId: string;
}
