package app

// generate_catalog.go — implements `gocell generate catalog`, which emits a
// build-time Go file containing a typed *kerneldepgraph.Graph literal.
//
// The generated file is consumed by cmd/corebundle via generatedPackageGraph
// so that the HTTP handler never needs a runtime goroutine to load the graph.

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/ghbvf/gocell/kernel/clock"
	kerneldepgraph "github.com/ghbvf/gocell/kernel/depgraph"
	"github.com/ghbvf/gocell/tools/depgraph"
)

// generateCatalog implements:
//
//	gocell generate catalog --out=<path> --package=<pkg> [--root=<dir>]
func generateCatalog(args []string) error {
	fs := flag.NewFlagSet("generate catalog", flag.ContinueOnError)
	out := fs.String("out", "", "output .go file path (required)")
	pkg := fs.String("package", "", "Go package declaration name (required)")
	root := fs.String("root", "", "project root directory; empty triggers go.mod auto-detection")
	if err := fs.Parse(args); err != nil {
		return err
	}

	if *out == "" {
		return fmt.Errorf("--out is required")
	}
	if *pkg == "" {
		return fmt.Errorf("--package is required")
	}

	rootDir, err := resolveRoot(*root)
	if err != nil {
		return err
	}

	modulePath, err := readModule(rootDir)
	if err != nil {
		return fmt.Errorf("cannot read module from go.mod: %w", err)
	}

	// Load the package dep graph synchronously (CLI context — acceptable latency).
	g, err := depgraph.Load(depgraph.LoadOptions{Dir: rootDir}, "./...")
	if err != nil {
		return fmt.Errorf("generate catalog: depgraph load: %w", err)
	}

	// Emit the Go source file.
	src, err := emitCatalogFile(*pkg, modulePath, g)
	if err != nil {
		return fmt.Errorf("generate catalog: emit: %w", err)
	}

	// Ensure parent dir exists.
	if err := os.MkdirAll(filepath.Dir(filepath.Clean(*out)), 0o750); err != nil {
		return fmt.Errorf("generate catalog: mkdir: %w", err)
	}

	if err := os.WriteFile(filepath.Clean(*out), src, 0o600); err != nil {
		return fmt.Errorf("generate catalog: write: %w", err)
	}
	fmt.Printf("Generated: %s\n", *out)
	return nil
}

// emitCatalogFile produces a gofmt'd Go source file containing
// generatedPackageGraph as a typed *kerneldepgraph.Graph literal built via
// kerneldepgraph.FromNodes. This avoids emitting the byID map directly and
// ensures ByID() works at runtime.
func emitCatalogFile(pkg, modulePath string, g *kerneldepgraph.Graph) ([]byte, error) {
	var b bytes.Buffer

	now := clock.Real().Now().UTC().Format(time.RFC3339)
	fmt.Fprintf(&b, "// Code generated by gocell generate catalog. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// source: %s\n", modulePath)
	fmt.Fprintf(&b, "// generated: %s\n", now)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import kerneldepgraph %q\n\n", "github.com/ghbvf/gocell/kernel/depgraph")

	// Sort packages for deterministic output.
	pkgs := make([]*kerneldepgraph.Node, len(g.Packages))
	copy(pkgs, g.Packages)
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].ID < pkgs[j].ID })

	fmt.Fprintf(&b, "// generatedPackageGraph is the build-time package dependency graph.\n")
	fmt.Fprintf(&b, "// Rebuild with: go generate ./cmd/corebundle/\n")
	fmt.Fprintf(&b, "var generatedPackageGraph = func() *kerneldepgraph.Graph {\n")
	fmt.Fprintf(&b, "\tnodes := []*kerneldepgraph.Node{\n")

	for _, n := range pkgs {
		fmt.Fprintf(&b, "\t\t{\n")
		fmt.Fprintf(&b, "\t\t\tID:    %s,\n", goString(n.ID))
		fmt.Fprintf(&b, "\t\t\tLayer: %s,\n", goString(n.Layer))
		if n.CellID != "" {
			fmt.Fprintf(&b, "\t\t\tCellID: %s,\n", goString(n.CellID))
		}
		if n.SliceID != "" {
			fmt.Fprintf(&b, "\t\t\tSliceID: %s,\n", goString(n.SliceID))
		}
		if n.TestOnly {
			fmt.Fprintf(&b, "\t\t\tTestOnly: true,\n")
		}
		// Sort imports for determinism.
		imports := append([]string(nil), n.Imports...)
		sort.Strings(imports)
		fmt.Fprintf(&b, "\t\t\tImports: %s,\n", goStringSlice(imports))
		fmt.Fprintf(&b, "\t\t},\n")
	}

	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn kerneldepgraph.FromNodes(%s, nodes)\n", goString(g.Module))
	fmt.Fprintf(&b, "}()\n")

	// gofmt the output.
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w (source:\n%s)", err, b.String())
	}
	return formatted, nil
}

// goString returns a Go string literal for s.
func goString(s string) string {
	return fmt.Sprintf("%q", s)
}

// goStringSlice returns a Go []string literal.
func goStringSlice(ss []string) string {
	if len(ss) == 0 {
		return "[]string{}"
	}
	var sb strings.Builder
	sb.WriteString("[]string{")
	for i, s := range ss {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%q", s)
	}
	sb.WriteString("}")
	return sb.String()
}
