// Package placeorder implements the placeorder slice: accepting an order
// placement request, persisting the order, and enrolling a saga instance for
// fulfillment orchestration via the journal.
//
// Demo mode uses an in-memory journal (shared with the saga coordinator).
// The slice is L3 WorkflowEventual: the saga coordinator drives the forward
// fulfillment steps asynchronously after enrollment.
package placeorder

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"github.com/ghbvf/gocell/examples/orderfulfillment/cells/orderfulfillmentcell/internal/domain"
	"github.com/ghbvf/gocell/examples/orderfulfillment/cells/orderfulfillmentcell/internal/ports"
	of "github.com/ghbvf/gocell/generated/contracts/saga/orderfulfillment/v1"
	"github.com/ghbvf/gocell/kernel/clock"
	ksaga "github.com/ghbvf/gocell/kernel/saga"
	"github.com/ghbvf/gocell/kernel/saga/journal"
	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/idutil"
	"github.com/ghbvf/gocell/pkg/validation"
)

// Option configures the placeorder Service.
type Option func(*Service)

// WithOrderRepository sets the order repository.
// Typed-nil inputs are not stored; the factory will fail-fast if the repo
// remains unset.
func WithOrderRepository(r ports.OrderRepository) Option {
	return func(s *Service) {
		if !validation.IsNilInterface(r) {
			s.orders = r
		}
	}
}

// WithJournal sets the saga journal for enrolling instances.
// Typed-nil inputs are not stored; the factory will fail-fast if the journal
// remains unset.
func WithJournal(j journal.Enqueuer) Option {
	return func(s *Service) {
		if !validation.IsNilInterface(j) {
			s.journal = j
		}
	}
}

// WithLogger sets the structured logger. A nil value is a silent noop.
func WithLogger(l *slog.Logger) Option {
	return func(s *Service) {
		if l != nil {
			s.logger = l
		}
	}
}

// Service implements the place-order business logic.
// Required fields are tagged gocell:"required"; validateRequired() is
// generated by `gocell generate required-deps`.
type Service struct {
	orders  ports.OrderRepository `gocell:"required"`
	journal journal.Enqueuer      `gocell:"required"`
	clock   clock.Clock
	logger  *slog.Logger
}

// NewService creates a placeorder Service. Returns an error if required
// dependencies (orders, journal) are nil.
func NewService(clk clock.Clock, opts ...Option) (*Service, error) {
	clock.MustHaveClock(clk, "placeorder.NewService")
	s := &Service{
		clock:  clk,
		logger: slog.Default(),
	}
	for _, o := range opts {
		o(s)
	}
	if err := s.validateRequired(); err != nil {
		return nil, err
	}
	return s, nil
}

// PlaceOrder persists a new order and enrolls a saga instance for
// fulfillment. Returns the order ID on success.
//
// Idempotency (Temporal workflow-id / DTM GID model): the idempotencyKey is
// mapped directly to the order ID ("ord-"+idempotencyKey). A repeated call
// with the same key returns the same orderID without re-running any saga step.
// The saga runs asynchronously — the caller gets an immediate 202 Accepted.
func (s *Service) PlaceOrder(
	ctx context.Context, idempotencyKey, item string, amountCents int64, paymentShouldFail bool,
) (orderID string, err error) {
	orderID = "ord-" + idempotencyKey

	order := &domain.Order{
		ID:                orderID,
		Item:              item,
		AmountCents:       amountCents,
		PaymentShouldFail: paymentShouldFail,
		CreatedAt:         s.clock.Now(),
	}

	if createErr := s.orders.Create(ctx, order); createErr != nil {
		// Idempotent hit: an order with this ID already exists in the repository
		// (the primary dedup authority). Return the existing orderID without
		// re-enrolling the saga.
		var ec *errcode.Error
		if errors.As(createErr, &ec) && ec.Kind == errcode.KindConflict {
			s.logger.Info(
				"placeorder: idempotent hit, returning existing order",
				slog.String("order_id", orderID),
			)
			return orderID, nil
		}
		return "", fmt.Errorf("placeorder: persist order: %w", createErr)
	}

	inst := ksaga.NewInstance(
		idutil.SafeID(orderID),
		of.DefinitionID,
		s.clock.Now(),
	)
	if enqErr := s.journal.Enqueue(ctx, inst); enqErr != nil {
		// Defense-in-depth: duplicate saga instance (journal already has this ID).
		var ec *errcode.Error
		if errors.As(enqErr, &ec) && ec.Code == errcode.ErrSagaDuplicateInstance {
			s.logger.Info(
				"placeorder: saga already enrolled (defense-in-depth idempotent hit)",
				slog.String("order_id", orderID),
			)
			return orderID, nil
		}
		return "", fmt.Errorf("placeorder: enqueue saga: %w", enqErr)
	}

	s.logger.Info(
		"placeorder: order placed, saga enrolled",
		slog.String("order_id", orderID),
		slog.String("definition_id", string(of.DefinitionID)),
	)
	return orderID, nil
}
