// Package placeorder implements the placeorder slice: accepting an order
// placement request, persisting the order, and enrolling a saga instance for
// fulfillment orchestration via the journal.
//
// Demo mode uses an in-memory journal (shared with the saga coordinator).
// The slice is L3 WorkflowEventual: the saga coordinator drives the forward
// fulfillment steps asynchronously after enrollment.
package placeorder

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/google/uuid"

	"github.com/ghbvf/gocell/examples/orderfulfillment/cells/orderfulfillmentcell/internal/domain"
	"github.com/ghbvf/gocell/examples/orderfulfillment/cells/orderfulfillmentcell/internal/ports"
	of "github.com/ghbvf/gocell/generated/contracts/saga/orderfulfillment/v1"
	"github.com/ghbvf/gocell/kernel/clock"
	ksaga "github.com/ghbvf/gocell/kernel/saga"
	"github.com/ghbvf/gocell/kernel/saga/journal"
	"github.com/ghbvf/gocell/pkg/idutil"
)

// Option configures the placeorder Service.
type Option func(*Service)

// WithOrderRepository sets the order repository.
// A nil value is a silent noop; the factory will fail-fast if the repo
// remains unset.
func WithOrderRepository(r ports.OrderRepository) Option {
	return func(s *Service) {
		if r != nil {
			s.orders = r
		}
	}
}

// WithJournal sets the saga journal for enrolling instances.
// A nil value is a silent noop; the factory will fail-fast if the journal
// remains unset.
func WithJournal(j journal.JournalCore) Option {
	return func(s *Service) {
		if j != nil {
			s.journal = j
		}
	}
}

// WithLogger sets the structured logger. A nil value is a silent noop.
func WithLogger(l *slog.Logger) Option {
	return func(s *Service) {
		if l != nil {
			s.logger = l
		}
	}
}

// Service implements the place-order business logic.
// Required fields are tagged gocell:"required"; validateRequired() is
// generated by `gocell generate required-deps`.
type Service struct {
	orders  ports.OrderRepository `gocell:"required"`
	journal journal.JournalCore   `gocell:"required"`
	clock   clock.Clock
	logger  *slog.Logger
}

// NewService creates a placeorder Service. Returns an error if required
// dependencies (orders, journal) are nil.
func NewService(clk clock.Clock, opts ...Option) (*Service, error) {
	clock.MustHaveClock(clk, "placeorder.NewService")
	s := &Service{
		clock:  clk,
		logger: slog.Default(),
	}
	for _, o := range opts {
		o(s)
	}
	if err := s.validateRequired(); err != nil {
		return nil, err
	}
	return s, nil
}

// PlaceOrder persists a new order and enrolls a saga instance for
// fulfillment. Returns the order ID on success.
// The saga runs asynchronously — the caller gets an immediate 202 Accepted.
func (s *Service) PlaceOrder(ctx context.Context, item string, amountCents int64, paymentShouldFail bool) (orderID string, err error) {
	order := &domain.Order{
		ID:                "ord-" + uuid.NewString(),
		Item:              item,
		AmountCents:       amountCents,
		PaymentShouldFail: paymentShouldFail,
		CreatedAt:         s.clock.Now(),
	}
	if err := s.orders.Create(ctx, order); err != nil {
		return "", fmt.Errorf("placeorder: persist order: %w", err)
	}

	inst := ksaga.NewInstance(
		idutil.SafeID(order.ID),
		of.DefinitionID,
		s.clock.Now(),
	)
	if err := s.journal.Enqueue(ctx, inst); err != nil {
		return "", fmt.Errorf("placeorder: enqueue saga: %w", err)
	}

	s.logger.Info("placeorder: order placed, saga enrolled",
		slog.String("order_id", order.ID),
		slog.String("definition_id", string(of.DefinitionID)),
	)
	return order.ID, nil
}
