// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/orderfulfillment/cells/orderfulfillmentcell/slices/placeorder/slice.yaml

package placeorder

import (
	"github.com/ghbvf/gocell/framework/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "placeorder",
	BelongsToCell:    "orderfulfillmentcell",
	ConsistencyLevel: "L3",
	Lifecycle:        "experimental",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "http.orderfulfillment.placeorder.v1", Role: "serve"},
		{Contract: "saga.orderfulfillment.v1", Role: "orchestrate"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.placeorder.service",
		},
		Contract: []string{
			"contract.http.orderfulfillment.placeorder.v1.serve",
			"contract.saga.orderfulfillment.v1.orchestrate",
		},
	},
	AllowedFiles: []string{
		"examples/orderfulfillment/cells/orderfulfillmentcell/slices/placeorder/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }
