//go:build ignore_event_subscription_coverage_archtest_fixtures

// Code generated by gocell generate contract. DO NOT EDIT.

// Negative fixture: file contains the EXACT bytes "func NewSubscription"
// but NOT as a real top-level function declaration — instead it appears in:
//   1. A package-level comment.
//   2. A string literal value.
//   3. A `var NewSubscription = ...` declaration (variable, not function).
//
// The legacy bytes.Contains(content, "func NewSubscription") scan would
// FALSE-PASS because the substring is present three times. AST scan must
// reject because no *ast.FuncDecl with Name == "NewSubscription" exists.

package fakesub

// Note: legacy comment intentionally contains "func NewSubscription" text
// to bait file-level byte scanners.
import "fmt"

var noSubscriptionMarker = "func NewSubscription"

var NewSubscription = func() {
	fmt.Println("not a real func declaration — variable shadow")
}
