// Code generated by gocell generate required-deps. DO NOT EDIT.

package orderquery

import (
	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/validation"
)

// validateRequired verifies every required dependency on the Service struct
// is present and non-typed-nil. Generated from gocell:"required" struct field
// tags; do not edit by hand.
func (s *Service) validateRequired() error {
	if validation.IsNilInterface(s.repo) {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"orderquery.NewService: repo required")
	}
	if s.codec == nil {
		return errcode.New(errcode.KindInternal, errcode.ErrCellMissingCodec,
			"order-query: cursor codec is required")
	}
	return nil
}
