// Code generated by gocell generate contract. DO NOT EDIT.
// source: examples/orderfulfillment/contracts/http/orderfulfillment/orderstatus/v1/contract.yaml

/** http.orderfulfillment.orderstatus.v1.request */
export interface Request {
  id: string;
}

/** http.orderfulfillment.orderstatus.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  orderId: string;
  status: ResponseDataStatus;
}

/** ResponseDataStatus enumerates the closed value-set for the status field. */
export type ResponseDataStatus = 'accepted' | 'running' | 'succeeded' | 'compensated' | 'failed';
