package healthz

import (
	"log/slog"
	"regexp"

	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/panicregister"
)

// ProbeName is the typed name for every healthz probe: adapter
// dependency-availability probes ("<x>_ready"), framework probes
// ("config_watcher", "config_drift", "outbox_failopen_rate_<cell>"), and
// cellgen cell-repo probes ("<cell>_repo_ready").
//
// Authoring path is split by ownership:
//
//   - Adapter dependency probes (e.g. postgres_ready) declare typed const at
//     the adapter's own package level (e.g. `const ProbeReady ProbeName =
//     "postgres_ready"` in adapters/postgres). The const becomes the single
//     truth for the probe name.
//
//   - Framework probes (config_watcher, config_drift) are typed const in this
//     package — see [ConfigWatcherProbeName] / [ConfigDriftProbeName].
//
//   - Cell-repo probes are typed const generated by cellgen into
//     `cells/<cell>/healthz_gen.go` (e.g. `const ProbeRepoReady ProbeName =
//     "configcore_repo_ready"`).
//
//   - Composed runtime names (where part of the name comes from runtime data,
//     e.g. "outbox_failopen_rate_<cell>") flow through a typed constructor
//     such as [EmitterFailOpenProbeName] — never via raw string concat at the
//     callsite.
//
// Hand-written `reg.RegisterReadiness(ProbeName(...), ...)` casts of arbitrary
// strings are rejected by archtest PROBENAME-SEALED-FUNNEL-01 (downstream A2:
// callsite must resolve to declared *types.Const; upstream A1: const must be
// declared in a sanctioned package; A3: any string-conversion at the callsite
// fails closed). Composed-name constructors are the only sanctioned path for
// runtime data to enter the typed-name funnel.
//
// ref: kubernetes/apimachinery `pkg/util/validation/validation.go::IsDNS1123Label`
// (runtime validator-shape on bare string — closest open-source analog;
// gocell tightens this to type-system + CI-time double-lock).
type ProbeName string

// String returns the underlying name as a plain string. It exists so
// `slog.Attr` and `fmt.Sprintf("%s", ...)` carry the literal probe name
// without revealing the typed nature in formatted output.
func (p ProbeName) String() string { return string(p) }

// probeNamePattern enforces snake_case (lowercase ASCII + digits + underscores),
// no leading digit, no consecutive underscores, no hyphens, no whitespace.
// The trailing "_ready" suffix is NOT enforced here — that overlay applies
// only to adapter dependency probes and is checked by
// archtest PROBENAME-SEALED-FUNNEL-01/A1 (adapter package-set overlay).
//
// Framework probes (`config_watcher`, `outbox_failopen_rate_<cell>`) and cell
// repo probes (`<cell>_repo_ready`) all satisfy this base pattern.
var probeNamePattern = regexp.MustCompile(`^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$`)

const probeNameMaxLen = 48

// NewProbeName validates s and returns a typed [ProbeName]. It is the only
// sanctioned runtime entry point — composed-name constructors call this with
// a literal+runtime concatenation, and tests use [MustProbeName] (panic
// variant) so the validation regex governs every test fixture too.
//
// Returns [errcode.ErrValidationFailed] when s is empty, exceeds 48 runes,
// contains uppercase letters, hyphens, whitespace, double-underscores, or
// starts with a digit.
func NewProbeName(s string) (ProbeName, error) {
	if s == "" {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: probe name must not be empty")
	}
	if len(s) > probeNameMaxLen {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: probe name exceeds length budget",
			errcode.WithDetails(
				slog.Int("max", probeNameMaxLen),
				slog.Int("got", len(s)),
			))
	}
	if !probeNamePattern.MatchString(s) {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: probe name must match snake_case lowercase regex",
			errcode.WithDetails(slog.String("name", s)))
	}
	return ProbeName(s), nil
}

// MustProbeName is the panic variant of [NewProbeName] for sites where an
// invalid name is a programmer error rather than a runtime condition. It is
// intended for use in any *_test.go file (any package) and the kernel/healthz
// internals; production callers outside kernel/healthz are rejected by archtest
// PROBENAME-SEALED-FUNNEL-01/A4b (caller allowlist).
//
// It routes through [panicregister.Approved] so the kernel recovery layer
// classifies the panic correctly. Production code that needs to validate a
// runtime-supplied string must use [NewProbeName] (returns an error) instead
// of MustProbeName (panics), to avoid availability risk when adapter Checkers()
// map keys contain unexpected characters.
func MustProbeName(s string) ProbeName {
	name, err := NewProbeName(s)
	if err != nil {
		panic(panicregister.Approved("healthz-probe-name-invalid",
			errcode.Assertion("healthz.MustProbeName(%q): %v", s, err)))
	}
	return name
}

// ConfigWatcherProbeName is the framework probe registered when a config
// watcher is active. Declared here (not in `runtime/bootstrap`) so the
// kernel layer owns the typed const set and bootstrap consumes it.
const ConfigWatcherProbeName ProbeName = "config_watcher"

// ConfigDriftProbeName is the framework probe registered when config supports
// generation-tracked drift detection.
const ConfigDriftProbeName ProbeName = "config_drift"

// EventRouterProbeName is the framework probe registered by the bootstrap event
// router, indicating the event routing layer is alive. Declared here so that
// bootstrap consumes a typed const rather than calling MustProbeName with a
// literal — archtest PROBENAME-SEALED-FUNNEL-01/A4b enforces that MustProbeName
// has zero production callers outside kernel/healthz and *_test.go.
const EventRouterProbeName ProbeName = "event_router"

const emitterFailOpenProbeNamePrefix = "outbox_failopen_rate_"

// EmitterFailOpenProbeName composes the typed probe name for the outbox
// direct-emitter fail-open-rate probe scoped to cellID. The cellID is
// validated against the full [NewProbeName] shape (so an invalid cellID
// such as "Bad-Cell" yields an error here, surfacing at emitter
// construction rather than per-probe invocation).
//
// This is the SOLE sanctioned composed-name constructor for emitter
// probes — bare `"outbox_failopen_rate_" + cellID` concat at callsites is
// rejected by archtest PROBENAME-SEALED-FUNNEL-01/A5.
func EmitterFailOpenProbeName(cellID string) (ProbeName, error) {
	if cellID == "" {
		return "", errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"healthz: emitter probe cellID must not be empty")
	}
	return NewProbeName(emitterFailOpenProbeNamePrefix + cellID)
}
