package healthz

import (
	"context"

	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/panicregister"
)

// Probe is a named readiness check.
//
// Name returns a stable lower-case snake_case identifier ending in "_ready"
// for dependency probes; framework probes use stable identifiers without the
// "_ready" suffix. Name shape is enforced **statically** by archtest, not at
// runtime (runtime Aggregator.Register only rejects empty and duplicate names);
// adding a runtime regex check would create a parallel governance surface and is
// intentionally avoided. Two archtests split the surface by authoring site:
//   - adapter dependency-availability probes authored via
//     lifecycle.ManagedResource.Checkers() / adapterutil.HealthToCheckers —
//     OPS-CONTRACT-STRING-FUNNEL-01 (must be a healthz.ReadyProbeName const;
//     see kernel/healthz/readyprobename.go);
//   - framework + cellgen probes constructed directly via NewProbe(name, fn)
//     (config_watcher, outbox_failopen_rate_<cell>, <cell>_repo_ready) —
//     READYZ-PROBE-NAMING-01 (no hyphens; see
//     tools/archtest/readyz_probe_naming_test.go).
//
// Check is invoked by the Aggregator with a context carrying the probe
// deadline. Returning nil indicates healthy; a non-nil error indicates
// degraded or down — the Aggregator classifies the outcome by inspecting
// errors.Is(err, context.DeadlineExceeded) (timeout → Down) and the error
// chain (anything else non-nil → Down by default; cells may signal a
// fail-open degraded condition with a sentinel error matched by the
// transport layer).
//
// ref: kubernetes/kubernetes apiserver healthz.HealthChecker
// (Name + Check). GoCell drops the *http.Request dependency: probes have
// no HTTP context at the kernel layer.
type Probe interface {
	Name() string
	Check(ctx context.Context) error
}

// RepoProber is implemented by a cell's primary repository/store to expose a
// differentiated readiness check.
//
// "Differentiated" means the check exercises a failure domain distinct from
// adapter pool-level pings (e.g. postgres_ready). A RepoReady implementation
// backed by SQL is expected to issue a representative query against the
// cell's own relation(s) — surfacing schema/migration drift, missing tables,
// and table-level permission loss that a connection ping cannot detect.
// In-memory implementations return nil (always ready).
//
// This interface is separate from Probe because cellgen-generated
// RegisterRepoReady helpers take a RepoProber (semantic constraint:
// repository readiness) rather than a generic Probe (any function). The
// codegen pass wraps the RepoProber into a Probe with the cell-derived
// canonical name "<cellid>_repo_ready" — naming, wrapping, and registration
// are all centralized in the cellgen template.
type RepoProber interface {
	RepoReady(ctx context.Context) error
}

// NewProbe constructs a Probe with the given name and check function.
// It is the only sanctioned way to wrap a closure as a Probe — cells and
// adapters that need a one-off probe go through this constructor so the
// resulting value participates in HEALTHZ-WRITE-01 form-uniqueness.
//
// NewProbe panics if name is empty or fn is nil — both are programmer
// errors caught at composition time, not runtime failures of a healthy
// probe execution. The panics route through panicregister.Approved so the
// kernel recovery middleware classifies them correctly.
func NewProbe(name string, fn func(context.Context) error) Probe {
	if name == "" {
		panic(panicregister.Approved("healthz-probe-empty-name",
			errcode.Assertion("healthz.NewProbe: name must not be empty")))
	}
	if fn == nil {
		panic(panicregister.Approved("healthz-probe-nil-fn",
			errcode.Assertion("healthz.NewProbe: fn must not be nil")))
	}
	return funcProbe{name: name, fn: fn}
}

// ProbeSet is implemented by components that expose a collection of Probe
// values belonging to the same owner (e.g. outbox.DirectEmitter registers one
// probe per cell). Callers iterate Probes() and register each with an
// Aggregator via RegisterEmitterProbes (generated by cellgen).
//
// ref: kernel/outbox.DirectEmitter.Probes — primary implementor
type ProbeSet interface {
	Probes() []Probe
}

// funcProbe is the unexported Probe implementation returned by NewProbe.
// Keeping it unexported funnels all closure-based probes through NewProbe,
// which makes "wrap a closure as a Probe" form-unique for archtest.
type funcProbe struct {
	name string
	fn   func(context.Context) error
}

func (p funcProbe) Name() string                    { return p.name }
func (p funcProbe) Check(ctx context.Context) error { return p.fn(ctx) }
