// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/iotdevice/cells/devicecell/slices/devicelist/slice.yaml

package devicelist

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "devicelist",
	BelongsToCell:    "devicecell",
	ConsistencyLevel: "L0",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "http.device.list.v1", Role: "serve"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.devicelist.service",
		},
		Contract: []string{
			"contract.http.device.list.v1.serve",
		},
	},
	AllowedFiles: []string{
		"examples/iotdevice/cells/devicecell/slices/devicelist/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }
