// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/auth/user/update/v1/contract.yaml

/** http.auth.user.update.v1.request */
export interface Request {
  id: string;
  email?: string;
}

/** http.auth.user.update.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  id: string;
  username: string;
  email: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}
