//go:build archtest_fixture

// Package basesliceredfixture contains intentionally-violating forms for the
// BASESLICE-CTOR-FUNNEL-01 archtest detector. Gated by the archtest_fixture
// build tag (must agree with archtestmeta.FixtureBuildTag).
//
// This file exercises RED shape 3: a metadata.SliceMeta{...} composite literal
// in non-generated production code, which bypasses the codegen funnel
// (slice_gen.go.sliceMeta). The only legitimate source of SliceMeta literals
// is *_gen.go files (codegen output); non-gen code must call
// slicePkg.SliceMetadata().
package basesliceredfixture

import "github.com/ghbvf/gocell/kernel/metadata"

// VIOLATION: metadata.SliceMeta{} — forbidden composite literal in non-gen
// production code. Must use slicePkg.SliceMetadata() (generated by gocell generate cell).
//
//nolint:all // intentional violation for archtest RED fixture
var redSliceMetaLiteral = metadata.SliceMeta{ //nolint:unused
	ID:               "red-fixture-slice",
	BelongsToCell:    "red-fixture-cell",
	ConsistencyLevel: "L1",
}
