// Code generated by gocell generate assembly. DO NOT EDIT.
// Source: examples/demo/assembly.yaml
package main

func generatedCellModules() []CellModule {
	return []CellModule{
		DemoCellModule{},
	}
}
