// Code generated by gocell generate assembly. DO NOT EDIT.
// Source: assemblies/iotdevice/assembly.yaml
package main

func generatedCellModules() []CellModule {
	return []CellModule{
		DeviceCellModule{},
	}
}
