// Code generated by gocell generate assembly. DO NOT EDIT.
// Source: {{.SourcePath}}
package main
{{- if .Capabilities}}

import "github.com/ghbvf/gocell/runtime/capability"
{{- end}}

func generatedCellModules() []CellModule {
	return []CellModule{
{{- range .Modules}}
		{{.}}{},
{{- end}}
	}
}
{{- if .Capabilities}}

// generatedCapabilities lists the assembly-level shared infrastructure
// capabilities — the sorted union of the assembly cells' cell.yaml `requires`.
// The composition root provisions each once and injects the resulting
// runtime/capability provider into consuming modules.
func generatedCapabilities() []capability.Kind {
	return []capability.Kind{
{{- range .Capabilities}}
		capability.{{.}},
{{- end}}
	}
}
{{- end}}
