// Code generated by gocell generate assembly. DO NOT EDIT.
// Source: {{.SourcePath}}
package main

import (
{{- range .PlatformImports}}
	{{.}}
{{- end}}
	"github.com/ghbvf/gocell/runtime/capability"
	"github.com/ghbvf/gocell/runtime/composition"
)

func generatedCellModules() []composition.CellModule {
	return []composition.CellModule{
{{- range .Modules}}
		{{.}},
{{- end}}
	}
}
{{- if .Capabilities}}

// generatedCapabilities lists the assembly-level shared infrastructure
// capabilities — the sorted union of the assembly cells' cell.yaml `requires`.
// The composition root provisions each once and injects the resulting
// runtime/capability provider into consuming modules. Emitted iff the union is
// non-empty: an assembly whose cells require nothing has no provisioner to call
// it, so the function (and its capability import) are omitted to avoid dead code.
func generatedCapabilities() []capability.Kind {
	return []capability.Kind{
{{- range .Capabilities}}
		capability.{{.}},
{{- end}}
	}
}
{{- end}}
