// Code generated by gocell generate assembly. DO NOT EDIT.
// Source: assemblies/{{.AssemblyID}}/assembly.yaml
package main

func generatedCellModules() []CellModule {
	return []CellModule{
{{- range .Modules}}
		{{.}}{},
{{- end}}
	}
}
