// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/todoorder/cells/ordercell/slices/orderprojection/slice.yaml

package orderprojection

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "orderprojection",
	BelongsToCell:    "ordercell",
	ConsistencyLevel: "L3",
	Lifecycle:        "experimental",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "event.order-created.v1", Role: "subscribe", Handler: "HandleOrderCreated", Projection: "order_status", OnReset: "ResetOrderStatus"},
		{Contract: "event.order-status-changed.v1", Role: "subscribe", Handler: "HandleOrderStatusChanged", Projection: "order_transition", OnReset: "ResetOrderTransition"},
		{Contract: "projection.order.status-summary.v1", Role: "provide"},
		{Contract: "http.order.projection-summary.v1", Role: "serve"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.orderprojection.service",
		},
		Contract: []string{
			"contract.event.order-created.v1.subscribe",
			"contract.event.order-status-changed.v1.subscribe",
			"contract.projection.order.status-summary.v1.provide",
			"contract.http.order.projection-summary.v1.serve",
		},
	},
	AllowedFiles: []string{
		"examples/todoorder/cells/ordercell/slices/orderprojection/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }
