// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/todoorder/cells/ordercell/slices/orderprojection/slice.yaml

package orderprojection

import (
	"context"

	"github.com/ghbvf/gocell/kernel/metadata"

	"github.com/ghbvf/gocell/kernel/outbox"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "orderprojection",
	BelongsToCell:    "ordercell",
	ConsistencyLevel: "L3",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "event.order-created.v1", Role: "subscribe", Handler: "HandleOrderCreated"},
		{Contract: "event.order-status-changed.v1", Role: "subscribe", Handler: "HandleOrderStatusChanged"},
		{Contract: "projection.order.status-summary.v1", Role: "provide"},
		{Contract: "http.order.projection-summary.v1", Role: "serve"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.orderprojection.service",
		},
		Contract: []string{
			"contract.event.order-created.v1.subscribe",
			"contract.event.order-status-changed.v1.subscribe",
			"contract.projection.order.status-summary.v1.provide",
			"contract.http.order.projection-summary.v1.serve",
		},
	},
	AllowedFiles: []string{
		"examples/todoorder/cells/ordercell/slices/orderprojection/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }

// eventHandlerService documents the handler methods orderprojection's service
// must provide so that cell_gen.go's reg.Subscribe call is typed. The interface
// is intentionally unexported to avoid colliding with a concrete Service struct.
// Build-time safety comes from the c.<field>.<method>(...) invocations in
// cell_gen.go — Go rejects compilation if the method is missing or renamed.
type eventHandlerService interface {
	// HandleOrderCreated handles event.order-created.v1.
	HandleOrderCreated(ctx context.Context, e outbox.Entry) outbox.HandleResult
	// HandleOrderStatusChanged handles event.order-status-changed.v1.
	HandleOrderStatusChanged(ctx context.Context, e outbox.Entry) outbox.HandleResult
}
