// Package metricschema builds the generated metrics schema from type-checked
// assembly reachability.
package metricschema

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"go/ast"
	"go/constant"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/ghbvf/gocell/kernel/metadata"
	"golang.org/x/tools/go/packages"
	"gopkg.in/yaml.v3"
)

const (
	kernelMetricsPkg = "github.com/ghbvf/gocell/kernel/observability/metrics"
	adapterPromPkg   = "github.com/ghbvf/gocell/adapters/prometheus"
	prometheusPkg    = "github.com/prometheus/client_golang/prometheus"
	errcodePkg       = "github.com/ghbvf/gocell/pkg/errcode"
)

// Schema describes concrete metric registrations reachable from an assembly
// entrypoint.
type Schema struct {
	AssemblyID string  `yaml:"assemblyId"`
	Scope      string  `yaml:"scope"`
	Entrypoint string  `yaml:"entrypoint"`
	Metrics    []Entry `yaml:"metrics"`
}

// Entry describes a single concrete metric registration.
type Entry struct {
	Name         string   `yaml:"name"`
	FQName       string   `yaml:"fqName,omitempty"`
	Namespace    string   `yaml:"namespace,omitempty"`
	Subsystem    string   `yaml:"subsystem,omitempty"`
	Type         string   `yaml:"type"`
	Help         string   `yaml:"help,omitempty"`
	Labels       []string `yaml:"labels"`
	ConstLabels  []string `yaml:"constLabels,omitempty"`
	Buckets      []string `yaml:"buckets,omitempty"`
	BucketSource string   `yaml:"bucketSource,omitempty"`
	File         string   `yaml:"file"`
	Line         int      `yaml:"line"`
}

// Diagnostic describes a typed OBS-01 violation.
type Diagnostic struct {
	Rule        string
	File        string
	Line        int
	Column      int
	Metric      string
	Label       string
	Fingerprint string
	Message     string
}

// ErrUnresolvedMetricSchema is returned when a concrete metric registration
// has an unresolved identity field. Names, labels, namespaces, const-label keys,
// and buckets are part of the generated schema contract, so the generator fails
// instead of emitting an empty or placeholder value.
var ErrUnresolvedMetricSchema = errors.New("metrics schema: unresolved metric schema")

// ErrUnresolvedLabel is kept as the historical sentinel for existing callers
// that only checked unresolved labels.
var ErrUnresolvedLabel = ErrUnresolvedMetricSchema

const header = "# Generated by gocell generate metrics-schema. DO NOT EDIT.\n"

type scanPackage struct {
	pkg                *packages.Package
	inits              map[types.Object]ast.Expr
	fset               *token.FileSet
	root               string
	seenOpts           map[*ast.CompositeLit]bool
	namespace          string
	prometheusOptSinks map[*types.Func][]prometheusOptSink
}

type opts struct {
	name         string
	namespace    string
	subsystem    string
	help         string
	labels       []string
	constLabels  []string
	buckets      []string
	bucketSource string
}

type prometheusOptSink struct {
	ParamIndex      int
	LabelParamIndex int
	MetricType      string
	Vec             bool
	Labels          []string
}

// Build walks the package graph reachable from assemblyID's build entrypoint
// and returns all concrete metric registrations in project-owned packages.
func Build(projectRoot string, project *metadata.ProjectMeta, assemblyID string) (*Schema, error) {
	asm := project.Assemblies[assemblyID]
	if asm == nil {
		return nil, fmt.Errorf("assembly %q not found", assemblyID)
	}
	entrypoint := asm.Build.Entrypoint
	if entrypoint == "" {
		entrypoint = filepath.Join("cmd", assemblyID, "main.go")
	}
	pattern := "./" + filepath.ToSlash(filepath.Dir(entrypoint))
	pkgs, err := loadPackages(projectRoot, pattern)
	if err != nil {
		return nil, err
	}
	namespace, err := prometheusProviderNamespace(projectRoot, pkgs)
	if err != nil {
		return nil, err
	}

	schema := &Schema{
		AssemblyID: assemblyID,
		Scope:      "assembly-reachable",
		Entrypoint: filepath.ToSlash(entrypoint),
	}
	for _, p := range pkgs {
		sp := newScanPackage(projectRoot, p, namespace)
		entries, scanErr := sp.scanMetrics()
		if scanErr != nil {
			return nil, scanErr
		}
		schema.Metrics = append(schema.Metrics, entries...)
	}
	sort.Slice(schema.Metrics, func(i, j int) bool {
		if schema.Metrics[i].Name != schema.Metrics[j].Name {
			return schema.Metrics[i].Name < schema.Metrics[j].Name
		}
		if schema.Metrics[i].File != schema.Metrics[j].File {
			return schema.Metrics[i].File < schema.Metrics[j].File
		}
		return schema.Metrics[i].Line < schema.Metrics[j].Line
	})
	return schema, nil
}

// Marshal serializes schema with the generated-file header.
func Marshal(schema *Schema) ([]byte, error) {
	body, err := yaml.Marshal(schema)
	if err != nil {
		return nil, err
	}
	return append([]byte(header), body...), nil
}

func loadPackages(root string, patterns ...string) ([]*packages.Package, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo |
			packages.NeedImports | packages.NeedDeps,
		Dir: root,
	}
	roots, err := packages.Load(cfg, patterns...)
	if err != nil {
		return nil, fmt.Errorf("packages.Load: %w", err)
	}
	var out []*packages.Package
	var loadErrs []packages.Error
	packages.Visit(roots, nil, func(p *packages.Package) {
		loadErrs = append(loadErrs, p.Errors...)
		if packageHasProjectFile(root, p) {
			out = append(out, p)
		}
	})
	if len(loadErrs) > 0 {
		return nil, fmt.Errorf("packages.Load: %d error(s): first=%v", len(loadErrs), loadErrs[0])
	}
	return out, nil
}

func packageHasProjectFile(root string, p *packages.Package) bool {
	for _, f := range p.CompiledGoFiles {
		if isProjectGoFile(root, f) {
			return true
		}
	}
	return false
}

func isProjectGoFile(root, file string) bool {
	if strings.HasSuffix(file, "_test.go") {
		return false
	}
	rel, err := filepath.Rel(root, file)
	if err != nil || strings.HasPrefix(rel, ".."+string(filepath.Separator)) || rel == ".." {
		return false
	}
	rel = filepath.ToSlash(rel)
	return !strings.HasPrefix(rel, "tools/") && !strings.Contains(rel, "/testdata/")
}

func newScanPackage(root string, p *packages.Package, namespace string) *scanPackage {
	sp := &scanPackage{
		pkg:       p,
		inits:     map[types.Object]ast.Expr{},
		fset:      p.Fset,
		root:      root,
		seenOpts:  map[*ast.CompositeLit]bool{},
		namespace: namespace,
	}
	for _, file := range p.Syntax {
		ast.Inspect(file, func(n ast.Node) bool {
			vs, ok := n.(*ast.ValueSpec)
			if !ok {
				return true
			}
			for i, name := range vs.Names {
				if i >= len(vs.Values) {
					continue
				}
				if obj := p.TypesInfo.Defs[name]; obj != nil {
					sp.inits[obj] = vs.Values[i]
				}
			}
			return true
		})
	}
	sp.prometheusOptSinks = sp.collectPrometheusOptSinks()
	return sp
}

func prometheusProviderNamespace(root string, pkgs []*packages.Package) (string, error) {
	var namespace string
	for _, p := range pkgs {
		ns, err := prometheusProviderNamespaceForPackage(root, p)
		if err != nil {
			return "", err
		}
		if ns == "" {
			continue
		}
		if namespace != "" && namespace != ns {
			return "", fmt.Errorf("metrics schema: multiple Prometheus provider namespaces found: %q and %q", namespace, ns)
		}
		namespace = ns
	}
	return namespace, nil
}

func prometheusProviderNamespaceForPackage(root string, p *packages.Package) (string, error) {
	sp := newScanPackage(root, p, "")
	var namespace string
	for _, file := range p.Syntax {
		path := p.Fset.Position(file.Pos()).Filename
		if !isProjectGoFile(root, path) {
			continue
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return "", err
		}
		ns, err := sp.prometheusProviderNamespaceForFile(file, filepath.ToSlash(rel))
		if err != nil {
			return "", err
		}
		if ns == "" {
			continue
		}
		if namespace != "" && namespace != ns {
			return "", fmt.Errorf("metrics schema: multiple Prometheus provider namespaces found in %s: %q and %q",
				p.PkgPath, namespace, ns)
		}
		namespace = ns
	}
	return namespace, nil
}

func (sp *scanPackage) prometheusProviderNamespaceForFile(file *ast.File, rel string) (string, error) {
	var namespace string
	var scanErr error
	ast.Inspect(file, func(n ast.Node) bool {
		if scanErr != nil {
			return false
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		ns, ok, err := sp.prometheusProviderNamespaceFromCall(call, rel)
		if err != nil {
			scanErr = err
			return false
		}
		if !ok || ns == "" {
			return true
		}
		if namespace != "" && namespace != ns {
			scanErr = fmt.Errorf("metrics schema: multiple Prometheus provider namespaces found in %s: %q and %q",
				rel, namespace, ns)
			return false
		}
		namespace = ns
		return true
	})
	return namespace, scanErr
}

func (sp *scanPackage) prometheusProviderNamespaceFromCall(call *ast.CallExpr, rel string) (string, bool, error) {
	if !isAdapterPrometheusNewMetricProvider(sp.pkg.TypesInfo, call) || len(call.Args) == 0 {
		return "", false, nil
	}
	lit := sp.resolveCompositeLit(call.Args[0])
	if lit == nil {
		return "", false, sp.unresolved(call.Args[0], rel, "prometheus metric provider config must be a resolvable literal")
	}
	return sp.metricProviderConfigNamespace(lit, rel)
}

func isAdapterPrometheusNewMetricProvider(info *types.Info, call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	fn, ok := info.Uses[sel.Sel].(*types.Func)
	return ok && fn.Pkg() != nil && fn.Pkg().Path() == adapterPromPkg && fn.Name() == "NewMetricProvider"
}

func (sp *scanPackage) metricProviderConfigNamespace(lit *ast.CompositeLit, rel string) (string, bool, error) {
	pkgPath, typ, ok := namedType(sp.pkg.TypesInfo, lit.Type)
	if !ok || pkgPath != adapterPromPkg || typ != "MetricProviderConfig" {
		return "", false, nil
	}
	for _, elt := range lit.Elts {
		key, value, ok := keyValueField(elt)
		if !ok || key != "Namespace" {
			continue
		}
		ns, ok := sp.string(value)
		if !ok {
			return "", false, sp.unresolved(value, rel, "prometheus metric provider namespace must be a compile-time string")
		}
		return ns, true, nil
	}
	return "", false, nil
}

func (sp *scanPackage) scanMetrics() ([]Entry, error) {
	var entries []Entry
	for _, file := range sp.pkg.Syntax {
		path := sp.fset.Position(file.Pos()).Filename
		if !isProjectGoFile(sp.root, path) {
			continue
		}
		rel, err := filepath.Rel(sp.root, path)
		if err != nil {
			return nil, err
		}
		rel = filepath.ToSlash(rel)
		if rel == "adapters/prometheus/metric_provider.go" {
			continue
		}
		direct, scanErr := sp.scanDirectPrometheus(file, rel)
		if scanErr != nil {
			return nil, scanErr
		}
		entries = append(entries, direct...)
		generic, scanErr := sp.scanOptsLiterals(file, rel)
		if scanErr != nil {
			return nil, scanErr
		}
		entries = append(entries, generic...)
	}
	return entries, nil
}

func (sp *scanPackage) scanDirectPrometheus(file *ast.File, rel string) ([]Entry, error) {
	var entries []Entry
	for _, decl := range file.Decls {
		var direct []Entry
		var err error
		if fn, ok := decl.(*ast.FuncDecl); ok {
			direct, err = sp.scanDirectPrometheusNode(fn.Body, rel, functionParamSet(sp.pkg.TypesInfo, fn.Type))
		} else {
			direct, err = sp.scanDirectPrometheusNode(decl, rel, nil)
		}
		if err != nil {
			return nil, err
		}
		entries = append(entries, direct...)
	}
	return entries, nil
}

func (sp *scanPackage) scanDirectPrometheusNode(node ast.Node, rel string, params map[types.Object]bool) ([]Entry, error) {
	var entries []Entry
	var scanErr error
	ast.Inspect(node, func(n ast.Node) bool {
		if scanErr != nil {
			return false
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		entry, ok, err := sp.directPrometheusEntry(call, rel, params)
		if err != nil {
			scanErr = err
			return false
		}
		if ok {
			entries = append(entries, entry)
			return true
		}
		wrapperEntries, ok, err := sp.prometheusWrapperEntries(call, rel)
		if err != nil {
			scanErr = err
			return false
		}
		if ok {
			entries = append(entries, wrapperEntries...)
		}
		return true
	})
	return entries, scanErr
}

func (sp *scanPackage) collectPrometheusOptSinks() map[*types.Func][]prometheusOptSink {
	out := map[*types.Func][]prometheusOptSink{}
	for _, file := range sp.pkg.Syntax {
		rel := sp.relForNode(file)
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}
			obj, sinks := sp.collectPrometheusOptSinksForFunc(fn, rel)
			if obj == nil || len(sinks) == 0 {
				continue
			}
			out[obj] = append(out[obj], sinks...)
		}
	}
	return out
}

func (sp *scanPackage) collectPrometheusOptSinksForFunc(
	fn *ast.FuncDecl,
	rel string,
) (*types.Func, []prometheusOptSink) {
	if fn.Body == nil {
		return nil, nil
	}
	obj, ok := sp.pkg.TypesInfo.Defs[fn.Name].(*types.Func)
	if !ok {
		return nil, nil
	}
	params := functionParamIndexes(sp.pkg.TypesInfo, fn.Type)
	if len(params) == 0 {
		return obj, nil
	}
	var sinks []prometheusOptSink
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sink, ok := sp.prometheusOptSinkFromCall(call, params, rel)
		if ok {
			sinks = append(sinks, sink)
		}
		return true
	})
	return obj, sinks
}

func (sp *scanPackage) prometheusOptSinkFromCall(
	call *ast.CallExpr,
	params map[types.Object]int,
	rel string,
) (prometheusOptSink, bool) {
	metricType, vec, ok := prometheusConstructor(sp.pkg.TypesInfo, call)
	if !ok || len(call.Args) == 0 {
		return prometheusOptSink{}, false
	}
	idx, ok := params[sp.objectForExpr(call.Args[0])]
	if !ok {
		return prometheusOptSink{}, false
	}
	sink := prometheusOptSink{
		ParamIndex:      idx,
		LabelParamIndex: -1,
		MetricType:      metricType,
		Vec:             vec,
	}
	if vec && len(call.Args) > 1 {
		if labelIdx, ok := params[sp.objectForExpr(call.Args[1])]; ok {
			sink.LabelParamIndex = labelIdx
		} else if labels, err := sp.stringSlice(call.Args[1], rel); err == nil {
			sink.Labels = labels
		}
	}
	return sink, true
}

func (sp *scanPackage) relForNode(node ast.Node) string {
	path := sp.fset.Position(node.Pos()).Filename
	rel, err := filepath.Rel(sp.root, path)
	if err != nil {
		return path
	}
	return filepath.ToSlash(rel)
}

func (sp *scanPackage) directPrometheusEntry(call *ast.CallExpr, rel string, params map[types.Object]bool) (Entry, bool, error) {
	if len(call.Args) == 0 {
		return Entry{}, false, nil
	}
	metricType, vec, ok := prometheusConstructor(sp.pkg.TypesInfo, call)
	if !ok {
		return Entry{}, false, nil
	}
	lit := sp.resolveCompositeLit(call.Args[0])
	if lit == nil {
		if params[sp.objectForExpr(call.Args[0])] {
			return Entry{}, false, nil
		}
		return Entry{}, false, sp.unresolved(call.Args[0], rel, "Prometheus metric opts must be a resolvable literal")
	}
	parsed, hasName, err := sp.extractPrometheusOpts(lit, rel)
	if err != nil || !hasName {
		return Entry{}, hasName, err
	}
	sp.seenOpts[lit] = true
	if vec {
		labels, labelErr := sp.prometheusVecLabels(call, rel)
		if labelErr != nil {
			return Entry{}, false, labelErr
		}
		parsed.labels = labels
	}
	return sp.entryFromOpts(metricType, parsed, rel, lit.Pos()), true, nil
}

func (sp *scanPackage) prometheusWrapperEntries(call *ast.CallExpr, rel string) ([]Entry, bool, error) {
	sinks := sp.prometheusOptSinks[calledFunc(sp.pkg.TypesInfo, call)]
	if len(sinks) == 0 {
		return nil, false, nil
	}
	entries := make([]Entry, 0, len(sinks))
	for _, sink := range sinks {
		if sink.ParamIndex >= len(call.Args) {
			return nil, false, sp.unresolved(call, rel, "Prometheus metric helper opts argument is missing")
		}
		lit := sp.resolveCompositeLit(call.Args[sink.ParamIndex])
		if lit == nil {
			return nil, false, sp.unresolved(call.Args[sink.ParamIndex], rel, "Prometheus metric helper opts must be a resolvable literal")
		}
		parsed, hasName, err := sp.extractPrometheusOpts(lit, rel)
		if err != nil {
			return nil, false, err
		}
		if !hasName {
			continue
		}
		sp.seenOpts[lit] = true
		if sink.Vec {
			labels, err := sp.prometheusWrapperLabels(call, sink, rel)
			if err != nil {
				return nil, false, err
			}
			parsed.labels = labels
		}
		entries = append(entries, sp.entryFromOpts(sink.MetricType, parsed, rel, lit.Pos()))
	}
	return entries, true, nil
}

func (sp *scanPackage) prometheusWrapperLabels(call *ast.CallExpr, sink prometheusOptSink, rel string) ([]string, error) {
	if sink.LabelParamIndex >= 0 {
		if sink.LabelParamIndex >= len(call.Args) {
			return nil, sp.unresolved(call, rel, "Prometheus metric helper label argument is missing")
		}
		return sp.stringSlice(call.Args[sink.LabelParamIndex], rel)
	}
	if sink.Labels != nil {
		return append([]string(nil), sink.Labels...), nil
	}
	return nil, sp.unresolved(call, rel, "Prometheus metric helper labels must be resolvable")
}

func (sp *scanPackage) prometheusVecLabels(call *ast.CallExpr, rel string) ([]string, error) {
	if len(call.Args) < 2 {
		return nil, sp.unresolved(call, rel, "missing Prometheus vec label argument")
	}
	return sp.stringSlice(call.Args[1], rel)
}

func (sp *scanPackage) scanOptsLiterals(file *ast.File, rel string) ([]Entry, error) {
	var entries []Entry
	var scanErr error
	ast.Inspect(file, func(n ast.Node) bool {
		if scanErr != nil {
			return false
		}
		lit, ok := n.(*ast.CompositeLit)
		if !ok || sp.seenOpts[lit] {
			return true
		}
		entry, ok, err := sp.optsLiteralEntry(lit, rel)
		if err != nil {
			scanErr = err
			return false
		}
		if ok {
			entries = append(entries, entry)
		}
		return true
	})
	return entries, scanErr
}

func (sp *scanPackage) optsLiteralEntry(lit *ast.CompositeLit, rel string) (Entry, bool, error) {
	pkgPath, typ, ok := namedType(sp.pkg.TypesInfo, lit.Type)
	if !ok {
		return Entry{}, false, nil
	}
	metricType, parsed, hasName, err := sp.extractTypedOpts(pkgPath, typ, lit, rel)
	if err != nil || !hasName {
		return Entry{}, false, err
	}
	return sp.entryFromOpts(metricType, parsed, rel, lit.Pos()), true, nil
}

func (sp *scanPackage) extractTypedOpts(pkgPath, typ string, lit *ast.CompositeLit, rel string) (string, opts, bool, error) {
	switch pkgPath {
	case kernelMetricsPkg:
		metricType, ok := kernelMetricType(typ)
		if !ok {
			return "", opts{}, false, nil
		}
		parsed, hasName, err := sp.extractKernelOpts(lit, rel)
		return metricType, parsed, hasName, err
	case prometheusPkg:
		metricType, ok := prometheusOptsType(typ)
		if !ok {
			return "", opts{}, false, nil
		}
		parsed, hasName, err := sp.extractPrometheusOpts(lit, rel)
		return metricType, parsed, hasName, err
	}
	return "", opts{}, false, nil
}

func (sp *scanPackage) entryFromOpts(metricType string, parsed opts, rel string, pos token.Pos) Entry {
	namespace := parsed.namespace
	if namespace == "" {
		namespace = sp.namespace
	}
	labels := mergeLabels(parsed.labels, parsed.constLabels)
	fqName := promFQName(namespace, parsed.subsystem, parsed.name)
	e := Entry{
		Name:         parsed.name,
		FQName:       fqName,
		Namespace:    namespace,
		Subsystem:    parsed.subsystem,
		Type:         metricType,
		Help:         parsed.help,
		Labels:       labels,
		ConstLabels:  sortedUnique(parsed.constLabels),
		Buckets:      parsed.buckets,
		BucketSource: parsed.bucketSource,
		File:         rel,
		Line:         sp.fset.Position(pos).Line,
	}
	if e.FQName == e.Name {
		e.FQName = ""
	}
	return e
}

func (sp *scanPackage) extractKernelOpts(lit *ast.CompositeLit, rel string) (opts, bool, error) {
	var out opts
	for _, elt := range lit.Elts {
		key, value, ok := keyValueField(elt)
		if !ok {
			continue
		}
		if err := sp.applyKernelOptField(&out, key, value, rel); err != nil {
			return out, false, err
		}
	}
	return out, out.name != "", nil
}

func (sp *scanPackage) extractPrometheusOpts(lit *ast.CompositeLit, rel string) (opts, bool, error) {
	var out opts
	for _, elt := range lit.Elts {
		key, value, ok := keyValueField(elt)
		if !ok {
			continue
		}
		if err := sp.applyPrometheusOptField(&out, key, value, rel); err != nil {
			return out, false, err
		}
	}
	return out, out.name != "", nil
}

func keyValueField(expr ast.Expr) (string, ast.Expr, bool) {
	kv, ok := expr.(*ast.KeyValueExpr)
	if !ok {
		return "", nil, false
	}
	key, ok := kv.Key.(*ast.Ident)
	if !ok {
		return "", nil, false
	}
	return key.Name, kv.Value, true
}

func (sp *scanPackage) applyKernelOptField(out *opts, key string, value ast.Expr, rel string) error {
	switch key {
	case "Name":
		name, ok := sp.string(value)
		if !ok {
			return sp.unresolved(value, rel, "metric name must be a compile-time string")
		}
		out.name = name
	case "Help":
		out.help, _ = sp.string(value)
	case "LabelNames":
		labels, err := sp.stringSlice(value, rel)
		if err != nil {
			return err
		}
		out.labels = labels
	case "Buckets":
		return sp.applyBucketField(out, value, rel)
	}
	return nil
}

func (sp *scanPackage) applyPrometheusOptField(out *opts, key string, value ast.Expr, rel string) error {
	switch key {
	case "Name":
		name, ok := sp.string(value)
		if !ok {
			return sp.unresolved(value, rel, "metric name must be a compile-time string")
		}
		out.name = name
	case "Namespace":
		namespace, ok := sp.string(value)
		if !ok {
			namespace, ok = sp.defaultedPrometheusNamespace(value)
			if !ok {
				return sp.unresolved(value, rel, "metric namespace must be a compile-time string")
			}
		}
		out.namespace = namespace
	case "Subsystem":
		subsystem, ok := sp.string(value)
		if !ok {
			return sp.unresolved(value, rel, "metric subsystem must be a compile-time string")
		}
		out.subsystem = subsystem
	case "Help":
		out.help, _ = sp.string(value)
	case "ConstLabels":
		labels, err := sp.constLabelNames(value, rel)
		if err != nil {
			return err
		}
		out.constLabels = labels
	case "Buckets":
		return sp.applyBucketField(out, value, rel)
	}
	return nil
}

func (sp *scanPackage) applyBucketField(out *opts, value ast.Expr, rel string) error {
	buckets, source, err := sp.numberSliceOrSource(value, rel)
	if err != nil {
		return err
	}
	out.buckets = buckets
	out.bucketSource = source
	return nil
}

func (sp *scanPackage) string(expr ast.Expr) (string, bool) {
	if tv, ok := sp.pkg.TypesInfo.Types[expr]; ok && tv.Value != nil && tv.Value.Kind() == constant.String {
		return constant.StringVal(tv.Value), true
	}
	obj := sp.objectForExpr(expr)
	if s, ok := stringConstObject(obj); ok {
		return s, true
	}
	if init := sp.inits[obj]; init != nil && init != expr {
		return sp.string(init)
	}
	return "", false
}

func (sp *scanPackage) defaultedPrometheusNamespace(expr ast.Expr) (string, bool) {
	sel, ok := expr.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Namespace" {
		return "", false
	}
	pkgPath, typ := namedTypePathAndName(sp.pkg.TypesInfo.TypeOf(sel.X))
	if pkgPath == adapterPromPkg && typ == "HookObserverConfig" {
		return "gocell", true
	}
	return "", false
}

func (sp *scanPackage) objectForExpr(expr ast.Expr) types.Object {
	switch e := expr.(type) {
	case *ast.Ident:
		if obj := sp.pkg.TypesInfo.Uses[e]; obj != nil {
			return obj
		}
		return sp.pkg.TypesInfo.Defs[e]
	case *ast.SelectorExpr:
		return sp.pkg.TypesInfo.Uses[e.Sel]
	}
	return nil
}

func stringConstObject(obj types.Object) (string, bool) {
	c, ok := obj.(*types.Const)
	if !ok || c.Val().Kind() != constant.String {
		return "", false
	}
	return constant.StringVal(c.Val()), true
}

func (sp *scanPackage) stringSlice(expr ast.Expr, rel string) ([]string, error) {
	if lit := sp.resolveCompositeLit(expr); lit != nil {
		out := make([]string, 0, len(lit.Elts))
		for _, elt := range lit.Elts {
			s, ok := sp.string(elt)
			if !ok {
				return nil, sp.unresolved(elt, rel, "label names must be compile-time strings")
			}
			out = append(out, s)
		}
		return uniquePreserveOrder(out), nil
	}
	return nil, sp.unresolved(expr, rel, "label names must be a resolvable string slice")
}

func (sp *scanPackage) numberSliceOrSource(expr ast.Expr, rel string) ([]string, string, error) {
	if lit := sp.resolveCompositeLit(expr); lit != nil {
		out := make([]string, 0, len(lit.Elts))
		for _, elt := range lit.Elts {
			s, ok := sp.number(elt)
			if !ok {
				return nil, "", sp.unresolved(elt, rel, "bucket values must be numeric constants")
			}
			out = append(out, s)
		}
		return out, "", nil
	}
	source := sp.bucketSource(expr)
	if source == "" {
		return nil, "", sp.unresolved(expr, rel, "bucket source is not representable")
	}
	return nil, source, nil
}

func (sp *scanPackage) bucketSource(expr ast.Expr) string {
	sel, ok := expr.(*ast.SelectorExpr)
	if !ok {
		return exprString(sp.fset, expr)
	}
	obj := sp.pkg.TypesInfo.Uses[sel.Sel]
	if obj == nil || obj.Pkg() == nil {
		return exprString(sp.fset, expr)
	}
	typ := namedTypeName(sp.pkg.TypesInfo.TypeOf(sel.X))
	if typ == "" {
		return obj.Pkg().Path() + "." + obj.Name()
	}
	return obj.Pkg().Path() + "." + typ + "." + obj.Name()
}

func namedTypeName(t types.Type) string {
	_, name := namedTypePathAndName(t)
	return name
}

func namedTypePathAndName(t types.Type) (string, string) {
	if ptr, ok := t.(*types.Pointer); ok {
		t = ptr.Elem()
	}
	named, ok := t.(*types.Named)
	if !ok || named.Obj() == nil || named.Obj().Pkg() == nil {
		return "", ""
	}
	return named.Obj().Pkg().Path(), named.Obj().Name()
}

func (sp *scanPackage) number(expr ast.Expr) (string, bool) {
	if bl, ok := expr.(*ast.BasicLit); ok && (bl.Kind == token.FLOAT || bl.Kind == token.INT) {
		return bl.Value, true
	}
	tv, ok := sp.pkg.TypesInfo.Types[expr]
	if !ok || tv.Value == nil {
		return "", false
	}
	switch tv.Value.Kind() {
	case constant.Int:
		return tv.Value.String(), true
	case constant.Float:
		f, exact := constant.Float64Val(tv.Value)
		if !exact {
			return tv.Value.String(), true
		}
		return strconv.FormatFloat(f, 'g', -1, 64), true
	}
	return "", false
}

func (sp *scanPackage) constLabelNames(expr ast.Expr, rel string) ([]string, error) {
	lit := sp.resolveCompositeLit(expr)
	if lit == nil {
		return nil, sp.unresolved(expr, rel, "const label names must be a resolvable map literal")
	}
	out := make([]string, 0, len(lit.Elts))
	for _, elt := range lit.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		key, ok := sp.string(kv.Key)
		if !ok {
			return nil, sp.unresolved(kv.Key, rel, "const label names must be compile-time strings")
		}
		out = append(out, key)
	}
	return sortedUnique(out), nil
}

func (sp *scanPackage) resolveCompositeLit(expr ast.Expr) *ast.CompositeLit {
	switch e := expr.(type) {
	case *ast.CompositeLit:
		return e
	case *ast.Ident:
		obj := sp.pkg.TypesInfo.Uses[e]
		if obj == nil {
			obj = sp.pkg.TypesInfo.Defs[e]
		}
		if init := sp.inits[obj]; init != nil && init != expr {
			return sp.resolveCompositeLit(init)
		}
	case *ast.SelectorExpr:
		if obj := sp.pkg.TypesInfo.Uses[e.Sel]; obj != nil {
			if init := sp.inits[obj]; init != nil && init != expr {
				return sp.resolveCompositeLit(init)
			}
		}
	}
	return nil
}

func (sp *scanPackage) unresolved(n ast.Node, rel, msg string) error {
	pos := sp.fset.Position(n.Pos())
	return fmt.Errorf("%w: %s:%d:%d: %s: %s",
		ErrUnresolvedMetricSchema, rel, pos.Line, pos.Column, msg, exprString(sp.fset, n))
}

func namedType(info *types.Info, expr ast.Expr) (string, string, bool) {
	t := info.TypeOf(expr)
	named, ok := t.(*types.Named)
	if !ok || named.Obj() == nil || named.Obj().Pkg() == nil {
		return "", "", false
	}
	return named.Obj().Pkg().Path(), named.Obj().Name(), true
}

func kernelMetricType(typ string) (string, bool) {
	switch typ {
	case "CounterOpts":
		return "counter", true
	case "HistogramOpts":
		return "histogram", true
	}
	return "", false
}

func prometheusOptsType(typ string) (string, bool) {
	switch typ {
	case "CounterOpts":
		return "counter", true
	case "HistogramOpts":
		return "histogram", true
	case "GaugeOpts":
		return "gauge", true
	case "SummaryOpts":
		return "summary", true
	}
	return "", false
}

func prometheusConstructor(info *types.Info, call *ast.CallExpr) (metricType string, vec bool, ok bool) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return "", false, false
	}
	fn, ok := info.Uses[sel.Sel].(*types.Func)
	if !ok || fn.Pkg() == nil || fn.Pkg().Path() != prometheusPkg {
		return "", false, false
	}
	switch fn.Name() {
	case "NewCounter", "NewCounterFunc":
		return "counter", false, true
	case "NewCounterVec":
		return "counter", true, true
	case "NewHistogram", "NewHistogramFunc":
		return "histogram", false, true
	case "NewHistogramVec":
		return "histogram", true, true
	case "NewGauge", "NewGaugeFunc":
		return "gauge", false, true
	case "NewGaugeVec":
		return "gauge", true, true
	case "NewSummary":
		return "summary", false, true
	case "NewSummaryVec":
		return "summary", true, true
	}
	return "", false, false
}

func mergeLabels(a, b []string) []string {
	out := append([]string(nil), a...)
	out = append(out, b...)
	return uniquePreserveOrder(out)
}

func sortedUnique(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	sort.Strings(in)
	out := in[:0]
	for _, s := range in {
		if len(out) == 0 || out[len(out)-1] != s {
			out = append(out, s)
		}
	}
	return append([]string(nil), out...)
}

func uniquePreserveOrder(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	seen := make(map[string]bool, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}

func promFQName(namespace, subsystem, name string) string {
	parts := make([]string, 0, 3)
	if namespace != "" {
		parts = append(parts, namespace)
	}
	if subsystem != "" {
		parts = append(parts, subsystem)
	}
	parts = append(parts, name)
	return strings.Join(parts, "_")
}

func exprString(fset *token.FileSet, n any) string {
	var b bytes.Buffer
	if err := format.Node(&b, fset, n); err != nil {
		return ""
	}
	return b.String()
}

// CheckOBS01 reports metric label values whose expression depends on
// errcode.Category or errcode.IsInfraError without a checked-in acknowledgement.
func CheckOBS01(projectRoot string, patterns ...string) ([]Diagnostic, error) {
	if len(patterns) == 0 {
		patterns = []string{"./..."}
	}
	pkgs, err := loadPackages(projectRoot, patterns...)
	if err != nil {
		return nil, err
	}
	acks, err := loadOBS01Acks(projectRoot)
	if err != nil {
		return nil, err
	}
	var diagnostics []Diagnostic
	for _, p := range pkgs {
		pkgDiagnostics, scanErr := scanOBS01Package(projectRoot, p, acks)
		if scanErr != nil {
			return nil, scanErr
		}
		diagnostics = append(diagnostics, pkgDiagnostics...)
	}
	sort.Slice(diagnostics, func(i, j int) bool {
		if diagnostics[i].File != diagnostics[j].File {
			return diagnostics[i].File < diagnostics[j].File
		}
		if diagnostics[i].Line != diagnostics[j].Line {
			return diagnostics[i].Line < diagnostics[j].Line
		}
		return diagnostics[i].Column < diagnostics[j].Column
	})
	return diagnostics, nil
}

type obs01SinkArg struct {
	Expr   ast.Expr
	Metric string
	Label  string
}

type obs01SinkBinding struct {
	Metric string
	Label  string
}

func scanOBS01Package(root string, p *packages.Package, acks map[string]obsAck) ([]Diagnostic, error) {
	var diagnostics []Diagnostic
	sinkParams := collectOBS01SinkParams(p)
	for _, file := range p.Syntax {
		path := p.Fset.Position(file.Pos()).Filename
		if !isProjectGoFile(root, path) {
			continue
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return nil, err
		}
		fileDiagnostics := scanOBS01File(p, file, filepath.ToSlash(rel), acks, sinkParams)
		diagnostics = append(diagnostics, fileDiagnostics...)
	}
	return diagnostics, nil
}

func scanOBS01File(
	p *packages.Package,
	file *ast.File,
	rel string,
	acks map[string]obsAck,
	sinkParams map[*types.Func]map[int][]obs01SinkBinding,
) []Diagnostic {
	var diagnostics []Diagnostic
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Body == nil {
			continue
		}
		diagnostics = append(diagnostics, scanOBS01Func(p, fn, rel, acks, sinkParams)...)
	}
	return diagnostics
}

func scanOBS01Func(
	p *packages.Package,
	fn *ast.FuncDecl,
	rel string,
	acks map[string]obsAck,
	sinkParams map[*types.Func]map[int][]obs01SinkBinding,
) []Diagnostic {
	var diagnostics []Diagnostic
	tainted := map[types.Object]bool{}
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.AssignStmt:
			markOBS01AssignedTaint(p.TypesInfo, node.Lhs, node.Rhs, tainted)
		case *ast.ValueSpec:
			markOBS01ValueSpecTaint(p.TypesInfo, node, tainted)
		case *ast.CallExpr:
			diagnostics = append(diagnostics, obs01DiagnosticsForCall(p, node, rel, acks, tainted, sinkParams)...)
		}
		return true
	})
	return diagnostics
}

func obs01DiagnosticsForCall(
	p *packages.Package,
	call *ast.CallExpr,
	rel string,
	acks map[string]obsAck,
	tainted map[types.Object]bool,
	sinkParams map[*types.Func]map[int][]obs01SinkBinding,
) []Diagnostic {
	var diagnostics []Diagnostic
	for _, sink := range metricLabelBindingArgs(p.TypesInfo, p.Fset, call) {
		if exprDependsOnErrcodeClassifier(p.TypesInfo, sink.Expr, tainted) {
			diagnostics = appendOBS01DiagnosticIfUnacked(diagnostics, p, sink, rel, acks)
		}
	}
	for _, sink := range obs01SinkArgs(p.TypesInfo, call, sinkParams) {
		if exprDependsOnErrcodeClassifier(p.TypesInfo, sink.Expr, tainted) {
			diagnostics = appendOBS01DiagnosticIfUnacked(diagnostics, p, sink, rel, acks)
		}
	}
	return diagnostics
}

func appendOBS01DiagnosticIfUnacked(
	out []Diagnostic,
	p *packages.Package,
	sink obs01SinkArg,
	rel string,
	acks map[string]obsAck,
) []Diagnostic {
	pos := p.Fset.Position(sink.Expr.Pos())
	fingerprint := obs01Fingerprint(rel, pos.Line, pos.Column, sink.Metric, sink.Label, exprString(p.Fset, sink.Expr))
	if ack, ok := acks[fingerprint]; ok && ack.matches(sink) {
		return out
	}
	return append(out, obs01Diagnostic(p, sink, rel, fingerprint))
}

func obs01Diagnostic(p *packages.Package, sink obs01SinkArg, rel, fingerprint string) Diagnostic {
	pos := p.Fset.Position(sink.Expr.Pos())
	return Diagnostic{
		Rule:        "OBS-01",
		File:        rel,
		Line:        pos.Line,
		Column:      pos.Column,
		Metric:      sink.Metric,
		Label:       sink.Label,
		Fingerprint: fingerprint,
		Message: fmt.Sprintf("metric label value depends on errcode.Category or errcode.IsInfraError (metric=%q label=%q fingerprint=%s); "+
			"add a checked-in docs/observability/metrics-migration-acks.yaml entry with this fingerprint after documenting the dashboard/alert migration",
			sink.Metric, sink.Label, fingerprint),
	}
}

func metricLabelBindingArgs(info *types.Info, fset *token.FileSet, call *ast.CallExpr) []obs01SinkArg {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return nil
	}
	metric := obs01MetricSinkName(info, fset, sel.X)
	if sel.Sel.Name == "WithLabelValues" {
		out := make([]obs01SinkArg, 0, len(call.Args))
		for i, arg := range call.Args {
			out = append(out, obs01SinkArg{
				Expr:   arg,
				Metric: metric,
				Label:  fmt.Sprintf("arg%d", i+1),
			})
		}
		return out
	}
	if sel.Sel.Name != "With" || len(call.Args) != 1 {
		return nil
	}
	pkgPath, typ, ok := namedType(info, call.Args[0])
	if !ok || typ != "Labels" || (pkgPath != kernelMetricsPkg && pkgPath != prometheusPkg) {
		return nil
	}
	return obs01LabelsArgs(info, fset, metric, call.Args[0])
}

func obs01LabelsArgs(info *types.Info, fset *token.FileSet, metric string, expr ast.Expr) []obs01SinkArg {
	lit, ok := expr.(*ast.CompositeLit)
	if !ok {
		return []obs01SinkArg{{
			Expr:   expr,
			Metric: metric,
			Label:  "<labels>",
		}}
	}
	out := make([]obs01SinkArg, 0, len(lit.Elts))
	for _, elt := range lit.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		out = append(out, obs01SinkArg{
			Expr:   kv.Value,
			Metric: metric,
			Label:  obs01LabelKey(info, fset, kv.Key),
		})
	}
	if len(out) == 0 {
		return []obs01SinkArg{{
			Expr:   expr,
			Metric: metric,
			Label:  "<labels>",
		}}
	}
	return out
}

func obs01MetricSinkName(info *types.Info, fset *token.FileSet, expr ast.Expr) string {
	if obj := objectForOBS01Expr(info, expr); obj != nil {
		return obj.Name()
	}
	if s := exprString(fset, expr); s != "" {
		return s
	}
	return "<metric>"
}

func obs01LabelKey(info *types.Info, fset *token.FileSet, expr ast.Expr) string {
	if s, ok := obs01ConstantString(info, expr); ok {
		return s
	}
	if s := exprString(fset, expr); s != "" {
		return s
	}
	return "<label>"
}

func obs01ConstantString(info *types.Info, expr ast.Expr) (string, bool) {
	if tv, ok := info.Types[expr]; ok && tv.Value != nil && tv.Value.Kind() == constant.String {
		return constant.StringVal(tv.Value), true
	}
	if s, ok := stringConstObject(objectForOBS01Expr(info, expr)); ok {
		return s, true
	}
	return "", false
}

func collectOBS01SinkParams(p *packages.Package) map[*types.Func]map[int][]obs01SinkBinding {
	out := map[*types.Func]map[int][]obs01SinkBinding{}
	for _, file := range p.Syntax {
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}
			collectOBS01SinkParamsForFunc(p.TypesInfo, p.Fset, fn, out)
		}
	}
	return out
}

func collectOBS01SinkParamsForFunc(
	info *types.Info,
	fset *token.FileSet,
	fn *ast.FuncDecl,
	out map[*types.Func]map[int][]obs01SinkBinding,
) {
	if fn.Body == nil {
		return
	}
	obj, ok := info.Defs[fn.Name].(*types.Func)
	if !ok {
		return
	}
	params := functionParamIndexes(info, fn.Type)
	if len(params) == 0 {
		return
	}
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		recordOBS01SinkParamDeps(info, fset, out, obj, call, params)
		return true
	})
}

func recordOBS01SinkParamDeps(
	info *types.Info,
	fset *token.FileSet,
	out map[*types.Func]map[int][]obs01SinkBinding,
	fn *types.Func,
	call *ast.CallExpr,
	params map[types.Object]int,
) {
	for _, sink := range metricLabelBindingArgs(info, fset, call) {
		for idx := range obs01ParamDeps(info, sink.Expr, params) {
			recordOBS01SinkBinding(out, fn, idx, obs01SinkBinding{
				Metric: sink.Metric,
				Label:  sink.Label,
			})
		}
	}
}

func recordOBS01SinkBinding(
	out map[*types.Func]map[int][]obs01SinkBinding,
	fn *types.Func,
	idx int,
	binding obs01SinkBinding,
) {
	if out[fn] == nil {
		out[fn] = map[int][]obs01SinkBinding{}
	}
	for _, existing := range out[fn][idx] {
		if existing == binding {
			return
		}
	}
	out[fn][idx] = append(out[fn][idx], binding)
}

func functionParamIndexes(info *types.Info, typ *ast.FuncType) map[types.Object]int {
	out := map[types.Object]int{}
	if typ.Params == nil {
		return out
	}
	idx := 0
	for _, field := range typ.Params.List {
		for _, name := range field.Names {
			if obj := info.Defs[name]; obj != nil {
				out[obj] = idx
			}
			idx++
		}
		if len(field.Names) == 0 {
			idx++
		}
	}
	return out
}

func functionParamSet(info *types.Info, typ *ast.FuncType) map[types.Object]bool {
	out := map[types.Object]bool{}
	if typ.Params == nil {
		return out
	}
	for _, field := range typ.Params.List {
		for _, name := range field.Names {
			if obj := info.Defs[name]; obj != nil {
				out[obj] = true
			}
		}
	}
	return out
}

func obs01ParamDeps(info *types.Info, expr ast.Expr, params map[types.Object]int) map[int]bool {
	out := map[int]bool{}
	ast.Inspect(expr, func(n ast.Node) bool {
		id, ok := n.(*ast.Ident)
		if !ok {
			return true
		}
		if idx, ok := params[objectForOBS01Expr(info, id)]; ok {
			out[idx] = true
		}
		return true
	})
	return out
}

func obs01SinkArgs(
	info *types.Info,
	call *ast.CallExpr,
	sinkParams map[*types.Func]map[int][]obs01SinkBinding,
) []obs01SinkArg {
	fn := calledFunc(info, call)
	if fn == nil || len(sinkParams[fn]) == 0 {
		return nil
	}
	indexes := make([]int, 0, len(sinkParams[fn]))
	for idx := range sinkParams[fn] {
		indexes = append(indexes, idx)
	}
	sort.Ints(indexes)
	var out []obs01SinkArg
	for _, idx := range indexes {
		if idx < len(call.Args) {
			for _, binding := range sinkParams[fn][idx] {
				out = append(out, obs01SinkArg{
					Expr:   call.Args[idx],
					Metric: binding.Metric,
					Label:  binding.Label,
				})
			}
		}
	}
	return out
}

func calledFunc(info *types.Info, call *ast.CallExpr) *types.Func {
	switch fun := call.Fun.(type) {
	case *ast.Ident:
		fn, _ := info.Uses[fun].(*types.Func)
		return fn
	case *ast.SelectorExpr:
		fn, _ := info.Uses[fun.Sel].(*types.Func)
		return fn
	}
	return nil
}

func markOBS01AssignedTaint(info *types.Info, lhs, rhs []ast.Expr, tainted map[types.Object]bool) {
	for i, left := range lhs {
		if i >= len(rhs) || !exprDependsOnErrcodeClassifier(info, rhs[i], tainted) {
			continue
		}
		if obj := objectForOBS01Expr(info, left); obj != nil {
			tainted[obj] = true
		}
	}
}

func markOBS01ValueSpecTaint(info *types.Info, spec *ast.ValueSpec, tainted map[types.Object]bool) {
	for i, name := range spec.Names {
		if i >= len(spec.Values) || !exprDependsOnErrcodeClassifier(info, spec.Values[i], tainted) {
			continue
		}
		if obj := info.Defs[name]; obj != nil {
			tainted[obj] = true
		}
	}
}

func exprDependsOnErrcodeClassifier(info *types.Info, expr ast.Expr, tainted map[types.Object]bool) bool {
	found := false
	ast.Inspect(expr, func(n ast.Node) bool {
		if found {
			return false
		}
		if id, ok := n.(*ast.Ident); ok {
			if tainted[objectForOBS01Expr(info, id)] {
				found = true
				return false
			}
			return true
		}
		if sel, ok := n.(*ast.SelectorExpr); ok && isErrcodeCategorySelector(info, sel) {
			found = true
			return false
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		if isErrcodeClassifierCall(info, call) {
			found = true
			return false
		}
		return true
	})
	return found
}

func objectForOBS01Expr(info *types.Info, expr ast.Expr) types.Object {
	switch e := expr.(type) {
	case *ast.Ident:
		if obj := info.Uses[e]; obj != nil {
			return obj
		}
		return info.Defs[e]
	case *ast.SelectorExpr:
		return info.Uses[e.Sel]
	}
	return nil
}

func isErrcodeClassifierCall(info *types.Info, call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	fn, ok := info.Uses[sel.Sel].(*types.Func)
	if !ok || fn.Pkg() == nil || fn.Pkg().Path() != errcodePkg {
		return false
	}
	return fn.Name() == "Category" || fn.Name() == "IsInfraError"
}

func isErrcodeCategorySelector(info *types.Info, sel *ast.SelectorExpr) bool {
	obj := info.Uses[sel.Sel]
	if obj == nil || obj.Pkg() == nil || obj.Pkg().Path() != errcodePkg {
		return false
	}
	return obj.Name() == "Category" || strings.HasPrefix(obj.Name(), "Category")
}

type obsAckFile struct {
	Acknowledgements []obsAck `yaml:"acknowledgements"`
}

type obsAck struct {
	Rule                 string   `yaml:"rule"`
	Fingerprint          string   `yaml:"fingerprint"`
	Metric               string   `yaml:"metric"`
	Label                string   `yaml:"label"`
	OldSemantics         string   `yaml:"oldSemantics"`
	NewSemantics         string   `yaml:"newSemantics"`
	DashboardOrAlertRefs []string `yaml:"dashboardOrAlertRefs"`
	Owner                string   `yaml:"owner"`
	ReviewedAt           string   `yaml:"reviewedAt"`
	Rationale            string   `yaml:"rationale"`
}

func loadOBS01Acks(root string) (map[string]obsAck, error) {
	path := filepath.Join(root, "docs", "observability", "metrics-migration-acks.yaml")
	out := map[string]obsAck{}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return out, nil
	}
	if err != nil {
		return nil, err
	}
	var file obsAckFile
	dec := yaml.NewDecoder(bytes.NewReader(data))
	dec.KnownFields(true)
	if err := dec.Decode(&file); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	for i, ack := range file.Acknowledgements {
		if ack.Rule != "OBS-01" {
			return nil, fmt.Errorf("%s: acknowledgement %d has unsupported rule %q", path, i+1, ack.Rule)
		}
		if err := ack.validate(path, i+1); err != nil {
			return nil, err
		}
		if _, exists := out[ack.Fingerprint]; exists {
			return nil, fmt.Errorf("%s: OBS-01 acknowledgement %d duplicates fingerprint %q", path, i+1, ack.Fingerprint)
		}
		out[ack.Fingerprint] = ack
	}
	return out, nil
}

func (ack obsAck) validate(path string, idx int) error {
	required := map[string]string{
		"fingerprint":  ack.Fingerprint,
		"metric":       ack.Metric,
		"label":        ack.Label,
		"oldSemantics": ack.OldSemantics,
		"newSemantics": ack.NewSemantics,
		"owner":        ack.Owner,
		"reviewedAt":   ack.ReviewedAt,
		"rationale":    ack.Rationale,
	}
	for field, value := range required {
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("%s: OBS-01 acknowledgement %d missing %s", path, idx, field)
		}
	}
	if len(ack.DashboardOrAlertRefs) == 0 {
		return fmt.Errorf("%s: OBS-01 acknowledgement %d missing dashboardOrAlertRefs", path, idx)
	}
	if strings.TrimSpace(ack.OldSemantics) == strings.TrimSpace(ack.NewSemantics) {
		return fmt.Errorf("%s: OBS-01 acknowledgement %d oldSemantics and newSemantics must differ", path, idx)
	}
	if _, err := time.Parse("2006-01-02", ack.ReviewedAt); err != nil {
		return fmt.Errorf("%s: OBS-01 acknowledgement %d reviewedAt must be YYYY-MM-DD: %w", path, idx, err)
	}
	for i, ref := range ack.DashboardOrAlertRefs {
		if strings.TrimSpace(ref) == "" {
			return fmt.Errorf("%s: OBS-01 acknowledgement %d has empty dashboardOrAlertRefs[%d]", path, idx, i)
		}
	}
	return nil
}

func (ack obsAck) matches(sink obs01SinkArg) bool {
	return ack.Metric == sink.Metric && ack.Label == sink.Label
}

func obs01Fingerprint(file string, line, column int, metric, label, expr string) string {
	sum := sha256.Sum256([]byte(fmt.Sprintf("%s\x00%d\x00%d\x00%s\x00%s\x00%s",
		file, line, column, metric, label, expr)))
	return hex.EncodeToString(sum[:])
}
