// Package outbox provides the runtime-layer Store interface and relay worker
// for transactional outbox delivery. SQL dialect is intentionally not part of
// this package's surface — adapter packages implement Store against concrete
// backends.
package outbox

import (
	"context"
	"time"

	kout "github.com/ghbvf/gocell/kernel/outbox"
)

// ClaimedEntry extends kernel/outbox.Entry with the Attempts counter that is
// relay-runtime state (not a domain concept) and the LeaseID fencing token
// that the calling worker must echo to MarkPublished / MarkRetry / MarkDead.
//
// LeaseID is a UUID generated by ClaimPending; it is the only authority over
// who owns a claiming row. After a stale-claim ReclaimStale, a worker holding
// the previous LeaseID will fail every CAS — its publish/fail completion
// becomes a no-op rather than overwriting the new owner's outcome.
type ClaimedEntry struct {
	kout.Entry
	Attempts int
	LeaseID  string
}

// Store is the contract between the relay worker and its backing storage.
// Implementations MUST be SQL-dialect-neutral at the interface boundary
// (no *sql.DB / *pgx.Tx in method signatures). Each method opens its own
// short transaction; methods do not compose into a larger transaction.
type Store interface {
	// ClaimPending atomically transitions up to batchSize rows from pending
	// to claiming status, skipping rows locked by other relay instances.
	// Each entry returned carries the LeaseID generated for this claim batch;
	// callers MUST echo LeaseID back through Mark* CAS to retain ownership.
	// Returns an empty slice + nil error when there is nothing to claim.
	ClaimPending(ctx context.Context, batchSize int) ([]ClaimedEntry, error)

	// MarkPublished optimistically transitions an entry from claiming to
	// published. The leaseID must match the value returned from ClaimPending;
	// updated=false means the lease was lost (entry reclaimed by ReclaimStale
	// or claimed by another worker) — not an error.
	MarkPublished(ctx context.Context, id, leaseID string) (updated bool, err error)

	// MarkRetry transitions a failing entry back to pending with attempts
	// incremented and the supplied nextRetryAt. Relay is responsible for
	// computing nextRetryAt (Go-side backoff). updated=false same as above.
	MarkRetry(ctx context.Context, id, leaseID string, attempts int, nextRetryAt time.Time, lastError string) (updated bool, err error)

	// MarkDead transitions a failing entry to dead (exceeded max attempts).
	// updated=false same as above.
	MarkDead(ctx context.Context, id, leaseID string, attempts int, lastError string) (updated bool, err error)

	// ReclaimStale transitions up to batchSize claiming rows whose claimed_at
	// is older than claimTTL back to pending (with attempts+1 and
	// next_retry_at = backoff) or to dead (when attempts+1 >= maxAttempts).
	// Returns count of rows recovered across both destinations. Callers MUST
	// loop until count < batchSize so a queue larger than one sweep drains
	// promptly without producing a multi-second UPDATE that blocks
	// VACUUM/replication.
	ReclaimStale(
		ctx context.Context,
		claimTTL time.Duration,
		maxAttempts int,
		baseDelay, maxDelay time.Duration,
		batchSize int,
	) (count int, err error)

	// CleanupPublished deletes a batch of published rows older than cutoff.
	// Caller is responsible for looping until deleted < batchSize.
	CleanupPublished(ctx context.Context, cutoff time.Time, batchSize int) (deleted int, err error)

	// CleanupDead deletes a batch of dead rows older than cutoff.
	CleanupDead(ctx context.Context, cutoff time.Time, batchSize int) (deleted int, err error)

	// CountPending returns the number of pending entries eligible for ClaimPending:
	// status=pending AND (next_retry_at IS NULL OR next_retry_at <= now()).
	// Rows that are pending but still in backoff (next_retry_at > now()) are
	// intentionally excluded so the count reflects actual work available to relay
	// workers — consistent with the ClaimPending eligibility predicate.
	//
	// May be approximate under high concurrency — multiple concurrent ClaimPending
	// calls can race between the COUNT and the next claim. Callers should treat
	// any error as transient and skip the metric update without panicking.
	//
	// ref: Eventuate transactional-outbox events_pending;
	// Debezium MilliSecondsBehindSource — non-blocking depth probe on reclaim cadence.
	CountPending(ctx context.Context) (int64, error)

	// OldestEligibleAt returns the oldest published_at (when status="published")
	// or dead_at (when status="dead") in the table. The relay uses this to schedule
	// data-driven cleanup wake-ups: sleep until oldest+retention instead of polling
	// on a fixed interval. Returns ok=false when no rows of the given status exist.
	//
	// status MUST be either "published" or "dead". Implementations should reject
	// other values to keep the contract narrow.
	OldestEligibleAt(ctx context.Context, status string) (at time.Time, ok bool, err error)
}
