// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/registry/contract/submit/v1/contract.yaml

/** http.registry.contract.submit.v1.request */
export interface Request {
  id: string;
  kind: RequestKind;
  payloadSchema?: string;
}

/** RequestKind enumerates the closed value-set for the kind field. */
export type RequestKind = 'http' | 'event' | 'command' | 'projection' | 'saga' | 'webhook' | 'grpc';

/** http.registry.contract.submit.v1.response */
export interface Response {
  data: ResponseData;
}

export interface ResponseData {
  id: string;
  kind: string;
  state: string;
  submitter: string;
  payloadSchema?: string;
  createdAt: string;
  updatedAt: string;
}
