package contractgen

import (
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/ghbvf/gocell/framework/kernel/metadata"
)

// TestTSGoType verifies the Go→TS type mapping table for all structural cases
// in tsGoType (pure function). This is the primary unit test for the type
// derivation logic before any template rendering happens.
func TestTSGoType(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		f    DTOField
		want string
	}{
		// scalar primitives
		{name: "string", f: DTOField{GoType: "string", BareJSONTag: "name"}, want: "string"},
		{name: "int64", f: DTOField{GoType: "int64", BareJSONTag: "count"}, want: "number"},
		{name: "float64", f: DTOField{GoType: "float64", BareJSONTag: "ratio"}, want: "number"},
		{name: "bool", f: DTOField{GoType: "bool", BareJSONTag: "active"}, want: "boolean"},
		{name: "ptr bool", f: DTOField{GoType: "*bool", BareJSONTag: "active"}, want: "boolean"},
		{name: "nullable string", f: DTOField{GoType: "*string", BareJSONTag: "occurredAt", Nullable: true}, want: "string | null"},
		{name: "nullable int64", f: DTOField{GoType: "*int64", BareJSONTag: "count", Nullable: true}, want: "number | null"},
		{name: "nullable enum", f: DTOField{GoType: "*PayloadOutcome", BareJSONTag: "outcome", Nullable: true}, want: "PayloadOutcome | null"},
		// object (pointer, non-list)
		{name: "object ptr", f: DTOField{GoType: "*ResponseData", ItemDTO: "ResponseData", IsList: false}, want: "ResponseData"},
		// object array
		{
			name: "object array",
			f:    DTOField{GoType: "[]*ResponseDataCellsItem", ItemDTO: "ResponseDataCellsItem", IsList: true},
			want: "ResponseDataCellsItem[]",
		},
		// scalar arrays
		{name: "string array", f: DTOField{GoType: "[]string", BareJSONTag: "tags"}, want: "string[]"},
		{name: "int64 array", f: DTOField{GoType: "[]int64", BareJSONTag: "ids"}, want: "number[]"},
		{name: "float64 array", f: DTOField{GoType: "[]float64", BareJSONTag: "vals"}, want: "number[]"},
		// any
		{name: "any", f: DTOField{GoType: "any", BareJSONTag: "meta"}, want: "unknown"},
		{name: "any array", f: DTOField{GoType: "[]any", BareJSONTag: "items"}, want: "unknown[]"},
		// enum: GoType == enum TypeName, handled by context; fallback to type name
		{name: "enum type", f: DTOField{GoType: "PayloadOutcome", BareJSONTag: "outcome"}, want: "PayloadOutcome"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := tsGoType(tc.f)
			if got != tc.want {
				t.Errorf("tsGoType(%+v) = %q, want %q", tc.f, got, tc.want)
			}
		})
	}
}

// TestRenderTS_BasicInterface verifies that renderTS produces a valid TS file
// with export interface for a minimal spec (single DTO, required + optional fields).
func TestRenderTS_BasicInterface(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "ping",
		ContractID:  "http.order.ping.v1",
		Kind:        "http",
		SourceFile:  "contracts/http/order/ping/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Response",
				Doc:  "ping response",
				Fields: []DTOField{
					{Name: "Message", BareJSONTag: "message", GoType: "string", Required: true},
					{Name: "Count", BareJSONTag: "count", GoType: "int64", Required: false},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)

	// Must have generated header
	if !strings.HasPrefix(out, "// Code generated by gocell generate") {
		t.Errorf("missing generated header prefix; got:\n%s", out[:min(200, len(out))])
	}
	// Must export interface
	if !strings.Contains(out, "export interface Response") {
		t.Errorf("missing 'export interface Response'; got:\n%s", out)
	}
	// required field: no '?'
	if !strings.Contains(out, "message: string;") {
		t.Errorf("missing required field 'message: string;'; got:\n%s", out)
	}
	// optional field: has '?'
	if !strings.Contains(out, "count?: number;") {
		t.Errorf("missing optional field 'count?: number;'; got:\n%s", out)
	}
}

func TestRenderTS_NullableScalar(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "auditlist",
		ContractID:  "http.audit.list.v1",
		Kind:        "http",
		SourceFile:  "contracts/http/audit/list/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Response",
				Fields: []DTOField{
					{Name: "OccurredAt", BareJSONTag: "occurredAt", GoType: "*string", Required: true, Nullable: true},
					{Name: "Count", BareJSONTag: "count", GoType: "*int64", Required: false, Nullable: true},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)
	if !strings.Contains(out, "occurredAt: string | null;") {
		t.Errorf("missing required nullable field 'occurredAt: string | null;'; got:\n%s", out)
	}
	if !strings.Contains(out, "count?: number | null;") {
		t.Errorf("missing optional nullable field 'count?: number | null;'; got:\n%s", out)
	}
}

// TestRenderTS_EnumUnion verifies that renderTS emits a TS union type for each
// EnumSpec, e.g. `export type PayloadOutcome = 'succeeded' | 'rejected';`.
func TestRenderTS_EnumUnion(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "widgetresolved",
		ContractID:  "event.widget-resolved.v1",
		Kind:        "event",
		SourceFile:  "contracts/event/widget-resolved/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Payload",
				Fields: []DTOField{
					{Name: "Outcome", BareJSONTag: "outcome", GoType: "PayloadOutcome", Required: true},
				},
				Enums: []EnumSpec{
					{
						TypeName:  "PayloadOutcome",
						FieldName: "outcome",
						Values: []EnumValue{
							{ConstName: "PayloadOutcomeSucceeded", Value: "succeeded"},
							{ConstName: "PayloadOutcomeRejected", Value: "rejected"},
						},
					},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)

	// Must have the union type
	if !strings.Contains(out, "export type PayloadOutcome =") {
		t.Errorf("missing enum union type 'export type PayloadOutcome ='; got:\n%s", out)
	}
	if !strings.Contains(out, "'succeeded'") {
		t.Errorf("missing enum value 'succeeded'; got:\n%s", out)
	}
	if !strings.Contains(out, "'rejected'") {
		t.Errorf("missing enum value 'rejected'; got:\n%s", out)
	}
	// The Payload interface should reference the enum type
	if !strings.Contains(out, "export interface Payload") {
		t.Errorf("missing 'export interface Payload'; got:\n%s", out)
	}
	// outcome field uses the enum type, not a raw string
	if !strings.Contains(out, "outcome: PayloadOutcome") {
		t.Errorf("expected 'outcome: PayloadOutcome' in interface; got:\n%s", out)
	}
}

// TestRenderTS_ObjectField verifies that object fields (ItemDTO != "") render
// as the referenced DTO name, not as a raw string or any.
func TestRenderTS_ObjectField(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "details",
		ContractID:  "http.item.details.v1",
		Kind:        "http",
		SourceFile:  "contracts/http/item/details/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Response",
				Fields: []DTOField{
					{Name: "Data", BareJSONTag: "data", GoType: "*ResponseData", ItemDTO: "ResponseData", IsList: false, Required: false},
				},
			},
			{
				Name: "ResponseData",
				Fields: []DTOField{
					{Name: "ID", BareJSONTag: "id", GoType: "string", Required: true},
					{Name: "Name", BareJSONTag: "name", GoType: "string", Required: false},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)

	if !strings.Contains(out, "export interface Response") {
		t.Errorf("missing 'export interface Response'; got:\n%s", out)
	}
	if !strings.Contains(out, "data?: ResponseData;") {
		t.Errorf("missing 'data?: ResponseData;'; got:\n%s", out)
	}
	if !strings.Contains(out, "export interface ResponseData") {
		t.Errorf("missing 'export interface ResponseData'; got:\n%s", out)
	}
}

// TestRenderTS_ArrayField verifies array-of-object fields render as X[].
func TestRenderTS_ArrayField(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "list",
		ContractID:  "http.order.list.v1",
		Kind:        "http",
		SourceFile:  "contracts/http/order/list/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Response",
				Fields: []DTOField{
					{Name: "Data", BareJSONTag: "data", GoType: "[]*ResponseDataItem", ItemDTO: "ResponseDataItem", IsList: true, Required: false},
				},
			},
			{
				Name: "ResponseDataItem",
				Fields: []DTOField{
					{Name: "ID", BareJSONTag: "id", GoType: "string", Required: true},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)

	if !strings.Contains(out, "data?: ResponseDataItem[];") {
		t.Errorf("missing 'data?: ResponseDataItem[];'; got:\n%s", out)
	}
}

// TestTSPkgAlias verifies that tsPkgAlias correctly derives camelCase namespace
// aliases from generated package paths, including proper handling of hyphens as
// word boundaries.
func TestTSPkgAlias(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name  string
		input string
		want  string
	}{
		{
			name:  "no hyphen – generated/ prefix",
			input: "generated/contracts/http/order/create/v1",
			want:  "httpOrderCreateV1",
		},
		{
			name:  "no hyphen – generated-ts/ prefix",
			input: "generated-ts/contracts/http/order/create/v1",
			want:  "httpOrderCreateV1",
		},
		{
			name:  "single hyphen segment",
			input: "generated-ts/contracts/event/auth/bootstrap-failed/v1",
			want:  "eventAuthBootstrapFailedV1",
		},
		{
			name:  "multi-hyphen segment",
			input: "generated/contracts/event/devicecert-rotation-resolved/v1",
			want:  "eventDevicecertRotationResolvedV1",
		},
		{
			name:  "generated-ts prefix stripped (not treated as path segment hyphens)",
			input: "generated-ts/contracts/event/order-created/v1",
			want:  "eventOrderCreatedV1",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := tsPkgAlias(tc.input)
			if got != tc.want {
				t.Errorf("tsPkgAlias(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

// TestTSGoType_ExtraScalars supplements the main TestTSGoType with scalar types
// that the base table doesn't cover: int32, uint32, uint64 → number; *string →
// string; *int64 → number.
func TestTSGoType_ExtraScalars(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		f    DTOField
		want string
	}{
		{name: "int32", f: DTOField{GoType: "int32", BareJSONTag: "x"}, want: "number"},
		{name: "uint32", f: DTOField{GoType: "uint32", BareJSONTag: "x"}, want: "number"},
		{name: "uint64", f: DTOField{GoType: "uint64", BareJSONTag: "x"}, want: "number"},
		{name: "ptr string", f: DTOField{GoType: "*string", BareJSONTag: "x"}, want: "string"},
		{name: "ptr int64", f: DTOField{GoType: "*int64", BareJSONTag: "x"}, want: "number"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := tsGoType(tc.f)
			if got != tc.want {
				t.Errorf("tsGoType(%+v) = %q, want %q", tc.f, got, tc.want)
			}
		})
	}
}

// TestTSQuote verifies that tsQuote correctly escapes special characters in TS
// single-quoted string literals.
func TestTSQuote(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name  string
		input string
		want  string
	}{
		{name: "plain value", input: "succeeded", want: "'succeeded'"},
		{name: "value with single quote", input: "it's", want: `'it\'s'`},
		{name: "value with backslash", input: `a\b`, want: `'a\\b'`},
		{name: "value with both", input: `a'b\c`, want: `'a\'b\\c'`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := tsQuote(tc.input)
			if got != tc.want {
				t.Errorf("tsQuote(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

// TestBuildTSView_HeaderSkip verifies that fields with JSONTag "-" (header-only)
// are excluded from the TS interface output.
func TestBuildTSView_HeaderSkip(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "testevent",
		ContractID:  "event.test.v1",
		Kind:        "event",
		SourceFile:  "contracts/event/test/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Headers",
				Fields: []DTOField{
					{Name: "XTenantID", JSONTag: "-", GoType: "string"},
					{Name: "Visible", BareJSONTag: "visible", GoType: "string", Required: true},
				},
			},
		},
	}

	views := buildTSView(spec)
	if len(views) != 1 {
		t.Fatalf("expected 1 view, got %d", len(views))
	}
	fields := views[0].Fields
	for _, f := range fields {
		if f.Key == "-" || f.Key == "XTenantID" {
			t.Errorf("header-only field should be excluded from TS view, but got key %q", f.Key)
		}
	}
	// The visible field should be present.
	found := false
	for _, f := range fields {
		if f.Key == "visible" {
			found = true
		}
	}
	if !found {
		t.Error("expected 'visible' field in TS view, but not found")
	}
}

// TestRenderTS_HeaderSkip verifies that renderTS omits header-only fields
// (JSONTag="-") from the generated TS interface.
func TestRenderTS_HeaderSkip(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "testevent",
		ContractID:  "event.test.v1",
		Kind:        "event",
		SourceFile:  "contracts/event/test/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Headers",
				Fields: []DTOField{
					{Name: "XTenantID", JSONTag: "-", GoType: "string"},
					{Name: "Visible", BareJSONTag: "visible", GoType: "string", Required: true},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)

	if strings.Contains(out, "XTenantID") {
		t.Errorf("header-only field XTenantID must not appear in TS output; got:\n%s", out)
	}
	if !strings.Contains(out, "visible: string;") {
		t.Errorf("expected 'visible: string;' in TS output; got:\n%s", out)
	}
}

// TestRenderTSBarrel_NilProject verifies RenderTSBarrel returns an error for nil project.
func TestRenderTSBarrel_NilProject(t *testing.T) {
	t.Parallel()
	_, ok, err := RenderTSBarrel("/tmp/root", nil)
	if err == nil {
		t.Fatal("expected error for nil project, got nil")
	}
	if ok {
		t.Error("expected ok=false for nil project")
	}
}

// TestRenderTSBarrel_NoTSContracts verifies RenderTSBarrel returns ok=false when
// no contracts emit TS (all webhook or grpc).
func TestRenderTSBarrel_NoTSContracts(t *testing.T) {
	t.Parallel()
	p := &metadata.ProjectMeta{
		Contracts: map[string]*metadata.ContractMeta{
			"webhook.order.notify.v1": {
				ID:         "webhook.order.notify.v1",
				Kind:       "webhook",
				Codegen:    true,
				Transports: []string{"http"}, // required by buildContractSpec FMT-39 guard
			},
		},
	}
	root := findRepoRoot()
	_, ok, err := RenderTSBarrel(root, p)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if ok {
		t.Error("expected ok=false when no contracts emit TS")
	}
}

// TestRenderTSBarrel_MultiContract verifies RenderTSBarrel produces a barrel with
// correctly sorted aliases and correct import paths when there are multiple TS-emitting contracts.
func TestRenderTSBarrel_MultiContract(t *testing.T) {
	t.Parallel()
	// Use the synth_http_minimal fixture root so buildContractSpec can resolve schema files.
	testDir := filepath.Join("testdata", "synth", "synth_http_minimal")
	absTestDir, err := filepath.Abs(testDir)
	if err != nil {
		t.Fatalf("abs: %v", err)
	}

	// Create a second synth contract pointing to the same schema files (synthetic only,
	// to exercise multi-contract barrel emission). We build the barrel via a cloned
	// project that has two codegen=true contracts.
	parser := metadata.NewParser(absTestDir)
	p, err := parser.Parse()
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	// Use the real root dir, not the synth testdata, so relFromRoot resolves.
	root := findRepoRoot()

	// Build one real barrel using the synth fixture.
	artifact, ok, err := RenderTSBarrel(absTestDir, p)
	if err != nil {
		t.Fatalf("RenderTSBarrel: %v", err)
	}
	if !ok {
		t.Fatal("expected ok=true for synth project with http contract")
	}

	out := string(artifact.Content)
	_ = root

	// Must have generated header.
	if !strings.HasPrefix(out, "// Code generated by gocell generate") {
		t.Errorf("missing generated header; got:\n%s", out[:min(200, len(out))])
	}
	// Must have at least one export line.
	if !strings.Contains(out, "export * as ") {
		t.Errorf("expected export * as in barrel; got:\n%s", out)
	}
	// The barrel entries must be sorted by alias (spot-check: no descending pair).
	lines := strings.Split(out, "\n")
	var aliases []string
	for _, l := range lines {
		if strings.HasPrefix(l, "export * as ") {
			// Extract alias between "export * as " and " from"
			rest := strings.TrimPrefix(l, "export * as ")
			alias := strings.SplitN(rest, " ", 2)[0]
			aliases = append(aliases, alias)
		}
	}
	if !sort.StringsAreSorted(aliases) {
		t.Errorf("barrel aliases must be sorted; got: %v", aliases)
	}

	// Path must be "generated-ts/index.ts".
	if artifact.Path != "generated-ts/index.ts" {
		t.Errorf("artifact.Path = %q, want generated-ts/index.ts", artifact.Path)
	}
}

// TestTSPropertyKey verifies that wire keys which are not safe TS identifiers
// are emitted as quoted string-literal property names, while safe identifiers
// stay bare (F2: a legal JSON key like "foo-bar" must not render as illegal
// bare TS `foo-bar?:`).
func TestTSPropertyKey(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name  string
		input string
		want  string
	}{
		{name: "camelCase identifier", input: "accessToken", want: "accessToken"},
		{name: "underscore", input: "_internal", want: "_internal"},
		{name: "dollar", input: "$ref", want: "$ref"},
		{name: "digits after letter", input: "field2", want: "field2"},
		{name: "hyphen", input: "foo-bar", want: "'foo-bar'"},
		{name: "space", input: "foo bar", want: "'foo bar'"},
		{name: "leading digit", input: "1st", want: "'1st'"},
		{name: "single quote", input: "it's", want: `'it\'s'`},
		{name: "backslash", input: `a\b`, want: `'a\\b'`},
		{name: "dot", input: "a.b", want: "'a.b'"},
		{name: "non-ascii", input: "naïve", want: "'naïve'"},
		{name: "empty", input: "", want: "''"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := tsPropertyKey(tc.input)
			if got != tc.want {
				t.Errorf("tsPropertyKey(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

// TestTSDocComment verifies that the JSDoc block-comment terminator is
// neutralized in doc text so a schema title cannot close /** */ and inject TS
// source (F3).
func TestTSDocComment(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name  string
		input string
		want  string
	}{
		{name: "plain", input: "the user response", want: "the user response"},
		{name: "comment terminator", input: "x */ injected", want: "x *\\/ injected"},
		{name: "multiple terminators", input: "*/*/", want: "*\\/*\\/"},
		{name: "newline preserved", input: "line1\nline2", want: "line1\nline2"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := tsDocComment(tc.input)
			if got != tc.want {
				t.Errorf("tsDocComment(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

// TestRenderTS_PropertyKeyQuotingAndDocEscape proves the F2/F3 escaping is wired
// into renderTS end-to-end: a hyphenated wire key renders as a quoted property
// name and a doc containing the comment terminator is neutralized.
func TestRenderTS_PropertyKeyQuotingAndDocEscape(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "edge",
		ContractID:  "http.edge.case.v1",
		Kind:        "http",
		SourceFile:  "contracts/http/edge/case/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Response",
				Doc:  "danger */ export const injected = 1; /*",
				Fields: []DTOField{
					{Name: "FooBar", BareJSONTag: "foo-bar", GoType: "string", Required: true},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)

	if !strings.Contains(out, "'foo-bar': string;") {
		t.Errorf("hyphenated key must render quoted as 'foo-bar': string;; got:\n%s", out)
	}
	if strings.Contains(out, "foo-bar: string;") && !strings.Contains(out, "'foo-bar': string;") {
		t.Errorf("unquoted hyphenated key leaked into output; got:\n%s", out)
	}
	// The doc must not contain a live comment terminator that closes the JSDoc.
	if strings.Contains(out, "*/ export const injected") {
		t.Errorf("JSDoc terminator was not neutralized — TS injection possible; got:\n%s", out)
	}
	if !strings.Contains(out, "*\\/ export const injected") {
		t.Errorf("expected neutralized terminator '*\\/' in doc; got:\n%s", out)
	}
}

// TestSpecEmitsTS verifies the single TS-emit predicate (F1): only specs with at
// least one DTO and an emitting kind (not webhook/grpc/responseProjection) emit
// TS. An empty-DTO contract would render a header-only types.ts (not a module),
// so it must be skipped by the disk write, the barrel and the verify manifest.
func TestSpecEmitsTS(t *testing.T) {
	t.Parallel()
	dto := []DTOSpec{{Name: "Response", Fields: []DTOField{{Name: "X", BareJSONTag: "x", GoType: "string"}}}}
	cases := []struct {
		name string
		spec *ContractGenSpec
		want bool
	}{
		{name: "nil spec", spec: nil, want: false},
		{name: "webhook", spec: &ContractGenSpec{Kind: "webhook", DTOs: dto}, want: false},
		{name: "grpc", spec: &ContractGenSpec{Kind: "grpc", DTOs: dto}, want: false},
		{name: "http empty DTOs", spec: &ContractGenSpec{Kind: "http"}, want: false},
		{name: "projection empty DTOs (F1 bug)", spec: &ContractGenSpec{Kind: "projection"}, want: false},
		{name: "http with DTOs", spec: &ContractGenSpec{Kind: "http", DTOs: dto}, want: true},
		{name: "projection with DTOs", spec: &ContractGenSpec{Kind: "projection", DTOs: dto}, want: true},
		{name: "event with DTOs", spec: &ContractGenSpec{Kind: "event", DTOs: dto}, want: true},
		{
			name: "http responseProjection",
			spec: &ContractGenSpec{Kind: "http", DTOs: dto, Endpoint: &httpEndpointSpec{ResponseProjection: true}},
			want: false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := specEmitsTS(tc.spec); got != tc.want {
				t.Errorf("specEmitsTS(%s) = %v, want %v", tc.name, got, tc.want)
			}
		})
	}
}

// TestDetectBarrelAliasCollision verifies the fail-fast guard (F4): two contracts
// that derive the same lossy alias from distinct paths must be rejected, while a
// set of distinct aliases passes.
func TestDetectBarrelAliasCollision(t *testing.T) {
	t.Parallel()

	t.Run("distinct aliases pass", func(t *testing.T) {
		t.Parallel()
		entries := []tsBarrelEntry{
			{Alias: "eventFooV1", ImportPath: "./contracts/event/foo/v1/types"},
			{Alias: "eventBarV1", ImportPath: "./contracts/event/bar/v1/types"},
		}
		if err := detectBarrelAliasCollision(entries); err != nil {
			t.Errorf("distinct aliases must not collide; got %v", err)
		}
	})

	t.Run("collision fails fast", func(t *testing.T) {
		t.Parallel()
		// "event/foo-bar/v1" and "event/foo/bar/v1" both collapse to eventFooBarV1.
		entries := []tsBarrelEntry{
			{Alias: "eventFooBarV1", ImportPath: "./contracts/event/foo-bar/v1/types"},
			{Alias: "eventFooBarV1", ImportPath: "./contracts/event/foo/bar/v1/types"},
		}
		err := detectBarrelAliasCollision(entries)
		if err == nil {
			t.Fatal("expected collision error, got nil")
		}
		// Error must name the alias and both import paths for diagnosability.
		for _, want := range []string{"eventFooBarV1", "event/foo-bar/v1", "event/foo/bar/v1"} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("collision error missing %q; got %q", want, err.Error())
			}
		}
	})
}

// TestRenderBarrel verifies the barrel index.ts output.
func TestRenderBarrel(t *testing.T) {
	t.Parallel()
	entries := []tsBarrelEntry{
		{Alias: "httpOrderCreateV1", ImportPath: "./contracts/http/order/create/v1/types"},
		{Alias: "eventOrderCreatedV1", ImportPath: "./contracts/event/order-created/v1/types"},
	}
	got, err := renderBarrel(entries)
	if err != nil {
		t.Fatalf("renderBarrel: %v", err)
	}
	out := string(got)

	// Must have header
	if !strings.HasPrefix(out, "// Code generated by gocell generate") {
		t.Errorf("missing generated header; got:\n%s", out[:min(200, len(out))])
	}
	// Must have re-exports
	if !strings.Contains(out, "export * as httpOrderCreateV1 from") {
		t.Errorf("missing httpOrderCreateV1 export; got:\n%s", out)
	}
	if !strings.Contains(out, "export * as eventOrderCreatedV1 from") {
		t.Errorf("missing eventOrderCreatedV1 export; got:\n%s", out)
	}
}
