package contractgen

import (
	"strings"
	"testing"
)

// TestTSGoType verifies the Go→TS type mapping table for all structural cases
// in tsGoType (pure function). This is the primary unit test for the type
// derivation logic before any template rendering happens.
func TestTSGoType(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		f    DTOField
		want string
	}{
		// scalar primitives
		{name: "string", f: DTOField{GoType: "string", BareJSONTag: "name"}, want: "string"},
		{name: "int64", f: DTOField{GoType: "int64", BareJSONTag: "count"}, want: "number"},
		{name: "float64", f: DTOField{GoType: "float64", BareJSONTag: "ratio"}, want: "number"},
		{name: "bool", f: DTOField{GoType: "bool", BareJSONTag: "active"}, want: "boolean"},
		{name: "ptr bool", f: DTOField{GoType: "*bool", BareJSONTag: "active"}, want: "boolean"},
		// object (pointer, non-list)
		{name: "object ptr", f: DTOField{GoType: "*ResponseData", ItemDTO: "ResponseData", IsList: false}, want: "ResponseData"},
		// object array
		{name: "object array", f: DTOField{GoType: "[]*ResponseDataCellsItem", ItemDTO: "ResponseDataCellsItem", IsList: true}, want: "ResponseDataCellsItem[]"},
		// scalar arrays
		{name: "string array", f: DTOField{GoType: "[]string", BareJSONTag: "tags"}, want: "string[]"},
		{name: "int64 array", f: DTOField{GoType: "[]int64", BareJSONTag: "ids"}, want: "number[]"},
		{name: "float64 array", f: DTOField{GoType: "[]float64", BareJSONTag: "vals"}, want: "number[]"},
		// any
		{name: "any", f: DTOField{GoType: "any", BareJSONTag: "meta"}, want: "unknown"},
		{name: "any array", f: DTOField{GoType: "[]any", BareJSONTag: "items"}, want: "unknown[]"},
		// enum: GoType == enum TypeName, handled by context; fallback to type name
		{name: "enum type", f: DTOField{GoType: "PayloadOutcome", BareJSONTag: "outcome"}, want: "PayloadOutcome"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := tsGoType(tc.f)
			if got != tc.want {
				t.Errorf("tsGoType(%+v) = %q, want %q", tc.f, got, tc.want)
			}
		})
	}
}

// TestRenderTS_BasicInterface verifies that renderTS produces a valid TS file
// with export interface for a minimal spec (single DTO, required + optional fields).
func TestRenderTS_BasicInterface(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "ping",
		ContractID:  "http.order.ping.v1",
		Kind:        "http",
		SourceFile:  "contracts/http/order/ping/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Response",
				Doc:  "ping response",
				Fields: []DTOField{
					{Name: "Message", BareJSONTag: "message", GoType: "string", Required: true},
					{Name: "Count", BareJSONTag: "count", GoType: "int64", Required: false},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)

	// Must have generated header
	if !strings.HasPrefix(out, "// Code generated by gocell generate") {
		t.Errorf("missing generated header prefix; got:\n%s", out[:min(200, len(out))])
	}
	// Must export interface
	if !strings.Contains(out, "export interface Response") {
		t.Errorf("missing 'export interface Response'; got:\n%s", out)
	}
	// required field: no '?'
	if !strings.Contains(out, "message: string;") {
		t.Errorf("missing required field 'message: string;'; got:\n%s", out)
	}
	// optional field: has '?'
	if !strings.Contains(out, "count?: number;") {
		t.Errorf("missing optional field 'count?: number;'; got:\n%s", out)
	}
}

// TestRenderTS_EnumUnion verifies that renderTS emits a TS union type for each
// EnumSpec: `export type PayloadOutcome = 'succeeded' | 'rejected';`
func TestRenderTS_EnumUnion(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "widgetresolved",
		ContractID:  "event.widget-resolved.v1",
		Kind:        "event",
		SourceFile:  "contracts/event/widget-resolved/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Payload",
				Fields: []DTOField{
					{Name: "Outcome", BareJSONTag: "outcome", GoType: "PayloadOutcome", Required: true},
				},
				Enums: []EnumSpec{
					{
						TypeName:  "PayloadOutcome",
						FieldName: "outcome",
						Values: []EnumValue{
							{ConstName: "PayloadOutcomeSucceeded", Value: "succeeded"},
							{ConstName: "PayloadOutcomeRejected", Value: "rejected"},
						},
					},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)

	// Must have the union type
	if !strings.Contains(out, "export type PayloadOutcome =") {
		t.Errorf("missing enum union type 'export type PayloadOutcome ='; got:\n%s", out)
	}
	if !strings.Contains(out, "'succeeded'") {
		t.Errorf("missing enum value 'succeeded'; got:\n%s", out)
	}
	if !strings.Contains(out, "'rejected'") {
		t.Errorf("missing enum value 'rejected'; got:\n%s", out)
	}
	// The Payload interface should reference the enum type
	if !strings.Contains(out, "export interface Payload") {
		t.Errorf("missing 'export interface Payload'; got:\n%s", out)
	}
	// outcome field uses the enum type, not a raw string
	if !strings.Contains(out, "outcome: PayloadOutcome") {
		t.Errorf("expected 'outcome: PayloadOutcome' in interface; got:\n%s", out)
	}
}

// TestRenderTS_ObjectField verifies that object fields (ItemDTO != "") render
// as the referenced DTO name, not as a raw string or any.
func TestRenderTS_ObjectField(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "details",
		ContractID:  "http.item.details.v1",
		Kind:        "http",
		SourceFile:  "contracts/http/item/details/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Response",
				Fields: []DTOField{
					{Name: "Data", BareJSONTag: "data", GoType: "*ResponseData", ItemDTO: "ResponseData", IsList: false, Required: false},
				},
			},
			{
				Name: "ResponseData",
				Fields: []DTOField{
					{Name: "ID", BareJSONTag: "id", GoType: "string", Required: true},
					{Name: "Name", BareJSONTag: "name", GoType: "string", Required: false},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)

	if !strings.Contains(out, "export interface Response") {
		t.Errorf("missing 'export interface Response'; got:\n%s", out)
	}
	if !strings.Contains(out, "data?: ResponseData;") {
		t.Errorf("missing 'data?: ResponseData;'; got:\n%s", out)
	}
	if !strings.Contains(out, "export interface ResponseData") {
		t.Errorf("missing 'export interface ResponseData'; got:\n%s", out)
	}
}

// TestRenderTS_ArrayField verifies array-of-object fields render as X[].
func TestRenderTS_ArrayField(t *testing.T) {
	t.Parallel()
	spec := &ContractGenSpec{
		PackageName: "list",
		ContractID:  "http.order.list.v1",
		Kind:        "http",
		SourceFile:  "contracts/http/order/list/v1/contract.yaml",
		DTOs: []DTOSpec{
			{
				Name: "Response",
				Fields: []DTOField{
					{Name: "Data", BareJSONTag: "data", GoType: "[]*ResponseDataItem", ItemDTO: "ResponseDataItem", IsList: true, Required: false},
				},
			},
			{
				Name: "ResponseDataItem",
				Fields: []DTOField{
					{Name: "ID", BareJSONTag: "id", GoType: "string", Required: true},
				},
			},
		},
	}

	got, err := renderTS(spec)
	if err != nil {
		t.Fatalf("renderTS: %v", err)
	}
	out := string(got)

	if !strings.Contains(out, "data?: ResponseDataItem[];") {
		t.Errorf("missing 'data?: ResponseDataItem[];'; got:\n%s", out)
	}
}

// TestRenderBarrel verifies the barrel index.ts output.
func TestRenderBarrel(t *testing.T) {
	t.Parallel()
	entries := []tsBarrelEntry{
		{Alias: "httpOrderCreateV1", ImportPath: "./contracts/http/order/create/v1/types"},
		{Alias: "eventOrderCreatedV1", ImportPath: "./contracts/event/order-created/v1/types"},
	}
	got, err := renderBarrel(entries)
	if err != nil {
		t.Fatalf("renderBarrel: %v", err)
	}
	out := string(got)

	// Must have header
	if !strings.HasPrefix(out, "// Code generated by gocell generate") {
		t.Errorf("missing generated header; got:\n%s", out[:min(200, len(out))])
	}
	// Must have re-exports
	if !strings.Contains(out, "export * as httpOrderCreateV1 from") {
		t.Errorf("missing httpOrderCreateV1 export; got:\n%s", out)
	}
	if !strings.Contains(out, "export * as eventOrderCreatedV1 from") {
		t.Errorf("missing eventOrderCreatedV1 export; got:\n%s", out)
	}
}

// min returns the smaller of two ints.
func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
