// Code generated by gocell generate assembly. DO NOT EDIT.
// Source: examples/todoorder/assembly.yaml
package main

func generatedCellModules() []CellModule {
	return []CellModule{
		OrderCellModule{},
	}
}
