// Code generated by gocell generate cell. DO NOT EDIT.
// Source: examples/iotdevice/cells/devicecell/slices/devicecertcompletion/slice.yaml

package devicecertcompletion

import (
	"context"

	"github.com/ghbvf/gocell/framework/kernel/metadata"

	"github.com/ghbvf/gocell/framework/kernel/outbox"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "devicecertcompletion",
	BelongsToCell:    "devicecell",
	ConsistencyLevel: "L4",
	Lifecycle:        "experimental",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "event.devicecert-rotation-resolved.v1", Role: "publish"},
		{Contract: "event.devicecert-rotation-resolved.v1", Role: "subscribe", Handler: "HandleRotationResolved"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.devicecertcompletion.service",
		},
		Contract: []string{
			"contract.event.devicecert-rotation-resolved.v1.publish",
			"contract.event.devicecert-rotation-resolved.v1.subscribe",
		},
	},
	AllowedFiles: []string{
		"examples/iotdevice/cells/devicecell/slices/devicecertcompletion/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta.Clone() }

// eventHandlerService documents the handler methods devicecertcompletion's service
// must provide so that cell_gen.go's reg.Subscribe call is typed. The interface
// is intentionally unexported to avoid colliding with a concrete Service struct.
// Build-time safety comes from the c.<field>.<method>(...) invocations in
// cell_gen.go — Go rejects compilation if the method is missing or renamed.
type eventHandlerService interface {
	// HandleRotationResolved handles event.devicecert-rotation-resolved.v1.
	HandleRotationResolved(ctx context.Context, e outbox.Entry) outbox.HandleResult
}
