// Code generated by gocell generate required-deps. DO NOT EDIT.

package sessionvalidate

import (
	"github.com/ghbvf/gocell/framework/pkg/errcode"
	"github.com/ghbvf/gocell/framework/pkg/validation"
)

// validateRequired verifies every required dependency on the Service struct
// is present and non-typed-nil. Generated from gocell:"required" struct field
// tags; do not edit by hand.
func (s *Service) validateRequired() error {
	if validation.IsNilInterface(s.verifier) {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"session-validate: IntentTokenVerifier required")
	}
	if validation.IsNilInterface(s.userRepo) {
		return errcode.New(errcode.KindInternal, errcode.ErrCellInvalidConfig,
			"session-validate: UserRepository required")
	}
	if validation.IsNilInterface(s.txRunner) {
		return errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"session-validate: TxRunner required; use WithTxManager")
	}
	return nil
}
