// Code generated by gocell generate cell. DO NOT EDIT.

package grpc_service_in_contract_violate

import "github.com/ghbvf/gocell/framework/kernel/cell"

// generatedCellRegister models the SANCTIONED cellgen gRPC wiring: a
// reg.GRPCService call inside cell_gen.go bearing the cellgen DO-NOT-EDIT
// banner. GRPC-SERVICE-IN-CONTRACT-01/A must ALLOW this (no diagnostic) — it is
// the single legitimate production callsite shape. Paired with healthz_gen.go
// to prove the allowlist distinguishes cell_gen.go from sibling generated files.
//
// The inline composite literal form matches what gocell generate cell actually
// emits, enabling the B-check AST extractor (extractGRPCContractIDs) to resolve
// the ContractID string literal directly from the call site.
func generatedCellRegister(reg cell.Registrar) {
	_ = reg.GRPCService(cell.GRPCServiceSpec{
		ContractID: "grpc.fixture.v1",
		CellID:     "fixturecell",
		Listener:   cell.PrimaryListener,
		Register:   func() {}, // intentionally wrong type (func() vs func(grpc.ServiceRegistrar)); fixture only feeds AST scan, never reaches runtime
	})
}
