// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/auth/user/delete/v1/contract.yaml

/** http.auth.user.delete.v1.request */
export interface Request {
  id: string;
}

/** http.auth.user.delete.v1.response */
export interface Response {
}
