#!/usr/bin/env bash
# gen-deploy-secrets.sh — generate a fresh .env.local with cryptographically
# random secrets for local Docker deployment.
#
# Usage: hack/scripts/gen-deploy-secrets.sh [OUTPUT_FILE]
#   OUTPUT_FILE defaults to .env.local (relative to CWD).
#   Aborts if the file already exists; delete it first to regenerate.
#
# DO NOT COMMIT the generated file. It is listed in .gitignore.

set -euo pipefail

_output_file="${1:-.env.local}"

if [[ -e "${_output_file}" ]]; then
  echo "gen-deploy-secrets: '${_output_file}' already exists." >&2
  echo "Delete it first if you want to regenerate: rm '${_output_file}'" >&2
  exit 1
fi

_tmp_out="$(mktemp)"
trap 'rm -f "${_tmp_out}"' EXIT

# JWT keypair is NOT generated here. PEM is multiline and docker-compose env_file
# does not honour `\n` escapes, so an inline RSA key in .env.local would arrive
# at corebundle as one literal backslash-n string and fail PEM parsing. The
# corebundle container generates an ephemeral keypair at startup (see
# tests/e2e/Dockerfile.corebundle::start-corebundle.sh); container restart
# invalidates outstanding tokens, requiring fresh login. For production keypair
# persistence see docs/ops/local-docker-deploy.md §Production differences.

# Generate random secrets.
# PG passwords use hex (not base64): both are embedded in DSN userinfo
# (postgres://role:pw@host/db), where base64's '/' '+' '=' break URL parsing.
_pg_password="$(openssl rand -hex 16)"
_gocell_app_password="$(openssl rand -hex 16)"
# RabbitMQ password is hex (URL-safe): embedded in GOCELL_AMQP_URL userinfo
# (amqp://gocell:pw@rabbitmq:5672/), same rationale as the PG passwords (#1940).
_rabbitmq_password="$(openssl rand -hex 16)"
_master_key="$(openssl rand -hex 32)"
_cursor_key_config="$(openssl rand -base64 32)"
_hmac_key="$(openssl rand -base64 32)"
_audit_bootstrap_hmac_key="$(openssl rand -base64 32)"
_cursor_key_audit="$(openssl rand -base64 32)"
_cursor_key_access="$(openssl rand -base64 32)"
_ip_hash_salt_access="$(openssl rand -base64 32)"
_service_secret="$(openssl rand -base64 32)"
_metrics_token="$(openssl rand -base64 32)"
_readyz_verbose_token="$(openssl rand -hex 32)"
_ops_pass="$(openssl rand -hex 12)"

cat >"${_tmp_out}" <<EOF
# DO NOT COMMIT — generated by hack/scripts/gen-deploy-secrets.sh
# Contains cryptographically random secrets for local Docker deployment.
# Run the script again (after deleting this file) to rotate all secrets.

PG_PASSWORD=${_pg_password}
GOCELL_APP_PASSWORD=${_gocell_app_password}
RABBITMQ_PASSWORD=${_rabbitmq_password}
CONFIGCORE_MASTER_KEY=${_master_key}
CONFIGCORE_CURSOR_KEY=${_cursor_key_config}
AUDITCORE_HMAC_KEY=${_hmac_key}
AUDIT_BOOTSTRAP_HMAC_KEY=${_audit_bootstrap_hmac_key}
AUDITCORE_CURSOR_KEY=${_cursor_key_audit}
ACCESSCORE_CURSOR_KEY=${_cursor_key_access}
ACCESSCORE_IP_HASH_SALT=${_ip_hash_salt_access}
SERVICE_SECRET=${_service_secret}
METRICS_TOKEN=${_metrics_token}
READYZ_VERBOSE_TOKEN=${_readyz_verbose_token}
OPS_USER=ops
OPS_PASS=${_ops_pass}
EOF

mv "${_tmp_out}" "${_output_file}"
chmod 600 "${_output_file}"

echo "Generated ${_output_file}"
