// Code generated by gocell generate required-deps. DO NOT EDIT.

package rbaccheck

import (
	"github.com/ghbvf/gocell/pkg/errcode"
	"github.com/ghbvf/gocell/pkg/validation"
)

// validateRequired verifies every required dependency on the Service struct
// is present and non-typed-nil. Generated from gocell:"required" struct field
// tags; do not edit by hand.
func (s *Service) validateRequired() error {
	if validation.IsNilInterface(s.roleRepo) {
		return errcode.New(errcode.KindInvalid, errcode.ErrValidationFailed,
			"rbac-check: roleRepo is required")
	}
	if s.codec == nil {
		return errcode.New(errcode.KindInternal, errcode.ErrCellMissingCodec,
			"rbac-check: cursor codec is required")
	}
	return nil
}
