// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/accesscore/slices/rbaccheck/slice.yaml

package rbaccheck

import (
	"github.com/ghbvf/gocell/kernel/metadata"
)

// sliceMeta is the canonical metadata literal projected from slice.yaml.
// SliceMetadata returns the package-scope pointer; the cell composition root
// passes it to cell.MustNewBaseSliceFromMeta to construct *BaseSlice through
// the typed funnel.
var sliceMeta = &metadata.SliceMeta{
	ID:               "rbaccheck",
	BelongsToCell:    "accesscore",
	ConsistencyLevel: "L0",
	ContractUsages: []metadata.ContractUsage{
		{Contract: "http.auth.role.list.v1", Role: "serve"},
		{Contract: "http.auth.role.check.v1", Role: "serve"},
	},
	Verify: metadata.SliceVerifyMeta{
		Unit: []string{
			"unit.rbaccheck.service",
		},
		Contract: []string{
			"contract.http.auth.role.list.v1.serve",
			"contract.http.auth.role.check.v1.serve",
		},
	},
	AllowedFiles: []string{
		"cells/accesscore/slices/rbaccheck/**",
	},
}

// SliceMetadata returns the package-scope *metadata.SliceMeta projected
// from slice.yaml. Composition roots consume this via
// cell.MustNewBaseSliceFromMeta(<slicePkg>.SliceMetadata()) — the typed
// funnel that replaces the legacy `cell.NewBaseSlice(id, cellID, level)`
// literal pattern.
func SliceMetadata() *metadata.SliceMeta { return sliceMeta }
