// Code generated by gocell generate cell. DO NOT EDIT.
// Source: cells/accesscore/cell.yaml

package accesscore

import (
	"context"
	"fmt"

	sub0 "github.com/ghbvf/gocell/generated/contracts/event/config/entry-deleted/v1"
	sub1 "github.com/ghbvf/gocell/generated/contracts/event/config/entry-upserted/v1"
	sub2 "github.com/ghbvf/gocell/generated/contracts/event/role/assigned/v1"
	sub3 "github.com/ghbvf/gocell/generated/contracts/event/role/revoked/v1"
	"github.com/ghbvf/gocell/kernel/cell"
	"github.com/ghbvf/gocell/kernel/metadata"
)

var _ cell.Cell = (*AccessCore)(nil)

// cellMeta is the canonical metadata literal projected from cell.yaml.
// loadCellMetadata returns the package-scope pointer; cell.go's constructor
// passes it to cell.MustNewBaseCell which deep-copies the value so callers
// cannot mutate the generated literal.
var cellMeta = &metadata.CellMeta{
	ID:               "accesscore",
	Type:             "core",
	ConsistencyLevel: "L2",
	DurabilityMode:   "durable",
	Owner:            metadata.OwnerMeta{Team: "platform", Role: "cell-owner"},
	Schema:           metadata.SchemaMeta{Primary: "cell_access_core"},
	Verify: metadata.CellVerifyMeta{Smoke: []string{
		"smoke.accesscore.startup",
	}},
	GoStructName: metadata.MustNewGoIdentifier("AccessCore"),
}

func loadCellMetadata() *metadata.CellMeta { return cellMeta }

//nolint:gocognit // generated code: complexity intrinsic to cell's subscribe count
func (c *AccessCore) Init(ctx context.Context, reg cell.Registry) error {
	if err := c.BaseCell.Init(ctx, reg); err != nil {
		return err
	}
	// initInternal: hand-written init hook (permanent K#04 convention; implement in cell.go)
	if err := c.initInternal(ctx, reg); err != nil {
		return err
	}

	reg.RouteGroup(cell.RouteGroup{
		Listener: cell.PrimaryListener,
		Prefix:   "/api/v1/access",
		Register: func(mux cell.RouteMux) error {
			var firstErr error
			captureErr := func(err error) {
				if err != nil && firstErr == nil {
					firstErr = err
				}
			}
			mux.Route("/roles", func(s cell.RouteMux) {
				captureErr(c.rbacHandler.RegisterRoutes(s))
			})
			mux.Route("/sessions", func(s cell.RouteMux) {
				captureErr(c.loginHandler.RegisterRoutes(s))
				captureErr(c.refreshHandler.RegisterRoutes(s))
				captureErr(c.logoutHandler.RegisterRoutes(s))
			})
			mux.Route("/setup", func(s cell.RouteMux) {
				captureErr(c.setupHandler.RegisterRoutes(s))
			})
			mux.Route("/users", func(s cell.RouteMux) {
				captureErr(c.identityHandler.RegisterRoutes(s))
			})
			return firstErr
		},
	})

	reg.RouteGroup(cell.RouteGroup{
		Listener: cell.InternalListener,
		Prefix:   "/internal/v1/access",
		Register: func(mux cell.RouteMux) error {
			var firstErr error
			captureErr := func(err error) {
				if err != nil && firstErr == nil {
					firstErr = err
				}
			}
			mux.Route("/roles", func(s cell.RouteMux) {
				captureErr(c.rbacAssignHandler.RegisterRoutes(s))
			})
			return firstErr
		},
	})

	if err := sub0.NewSubscription(c.configReceiveSvc.HandleEntryDeleted, "accesscore", "accesscore", "configreceive").Mount(reg); err != nil {
		return fmt.Errorf("accesscore: subscribe event.config.entry-deleted.v1: %w", err)
	}

	if err := sub1.NewSubscription(c.configReceiveSvc.HandleEntryUpserted, "accesscore", "accesscore", "configreceive").Mount(reg); err != nil {
		return fmt.Errorf("accesscore: subscribe event.config.entry-upserted.v1: %w", err)
	}

	if err := sub2.NewSubscription(c.rbacSessionConsumer.HandleRoleChanged, "accesscore-rbac-session-sync", "accesscore", "sessionlogout").Mount(reg); err != nil {
		return fmt.Errorf("accesscore: subscribe event.role.assigned.v1: %w", err)
	}

	if err := sub3.NewSubscription(c.rbacSessionConsumer.HandleRoleChanged, "accesscore-rbac-session-sync", "accesscore", "sessionlogout").Mount(reg); err != nil {
		return fmt.Errorf("accesscore: subscribe event.role.revoked.v1: %w", err)
	}

	return nil
}
