// Code generated by gocell generate assembly. DO NOT EDIT.
// Source: assemblies/corebundle/assembly.yaml
package main

func generatedCellModules() []CellModule {
	return []CellModule{
		ConfigCoreModule{},
		AccessCoreModule{},
		AuditCoreModule{},
	}
}
