// Code generated by gocell generate assembly. DO NOT EDIT.
// Source: assemblies/corebundle/assembly.yaml
package main

import (
	cellmodulesaccesscore "github.com/ghbvf/gocell/cellmodules/accesscore"
	cellmodulesauditcore "github.com/ghbvf/gocell/cellmodules/auditcore"
	cellmodulesconfigcore "github.com/ghbvf/gocell/cellmodules/configcore"
	"github.com/ghbvf/gocell/kernel/observability/correlation"
	"github.com/ghbvf/gocell/runtime/capability"
	"github.com/ghbvf/gocell/runtime/composition"
)

func generatedCellModules() []composition.CellModule {
	return []composition.CellModule{
		cellmodulesconfigcore.Module(),
		cellmodulesauditcore.Module(),
		cellmodulesaccesscore.Module(),
	}
}

// generatedCapabilities lists the assembly-level shared infrastructure
// capabilities — the sorted union of the assembly cells' cell.yaml `requires`.
// The composition root provisions each once and injects the resulting
// runtime/capability provider into consuming modules. Emitted iff the union is
// non-empty: an assembly whose cells require nothing has no provisioner to call
// it, so the function (and its capability import) are omitted to avoid dead code.
func generatedCapabilities() []capability.Kind {
	return []capability.Kind{
		capability.Postgres,
		capability.Redis,
	}
}

// generatedCellOwners returns the compile-time cell→owner topology derived from
// each cell's cell.yaml owner block. The map is keyed by cell ID; values are
// correlation.CellOwner{Team, Role}. Used by the composition root to build the
// correlation.Topology passed to the correlate reverse-lookup service.
func generatedCellOwners() map[string]correlation.CellOwner {
	return map[string]correlation.CellOwner{
		"configcore": {Team: "platform", Role: "cell-owner"},
		"auditcore":  {Team: "platform", Role: "cell-owner"},
		"accesscore": {Team: "platform", Role: "cell-owner"},
	}
}
