// Code generated by gocell generate contract. DO NOT EDIT.
// source: contracts/http/policy/list/v1/contract.yaml

/** http.policy.list.v1.request */
export interface Request {
  cursor?: string;
  limit?: number;
}

/** http.policy.list.v1.response */
export interface Response {
  data: ResponseDataItem[];
  nextCursor: string;
  hasMore: boolean;
}

/** policy */
export interface ResponseDataItem {
  id: string;
  name: string;
  description?: string;
  version: number;
  rules: ResponseDataItemRulesItem[];
}

/** policy rule */
export interface ResponseDataItemRulesItem {
  id: string;
  name: string;
  effect: string;
  conditions?: ResponseDataItemRulesItemConditionsItem[];
  obligations?: ResponseDataItemRulesItemObligations;
}

export interface ResponseDataItemRulesItemConditionsItem {
  source: string;
  key: string;
  operator: string;
  values?: string[];
  rhsSource?: string;
  rhsKey?: string;
}

export interface ResponseDataItemRulesItemObligations {
  rowScope?: string;
  fieldMask?: string[];
}
